;-*- Mode: Merlin -*-
;
; src/modules/00_entry.s -- AMACS: JMP entry-vector table + pointer block
; Address range $1000-$1034. GENERATED by tools/disasm.py.
; `put' from src/amacs.s; symbols/labels are global across modules.
;
; ---- $1000-$1026  code ----
        jmp L1046    ; $1000
        jmp L1055    ; $1003
        jmp DSK:OpenFile    ; $1006
        jmp PrepRead    ; $1009
        jmp DSK:CloseFile    ; $100C
        jmp DSK:ReadByte    ; $100F
        jmp SI:CompleteMe    ; $1012
        jmp InitArgument    ; $1015
        jmp SetVariable    ; $1018
        jmp GiveArgs    ; $101B
        jmp FunctionRef    ; $101E
        jmp BindKey    ; $1021
        jmp PushTYI    ; $1024
; ---- $1027-$1034  ptrtable  entry pointer block (CompList..C_XCharCount) ----
        da  CompList        ; $1027  -> $5987
        da  CommandNames    ; $1029  -> $9B37
        da  CharIndex       ; $102B  -> $3F6D
        da  ComTab          ; $102D  -> $4F84
        da  C_XCharacters   ; $102F  -> $7DB8
        da  C_XVectors      ; $1031  -> $7DDE
        da  C_XCharCount    ; $1033  -> $7E2A
