;-*- Mode: Merlin -*-
;
; src/modules/01_boot.s -- AMACS: cold/warm start and initialization
; Address range $1035-$111A. GENERATED by tools/disasm.py.
; `put' from src/amacs.s; symbols/labels are global across modules.
;
; ---- $1035-$111A  code ----
;
; === AMACSStack ===
        brk    ; $1035
L1036   lda #$55    ; $1036
        sta $03F2    ; $1038
        lda #$10    ; $103B
        sta $03F3    ; $103D
        eor #$A5    ; $1040
        sta $03F4    ; $1042
        rts    ; $1045
L1046   tsx    ; $1046
        stx AMACSStack    ; $1047
        jsr L1036    ; $104A
        jsr InitAMACS    ; $104D
        lda #$06    ; $1050
        jmp TopLoop    ; $1052
L1055   ldx AMACSStack    ; $1055
        txs    ; $1058
        jsr L1036    ; $1059
        jsr ResetBoot    ; $105C
        lda #$01    ; $105F
;
; === TopLoop ===
        pha    ; $1061
        jsr SetGap    ; $1062
        pla    ; $1065
        bit AbortedTO?    ; $1066
        bpl L1070    ; $1069
        inc AbortedTO?    ; $106B
        beq L1073    ; $106E
L1070   jsr GenDisplay    ; $1070
L1073   jsr InitArgument    ; $1073
        jsr InitStrArgs    ; $1076
        jsr TopBlink    ; $1079
        jsr Dispatch    ; $107C
        jmp TopLoop    ; $107F
;
; === ExitAMACS ===
        jmp DSK:Quit    ; $1082
;
; === TopBlink ===
        ldx #$29    ; $1085
L1087   lda $00,x    ; $1087
        sta UseAuxZP    ; $1089   <== BANK: aux zero-page/stack (ALTZP on)
        sta $00,x    ; $108C
        sta UseMainZP    ; $108E   <== BANK: main zero-page/stack (ALTZP off)
        dex    ; $1091
        cpx #$1F    ; $1092
        bne L1087    ; $1094
        sta UseAuxZP    ; $1096   <== BANK: aux zero-page/stack (ALTZP on)
        jsr GetBank1    ; $1099
        jsr SetParens    ; $109C
        sta UseMainZP    ; $109F   <== BANK: main zero-page/stack (ALTZP off)
        jsr GetBank2    ; $10A2
        jmp BlinkCursor    ; $10A5
;
; === InitAMACS ===
        lda RdWrBank2    ; $10A8   <== BANK: language-card RAM bank 2 (read+write, BIT twice)
        lda RdWrBank2    ; $10AB   <== BANK: language-card RAM bank 2 (read+write, BIT twice)
        jsr InitFiler    ; $10AE
        jsr InitModeLine    ; $10B1
        jsr InitBuffers    ; $10B4
        ldx #$00    ; $10B7
L10B9   lda $1116,x    ; $10B9
        sta $0200,x    ; $10BC
        beq L10C4    ; $10BF
        inx    ; $10C1
        bne L10B9    ; $10C2
L10C4   jsr CreateBuffer    ; $10C4
        lda TYI_PushIndex    ; $10C7
        cmp TYI_PopIndex    ; $10CA
        bne L10DA    ; $10CD
        lda HardHyper    ; $10CF
        and HardMeta    ; $10D2
        bmi L10DA    ; $10D5
        jsr BufferLoad    ; $10D7
L10DA   jmp WarmBoot    ; $10DA
;
; === ResetBoot ===
        lda #$00    ; $10DD
        sta TYI_PushIndex    ; $10DF
        sta TYI_PopIndex    ; $10E2
;
; === WarmBoot ===
        lda RdRomBank    ; $10E5   <== BANK: language-card ROM (read)
        jsr ResetTTY    ; $10E8
        lda RdWrBank2    ; $10EB   <== BANK: language-card RAM bank 2 (read+write, BIT twice)
        lda RdWrBank2    ; $10EE   <== BANK: language-card RAM bank 2 (read+write, BIT twice)
        lda WindowBot    ; $10F1
        sec    ; $10F3
        sbc #$04    ; $10F4
        sta ModeLineCV    ; $10F6
        sta WindowBot    ; $10F9
        ldy #$3F    ; $10FB
        lda (BuffData),y    ; $10FD
        jsr SelectMode    ; $10FF
        jsr MakeModeLine    ; $1102
        lda #$14    ; $1105
        sta CoutDef    ; $1107
        lda #$26    ; $110A
        sta $2607    ; $110C
        jsr InitTypeout    ; $110F
        jsr DisplayPage    ; $1112
        rts    ; $1115
        cmp $E9E1    ; $1116
        dfb $EE        ; $1119  (truncated)
        brk    ; $111A
