;-*- Mode: Merlin -*-
;
; src/modules/02_window.s -- AMACS: window management
; Address range $111B-$13EE. GENERATED by tools/disasm.py.
; `put' from src/amacs.s; symbols/labels are global across modules.
;
; ---- $111B-$111C  data  TwoWindows? flag ----
        dfb $00,$00    ; $111B  ..
; ---- $111D-$1125  data  WindowOne (9-byte window descriptor record) ----
        dfb $00,$50,$00,$0A,$00,$00,$00,$00,$00    ; $111D  .P.......
; ---- $1126-$112E  data  WindowTwo (9-byte window descriptor record) ----
        dfb $00,$50,$0B,$14,$00,$00,$00,$00,$00    ; $1126  .P.......
; ---- $112F-$112F  data  SelectedWind (current window index) ----
        dfb $00    ; $112F  .
; ---- $1130-$13EE  code ----
;
; === GetSelWind ===
        sta SelectedWind    ; $1130
        jsr L1293    ; $1133
        ldy #$00    ; $1136
L1138   lda ($00),y    ; $1138
        sta: WindowLft,y    ; $113A
        iny    ; $113D
        cpy #$04    ; $113E
        bcc L1138    ; $1140
        lda WindowBot    ; $1142
        sta ModeLineCV    ; $1144
        ldy #$04    ; $1147
        lda ($00),y    ; $1149
        tax    ; $114B
        lda $01    ; $114C
        pha    ; $114E
        lda $00    ; $114F
        pha    ; $1151
        jsr L1370    ; $1152
        pla    ; $1155
        sta $00    ; $1156
        pla    ; $1158
        sta $01    ; $1159
        lda $1121    ; $115B
        cmp $112A    ; $115E
        beq L1164    ; $1161
        rts    ; $1163
L1164   ldy #$05    ; $1164
        lda ($00),y    ; $1166
        sta $02    ; $1168
        iny    ; $116A
        lda ($00),y    ; $116B
        sta $03    ; $116D
        jsr L11C2    ; $116F
        lda $02    ; $1172
        sta TheBuffer    ; $1174
        lda $03    ; $1176
        sta $61    ; $1178
        lda $01    ; $117A
        pha    ; $117C
        lda $00    ; $117D
        pha    ; $117F
        jsr SetGap    ; $1180
        pla    ; $1183
        sta $00    ; $1184
        pla    ; $1186
        sta $01    ; $1187
        ldy #$07    ; $1189
        lda ($00),y    ; $118B
        sta $02    ; $118D
        iny    ; $118F
        lda ($00),y    ; $1190
        sta $03    ; $1192
        jsr L11C2    ; $1194
        lda $02    ; $1197
        sta $04    ; $1199
        lda $03    ; $119B
        sta $05    ; $119D
        jsr BackScrLine    ; $119F
        lda $04    ; $11A2
        sta PageTop    ; $11A4
        lda $05    ; $11A6
        sta $63    ; $11A8
        jsr FindPoint    ; $11AA
        beq L11B2    ; $11AD
        jmp CenterPage    ; $11AF
L11B2   lda CV    ; $11B2
        pha    ; $11B4
        lda CH    ; $11B5
        pha    ; $11B7
        jsr DisplayPage    ; $11B8
        pla    ; $11BB
        sta CH    ; $11BC
        pla    ; $11BE
        sta CV    ; $11BF
        rts    ; $11C1
L11C2   lda $02    ; $11C2
        clc    ; $11C4
        adc PhysBuffTop    ; $11C5
        sta $02    ; $11C7
        lda $03    ; $11C9
        adc $6F    ; $11CB
        sta $03    ; $11CD
        cmp $6F    ; $11CF
        bcc L11DB    ; $11D1
        bne L11E4    ; $11D3
        lda $02    ; $11D5
        cmp PhysBuffTop    ; $11D7
        bcs L11E4    ; $11D9
L11DB   lda PhysBuffTop    ; $11DB
        sta $02    ; $11DD
        lda $6F    ; $11DF
        sta $03    ; $11E1
        rts    ; $11E3
L11E4   lda $03    ; $11E4
        cmp $6B    ; $11E6
        bcc L1222    ; $11E8
        bne L11F4    ; $11EA
        lda $02    ; $11EC
        cmp GapTop    ; $11EE
        bcc L1222    ; $11F0
        beq L1222    ; $11F2
L11F4   lda $02    ; $11F4
        sec    ; $11F6
        sbc GapTop    ; $11F7
        sta $02    ; $11F9
        lda $03    ; $11FB
        sbc $6B    ; $11FD
        sta $03    ; $11FF
        lda $02    ; $1201
        sec    ; $1203
        adc GapBot    ; $1204
        sta $02    ; $1206
        lda $03    ; $1208
        adc $6D    ; $120A
        sta $03    ; $120C
        cmp $69    ; $120E
        bcc L1222    ; $1210
        bne L121A    ; $1212
        lda $02    ; $1214
        cmp BuffBot    ; $1216
        bcc L1222    ; $1218
L121A   lda BuffBot    ; $121A
        sta $02    ; $121C
        lda $69    ; $121E
        sta $03    ; $1220
L1222   rts    ; $1222
;
; === TwoWindows ===
        lda SelectedBuff    ; $1223
        sta $1292    ; $1226
        bit TwoWindows?    ; $1229
        bmi L123C    ; $122C
        sta $1121    ; $122E
        sta $112A    ; $1231
        bpl L123C    ; $1234
L1236   jsr Beep    ; $1236
L1239   lda #$01    ; $1239
        rts    ; $123B
L123C   bit $111C    ; $123C
        bmi L1236    ; $123F
        lda #$18    ; $1241
        sta CenterLine    ; $1243
        lda $1292    ; $1246
        cmp $1121    ; $1249
        beq L1256    ; $124C
        cmp $112A    ; $124E
        beq L1256    ; $1251
        sta $1121    ; $1253
L1256   lda #$FF    ; $1256
        sta $111C    ; $1258
        sta TwoWindows?    ; $125B
        ldy $1292    ; $125E
        ldx $1121    ; $1261
        lda BuffActList,x    ; $1264
        bmi L126C    ; $1267
        sty $1121    ; $1269
L126C   ldx $112A    ; $126C
        lda BuffActList,x    ; $126F
        bmi L1277    ; $1272
        sty $112A    ; $1274
L1277   lda $1121    ; $1277
        cmp $112A    ; $127A
        bne L1285    ; $127D
        jsr L1293    ; $127F
        jsr L130E    ; $1282
L1285   lda #$01    ; $1285
        jsr GetSelWind    ; $1287
        lda #$02    ; $128A
        jsr GetSelWind    ; $128C
        jmp L1239    ; $128F
        brk    ; $1292
L1293   lda #$1D    ; $1293
        sta $00    ; $1295
        lda #$11    ; $1297
        sta $01    ; $1299
        ldy SelectedWind    ; $129B
        dey    ; $129E
        beq L12A9    ; $129F
        lda #$26    ; $12A1
        sta $00    ; $12A3
        lda #$11    ; $12A5
        sta $01    ; $12A7
L12A9   ldy #$04    ; $12A9
        lda ($00),y    ; $12AB
        tay    ; $12AD
        lda BuffActList,y    ; $12AE
        bmi L12BF    ; $12B1
        lda SelectedBuff    ; $12B3
        ldy #$04    ; $12B6
        sta ($00),y    ; $12B8
        pha    ; $12BA
        jsr L130E    ; $12BB
        pla    ; $12BE
L12BF   tya    ; $12BF
        rts    ; $12C0
;
; === OtherWindow ===
        bit TwoWindows?    ; $12C1
        bmi L12C9    ; $12C4
        jmp L1330    ; $12C6
L12C9   bit $111C    ; $12C9
        bmi L12F6    ; $12CC
        lda SelectedBuff    ; $12CE
        cmp $1121    ; $12D1
        beq L12DF    ; $12D4
        cmp $112A    ; $12D6
        bne L12E4    ; $12D9
        lda #$02    ; $12DB
        bne L12E1    ; $12DD
L12DF   lda #$01    ; $12DF
L12E1   sta SelectedWind    ; $12E1
L12E4   lda SelectedWind    ; $12E4
        eor #$03    ; $12E7
        sta SelectedWind    ; $12E9
        jsr L1293    ; $12EC
        tax    ; $12EF
        jsr L1370    ; $12F0
        jmp L1333    ; $12F3
L12F6   jsr L1293    ; $12F6
        lda SelectedBuff    ; $12F9
        ldy #$04    ; $12FC
        sta ($00),y    ; $12FE
        jsr L130E    ; $1300
        lda SelectedWind    ; $1303
        eor #$03    ; $1306
        jsr GetSelWind    ; $1308
        jmp L1333    ; $130B
L130E   ldy #$05    ; $130E
        lda TheBuffer    ; $1310
        sec    ; $1312
        sbc PhysBuffTop    ; $1313
        sta ($00),y    ; $1315
        iny    ; $1317
        lda $61    ; $1318
        sbc $6F    ; $131A
        sta ($00),y    ; $131C
        iny    ; $131E
        lda PageTop    ; $131F
        sec    ; $1321
        sbc PhysBuffTop    ; $1322
        sta ($00),y    ; $1324
        iny    ; $1326
        lda $63    ; $1327
        sbc $6F    ; $1329
        sta ($00),y    ; $132B
        rts    ; $132D
L132E   pla    ; $132E
        pla    ; $132F
L1330   jsr Beep    ; $1330
L1333   lda #$01    ; $1333
        rts    ; $1335
;
; === EnsureWinds ===
        lda TwoWindows?    ; $1336
        and $111C    ; $1339
        bpl L132E    ; $133C
        rts    ; $133E
;
; === OneWindow ===
        jsr EnsureWinds    ; $133F
        lda #$09    ; $1342
        sta CenterLine    ; $1344
        lda #$00    ; $1347
        sta WindowTop    ; $1349
        sta WindowLft    ; $134B
        lda #$14    ; $134D
        sta WindowBot    ; $134F
        sta ModeLineCV    ; $1351
        jsr L1293    ; $1354
        lda SelectedBuff    ; $1357
        ldy #$04    ; $135A
        sta ($00),y    ; $135C
        tax    ; $135E
        jsr L130E    ; $135F
        jsr L1370    ; $1362
        jsr DisplayPage    ; $1365
        lda #$00    ; $1368
        sta $111C    ; $136A
        jmp L1333    ; $136D
L1370   jsr IN:OpenBuff    ; $1370
        lda $1121    ; $1373
        cmp $112A    ; $1376
        beq L137E    ; $1379
        jsr DisplayPage    ; $137B
L137E   rts    ; $137E
;
; === GrowWindow ===
        bit $111C    ; $137F
        bmi L1387    ; $1382
        jmp L1330    ; $1384
L1387   jsr GetArgSign    ; $1387
        bpl L1396    ; $138A
        lda SelectedWind    ; $138C
        cmp #$01    ; $138F
        beq L13BE    ; $1391
        jmp L139D    ; $1393
L1396   lda SelectedWind    ; $1396
        cmp #$01    ; $1399
        bne L13BE    ; $139B
L139D   lda $1120    ; $139D
        clc    ; $13A0
        adc Argument    ; $13A1
        bcs L13BB    ; $13A4
        cmp #$10    ; $13A6
        bcc L13AC    ; $13A8
        lda #$10    ; $13AA
L13AC   sta $1120    ; $13AC
        sta $1128    ; $13AF
        inc $1128    ; $13B2
        jsr OtherWindow    ; $13B5
        jmp OtherWindow    ; $13B8
L13BB   lda #$01    ; $13BB
        rts    ; $13BD
L13BE   lda $1120    ; $13BE
        sec    ; $13C1
        sbc Argument    ; $13C2
        bcc L13BB    ; $13C5
        cmp #$03    ; $13C7
        bcs L13AC    ; $13C9
        lda #$03    ; $13CB
        bne L13AC    ; $13CD
        stz $14    ; $13CF
        sta ($14,x)    ; $13D1
        dfb $8F        ; $13D3  (data/65C02-bit)
        trb $A7    ; $13D4
        trb MarkPnt    ; $13D6
        trb $1C    ; $13D8
        trb $32    ; $13DA
        trb $3C    ; $13DC
        trb $51    ; $13DE
        trb WindowLft    ; $13E0
        rol $A05A    ; $13E2
        dfb $03        ; $13E5  (data/65C02-bit)
L13E6   lda ($00),y    ; $13E6
        sta: $00F0,y    ; $13E8
        dey    ; $13EB
        bpl L13E6    ; $13EC
        rts    ; $13EE
