;-*- Mode: Merlin -*-
;
; src/modules/03_variable.s -- AMACS: settable-variable get/set
; Address range $13EF-$1584. GENERATED by tools/disasm.py.
; `put' from src/amacs.s; symbols/labels are global across modules.
;
; ---- $13EF-$1457  code ----
;
; === PrintVar ===
        jsr $13E1    ; $13EF
        lda $F0    ; $13F2
        asl    ; $13F4
        tax    ; $13F5
        ldy #$00    ; $13F6
        sty PD:Justify    ; $13F8
        lda $13D9,x    ; $13FB
        sta $02    ; $13FE
        lda $13DA,x    ; $1400
        sta $03    ; $1403
        jmp ($0002)    ; $1405
L1408   jsr $13E1    ; $1408
        lda $F0    ; $140B
        asl    ; $140D
        tax    ; $140E
        lda $13CF,x    ; $140F
        sta $02    ; $1412
        lda $13D0,x    ; $1414
        sta $03    ; $1417
        jmp ($0002)    ; $1419
        lda ($F2),y    ; $141C
        bpl L142C    ; $141E
        eor #$FF    ; $1420
        clc    ; $1422
        adc #$01    ; $1423
        pha    ; $1425
        lda #$AD    ; $1426
        jsr CharOut    ; $1428
        pla    ; $142B
L142C   tax    ; $142C
        lda #$00    ; $142D
        jmp PrintDec    ; $142F
        lda ($F2),y    ; $1432
        tax    ; $1434
        iny    ; $1435
        lda ($F2),y    ; $1436
        jsr PrintDec    ; $1438
        rts    ; $143B
        lda #$A2    ; $143C
        jsr CharOut    ; $143E
L1441   lda ($F2),y    ; $1441
        beq L144B    ; $1443
        jsr CharOut    ; $1445
        iny    ; $1448
        bne L1441    ; $1449
L144B   lda #$A2    ; $144B
        jsr CharOut    ; $144D
        rts    ; $1450
        lda ($F2),y    ; $1451
        bpl L145C    ; $1453
        jsr PrintMessage    ; $1455
; ---- $1458-$145A  data  msg: On ----
        dfb $CF,$EE,$00    ; $1458  On.
; ---- $145B-$145E  code ----
        rts    ; $145B
L145C   jsr PrintMessage    ; $145C
; ---- $145F-$1462  data  msg: Off ----
        dfb $CF,$E6,$E6,$00    ; $145F  Off.
; ---- $1463-$14F6  code ----
        rts    ; $1463
        lda $7A5C    ; $1464
        bne L1480    ; $1467
        lda Argument    ; $1469
        cmp $F1    ; $146C
        bcc L1472    ; $146E
        bne L1480    ; $1470
L1472   ldy #$00    ; $1472
        bit ArgSign    ; $1474
        bpl L147E    ; $1477
        eor #$FF    ; $1479
        clc    ; $147B
        adc #$01    ; $147C
L147E   sta ($F2),y    ; $147E
L1480   rts    ; $1480
        ldy #$00    ; $1481
        lda Argument    ; $1483
        sta ($F2),y    ; $1486
        iny    ; $1488
        lda $7A5C    ; $1489
        sta ($F2),y    ; $148C
        rts    ; $148E
        ldy #$00    ; $148F
L1491   lda $0200,y    ; $1491
        cmp #$9B    ; $1494
        beq L14A2    ; $1496
        sta ($F2),y    ; $1498
        iny    ; $149A
        cpy $F1    ; $149B
        bcc L1491    ; $149D
        dey    ; $149F
        beq L14A6    ; $14A0
L14A2   lda #$00    ; $14A2
        sta ($F2),y    ; $14A4
L14A6   rts    ; $14A6
        lda ArgSign    ; $14A7
        ldy #$00    ; $14AA
        sta ($F2),y    ; $14AC
        rts    ; $14AE
;
; === SetVariable ===
        jsr GetStrArg    ; $14AF
        beq L14B9    ; $14B2
        jsr ReadVariable    ; $14B4
        bne L14D0    ; $14B7
L14B9   lda #$5D    ; $14B9
        sta CompList    ; $14BB
        lda #$97    ; $14BE
        sta $5988    ; $14C0
        lda #$9B    ; $14C3
        sta $0200,x    ; $14C5
        jsr SI:CompleteMe    ; $14C8
        beq L14D3    ; $14CB
L14CD   jsr Beep    ; $14CD
L14D0   lda #$01    ; $14D0
        rts    ; $14D2
L14D3   jsr PopCompPoint    ; $14D3
        jsr PushCompPoint    ; $14D6
        jsr $13E1    ; $14D9
        lda $F0    ; $14DC
        cmp #$02    ; $14DE
        beq L14E7    ; $14E0
        jsr AnyArgument?    ; $14E2
        beq L1510    ; $14E5
L14E7   jsr GetStrArg    ; $14E7
        beq L150D    ; $14EA
        lda #$16    ; $14EC
        sta $5725    ; $14EE
        jsr OpenEchoArea    ; $14F1
        jsr PrintMessage    ; $14F4
; ---- $14F7-$14FE  data  msg: .Value: ----
        dfb $8D,$D6,$E1,$EC,$F5,$E5,$BA,$00    ; $14F7  .Value:.
; ---- $14FF-$1584  code ----
        jsr ReadArgLine    ; $14FF
        php    ; $1502
        txa    ; $1503
        pha    ; $1504
        jsr CloseEchoArea    ; $1505
        pla    ; $1508
        tax    ; $1509
        plp    ; $150A
        bne L14CD    ; $150B
L150D   jsr L1519    ; $150D
L1510   jsr PopCompPoint    ; $1510
        jsr L1408    ; $1513
        lda #$01    ; $1516
        rts    ; $1518
L1519   lda #$9B    ; $1519
        sta $0200,x    ; $151B
        lda $F0    ; $151E
        cmp #$02    ; $1520
        beq L1555    ; $1522
        cmp #$03    ; $1524
        bne L155E    ; $1526
        cpx #$02    ; $1528
        bcc L155E    ; $152A
        lda $0200    ; $152C
        cmp #$AD    ; $152F
        beq L155E    ; $1531
        cmp #$B0    ; $1533
        bcc L1556    ; $1535
        cmp #$BA    ; $1537
        bcc L155E    ; $1539
        jsr UpperCon    ; $153B
        cmp #$CF    ; $153E
        bne L1556    ; $1540
        lda $0202    ; $1542
        cmp #$9B    ; $1545
        beq L1550    ; $1547
        lda #$00    ; $1549
        sta ArgSign    ; $154B
        beq L1555    ; $154E
L1550   lda #$FF    ; $1550
        sta ArgSign    ; $1552
L1555   rts    ; $1555
L1556   ldy #$00    ; $1556
        lda ($F2),y    ; $1558
        sta ArgSign    ; $155A
        rts    ; $155D
L155E   ldx #$00    ; $155E
        stx Argument    ; $1560
        lda $0200    ; $1563
        cmp #$AD    ; $1566
        bne L1570    ; $1568
        lda #$FF    ; $156A
        sta ArgSign    ; $156C
        inx    ; $156F
L1570   lda $0200,x    ; $1570
        cmp #$B0    ; $1573
        bcc L1555    ; $1575
        cmp #$BA    ; $1577
        bcs L1555    ; $1579
        sec    ; $157B
        sbc #$B0    ; $157C
        jsr AddArgDigit    ; $157E
        inx    ; $1581
        jmp L1570    ; $1582
