;-*- Mode: Merlin -*-
;
; src/modules/04_edit.s -- AMACS: insert/delete/rubout/char movement/CRLF
; Address range $1585-$1AD4. GENERATED by tools/disasm.py.
; `put' from src/amacs.s; symbols/labels are global across modules.
;
; ---- $1585-$1586  data  AutoPushPoint threshold ----
        dfb $F4,$01    ; $1585  t.
; ---- $1587-$1AC2  code ----
;
; === Delete ===
        jsr GetArgSign    ; $1587
        bpl L158F    ; $158A
        jmp Rubout    ; $158C
L158F   jsr AnyArgument?    ; $158F
        bne L15BE    ; $1592
        jsr SetGap    ; $1594
        lda $61    ; $1597
        pha    ; $1599
        lda TheBuffer    ; $159A
        pha    ; $159C
        ldy #$41    ; $159D
        lda (BuffData),y    ; $159F
        pha    ; $15A1
        jsr RightChar    ; $15A2
        pla    ; $15A5
        ldy #$41    ; $15A6
        sta (BuffData),y    ; $15A8
        jsr SetGap    ; $15AA
        pla    ; $15AD
        sta $00    ; $15AE
        pla    ; $15B0
        sta $01    ; $15B1
        lda #$00    ; $15B3
        jsr KillTempPoint    ; $15B5
L15B8   lda #$02    ; $15B8
        rts    ; $15BA
L15BB   lda #$01    ; $15BB
        rts    ; $15BD
L15BE   jsr ClrLastKill    ; $15BE
        jsr LinesPastPnt    ; $15C1
        sta $B5    ; $15C4
        jsr BuffDelete    ; $15C6
        bne L15BB    ; $15C9
        ldy #$00    ; $15CB
        jsr $D03F    ; $15CD
        cmp #$8D    ; $15D0
        bne L1613    ; $15D2
        lda CH    ; $15D4
        cmp WindowLft    ; $15D6
        bne L15B8    ; $15D8
        ldx CV    ; $15DA
        inx    ; $15DC
        inx    ; $15DD
        cpx WindowBot    ; $15DE
        bcs L15B8    ; $15E0
        lda CV    ; $15E2
        pha    ; $15E4
        lda CH    ; $15E5
        pha    ; $15E7
        jsr TV:DelLine    ; $15E8
        lda WindowBot    ; $15EB
        sta CV    ; $15ED
        dec CV    ; $15EF
        lda WindowLft    ; $15F1
        sta CH    ; $15F3
        lda $61    ; $15F5
        pha    ; $15F7
        lda TheBuffer    ; $15F8
        pha    ; $15FA
        jsr PointToCH    ; $15FB
        jsr DispPointEnd    ; $15FE
        pla    ; $1601
        sta TheBuffer    ; $1602
        pla    ; $1604
        sta $61    ; $1605
        pla    ; $1607
        sta CH    ; $1608
        pla    ; $160A
        sta CV    ; $160B
        jsr vtab    ; $160D
        lda #$00    ; $1610
        rts    ; $1612
L1613   jsr LinesPastPnt    ; $1613
        cmp $B5    ; $1616
        bne L15B8    ; $1618
        lda #$05    ; $161A
        rts    ; $161C
;
; === Rubout ===
        jsr GetArgSign    ; $161D
        bpl L1625    ; $1620
        jmp Delete    ; $1622
L1625   jsr AnyArgument?    ; $1625
        bne L165B    ; $1628
        lda $61    ; $162A
        pha    ; $162C
        lda TheBuffer    ; $162D
        pha    ; $162F
        ldy #$41    ; $1630
        lda (BuffData),y    ; $1632
        pha    ; $1634
        jsr LeftChar    ; $1635
        pla    ; $1638
        ldy #$41    ; $1639
        sta (BuffData),y    ; $163B
        lda TheBuffer    ; $163D
        sta $00    ; $163F
        lda $61    ; $1641
        sta $01    ; $1643
        pla    ; $1645
        sta TheBuffer    ; $1646
        pla    ; $1648
        sta $61    ; $1649
        lda #$FF    ; $164B
        jsr KillTempPoint    ; $164D
L1650   jsr FindPoint    ; $1650
        beq L1658    ; $1653
L1655   lda #$06    ; $1655
        rts    ; $1657
L1658   lda #$02    ; $1658
        rts    ; $165A
L165B   jsr ClrLastKill    ; $165B
        lda CV    ; $165E
        sta $168A    ; $1660
        jsr LinesPastPnt    ; $1663
        sta $B5    ; $1666
        jsr BuffRubout    ; $1668
        ldy #$00    ; $166B
        jsr $D01B    ; $166D
        cmp #$8D    ; $1670
        beq L1650    ; $1672
        jsr FindPoint    ; $1674
        bne L1655    ; $1677
        jsr LinesPastPnt    ; $1679
        cmp $B5    ; $167C
        bne L1658    ; $167E
        lda CV    ; $1680
        cmp $168A    ; $1682
        bne L1658    ; $1685
        lda #$05    ; $1687
        rts    ; $1689
        brk    ; $168A
;
; === RubWithTab ===
        jsr ClrLastKill    ; $168B
        lda ArgSign    ; $168E
        bmi L16C9    ; $1691
        jsr PointBackward    ; $1693
        bne L16C9    ; $1696
        ldy #$00    ; $1698
        jsr $D01B    ; $169A
        cmp #$89    ; $169D
        bne L16C3    ; $169F
        jsr FindPoint    ; $16A1
        lda CH    ; $16A4
        jsr TabBump    ; $16A6
        sec    ; $16A9
        sbc CH    ; $16AA
        sta $B5    ; $16AC
        jsr SetGap    ; $16AE
        inc GapBot    ; $16B1
        bne L16B7    ; $16B3
        inc $6D    ; $16B5
L16B7   lda #$A0    ; $16B7
        jsr BuffInsert    ; $16B9
        dec $B5    ; $16BC
        bne L16B7    ; $16BE
        jmp L16C9    ; $16C0
L16C3   jsr PointForward    ; $16C3
        jsr SetGap    ; $16C6
L16C9   jmp Rubout    ; $16C9
;
; === TabInsert ===
        lda #$89    ; $16CC
;
; === Insert ===
        sta $B6    ; $16CE
        jsr LinesPastPnt    ; $16D0
        sta $B4    ; $16D3
        jsr ClrLastKill    ; $16D5
L16D8   jsr ZeroArg?    ; $16D8
        beq L1738    ; $16DB
        lda $B6    ; $16DD
        jsr BuffInsert    ; $16DF
        bne L1735    ; $16E2
        lda $B6    ; $16E4
        jsr GetXCharLen    ; $16E6
        txa    ; $16E9
        sec    ; $16EA
        adc CH    ; $16EB
        cmp WindowRgt    ; $16ED
        bcc L1723    ; $16EF
        ldx CV    ; $16F1
        inx    ; $16F3
        cpx WindowBot    ; $16F4
        bcc L1709    ; $16F6
        jsr CenterPage    ; $16F8
L16FB   lda Argument    ; $16FB
        bne L1703    ; $16FE
        dec $7A5C    ; $1700
L1703   dec Argument    ; $1703
        jmp L16D8    ; $1706
L1709   lda $B6    ; $1709
        jsr CharOut    ; $170B
        jsr ClearEOL    ; $170E
        ldx WindowRgt    ; $1711
        dex    ; $1713
        stx CH    ; $1714
        lda #$A1    ; $1716
        jsr CharOut    ; $1718
        inc $B4    ; $171B
L171D   jsr DisplayDown    ; $171D
        jmp L16FB    ; $1720
L1723   lda $B6    ; $1723
        jsr CharOut    ; $1725
        jsr LinesPastPnt    ; $1728
        cmp $B4    ; $172B
        bne L171D    ; $172D
        jsr DispPointEnd    ; $172F
        jmp L16FB    ; $1732
L1735   jsr Beep    ; $1735
L1738   lda #$00    ; $1738
        rts    ; $173A
;
; === RightChar ===
        jsr GetArgSign    ; $173B
        bmi LeftChar    ; $173E
        jsr ClrLastKill    ; $1740
L1743   jsr ZeroArg?    ; $1743
        beq L175B    ; $1746
        jsr PointForward    ; $1748
        bne L175B    ; $174B
        lda Argument    ; $174D
        bne L1755    ; $1750
        dec $7A5C    ; $1752
L1755   dec Argument    ; $1755
        jmp L1743    ; $1758
L175B   lda #$01    ; $175B
        rts    ; $175D
;
; === LeftChar ===
        jsr GetArgSign    ; $175E
        bmi RightChar    ; $1761
        jsr ClrLastKill    ; $1763
L1766   jsr ZeroArg?    ; $1766
        beq L177E    ; $1769
        jsr PointBackward    ; $176B
        bne L177E    ; $176E
        lda Argument    ; $1770
        bne L1778    ; $1773
        dec $7A5C    ; $1775
L1778   dec Argument    ; $1778
        jmp L1766    ; $177B
L177E   lda #$01    ; $177E
        rts    ; $1780
;
; === NewCenter ===
        jsr GetArgSign    ; $1781
        bmi L179A    ; $1784
        bit ExplicitArg    ; $1786
        bpl L17A6    ; $1789
        jsr L17C2    ; $178B
        lda Argument    ; $178E
L1791   sta CenterPoint    ; $1791
        jsr CenterPage1    ; $1794
        lda #$00    ; $1797
        rts    ; $1799
L179A   jsr L17C2    ; $179A
        lda WindowBot    ; $179D
        clc    ; $179F
        sbc Argument    ; $17A0
        jmp L1791    ; $17A3
L17A6   lda Argument    ; $17A6
        bne L17AE    ; $17A9
        dec $7A5C    ; $17AB
L17AE   dec Argument    ; $17AE
        lda Argument    ; $17B1
        ora $7A5C    ; $17B4
        beq L17BC    ; $17B7
        lda #$03    ; $17B9
        rts    ; $17BB
L17BC   jsr ClearPage    ; $17BC
        lda #$06    ; $17BF
        rts    ; $17C1
L17C2   lda #$00    ; $17C2
        sta $7A5C    ; $17C4
        lda WindowBot    ; $17C7
        sec    ; $17C9
        sbc WindowTop    ; $17CA
        sta $17E0    ; $17CC
        lda Argument    ; $17CF
L17D2   cmp $17E0    ; $17D2
        bcc L17DC    ; $17D5
        sbc $17E0    ; $17D7
        bne L17D2    ; $17DA
L17DC   sta Argument    ; $17DC
        rts    ; $17DF
        brk    ; $17E0
;
; === ScreenEdge ===
        jsr GetArgSign    ; $17E1
        bmi L17FA    ; $17E4
        bit ExplicitArg    ; $17E6
        bpl L1806    ; $17E9
L17EB   jsr L17C2    ; $17EB
L17EE   sta CV    ; $17EE
        lda WindowLft    ; $17F0
        sta CH    ; $17F2
        jsr PointToCH    ; $17F4
        lda #$00    ; $17F7
        rts    ; $17F9
L17FA   jsr L17C2    ; $17FA
        lda WindowBot    ; $17FD
        clc    ; $17FF
        sbc Argument    ; $1800
        jmp L17EE    ; $1803
L1806   lda Argument    ; $1806
        bne L180E    ; $1809
        dec $7A5C    ; $180B
L180E   dec Argument    ; $180E
        jsr ZeroArg?    ; $1811
        beq L1820    ; $1814
        inc Argument    ; $1816
        bne L181E    ; $1819
        inc $7A5C    ; $181B
L181E   bne L17EB    ; $181E
L1820   lda CV    ; $1820
        jmp L17EE    ; $1822
;
; === SkipComment? ===
        dfb $FF        ; $1825  (data/65C02-bit)
;
; === CRLF ===
        jsr ClrLastKill    ; $1826
L1829   jsr ZeroArg?    ; $1829
        beq L1882    ; $182C
        jsr PrintReturn    ; $182E
        jsr LinesPastPnt    ; $1831
        sta $1851    ; $1834
        jsr L188B    ; $1837
        beq L1866    ; $183A
        lda CV    ; $183C
        cmp WindowTop    ; $183E
        beq L1885    ; $1840
        cmp WindowBot    ; $1842
        bcs L1885    ; $1844
        ldx $1851    ; $1846
        beq L1852    ; $1849
        jsr DisplayDown    ; $184B
        jmp L1866    ; $184E
        brk    ; $1851
L1852   pha    ; $1852
        jsr TV:InsLine    ; $1853
        jsr SetGap    ; $1856
        lda WindowLft    ; $1859
        sta CH    ; $185B
        pla    ; $185D
        sta CV    ; $185E
        jsr vtab1    ; $1860
        jsr DispPointEnd    ; $1863
L1866   lda Argument    ; $1866
        bne L186E    ; $1869
        dec $7A5C    ; $186B
L186E   dec Argument    ; $186E
        lda #$04    ; $1871
        ldy #$40    ; $1873
        and (BuffData),y    ; $1875
        beq L1829    ; $1877
        jsr PrevIndent    ; $1879
        jsr GenDisplay    ; $187C
        jmp L1829    ; $187F
L1882   lda #$00    ; $1882
        rts    ; $1884
L1885   jsr CenterPage    ; $1885
        jmp L1866    ; $1888
L188B   jsr SetGap    ; $188B
        lda #$00    ; $188E
        sta $B6    ; $1890
        ldx GapBot    ; $1892
        ldy $6D    ; $1894
        inx    ; $1896
        bne L189A    ; $1897
        iny    ; $1899
L189A   stx $02    ; $189A
        sty $03    ; $189C
        lda BuffBot    ; $189E
        sec    ; $18A0
        sbc GapBot    ; $18A1
        sta $00    ; $18A3
        lda $69    ; $18A5
        sbc $6D    ; $18A7
        sta $01    ; $18A9
        bne L1919    ; $18AB
        lda $00    ; $18AD
        cmp #$04    ; $18AF
        bcs L1919    ; $18B1
L18B3   bit SkipComment?    ; $18B3
        bpl L1913    ; $18B6
        ldy #$00    ; $18B8
        ldx #$00    ; $18BA
        cpx CommentEnd    ; $18BC
        beq L1913    ; $18BF
        bit $B6    ; $18C1
        bmi L1913    ; $18C3
L18C5   lda $03    ; $18C5
        cmp $69    ; $18C7
        bcc L18D1    ; $18C9
        lda $02    ; $18CB
        cmp BuffBot    ; $18CD
        bcs L18E6    ; $18CF
L18D1   jsr $D009    ; $18D1
        cmp #$8D    ; $18D4
        beq L18E6    ; $18D6
        cmp CommentEnd,x    ; $18D8
        bne L1913    ; $18DB
        inc $02    ; $18DD
        bne L18E3    ; $18DF
        inc $03    ; $18E1
L18E3   inx    ; $18E3
        bne L18C5    ; $18E4
L18E6   lda CommentEnd,x    ; $18E6
        bne L1913    ; $18E9
        lda $02    ; $18EB
        sta TheBuffer    ; $18ED
        lda $03    ; $18EF
        sta $61    ; $18F1
        jsr SetGap    ; $18F3
        jsr InsertReturn    ; $18F6
        jsr FindPoint    ; $18F9
        bne L1912    ; $18FC
        lda CV    ; $18FE
        pha    ; $1900
        lda CH    ; $1901
        pha    ; $1903
        jsr DisplayPage    ; $1904
        pla    ; $1907
        sta CH    ; $1908
        pla    ; $190A
        sta CV    ; $190B
        jsr vtab    ; $190D
        lda #$00    ; $1910
L1912   rts    ; $1912
L1913   jsr InsertReturn    ; $1913
        lda #$FF    ; $1916
        rts    ; $1918
L1919   ldy #$00    ; $1919
        ldx #$03    ; $191B
L191D   jsr $D009    ; $191D
        cmp #$89    ; $1920
        beq L192F    ; $1922
        cmp #$A0    ; $1924
        beq L192F    ; $1926
        cmp #$8D    ; $1928
        bne L18B3    ; $192A
        dex    ; $192C
        sta $B6    ; $192D
L192F   inx    ; $192F
        dex    ; $1930
        beq L194A    ; $1931
        inc $02    ; $1933
        bne L1939    ; $1935
        inc $03    ; $1937
L1939   lda $00    ; $1939
        bne L193F    ; $193B
        dec $01    ; $193D
L193F   dec $00    ; $193F
        lda $00    ; $1941
        ora $01    ; $1943
        bne L191D    ; $1945
        jmp L18B3    ; $1947
L194A   inc GapBot    ; $194A
        bne L1950    ; $194C
        inc $6D    ; $194E
L1950   jsr $D03F    ; $1950
        cmp #$8D    ; $1953
        bne L194A    ; $1955
        lda GapBot    ; $1957
        bne L195D    ; $1959
        dec $6D    ; $195B
L195D   dec GapBot    ; $195D
        jsr PointForward    ; $195F
        jsr SetGap    ; $1962
        jsr FindPoint    ; $1965
        rts    ; $1968
;
; === InsertReturn ===
        lda #$8D    ; $1969
        jmp BuffInsert    ; $196B
;
; === OpenLine ===
        jsr ClrLastKill    ; $196E
        lda $7A5C    ; $1971
        bne L1980    ; $1974
        lda WindowBot    ; $1976
        sec    ; $1978
        sbc CV    ; $1979
        cmp Argument    ; $197B
        bcs L19B1    ; $197E
L1980   jsr SetGap    ; $1980
        lda $61    ; $1983
        pha    ; $1985
        lda TheBuffer    ; $1986
        pha    ; $1988
L1989   lda Argument    ; $1989
        ora $7A5C    ; $198C
        beq L19A2    ; $198F
        jsr InsertReturn    ; $1991
        lda Argument    ; $1994
        bne L199C    ; $1997
        dec $7A5C    ; $1999
L199C   dec Argument    ; $199C
        jmp L1989    ; $199F
L19A2   pla    ; $19A2
        sta TheBuffer    ; $19A3
        pla    ; $19A5
        sta $61    ; $19A6
        jsr SetGap    ; $19A8
        jsr ClearEOP    ; $19AB
        lda #$00    ; $19AE
        rts    ; $19B0
L19B1   jsr ZeroArg?    ; $19B1
        bne L19B9    ; $19B4
        jmp L1A3E    ; $19B6
L19B9   jsr LinesPastPnt    ; $19B9
        pha    ; $19BC
        jsr SetGap    ; $19BD
        lda $61    ; $19C0
        pha    ; $19C2
        lda TheBuffer    ; $19C3
        pha    ; $19C5
        jsr InsertReturn    ; $19C6
        pla    ; $19C9
        sta TheBuffer    ; $19CA
        pla    ; $19CC
        sta $61    ; $19CD
        jsr SetGap    ; $19CF
        jsr ClearEOL    ; $19D2
        ldx CV    ; $19D5
        inx    ; $19D7
        cpx WindowBot    ; $19D8
        bcs L1A3A    ; $19DA
        lda GapBot    ; $19DC
        clc    ; $19DE
        adc #$02    ; $19DF
        tax    ; $19E1
        lda $6D    ; $19E2
        adc #$00    ; $19E4
        cmp $69    ; $19E6
        bne L19EE    ; $19E8
        cpx BuffBot    ; $19EA
        beq L1A3A    ; $19EC
L19EE   pla    ; $19EE
        beq L19F7    ; $19EF
        jsr DisplayDown    ; $19F1
        jmp L1A2C    ; $19F4
L19F7   lda CV    ; $19F7
        pha    ; $19F9
        lda CH    ; $19FA
        pha    ; $19FC
        inc CV    ; $19FD
        jsr TV:InsLine    ; $19FF
        ldy #$02    ; $1A02
        jsr $D03F    ; $1A04
        cmp #$8D    ; $1A07
        beq L1A23    ; $1A09
        tya    ; $1A0B
        clc    ; $1A0C
        adc GapBot    ; $1A0D
        sta TheBuffer    ; $1A0F
        lda #$00    ; $1A11
        adc $6D    ; $1A13
        sta $61    ; $1A15
        jsr SetGap    ; $1A17
        jsr DispPointEnd    ; $1A1A
        jsr PointBackward    ; $1A1D
        jsr SetGap    ; $1A20
L1A23   pla    ; $1A23
        sta CH    ; $1A24
        pla    ; $1A26
        sta CV    ; $1A27
        jsr vtab1    ; $1A29
L1A2C   lda Argument    ; $1A2C
        bne L1A34    ; $1A2F
        dec $7A5C    ; $1A31
L1A34   dec Argument    ; $1A34
        jmp L19B1    ; $1A37
L1A3A   pla    ; $1A3A
        jmp L1A2C    ; $1A3B
L1A3E   lda #$00    ; $1A3E
        rts    ; $1A40
;
; === GotoTop ===
        jsr ClrLastKill    ; $1A41
        lda TheBuffer    ; $1A44
        sta $00    ; $1A46
        lda $61    ; $1A48
        sta $01    ; $1A4A
        lda BuffTop    ; $1A4C
        sta TheBuffer    ; $1A4E
        lda $67    ; $1A50
        sta $61    ; $1A52
        jsr MovePush?    ; $1A54
        lda #$06    ; $1A57
        rts    ; $1A59
;
; === GotoBot ===
        jsr ClrLastKill    ; $1A5A
        lda $61    ; $1A5D
        pha    ; $1A5F
        lda TheBuffer    ; $1A60
        pha    ; $1A62
        lda BuffBot    ; $1A63
        sta TheBuffer    ; $1A65
        lda $69    ; $1A67
        sta $61    ; $1A69
        jsr SetGap    ; $1A6B
        pla    ; $1A6E
        sta $00    ; $1A6F
        pla    ; $1A71
        sta $01    ; $1A72
        jsr MovePush?    ; $1A74
        lda #$01    ; $1A77
        rts    ; $1A79
;
; === MovePush? ===
        lda $01    ; $1A7A
        cmp TheBuffer    ; $1A7C
        bcc L1A99    ; $1A7E
        beq L1A98    ; $1A80
        lda $00    ; $1A82
        sec    ; $1A84
        sbc TheBuffer    ; $1A85
        tax    ; $1A87
        lda $01    ; $1A88
        sbc $61    ; $1A8A
L1A8C   cmp $1586    ; $1A8C
        bcc L1A98    ; $1A8F
        bne L1AA6    ; $1A91
        cpx AutoPushPoint    ; $1A93
        bcs L1AA6    ; $1A96
L1A98   rts    ; $1A98
L1A99   lda TheBuffer    ; $1A99
        sec    ; $1A9B
        sbc $00    ; $1A9C
        tax    ; $1A9E
        lda $61    ; $1A9F
        sbc $01    ; $1AA1
        jmp L1A8C    ; $1AA3
L1AA6   lda $61    ; $1AA6
        pha    ; $1AA8
        lda TheBuffer    ; $1AA9
        pha    ; $1AAB
        lda $00    ; $1AAC
        sta TheBuffer    ; $1AAE
        lda $01    ; $1AB0
        sta $61    ; $1AB2
        jsr PushMark    ; $1AB4
        pla    ; $1AB7
        sta TheBuffer    ; $1AB8
        pla    ; $1ABA
        sta $61    ; $1ABB
        jsr NewEchoArea    ; $1ABD
        jsr PrintMessage    ; $1AC0
; ---- $1AC3-$1AD0  data  msg: Point pushed. ----
        dfb $D0,$EF,$E9,$EE,$F4,$A0,$F0,$F5,$F3,$E8,$E5,$E4,$AE,$00    ; $1AC3  Point pushed..
; ---- $1AD1-$1AD4  code ----
        jsr CloseEchoArea    ; $1AD1
        rts    ; $1AD4
