;-*- Mode: Merlin -*-
;
; src/modules/05_command.s -- AMACS: prefix dispatch, mode toggles, comments, fill, paragraphs, indent
; Address range $1AD5-$2603. GENERATED by tools/disasm.py.
; `put' from src/amacs.s; symbols/labels are global across modules.
;
; ---- $1AD5-$1B38  code ----
;
; === PrefixMeta ===
        lda #$00    ; $1AD5
        jsr L1B4E    ; $1AD7
        ldx #$01    ; $1ADA
        bne L1AF2    ; $1ADC
;
; === PrefixCtrl ===
        lda #$01    ; $1ADE
        jsr L1B4E    ; $1AE0
        ldx #$02    ; $1AE3
        cmp #$80    ; $1AE5
        bcc L1AF7    ; $1AE7
        bcs L1AF2    ; $1AE9
;
; === PrefixCMeta ===
        lda #$02    ; $1AEB
        jsr L1B4E    ; $1AED
        ldx #$00    ; $1AF0
L1AF2   ora #$80    ; $1AF2
        jsr UpperCon    ; $1AF4
L1AF7   and $1AFD,x    ; $1AF7
        jmp Dispatch    ; $1AFA
        dfb $3F        ; $1AFD  (data/65C02-bit)
        dfb $7F        ; $1AFE  (data/65C02-bit)
        dfb $BF        ; $1AFF  (data/65C02-bit)
;
; === ControlX ===
        lda #$04    ; $1B00
        jsr L1B4E    ; $1B02
        cmp #$80    ; $1B05
        bcc L1B32    ; $1B07
        ldx #$00    ; $1B09
        jsr UpperCon    ; $1B0B
L1B0E   cmp C_XCharacters,x    ; $1B0E
        beq L1B1C    ; $1B11
        inx    ; $1B13
        cpx C_XCharCount    ; $1B14
        bcc L1B0E    ; $1B17
        jmp L1B32    ; $1B19
L1B1C   txa    ; $1B1C
        asl    ; $1B1D
        tax    ; $1B1E
        lda C_XVectors,x    ; $1B1F
        sta $00    ; $1B22
        sta CommandVector    ; $1B24
        lda $7DDF,x    ; $1B27
        sta $01    ; $1B2A
        sta $7835    ; $1B2C
        jmp ($0000)    ; $1B2F
L1B32   pha    ; $1B32
        jsr NewEchoArea    ; $1B33
        jsr PrintMessage    ; $1B36
; ---- $1B39-$1B3D  data  msg: C-X ----
        dfb $C3,$AD,$D8,$A0,$00    ; $1B39  C-X .
; ---- $1B3E-$1C56  code ----
        pla    ; $1B3E
        jsr PrettyPrint    ; $1B3F
        jsr PrUnDefined    ; $1B42
        jsr Beep    ; $1B45
        jsr CloseEchoArea    ; $1B48
        lda #$01    ; $1B4B
        rts    ; $1B4D
L1B4E   jsr PreCharGet    ; $1B4E
        php    ; $1B51
        cmp #$87    ; $1B52
        beq L1B63    ; $1B54
        sta $00    ; $1B56
        plp    ; $1B58
        beq L1B62    ; $1B59
        ora #$80    ; $1B5B
        jsr EchoOutput    ; $1B5D
        lda $00    ; $1B60
L1B62   rts    ; $1B62
L1B63   jsr Beep    ; $1B63
        lda #$87    ; $1B66
        jsr EchoOutput    ; $1B68
        plp    ; $1B6B
        pla    ; $1B6C
        pla    ; $1B6D
        lda #$01    ; $1B6E
        rts    ; $1B70
;
; === RSrch ===
        lda #$FF    ; $1B71
        eor ArgSign    ; $1B73
        sta ArgSign    ; $1B76
;
; === ISrch ===
        lda ArgSign    ; $1B79
        sta ISearchDir    ; $1B7C
        jsr ClrLastKill    ; $1B7F
        jsr ISearch    ; $1B82
        lda #$01    ; $1B85
        rts    ; $1B87
;
; === RWordSearch ===
        lda ArgSign    ; $1B88
        eor #$FF    ; $1B8B
        sta ArgSign    ; $1B8D
;
; === WordSearch ===
        jsr ClrLastKill    ; $1B90
        lda ArgSign    ; $1B93
        jsr StrSearch    ; $1B96
        lda #$01    ; $1B99
        rts    ; $1B9B
;
; === TabsIndent ===
        dfb $FF        ; $1B9C  (data/65C02-bit)
;
; === SetTabsIndent ===
        lda ArgSign    ; $1B9D
        sta TabsIndent    ; $1BA0
        lda #$01    ; $1BA3
        rts    ; $1BA5
;
; === NotModified ===
        lda Modified?    ; $1BA6
        eor #$FF    ; $1BA9
        jsr SetAModified    ; $1BAB
        lda #$01    ; $1BAE
        rts    ; $1BB0
;
; === QuotedInsert ===
        jsr BlinkCursor    ; $1BB1
        jmp Insert    ; $1BB4
;
; === UpLine ===
        lda #$77    ; $1BB7
        sta $00    ; $1BB9
        lda #$34    ; $1BBB
        sta $01    ; $1BBD
        jmp L1BCA    ; $1BBF
;
; === DownLine ===
        lda #$39    ; $1BC2
        sta $00    ; $1BC4
        lda #$34    ; $1BC6
        sta $01    ; $1BC8
L1BCA   jsr ClrLastKill    ; $1BCA
        lda #$1B    ; $1BCD
        cmp $7837    ; $1BCF
        bne L1BDB    ; $1BD2
        lda #$B7    ; $1BD4
        cmp LastComVect    ; $1BD6
        beq L1BF1    ; $1BD9
L1BDB   lda #$1B    ; $1BDB
        cmp $7837    ; $1BDD
        bne L1BE9    ; $1BE0
        lda #$C2    ; $1BE2
        cmp LastComVect    ; $1BE4
        beq L1BF1    ; $1BE7
L1BE9   lda #$00    ; $1BE9
        sta GoalColumn    ; $1BEB
        sta $3407    ; $1BEE
L1BF1   jmp ($0000)    ; $1BF1
;
; === TopAbort ===
        jsr Beep    ; $1BF4
        jsr ClrEchoArea    ; $1BF7
        lda #$00    ; $1BFA
        sta MacroDef    ; $1BFC
        sta MacroExec    ; $1BFF
        jsr MakeModeLine    ; $1C02
        lda #$01    ; $1C05
        rts    ; $1C07
;
; === AtomMode ===
        lda #$01    ; $1C08
        bne ToggleMode    ; $1C0A
;
; === IndentMode ===
        lda #$04    ; $1C0C
        bne ToggleMode    ; $1C0E
;
; === AutoMode ===
        lda #$02    ; $1C10
        bne ToggleMode    ; $1C12
;
; === CapsMode ===
        lda #$10    ; $1C14
;
; === ToggleMode ===
        sta $1C47    ; $1C16
        ldy #$40    ; $1C19
        jsr AnyArgument?    ; $1C1B
        bne L1C27    ; $1C1E
        lda ArgSign    ; $1C20
        bpl L1C2E    ; $1C23
        bmi L1C3B    ; $1C25
L1C27   lda $1C47    ; $1C27
        and (BuffData),y    ; $1C2A
        bne L1C3B    ; $1C2C
L1C2E   lda $1C47    ; $1C2E
        ora (BuffData),y    ; $1C31
        sta (BuffData),y    ; $1C33
L1C35   jsr MakeModeLine    ; $1C35
        lda #$01    ; $1C38
        rts    ; $1C3A
L1C3B   lda $1C47    ; $1C3B
        eor #$FF    ; $1C3E
        and (BuffData),y    ; $1C40
        sta (BuffData),y    ; $1C42
        jmp L1C35    ; $1C44
        brk    ; $1C47
;
; === PointInfo ===
        jsr FindPoint    ; $1C48
        lda CV    ; $1C4B
        pha    ; $1C4D
        lda CH    ; $1C4E
        pha    ; $1C50
        jsr NewEchoArea    ; $1C51
        jsr PrintMessage    ; $1C54
; ---- $1C57-$1C5A  data  msg: X = ----
        dfb $D8,$A0,$BD,$00    ; $1C57  X =.
; ---- $1C5B-$1C61  code ----
        pla    ; $1C5B
        jsr L1CC6    ; $1C5C
        jsr PrintMessage    ; $1C5F
; ---- $1C62-$1C67  data  msg: , Y = ----
        dfb $AC,$A0,$D9,$A0,$BD,$00    ; $1C62  , Y =.
; ---- $1C68-$1C6E  code ----
        pla    ; $1C68
        jsr L1CC6    ; $1C69
        jsr PrintMessage    ; $1C6C
; ---- $1C6F-$1C76  data  msg: ,  CH = ----
        dfb $AC,$A0,$A0,$C3,$C8,$A0,$BD,$00    ; $1C6F  ,  CH =.
; ---- $1C77-$1C83  code ----
        iny    ; $1C77
        jsr $D03F    ; $1C78
        pha    ; $1C7B
        eor #$80    ; $1C7C
        jsr L1CC6    ; $1C7E
        jsr PrintMessage    ; $1C81
; ---- $1C84-$1C86  data  msg:  ( ----
        dfb $A0,$A8,$00    ; $1C84   (.
; ---- $1C87-$1C8D  code ----
        pla    ; $1C87
        jsr PrettyPrint    ; $1C88
        jsr PrintMessage    ; $1C8B
; ---- $1C8E-$1C9C  data  msg: ).Point is at ----
        dfb $A9,$89,$D0,$EF,$E9,$EE,$F4,$A0,$E9,$F3,$A0,$E1,$F4,$A0,$00    ; $1C8E  ).Point is at .
; ---- $1C9D-$1CAC  code ----
        sec    ; $1C9D
        lda TheBuffer    ; $1C9E
        sbc BuffTop    ; $1CA0
        tax    ; $1CA2
        lda $61    ; $1CA3
        sbc $67    ; $1CA5
        jsr PrintDec    ; $1CA7
        jsr PrintMessage    ; $1CAA
; ---- $1CAD-$1CB1  data  msg:  of ----
        dfb $A0,$EF,$E6,$A0,$00    ; $1CAD   of .
; ---- $1CB2-$20D7  code ----
        ldx SelectedBuff    ; $1CB2
        jsr MySize    ; $1CB5
        jsr PrintDec    ; $1CB8
        lda #$AE    ; $1CBB
        jsr CharOut    ; $1CBD
        jsr CloseEchoArea    ; $1CC0
        lda #$01    ; $1CC3
        rts    ; $1CC5
L1CC6   tax    ; $1CC6
        jsr ZeroJustify    ; $1CC7
        jmp PrintDec    ; $1CCA
;
; === WhatLossage ===
        jsr OpenTypeout    ; $1CCD
        lda TYI_PopIndex    ; $1CD0
        sec    ; $1CD3
        sbc #$3C    ; $1CD4
L1CD6   and #$3F    ; $1CD6
        sta $1CFE    ; $1CD8
        ldx $1CFE    ; $1CDB
        cpx TYI_PopIndex    ; $1CDE
        beq L1CF7    ; $1CE1
        lda TYIBuff,x    ; $1CE3
        beq L1CEE    ; $1CE6
        jsr PrettyPrint    ; $1CE8
        jsr PrintSpace    ; $1CEB
L1CEE   inc $1CFE    ; $1CEE
        lda $1CFE    ; $1CF1
        jmp L1CD6    ; $1CF4
L1CF7   jsr CloseTypeout    ; $1CF7
        lda #$01    ; $1CFA
        rts    ; $1CFC
        brk    ; $1CFD
        brk    ; $1CFE
;
; === CommentColumn ===
        jsr $00BB    ; $1CFF
        ds 10        ; $1D02  10 bytes $00 fill
;
; === StringInLine ===
        jsr SetGap    ; $1D0C
        lda GapBot    ; $1D0F
        sta $00    ; $1D11
        lda $6D    ; $1D13
        sta $01    ; $1D15
        ldy #$00    ; $1D17
L1D19   lda StringPntr    ; $1D19
        sta $02    ; $1D1C
        lda $1D0B    ; $1D1E
        sta $03    ; $1D21
L1D23   inc $00    ; $1D23
        bne L1D29    ; $1D25
        inc $01    ; $1D27
L1D29   lda $00    ; $1D29
        cmp BuffBot    ; $1D2B
        bne L1D44    ; $1D2D
        lda $01    ; $1D2F
        cmp $69    ; $1D31
        bne L1D44    ; $1D33
        lda ($02),y    ; $1D35
        beq L1D67    ; $1D37
        lda $00    ; $1D39
        bne L1D3F    ; $1D3B
        dec $01    ; $1D3D
L1D3F   dec $00    ; $1D3F
L1D41   lda #$FF    ; $1D41
        rts    ; $1D43
L1D44   lda ($02),y    ; $1D44
        beq L1D67    ; $1D46
        jsr UpperCon    ; $1D48
        sta $1D8A    ; $1D4B
        jsr $D000    ; $1D4E
        cmp #$8D    ; $1D51
        beq L1D41    ; $1D53
        ora #$80    ; $1D55
        jsr UpperCon    ; $1D57
        cmp $1D8A    ; $1D5A
        bne L1D19    ; $1D5D
        inc $02    ; $1D5F
        bne L1D65    ; $1D61
        inc $03    ; $1D63
L1D65   bne L1D23    ; $1D65
L1D67   lda StringPntr    ; $1D67
        sta $02    ; $1D6A
        lda $1D0B    ; $1D6C
        sta $03    ; $1D6F
L1D71   lda ($02),y    ; $1D71
        beq L1D78    ; $1D73
        iny    ; $1D75
        bne L1D71    ; $1D76
L1D78   sty $02    ; $1D78
        lda $00    ; $1D7A
        sec    ; $1D7C
        sbc $02    ; $1D7D
        sta $00    ; $1D7F
        lda $01    ; $1D81
        sbc #$00    ; $1D83
        sta $01    ; $1D85
        lda #$00    ; $1D87
        rts    ; $1D89
        brk    ; $1D8A
        brk    ; $1D8B
;
; === MakeComment ===
        jsr ClrLastKill    ; $1D8C
        jsr SetModified    ; $1D8F
        lda #$00    ; $1D92
        sta $1D8B    ; $1D94
        jsr FindComment    ; $1D97
        php    ; $1D9A
        jsr FindPoint    ; $1D9B
        jsr LinesPastPnt    ; $1D9E
        sta $1E69    ; $1DA1
        jsr DeleteSpace    ; $1DA4
        plp    ; $1DA7
        beq L1DC9    ; $1DA8
        ldy #$FF    ; $1DAA
        sty $1D8B    ; $1DAC
L1DAF   iny    ; $1DAF
        lda CommentBegin,y    ; $1DB0
        beq L1DBA    ; $1DB3
        jsr $D06F    ; $1DB5
        bne L1DAF    ; $1DB8
L1DBA   tya    ; $1DBA
        clc    ; $1DBB
        adc TheBuffer    ; $1DBC
        sta GapTop    ; $1DBE
        lda $61    ; $1DC0
        adc #$00    ; $1DC2
        sta $6B    ; $1DC4
        jsr SetGap    ; $1DC6
L1DC9   jsr FindPoint    ; $1DC9
        beq L1DD6    ; $1DCC
        jsr CenterPage    ; $1DCE
        lda #$FF    ; $1DD1
        sta $1E69    ; $1DD3
L1DD6   lda CH    ; $1DD6
        cmp WindowLft    ; $1DD8
        beq L1E1D    ; $1DDA
        cmp CommentColumn    ; $1DDC
        beq L1E1D    ; $1DDF
        bcs L1E10    ; $1DE1
        lda CommentColumn    ; $1DE3
        cmp WindowRgt    ; $1DE6
        bcs L1E1D    ; $1DE8
        bit TabsIndent    ; $1DEA
        bpl L1E09    ; $1DED
L1DEF   lda #$89    ; $1DEF
        jsr GetXCharLen    ; $1DF1
        txa    ; $1DF4
        clc    ; $1DF5
        adc CH    ; $1DF6
        cmp CommentColumn    ; $1DF8
        beq L1DFF    ; $1DFB
        bcs L1E09    ; $1DFD
L1DFF   jsr BumpXPos    ; $1DFF
        lda #$89    ; $1E02
        jsr BuffInsert    ; $1E04
        beq L1DEF    ; $1E07
L1E09   lda CH    ; $1E09
        cmp CommentColumn    ; $1E0B
        bcs L1E1D    ; $1E0E
L1E10   lda #$A0    ; $1E10
        jsr BuffInsert    ; $1E12
        ldx #$01    ; $1E15
        jsr BumpXPos    ; $1E17
        jmp L1E09    ; $1E1A
L1E1D   jsr SetGap    ; $1E1D
        jsr L1F94    ; $1E20
        iny    ; $1E23
        tya    ; $1E24
        clc    ; $1E25
        adc GapBot    ; $1E26
        sta TheBuffer    ; $1E28
        lda $6D    ; $1E2A
        adc #$00    ; $1E2C
        sta $61    ; $1E2E
        jsr SetGap    ; $1E30
        bit $1D8B    ; $1E33
        bpl L1E4F    ; $1E36
        ldy #$00    ; $1E38
L1E3A   lda CommentEnd,y    ; $1E3A
        beq L1E45    ; $1E3D
        jsr $D08A    ; $1E3F
        iny    ; $1E42
        bne L1E3A    ; $1E43
L1E45   tya    ; $1E45
        clc    ; $1E46
        adc GapTop    ; $1E47
        sta GapTop    ; $1E49
        bcc L1E4F    ; $1E4B
        inc $6B    ; $1E4D
L1E4F   jsr SetGap    ; $1E4F
        jsr DisplayLine    ; $1E52
        bit $1E69    ; $1E55
        bmi L1E68    ; $1E58
        jsr FindPoint    ; $1E5A
        jsr LinesPastPnt    ; $1E5D
        cmp $1E69    ; $1E60
        beq L1E68    ; $1E63
        jsr DisplayDown    ; $1E65
L1E68   rts    ; $1E68
        brk    ; $1E69
;
; === KillComment ===
        jsr FindComment    ; $1E6A
        php    ; $1E6D
        jsr DeleteSpace    ; $1E6E
        plp    ; $1E71
        bne L1E77    ; $1E72
        jmp KillLine    ; $1E74
L1E77   lda #$01    ; $1E77
        rts    ; $1E79
;
; === CommentLine ===
        jsr AnyArgument?    ; $1E7A
        bne CommentLineI    ; $1E7D
        lda CommentColumn    ; $1E7F
        pha    ; $1E82
        lda Argument    ; $1E83
        sta CommentColumn    ; $1E86
        jsr CommentLineI    ; $1E89
        pla    ; $1E8C
        sta CommentColumn    ; $1E8D
        lda #$01    ; $1E90
        rts    ; $1E92
;
; === CommentLineI ===
        lda CommentBegin    ; $1E93
        beq L1E9D    ; $1E96
        jsr MakeComment    ; $1E98
        lda #$01    ; $1E9B
L1E9D   rts    ; $1E9D
;
; === UpCommLine ===
        lda ArgSign    ; $1E9E
        eor #$FF    ; $1EA1
        sta ArgSign    ; $1EA3
;
; === DownCommLine ===
        lda CommentBegin    ; $1EA6
        beq L1EE6    ; $1EA9
        jsr GetArgSign    ; $1EAB
        sta $1EE9    ; $1EAE
L1EB1   jsr ZeroArg?    ; $1EB1
        beq L1EE6    ; $1EB4
        lda $7A5C    ; $1EB6
        pha    ; $1EB9
        lda Argument    ; $1EBA
        pha    ; $1EBD
        jsr InitArgument    ; $1EBE
        lda $1EE9    ; $1EC1
        sta ArgSign    ; $1EC4
        jsr DelBlankComm    ; $1EC7
        jsr DownLine    ; $1ECA
        jsr CommentLineI    ; $1ECD
        pla    ; $1ED0
        sta Argument    ; $1ED1
        pla    ; $1ED4
        sta $7A5C    ; $1ED5
        lda Argument    ; $1ED8
        bne L1EE0    ; $1EDB
        dec $7A5C    ; $1EDD
L1EE0   dec Argument    ; $1EE0
        jmp L1EB1    ; $1EE3
L1EE6   lda #$01    ; $1EE6
        rts    ; $1EE8
        brk    ; $1EE9
;
; === FindComment ===
        lda CommentBegin    ; $1EEA
        cmp #$BB    ; $1EED
        bne L1F13    ; $1EEF
        lda $1D01    ; $1EF1
        ora CommentEnd    ; $1EF4
        bne L1F13    ; $1EF7
        jsr L1F13    ; $1EF9
        bne L1F30    ; $1EFC
        jsr PointBackward    ; $1EFE
        bne L1F31    ; $1F01
        jsr $D01B    ; $1F03
        jsr WhiteSpace?    ; $1F06
        beq L1F31    ; $1F09
        jsr PointForward    ; $1F0B
        jsr PointForward    ; $1F0E
        beq L1F20    ; $1F11
L1F13   lda #$00    ; $1F13
        sta StringPntr    ; $1F15
        lda #$1D    ; $1F18
        sta $1D0B    ; $1F1A
        jsr BegOfLine    ; $1F1D
L1F20   jsr SetGap    ; $1F20
        jsr StringInLine    ; $1F23
        beq L1F31    ; $1F26
        jsr EndOfLine    ; $1F28
        jsr SetGap    ; $1F2B
        lda #$FF    ; $1F2E
L1F30   rts    ; $1F30
L1F31   lda $00    ; $1F31
        sta TheBuffer    ; $1F33
        lda $01    ; $1F35
        sta $61    ; $1F37
        jsr SetGap    ; $1F39
        lda #$00    ; $1F3C
        rts    ; $1F3E
;
; === DelBlankComm ===
        jsr FindComment    ; $1F3F
        bne L1F7B    ; $1F42
        jsr L1F94    ; $1F44
        iny    ; $1F47
        ldx #$00    ; $1F48
        stx $1F93    ; $1F4A
L1F4D   tya    ; $1F4D
        sec    ; $1F4E
        adc GapBot    ; $1F4F
        tax    ; $1F51
        lda $6D    ; $1F52
        adc #$00    ; $1F54
        cmp $69    ; $1F56
        bne L1F5E    ; $1F58
        cpx BuffBot    ; $1F5A
        beq L1F71    ; $1F5C
L1F5E   jsr $D03F    ; $1F5E
        cmp #$8D    ; $1F61
        beq L1F70    ; $1F63
        cmp #$89    ; $1F65
        beq L1F6D    ; $1F67
        cmp #$A0    ; $1F69
        bne L1F82    ; $1F6B
L1F6D   iny    ; $1F6D
        bne L1F4D    ; $1F6E
L1F70   dey    ; $1F70
L1F71   tya    ; $1F71
        clc    ; $1F72
        adc GapBot    ; $1F73
        sta GapBot    ; $1F75
        bcc L1F7B    ; $1F77
        inc $6D    ; $1F79
L1F7B   jsr DeleteSpace    ; $1F7B
        jsr DisplayLine    ; $1F7E
L1F81   rts    ; $1F81
L1F82   ldx $1F93    ; $1F82
        inc $1F93    ; $1F85
        lda CommentEnd,x    ; $1F88
        beq L1F81    ; $1F8B
        jsr $D09C    ; $1F8D
        beq L1F6D    ; $1F90
        rts    ; $1F92
        brk    ; $1F93
L1F94   ldy #$00    ; $1F94
L1F96   lda CommentBegin,y    ; $1F96
        beq L1F9E    ; $1F99
        iny    ; $1F9B
        bne L1F96    ; $1F9C
L1F9E   rts    ; $1F9E
;
; === SpaceBar ===
        lda #$02    ; $1F9F
        ldy #$40    ; $1FA1
        and (BuffData),y    ; $1FA3
        bne AutoFill    ; $1FA5
L1FA7   lda #$A0    ; $1FA7
        jmp Insert    ; $1FA9
;
; === FillColumn ===
        lsr: $00A0    ; $1FAC
        jsr L20F6    ; $1FAF
L1FB2   jsr CleanBegLine    ; $1FB2
        lda #$00    ; $1FB5
        sta $EB    ; $1FB7
        sta $EF    ; $1FB9
L1FBB   jsr L2108    ; $1FBB
        bne L1FE9    ; $1FBE
        bit EnableKDisp    ; $1FC0
        bpl L1FA7    ; $1FC3
        jsr FindPoint    ; $1FC5
        beq L1FD4    ; $1FC8
        jsr CenterPage    ; $1FCA
L1FCD   lda #$00    ; $1FCD
        sta EnableKDisp    ; $1FCF
        beq L1FA7    ; $1FD2
L1FD4   lda CV    ; $1FD4
        pha    ; $1FD6
        lda CH    ; $1FD7
        pha    ; $1FD9
        jsr DisplayPage    ; $1FDA
        pla    ; $1FDD
        sta CH    ; $1FDE
        pla    ; $1FE0
        sta CV    ; $1FE1
        jsr vtab1    ; $1FE3
        jmp L1FCD    ; $1FE6
L1FE9   jsr $D01B    ; $1FE9
        cmp #$A0    ; $1FEC
        bne L1FFA    ; $1FEE
        lda TheBuffer    ; $1FF0
        sta $EE    ; $1FF2
        lda $61    ; $1FF4
        sta $EF    ; $1FF6
        lda #$A0    ; $1FF8
L1FFA   tax    ; $1FFA
        inc TheBuffer    ; $1FFB
        bne L2001    ; $1FFD
        inc $61    ; $1FFF
L2001   jsr GatherTYI    ; $2001
        lda CH    ; $2004
        pha    ; $2006
        lda $EB    ; $2007
        sta CH    ; $2009
        txa    ; $200B
        jsr GetXCharLen    ; $200C
        pla    ; $200F
        sta CH    ; $2010
        txa    ; $2012
        clc    ; $2013
        adc $EB    ; $2014
        sta $EB    ; $2016
        cmp FillColumn    ; $2018
        bcc L1FBB    ; $201B
        lda $EF    ; $201D
        beq L1FBB    ; $201F
        sta $01    ; $2021
        lda $EE    ; $2023
        sta $00    ; $2025
        lda #$8D    ; $2027
        jsr $D054    ; $2029
        sta EnableKDisp    ; $202C
        lda $00    ; $202F
        sta TheBuffer    ; $2031
        lda $01    ; $2033
        sta $61    ; $2035
        inc TheBuffer    ; $2037
        bne L203D    ; $2039
        inc $61    ; $203B
L203D   lda FillPrefix    ; $203D
        bne L2045    ; $2040
        jmp L1FB2    ; $2042
L2045   lda $EC    ; $2045
        sec    ; $2047
        sbc TheBuffer    ; $2048
        sta $F0    ; $204A
        lda $ED    ; $204C
        sbc $61    ; $204E
        sta $F1    ; $2050
        lda #$00    ; $2052
        sta $EA    ; $2054
        jsr SetGap    ; $2056
L2059   ldy $EA    ; $2059
        lda FillPrefix,y    ; $205B
        beq L2067    ; $205E
        jsr BuffInsert    ; $2060
        inc $EA    ; $2063
        bne L2059    ; $2065
L2067   lda $61    ; $2067
        pha    ; $2069
        lda TheBuffer    ; $206A
        pha    ; $206C
        lda $F0    ; $206D
        sec    ; $206F
        adc GapBot    ; $2070
        sta TheBuffer    ; $2072
        lda $F1    ; $2074
        adc $6D    ; $2076
        sta $61    ; $2078
        jsr SetGap    ; $207A
        jsr L20F6    ; $207D
        pla    ; $2080
        sta TheBuffer    ; $2081
        pla    ; $2083
        sta $61    ; $2084
        jmp L1FB2    ; $2086
;
; === CleanBegLine ===
        jsr BegOfLine    ; $2089
        lda $61    ; $208C
        cmp $6B    ; $208E
        bcc L20A4    ; $2090
        bne L209C    ; $2092
        lda TheBuffer    ; $2094
        cmp GapTop    ; $2096
        beq L20A4    ; $2098
        bcc L20A4    ; $209A
L209C   lda GapTop    ; $209C
        sta TheBuffer    ; $209E
        lda $6B    ; $20A0
        sta $61    ; $20A2
L20A4   rts    ; $20A4
;
; === FillPrefix ===
        ds 7        ; $20A5  7 bytes $00 fill
;
; === SetFillPrefix ===
        jsr SetGap    ; $20AC
        jsr L20F6    ; $20AF
        jsr CleanBegLine    ; $20B2
        ldx #$00    ; $20B5
L20B7   jsr L2108    ; $20B7
        beq L20CD    ; $20BA
        jsr $D01B    ; $20BC
        sta FillPrefix,x    ; $20BF
        inc TheBuffer    ; $20C2
        bne L20C8    ; $20C4
        inc $61    ; $20C6
L20C8   inx    ; $20C8
        cpx #$06    ; $20C9
        bcc L20B7    ; $20CB
L20CD   lda #$00    ; $20CD
        sta FillPrefix,x    ; $20CF
        jsr NewEchoArea    ; $20D2
        jsr PrintMessage    ; $20D5
; ---- $20D8-$20DC  data  msg: .= " ----
        dfb $AE,$BD,$A0,$A2,$00    ; $20D8  .= ".
; ---- $20DD-$214C  code ----
L20DD   lda FillPrefix,y    ; $20DD
        beq L20E8    ; $20E0
        jsr CharOut    ; $20E2
        iny    ; $20E5
        bne L20DD    ; $20E6
L20E8   lda #$A2    ; $20E8
        jsr CharOut    ; $20EA
        jsr CloseEchoArea    ; $20ED
        jsr L20FF    ; $20F0
        lda #$01    ; $20F3
        rts    ; $20F5
L20F6   lda TheBuffer    ; $20F6
        sta $EC    ; $20F8
        lda $61    ; $20FA
        sta $ED    ; $20FC
        rts    ; $20FE
L20FF   lda $EC    ; $20FF
        sta TheBuffer    ; $2101
        lda $ED    ; $2103
        sta $61    ; $2105
        rts    ; $2107
L2108   lda TheBuffer    ; $2108
        cmp $EC    ; $210A
        bne L2112    ; $210C
        lda $61    ; $210E
        cmp $ED    ; $2110
L2112   rts    ; $2112
;
; === WhatSpace ===
        ldx #$00    ; $2113
        stx $2181    ; $2115
        stx $2180    ; $2118
L211B   ldx $2181    ; $211B
        lda BuffActList,x    ; $211E
        beq L212D    ; $2121
        jsr MySize    ; $2123
        clc    ; $2126
        adc $2180    ; $2127
        sta $2180    ; $212A
L212D   inc $2181    ; $212D
        lda $2181    ; $2130
        cmp #$0E    ; $2133
        bcc L211B    ; $2135
        jsr NewEchoArea    ; $2137
        lda #$BF    ; $213A
        sec    ; $213C
        sbc #$08    ; $213D
        sbc $2180    ; $213F
        lsr    ; $2142
        tax    ; $2143
        jsr ZeroJustify    ; $2144
        jsr PrintPages    ; $2147
        jsr PrintMessage    ; $214A
; ---- $214D-$2158  data  msg: available, ----
        dfb $E1,$F6,$E1,$E9,$EC,$E1,$E2,$EC,$E5,$AC,$A0,$00    ; $214D  available, .
; ---- $2159-$2168  code ----
        ldx SelectedBuff    ; $2159
        jsr MySize    ; $215C
        lsr    ; $215F
        tax    ; $2160
        lda #$00    ; $2161
        jsr PrintDec    ; $2163
        jsr PrintMessage    ; $2166
; ---- $2169-$2176  data  msg:  in current.. ----
        dfb $A0,$E9,$EE,$A0,$E3,$F5,$F2,$F2,$E5,$EE,$F4,$AE,$8D,$00    ; $2169   in current...
; ---- $2177-$2603  code ----
        jsr DSK:DiskSpace    ; $2177
        jsr CloseEchoArea    ; $217A
        lda #$01    ; $217D
        rts    ; $217F
        brk    ; $2180
        brk    ; $2181
;
; === Bottom? ===
        lda $00    ; $2182
        cmp BuffBot    ; $2184
        bne L218C    ; $2186
        lda $01    ; $2188
        cmp $69    ; $218A
L218C   rts    ; $218C
;
; === Top? ===
        lda $00    ; $218D
        cmp BuffTop    ; $218F
        bne L2197    ; $2191
        lda $01    ; $2193
        cmp $67    ; $2195
L2197   rts    ; $2197
;
; === LabelChars ===
        tay    ; $2198
        dfb $DB        ; $2199  (data/65C02-bit)
        ds 4        ; $219A  4 bytes $00 fill
;
; === LabelChar? ===
        sta $21CE    ; $219E
        ldx #$00    ; $21A1
L21A3   lda LabelChars,x    ; $21A3
        beq L21B0    ; $21A6
        cmp $21CE    ; $21A8
        beq L21C8    ; $21AB
        inx    ; $21AD
        bne L21A3    ; $21AE
L21B0   bit AlphaLabel    ; $21B0
        bmi L21CB    ; $21B3
        lda $21CE    ; $21B5
        cmp #$C1    ; $21B8
        bcc L21CB    ; $21BA
        cmp #$FB    ; $21BC
        bcs L21CB    ; $21BE
        cmp #$E1    ; $21C0
        bcs L21C8    ; $21C2
        cmp #$DB    ; $21C4
        bcs L21CB    ; $21C6
L21C8   ldx #$00    ; $21C8
        rts    ; $21CA
L21CB   ldx #$FF    ; $21CB
        rts    ; $21CD
        brk    ; $21CE
;
; === DownPara ===
        jsr GetArgSign    ; $21CF
        bmi UpPara    ; $21D2
        jsr SetGap    ; $21D4
        lda GapBot    ; $21D7
        sta $00    ; $21D9
        lda $6D    ; $21DB
        sta $01    ; $21DD
        ldy #$00    ; $21DF
L21E1   jsr ZeroArg?    ; $21E1
        bne L21F4    ; $21E4
L21E6   lda $00    ; $21E6
        sta TheBuffer    ; $21E8
        lda $01    ; $21EA
        sta $61    ; $21EC
        jsr SetGap    ; $21EE
        lda #$01    ; $21F1
        rts    ; $21F3
L21F4   inc $00    ; $21F4
        bne L21FA    ; $21F6
        inc $01    ; $21F8
L21FA   jsr Bottom?    ; $21FA
        beq L21E6    ; $21FD
        jsr $D000    ; $21FF
        jsr WhiteSpace?    ; $2202
        beq L21F4    ; $2205
L2207   inc $00    ; $2207
        bne L220D    ; $2209
        inc $01    ; $220B
L220D   jsr Bottom?    ; $220D
        beq L21E6    ; $2210
        jsr $D000    ; $2212
        cmp #$8D    ; $2215
        bne L2207    ; $2217
        inc $00    ; $2219
        bne L221F    ; $221B
        inc $01    ; $221D
L221F   jsr Bottom?    ; $221F
        beq L21E6    ; $2222
        jsr $D000    ; $2224
        cmp #$8D    ; $2227
        bne L2207    ; $2229
        lda Argument    ; $222B
        bne L2233    ; $222E
        dec $7A5C    ; $2230
L2233   dec Argument    ; $2233
        jmp L21E1    ; $2236
;
; === UpPara ===
        jsr GetArgSign    ; $2239
        bmi DownPara    ; $223C
        jsr SetGap    ; $223E
        lda TheBuffer    ; $2241
        sta $00    ; $2243
        lda $61    ; $2245
        sta $01    ; $2247
        ldy #$00    ; $2249
L224B   jsr ZeroArg?    ; $224B
        bne L225E    ; $224E
L2250   lda $00    ; $2250
        sta TheBuffer    ; $2252
        lda $01    ; $2254
        sta $61    ; $2256
        jsr SetGap    ; $2258
        lda #$01    ; $225B
        rts    ; $225D
L225E   jsr Top?    ; $225E
        beq L2250    ; $2261
        jsr $D000    ; $2263
        jsr WhiteSpace?    ; $2266
        bne L2276    ; $2269
        lda $00    ; $226B
        bne L2271    ; $226D
        dec $01    ; $226F
L2271   dec $00    ; $2271
        jmp L225E    ; $2273
L2276   jsr Top?    ; $2276
        beq L2250    ; $2279
        jsr $D000    ; $227B
        cmp #$8D    ; $227E
        bne L2296    ; $2280
        lda $00    ; $2282
        bne L2288    ; $2284
        dec $01    ; $2286
L2288   dec $00    ; $2288
        jsr Top?    ; $228A
        beq L2250    ; $228D
        jsr $D000    ; $228F
        cmp #$8D    ; $2292
        beq L22A1    ; $2294
L2296   lda $00    ; $2296
        bne L229C    ; $2298
        dec $01    ; $229A
L229C   dec $00    ; $229C
        jmp L2276    ; $229E
L22A1   inc $00    ; $22A1
        bne L22A7    ; $22A3
        inc $01    ; $22A5
L22A7   lda Argument    ; $22A7
        bne L22AF    ; $22AA
        dec $7A5C    ; $22AC
L22AF   dec Argument    ; $22AF
        jmp L224B    ; $22B2
;
; === MarkPara ===
        jsr InitArgument    ; $22B5
        jsr DownPara    ; $22B8
        jsr SetGap    ; $22BB
        jsr PushMark    ; $22BE
        jsr InitArgument    ; $22C1
        jmp UpPara    ; $22C4
;
; === FillPara ===
        lda $7A5C    ; $22C7
        pha    ; $22CA
        lda Argument    ; $22CB
        pha    ; $22CE
        jsr MarkPara    ; $22CF
        pla    ; $22D2
        sta Argument    ; $22D3
        pla    ; $22D6
        sta $7A5C    ; $22D7
        jmp FillRegion    ; $22DA
;
; === NextLabel ===
        jsr GetArgSign    ; $22DD
        bmi PrevLabel    ; $22E0
        jsr SetGap    ; $22E2
        lda GapBot    ; $22E5
        sta $00    ; $22E7
        lda $6D    ; $22E9
        sta $01    ; $22EB
        ldy #$00    ; $22ED
L22EF   jsr ZeroArg?    ; $22EF
        bne L2302    ; $22F2
L22F4   lda $00    ; $22F4
        sta TheBuffer    ; $22F6
        lda $01    ; $22F8
        sta $61    ; $22FA
        jsr SetGap    ; $22FC
        lda #$01    ; $22FF
        rts    ; $2301
L2302   inc $00    ; $2302
        bne L2308    ; $2304
        inc $01    ; $2306
L2308   jsr Bottom?    ; $2308
        beq L22F4    ; $230B
        jsr $D000    ; $230D
        cmp #$8D    ; $2310
        bne L2302    ; $2312
L2314   inc $00    ; $2314
        bne L231A    ; $2316
        inc $01    ; $2318
L231A   jsr Bottom?    ; $231A
        beq L22F4    ; $231D
        jsr $D000    ; $231F
        cmp #$8D    ; $2322
        beq L2314    ; $2324
        jsr LabelChar?    ; $2326
        bne L2302    ; $2329
L232B   inc $00    ; $232B
        bne L2331    ; $232D
        inc $01    ; $232F
L2331   jsr Bottom?    ; $2331
        beq L22F4    ; $2334
        jsr $D000    ; $2336
        jsr WhiteSpace?    ; $2339
        bne L232B    ; $233C
        lda Argument    ; $233E
        bne L2346    ; $2341
        dec $7A5C    ; $2343
L2346   dec Argument    ; $2346
        jmp L22EF    ; $2349
;
; === PrevLabel ===
        jsr GetArgSign    ; $234C
        bmi NextLabel    ; $234F
        jsr SetGap    ; $2351
        lda $61    ; $2354
        pha    ; $2356
        lda TheBuffer    ; $2357
        pha    ; $2359
        jsr EndOfLine    ; $235A
        jsr SetGap    ; $235D
        lda TheBuffer    ; $2360
        sta $00    ; $2362
        lda $61    ; $2364
        sta $01    ; $2366
        pla    ; $2368
        sta $00    ; $2369
        sta $2428    ; $236B
        pla    ; $236E
        sta $01    ; $236F
        sta $2429    ; $2371
        ldy #$00    ; $2374
L2376   jsr ZeroArg?    ; $2376
        bne L2389    ; $2379
L237B   lda $00    ; $237B
        sta TheBuffer    ; $237D
        lda $01    ; $237F
        sta $61    ; $2381
        jsr SetGap    ; $2383
        lda #$01    ; $2386
        rts    ; $2388
L2389   bit $23EF    ; $2389
        bmi L23A2    ; $238C
L238E   jsr Top?    ; $238E
        beq L237B    ; $2391
        lda $00    ; $2393
        bne L2399    ; $2395
        dec $01    ; $2397
L2399   dec $00    ; $2399
        jsr $D000    ; $239B
        cmp #$8D    ; $239E
        bne L238E    ; $23A0
L23A2   jsr Top?    ; $23A2
        beq L237B    ; $23A5
        lda $00    ; $23A7
        bne L23AD    ; $23A9
        dec $01    ; $23AB
L23AD   dec $00    ; $23AD
        jsr $D000    ; $23AF
        cmp #$8D    ; $23B2
        bne L23A2    ; $23B4
        inc $00    ; $23B6
        bne L23BC    ; $23B8
        inc $01    ; $23BA
L23BC   jsr $D000    ; $23BC
        jsr LabelChar?    ; $23BF
        bne L238E    ; $23C2
        lda $00    ; $23C4
        sta $2428    ; $23C6
        lda $01    ; $23C9
        sta $2429    ; $23CB
        bit $23EF    ; $23CE
        bmi L237B    ; $23D1
L23D3   inc $00    ; $23D3
        bne L23D9    ; $23D5
        inc $01    ; $23D7
L23D9   jsr $D000    ; $23D9
        jsr WhiteSpace?    ; $23DC
        bne L23D3    ; $23DF
        lda Argument    ; $23E1
        bne L23E9    ; $23E4
        dec $7A5C    ; $23E6
L23E9   dec Argument    ; $23E9
        jmp L2376    ; $23EC
        brk    ; $23EF
;
; === RepoWind ===
        jsr SetGap    ; $23F0
        jsr InitArgument    ; $23F3
        jsr PushMark    ; $23F6
        dec $23EF    ; $23F9
        jsr PrevLabel    ; $23FC
        inc $23EF    ; $23FF
        lda $2428    ; $2402
        sta PageTop    ; $2405
        lda $2429    ; $2407
        sta $63    ; $240A
        jsr SwapPointMark    ; $240C
        jsr SetGap    ; $240F
        jsr FindPoint    ; $2412
        beq L2422    ; $2415
        lda WindowBot    ; $2417
        sec    ; $2419
        sbc #$01    ; $241A
        sta CenterPoint    ; $241C
        jmp CenterPage1    ; $241F
L2422   jsr DisplayPage    ; $2422
        lda #$01    ; $2425
        rts    ; $2427
        brk    ; $2428
        brk    ; $2429
        brk    ; $242A
;
; === XorASCII ===
        dec $242A    ; $242B
        bmi ASCIIBuff    ; $242E
;
; === ASCIIBuff1 ===
        lda ArgSign    ; $2430
        eor #$FF    ; $2433
        sta ArgSign    ; $2435
;
; === ASCIIBuff ===
        lda BuffTop    ; $2438
        sta $00    ; $243A
        lda $67    ; $243C
        sta $01    ; $243E
        ldy #$00    ; $2440
L2442   lda $01    ; $2442
        cmp $6B    ; $2444
        bcc L2482    ; $2446
        bne L2460    ; $2448
        lda $00    ; $244A
        cmp GapTop    ; $244C
        bcc L2482    ; $244E
        bne L2460    ; $2450
        lda GapBot    ; $2452
        sta $00    ; $2454
        lda $6D    ; $2456
        sta $01    ; $2458
        inc $00    ; $245A
        bne L2460    ; $245C
        inc $01    ; $245E
L2460   lda $00    ; $2460
        cmp BuffBot    ; $2462
        bne L2482    ; $2464
        lda $01    ; $2466
        cmp $69    ; $2468
        bne L2482    ; $246A
        lda #$00    ; $246C
        sta $242A    ; $246E
        jsr SetModified    ; $2471
        jsr FindPoint    ; $2474
        beq L247C    ; $2477
        lda #$06    ; $2479
        rts    ; $247B
L247C   jsr DisplayPage    ; $247C
        lda #$01    ; $247F
        rts    ; $2481
L2482   jsr $D000    ; $2482
        bit $242A    ; $2485
        bpl L248F    ; $2488
        eor #$80    ; $248A
        jmp L249A    ; $248C
L248F   bit ArgSign    ; $248F
        bmi L2498    ; $2492
        ora #$80    ; $2494
        bmi L249A    ; $2496
L2498   and #$7F    ; $2498
L249A   jsr $D054    ; $249A
        inc $00    ; $249D
        bne L24A3    ; $249F
        inc $01    ; $24A1
L24A3   bne L2442    ; $24A3
;
; === IndentVbtm ===
        dfb $FF        ; $24A5  (data/65C02-bit)
;
; === IndentLine ===
        sta $2522    ; $24A6
        jsr SetGap    ; $24A9
        jsr LinesPastPnt    ; $24AC
        sta $2524    ; $24AF
        jsr BegOfLine    ; $24B2
        jsr DeleteSpace    ; $24B5
        lda #$00    ; $24B8
        sta $2523    ; $24BA
        ldy #$01    ; $24BD
        jsr $D03F    ; $24BF
        cmp #$8D    ; $24C2
        bne L24CB    ; $24C4
        bit IndentVbtm    ; $24C6
        bpl L2507    ; $24C9
L24CB   lda $2523    ; $24CB
        jsr TabBump    ; $24CE
        sta $2525    ; $24D1
        cmp $2522    ; $24D4
        bcc L24EC    ; $24D7
        beq L24EC    ; $24D9
        lda $2522    ; $24DB
        sec    ; $24DE
        sbc $2523    ; $24DF
        beq L2507    ; $24E2
        bmi L2507    ; $24E4
L24E6   lda #$01    ; $24E6
        ldx #$A0    ; $24E8
        bne L24FA    ; $24EA
L24EC   lda $2525    ; $24EC
        sec    ; $24EF
        sbc $2523    ; $24F0
        bit TabsIndent    ; $24F3
        bpl L24E6    ; $24F6
        ldx #$89    ; $24F8
L24FA   clc    ; $24FA
        adc $2523    ; $24FB
        sta $2523    ; $24FE
        txa    ; $2501
        jsr BuffInsert    ; $2502
        beq L24CB    ; $2505
L2507   jsr FindPoint    ; $2507
        beq L250F    ; $250A
        lda #$06    ; $250C
        rts    ; $250E
L250F   jsr DisplayLine    ; $250F
        jsr LinesPastPnt    ; $2512
        tax    ; $2515
        lda #$00    ; $2516
        cpx $2524    ; $2518
        beq L251F    ; $251B
        lda #$02    ; $251D
L251F   rts    ; $251F
        ds 6        ; $2520  6 bytes $00 fill
;
; === BackToIndent ===
        jsr BegOfLine    ; $2526
        ldy #$00    ; $2529
        sty CH    ; $252B
L252D   jsr $D01B    ; $252D
        cmp #$89    ; $2530
        beq L2538    ; $2532
        cmp #$A0    ; $2534
        bne L2543    ; $2536
L2538   jsr GetXCharLen    ; $2538
        jsr BumpXPos    ; $253B
        jsr PointForward    ; $253E
        beq L252D    ; $2541
L2543   ldy CH    ; $2543
        lda #$01    ; $2545
        rts    ; $2547
;
; === PrevIndent ===
        jsr GetPrevIndent    ; $2548
        jsr IndentLine    ; $254B
        rts    ; $254E
;
; === GetPrevIndent ===
        lda CV    ; $254F
        pha    ; $2551
        lda CH    ; $2552
        pha    ; $2554
        lda $61    ; $2555
        pha    ; $2557
        lda TheBuffer    ; $2558
        pha    ; $255A
        jsr BegOfLine    ; $255B
        jsr PointBackward    ; $255E
        jsr BackToIndent    ; $2561
        pla    ; $2564
        sta TheBuffer    ; $2565
        pla    ; $2567
        sta $61    ; $2568
        pla    ; $256A
        sta CH    ; $256B
        pla    ; $256D
        sta CV    ; $256E
        tya    ; $2570
        rts    ; $2571
;
; === OutdentCRLF ===
        jsr CRLF    ; $2572
        jsr GenDisplay    ; $2575
;
; === OutdentLine ===
        lda #$00    ; $2578
        sta $2600    ; $257A
        lda CV    ; $257D
        pha    ; $257F
        lda CH    ; $2580
        pha    ; $2582
        lda $61    ; $2583
        pha    ; $2585
        lda TheBuffer    ; $2586
        pha    ; $2588
L2589   jsr BegOfLine    ; $2589
        jsr PointBackward    ; $258C
        lda TheBuffer    ; $258F
        sta $2601    ; $2591
        lda $61    ; $2594
        sta $2602    ; $2596
        jsr BackToIndent    ; $2599
        tya    ; $259C
        sta $2603    ; $259D
        bne L25BA    ; $25A0
        jsr $D01B    ; $25A2
        cmp #$8D    ; $25A5
        bne L25ED    ; $25A7
        lda $2601    ; $25A9
        cmp BuffTop    ; $25AC
        bne L2589    ; $25AE
        lda $2602    ; $25B0
        cmp $67    ; $25B3
        bne L2589    ; $25B5
        jmp L25ED    ; $25B7
L25BA   lda $2601    ; $25BA
        cmp BuffTop    ; $25BD
        bne L25C8    ; $25BF
        lda $2602    ; $25C1
        cmp $67    ; $25C4
        beq L25ED    ; $25C6
L25C8   jsr BegOfLine    ; $25C8
        jsr PointBackward    ; $25CB
        lda TheBuffer    ; $25CE
        sta $2601    ; $25D0
        lda $61    ; $25D3
        sta $2602    ; $25D5
        jsr BackToIndent    ; $25D8
        tya    ; $25DB
        bne L25E5    ; $25DC
        jsr $D01B    ; $25DE
        cmp #$8D    ; $25E1
        beq L25BA    ; $25E3
L25E5   cpy $2603    ; $25E5
        bcs L25BA    ; $25E8
        sty $2600    ; $25EA
L25ED   pla    ; $25ED
        sta TheBuffer    ; $25EE
        pla    ; $25F0
        sta $61    ; $25F1
        pla    ; $25F3
        sta CH    ; $25F4
        pla    ; $25F6
        sta CV    ; $25F7
        lda $2600    ; $25F9
        jsr IndentLine    ; $25FC
        rts    ; $25FF
        ds 4        ; $2600  4 bytes $00 fill
