;-*- Mode: Merlin -*-
;
; src/modules/06_display.s -- AMACS: char output, key input, cursor, blink, beep, typeout, display engine, scroll
; Address range $2604-$33DB. GENERATED by tools/disasm.py.
; `put' from src/amacs.s; symbols/labels are global across modules.
;
; ---- $2604-$33DB  code ----
;
; === AltmodeChar ===
        ldy $00    ; $2604
;
; === CoutDef ===
        trb $26    ; $2606
;
; === CharOutXY ===
        stx CH    ; $2608
        sty CV    ; $260A
        pha    ; $260C
        jsr vtab    ; $260D
        pla    ; $2610
;
; === CharOut ===
        jmp (CoutDef)    ; $2611
;
; === SI:CharOut ===
        sty $2677    ; $2614
        stx $2676    ; $2617
        sta $2675    ; $261A
        php    ; $261D
        pla    ; $261E
        sta $2678    ; $261F
        lda $2675    ; $2622
        cmp #$A0    ; $2625
        bcs L2656    ; $2627
        cmp #$9B    ; $2629
        bne L2632    ; $262B
        lda AltmodeChar    ; $262D
        bne L2656    ; $2630
L2632   cmp #$8D    ; $2632
        bne L263C    ; $2634
        jsr PrintCR    ; $2636
        jmp L2666    ; $2639
L263C   cmp #$89    ; $263C
        bne L2646    ; $263E
        jsr PrintTab    ; $2640
        jmp L2666    ; $2643
L2646   lda #$DE    ; $2646
L2648   jsr L2656    ; $2648
        ora #$80    ; $264B
        cmp #$E1    ; $264D
        bcc L2654    ; $264F
        sbc #$20    ; $2651
        clc    ; $2653
L2654   adc #$40    ; $2654
L2656   ldy CH    ; $2656
        jsr StoreChar    ; $2658
        inc CH    ; $265B
        lda CH    ; $265D
        cmp WindowRgt    ; $265F
        bcc L2666    ; $2661
        jsr PrintCR1    ; $2663
L2666   lda $2678    ; $2666
        pha    ; $2669
        ldx $2676    ; $266A
        ldy $2677    ; $266D
        lda $2675    ; $2670
        plp    ; $2673
        rts    ; $2674
        ds 4        ; $2675  4 bytes $00 fill
;
; === PrintCR ===
        jsr ClearEOL    ; $2679
;
; === PrintCR1 ===
        lda WindowLft    ; $267C
        sta CH    ; $267E
        inc CV    ; $2680
        lda CV    ; $2682
        cmp WindowBot    ; $2684
        bcc L268C    ; $2686
        lda WindowTop    ; $2688
        sta CV    ; $268A
L268C   jsr vtab1    ; $268C
        rts    ; $268F
;
; === UseTabTable? ===
        dfb $FF        ; $2690  (data/65C02-bit)
;
; === TabBump ===
        bit UseTabTable?    ; $2691
        bmi L269C    ; $2694
        clc    ; $2696
        adc #$08    ; $2697
        and #$F8    ; $2699
        rts    ; $269B
L269C   sty $B8    ; $269C
        stx $B9    ; $269E
        sta $BA    ; $26A0
        inc $BA    ; $26A2
        lda #$00    ; $26A4
        tax    ; $26A6
        tay    ; $26A7
        dey    ; $26A8
        sec    ; $26A9
L26AA   ror    ; $26AA
        bcc L26B0    ; $26AB
        inx    ; $26AD
        bcs L26AA    ; $26AE
L26B0   pha    ; $26B0
        iny    ; $26B1
        and TabTable,x    ; $26B2
        bne $26BA    ; $26B5
        cpy WindowRgt    ; $26B7
        bit $BAC4    ; $26B9
        pla    ; $26BC
        bcc L26AA    ; $26BD
        tya    ; $26BF
        ldx $B9    ; $26C0
        ldy $B8    ; $26C2
        rts    ; $26C4
;
; === TabTable ===
        brk    ; $26C5
        bra L2648    ; $26C6
        bra $264A    ; $26C8
        bra $264C    ; $26CA
        bra $264E    ; $26CC
        bra $2675    ; $26CE
        bit WindowLft    ; $26D0
        sta ($26),y    ; $26D2
        cmp WindowRgt    ; $26D4
        bcc L26DA    ; $26D6
        lda WindowLft    ; $26D8
L26DA   cmp CH    ; $26DA
        beq L26E8    ; $26DC
        pha    ; $26DE
        lda #$A0    ; $26DF
        jsr CharOut    ; $26E1
        pla    ; $26E4
        jmp L26DA    ; $26E5
L26E8   rts    ; $26E8
;
; === vtab ===
        lda CV    ; $26E9
;
; === vtab1 ===
        pha    ; $26EB
        lsr    ; $26EC
        and #$03    ; $26ED
        ora #$04    ; $26EF
        sta BASH    ; $26F1
        pla    ; $26F3
        and #$18    ; $26F4
        bcc L26FA    ; $26F6
        adc #$7F    ; $26F8
L26FA   sta BASL    ; $26FA
        asl    ; $26FC
        asl    ; $26FD
        ora BASL    ; $26FE
        sta BASL    ; $2700
        rts    ; $2702
;
; === StoreChar ===
        sty scrny    ; $2703
        pha    ; $2705
        tya    ; $2706
        lsr    ; $2707
        tay    ; $2708
        pla    ; $2709
        sta Page2    ; $270A   <== BANK: display page 2 / aux (PAGE2 on)
        bcc L2712    ; $270D
        sta Page1    ; $270F   <== BANK: display page 1 / main (PAGE2 off)
L2712   sta (BASL),y    ; $2712
        sta Page1    ; $2714   <== BANK: display page 1 / main (PAGE2 off)
        ldy scrny    ; $2717
        rts    ; $2719
;
; === PickChar ===
        sty scrny    ; $271A
        tya    ; $271C
        lsr    ; $271D
        tay    ; $271E
        sta Page2    ; $271F   <== BANK: display page 2 / aux (PAGE2 on)
        bcc L2727    ; $2722
        sta Page1    ; $2724   <== BANK: display page 1 / main (PAGE2 off)
L2727   lda (BASL),y    ; $2727
        ldy scrny    ; $2729
        sta Page1    ; $272B   <== BANK: display page 1 / main (PAGE2 off)
        rts    ; $272E
;
; === KeyDownp ===
        lda HardKey    ; $272F
        bpl L2737    ; $2732
        lda #$00    ; $2734
        rts    ; $2736
L2737   lda #$FF    ; $2737
        rts    ; $2739
;
; === KeyAvail? ===
        jsr AnyTYI?    ; $273A
        beq L274F    ; $273D
        bit MacroExec    ; $273F
        bpl L274C    ; $2742
        jsr KeyFromMac    ; $2744
        jsr AnyTYI?    ; $2747
        beq L274F    ; $274A
L274C   jsr KeyDownp    ; $274C
L274F   rts    ; $274F
;
; === GetKey ===
        jsr GatherTYI    ; $2750
        jsr PopTYI    ; $2753
        jsr KeyToMac    ; $2756
        rts    ; $2759
;
; === KeyClickp ===
        brk    ; $275A
;
; === KeyClickVol ===
        dfb $03        ; $275B  (data/65C02-bit)
;
; === IIgsMode? ===
        brk    ; $275C
;
; === KeyModState ===
        brk    ; $275D
;
; === GetKeyPress ===
        jsr KeyDownp    ; $275E
        bne GetKeyPress    ; $2761
        lda HardMeta    ; $2763
        ora HardHyper    ; $2766
        and #$80    ; $2769
        eor HardKey    ; $276B
        pha    ; $276E
        lda HardModState    ; $276F
        sta KeyModState    ; $2772
        pla    ; $2775
        sta HardKeyReset    ; $2776
        bmi L2785    ; $2779
        cmp #$61    ; $277B
        bcc L2785    ; $277D
        cmp #$7B    ; $277F
        bcs L2785    ; $2781
        sbc #$1F    ; $2783
L2785   bit IIgsMode?    ; $2785
        bpl L2799    ; $2788
        sta UseAuxZP    ; $278A   <== BANK: aux zero-page/stack (ALTZP on)
        jsr GetBank1    ; $278D
        jsr CheckArrowKey    ; $2790
        sta UseMainZP    ; $2793   <== BANK: main zero-page/stack (ALTZP off)
        jsr GetBank2    ; $2796
L2799   bit KeyClickp    ; $2799
        bpl L27A6    ; $279C
        pha    ; $279E
        lda KeyClickVol    ; $279F
        jsr Click    ; $27A2
        pla    ; $27A5
L27A6   rts    ; $27A6
;
; === TYIBuff ===
        ds 67        ; $27A7  67 bytes $00 fill
;
; === KillTYI ===
        lda TYI_PopIndex    ; $27EA
        sta TYI_PushIndex    ; $27ED
        rts    ; $27F0
;
; === AnyTYI? ===
        lda TYI_PopIndex    ; $27F1
        cmp TYI_PushIndex    ; $27F4
        beq L27FC    ; $27F7
        lda #$00    ; $27F9
        rts    ; $27FB
L27FC   lda #$FF    ; $27FC
        rts    ; $27FE
;
; === UnTYI ===
        dec TYI_PopIndex    ; $27FF
        lda TYI_PopIndex    ; $2802
        and #$3F    ; $2805
        sta TYI_PopIndex    ; $2807
        rts    ; $280A
;
; === PushTYI ===
        stx $27E9    ; $280B
        ldx TYI_PushIndex    ; $280E
        sta TYIBuff,x    ; $2811
        inx    ; $2814
        txa    ; $2815
        and #$3F    ; $2816
        cmp TYI_PopIndex    ; $2818
        beq L2820    ; $281B
        sta TYI_PushIndex    ; $281D
L2820   ldx $27E9    ; $2820
        rts    ; $2823
;
; === PopTYI   (also TYI) ===
        jsr AnyTYI?    ; $2824
        bne L2842    ; $2827
        stx $27E9    ; $2829
        ldx TYI_PopIndex    ; $282C
        lda TYIBuff,x    ; $282F
        pha    ; $2832
        inx    ; $2833
        txa    ; $2834
        and #$3F    ; $2835
        sta TYI_PopIndex    ; $2837
        pla    ; $283A
        ldx #$00    ; $283B
        php    ; $283D
        ldx $27E9    ; $283E
        plp    ; $2841
L2842   rts    ; $2842
;
; === GatherTYI ===
        jsr KeyDownp    ; $2843
        bne L2861    ; $2846
        jsr GetKeyPress    ; $2848
        cmp #$87    ; $284B
        bne L2856    ; $284D
        jsr KillTYI    ; $284F
        lda #$87    ; $2852
        bne L285C    ; $2854
L2856   bit MacroExec    ; $2856
        bpl L285C    ; $2859
        rts    ; $285B
L285C   jsr PushTYI    ; $285C
        lda #$00    ; $285F
L2861   rts    ; $2861
;
; === ClearEOL ===
        lda #$A0    ; $2862
;
; === ClearEOL1 ===
        ldy CH    ; $2864
L2866   cpy WindowRgt    ; $2866
        bcs L2870    ; $2868
        jsr StoreChar    ; $286A
        iny    ; $286D
        bne L2866    ; $286E
L2870   rts    ; $2870
;
; === ClearPage ===
        jsr Home    ; $2871
;
; === ClearEOP ===
        lda #$A0    ; $2874
;
; === ClearEOP1 ===
        sta $289D    ; $2876
        lda CV    ; $2879
        pha    ; $287B
        lda CH    ; $287C
        pha    ; $287E
L287F   lda $289D    ; $287F
        jsr ClearEOL1    ; $2882
        lda #$00    ; $2885
        sta CH    ; $2887
        inc CV    ; $2889
        jsr vtab    ; $288B
        lda CV    ; $288E
        cmp WindowBot    ; $2890
        bcc L287F    ; $2892
        pla    ; $2894
        sta CH    ; $2895
        pla    ; $2897
        sta CV    ; $2898
        jmp vtab    ; $289A
        brk    ; $289D
;
; === Home ===
        lda WindowTop    ; $289E
        sta CV    ; $28A0
        lda WindowLft    ; $28A2
        sta CH    ; $28A4
        jmp vtab    ; $28A6
;
; === ResetTTY ===
        jsr $C300    ; $28A9
        lda #$14    ; $28AC
        sta CoutDef    ; $28AE
        lda #$26    ; $28B1
        sta $2607    ; $28B3
        rts    ; $28B6
;
; === Cursor2 ===
        ds 4        ; $28B7  4 bytes $00 fill
;
; === TimedBlink ===
        lda CV    ; $28BB
        pha    ; $28BD
        lda CH    ; $28BE
        pha    ; $28C0
        lda Cursor2    ; $28C1
        sta CH    ; $28C4
        lda $28B8    ; $28C6
        sta CV    ; $28C9
        jsr vtab    ; $28CB
        lda BlinkRate    ; $28CE
        beq L28D8    ; $28D1
        sec    ; $28D3
        sbc #$16    ; $28D4
        bne L28DA    ; $28D6
L28D8   lda #$58    ; $28D8
L28DA   sta BlinkRate    ; $28DA
L28DD   lda BlinkTime    ; $28DD
        ora $28BA    ; $28E0
        beq L28FB    ; $28E3
        jsr KeyAvail?    ; $28E5
        beq L290E    ; $28E8
        lda BlinkTime    ; $28EA
        bne L28F2    ; $28ED
        dec $28BA    ; $28EF
L28F2   dec BlinkTime    ; $28F2
        jsr BlinkOnce    ; $28F5
        jmp L28DD    ; $28F8
L28FB   pla    ; $28FB
        sta CH    ; $28FC
        pla    ; $28FE
        sta CV    ; $28FF
        jsr vtab    ; $2901
        lda BlinkRate    ; $2904
        clc    ; $2907
        adc #$16    ; $2908
        sta BlinkRate    ; $290A
        rts    ; $290D
L290E   pla    ; $290E
        sta CH    ; $290F
        pla    ; $2911
        sta CV    ; $2912
        jsr vtab    ; $2914
        lda BlinkRate    ; $2917
        clc    ; $291A
        adc #$16    ; $291B
        sta BlinkRate    ; $291D
        lda #$00    ; $2920
        sta BlinkTime    ; $2922
        sta $28BA    ; $2925
        php    ; $2928
        jsr GetKey    ; $2929
        plp    ; $292C
        rts    ; $292D
;
; === BlinkCursor ===
        jsr KeyAvail?    ; $292E
        beq L2939    ; $2931
        jsr BlinkOnce    ; $2933
        jmp BlinkCursor    ; $2936
L2939   jmp GetKey    ; $2939
;
; === AltBlink ===
        jsr TimedBlink    ; $293C
        beq L2944    ; $293F
        jmp BlinkCursor    ; $2941
L2944   rts    ; $2944
;
; === BlinkRate ===
        cli    ; $2945
;
; === BlinkOnce ===
        jsr L29DA    ; $2946
        jsr L29FF    ; $2949
        jsr CursorOff    ; $294C
        lda BlinkRate    ; $294F
L2952   pha    ; $2952
L2953   pha    ; $2953
        jsr KeyAvail?    ; $2954
        beq L2984    ; $2957
        pla    ; $2959
        sec    ; $295A
        sbc #$01    ; $295B
        bne L2953    ; $295D
        pla    ; $295F
        sec    ; $2960
        sbc #$01    ; $2961
        bne L2952    ; $2963
        jsr L2A03    ; $2965
        jsr CursorOff    ; $2968
        lda BlinkRate    ; $296B
L296E   pha    ; $296E
L296F   pha    ; $296F
        jsr KeyAvail?    ; $2970
        beq L2987    ; $2973
        pla    ; $2975
        sec    ; $2976
        sbc #$01    ; $2977
        bne L296F    ; $2979
        pla    ; $297B
        sbc #$01    ; $297C
        bne L296E    ; $297E
        jsr L2A03    ; $2980
        rts    ; $2983
L2984   jsr CursorOff    ; $2984
L2987   jsr L2A03    ; $2987
        lda #$00    ; $298A
        sta ParenFlag    ; $298C
        pla    ; $298F
        pla    ; $2990
        rts    ; $2991
;
; === CursorOff   (also CursorOn, InvertChar) ===
        tya    ; $2992
        pha    ; $2993
        ldy CH    ; $2994
        jsr PickChar    ; $2996
        sta $29B6    ; $2999
        eor #$80    ; $299C
        bit IIcMode?    ; $299E
        bpl L29B0    ; $29A1
        cmp #$60    ; $29A3
        bcs L29B0    ; $29A5
        and #$3F    ; $29A7
        bit $29B6    ; $29A9
        bmi L29B0    ; $29AC
        ora #$80    ; $29AE
L29B0   jsr StoreChar    ; $29B0
        pla    ; $29B3
        tay    ; $29B4
        rts    ; $29B5
        brk    ; $29B6
;
; === BeepVector ===
        and $6C2A,y    ; $29B7
        dfb $B7        ; $29BA  (data/65C02-bit)
        and #$A9    ; $29BB
        bra $2A07    ; $29BD
        lda #$0C    ; $29BF
L29C1   pha    ; $29C1
        sec    ; $29C2
L29C3   sbc #$01    ; $29C3
        bne L29C3    ; $29C5
        pla    ; $29C7
        sbc #$01    ; $29C8
        bne L29C1    ; $29CA
        bit HardBeep    ; $29CC
        pla    ; $29CF
        sbc #$01    ; $29D0
        bne Click    ; $29D2
        rts    ; $29D4
;
; === ParenFlag ===
        ds 5        ; $29D5  5 bytes $00 fill
L29DA   bit ParenFlag    ; $29DA
        bpl L2A36    ; $29DD
        tya    ; $29DF
        pha    ; $29E0
        lda CV    ; $29E1
        pha    ; $29E3
        lda CH    ; $29E4
        pha    ; $29E6
        lda ParenPos    ; $29E7
        sta CH    ; $29EA
        lda $29D7    ; $29EC
        sta CV    ; $29EF
        jsr vtab    ; $29F1
        ldy CH    ; $29F4
        jsr PickChar    ; $29F6
        sta $29D8    ; $29F9
        jmp L2A2B    ; $29FC
L29FF   lda #$A0    ; $29FF
        bne L2A06    ; $2A01
L2A03   lda $29D8    ; $2A03
L2A06   sta $29D9    ; $2A06
        bit ParenFlag    ; $2A09
        bpl L2A36    ; $2A0C
        tya    ; $2A0E
        pha    ; $2A0F
        lda CV    ; $2A10
        pha    ; $2A12
        lda CH    ; $2A13
        pha    ; $2A15
        lda ParenPos    ; $2A16
        sta CH    ; $2A19
        lda $29D7    ; $2A1B
        sta CV    ; $2A1E
        jsr vtab    ; $2A20
        ldy CH    ; $2A23
        lda $29D9    ; $2A25
        jsr StoreChar    ; $2A28
L2A2B   pla    ; $2A2B
        sta CH    ; $2A2C
        pla    ; $2A2E
        sta CV    ; $2A2F
        jsr vtab    ; $2A31
        pla    ; $2A34
        tay    ; $2A35
L2A36   rts    ; $2A36
;
; === BeepFlashes? ===
        brk    ; $2A37
;
; === BeepRings? ===
        dfb $FF        ; $2A38  (data/65C02-bit)
;
; === SysBeep ===
        bit BeepRings?    ; $2A39
        bpl L2A65    ; $2A3C
        lda CV    ; $2A3E
        pha    ; $2A40
        lda CH    ; $2A41
        pha    ; $2A43
        bit BeepFlashes?    ; $2A44
        bpl L2A4C    ; $2A47
        jsr InvModeLine    ; $2A49
L2A4C   bit BeepRings?    ; $2A4C
        bpl L2A54    ; $2A4F
        jsr Bell    ; $2A51
L2A54   bit BeepFlashes?    ; $2A54
        bpl L2A5C    ; $2A57
        jsr InvModeLine    ; $2A59
L2A5C   pla    ; $2A5C
        sta CH    ; $2A5D
        pla    ; $2A5F
        sta CV    ; $2A60
        jmp vtab1    ; $2A62
L2A65   bit BeepFlashes?    ; $2A65
        bmi L2A6B    ; $2A68
        rts    ; $2A6A
L2A6B   lda CV    ; $2A6B
        pha    ; $2A6D
        lda CH    ; $2A6E
        pha    ; $2A70
        jsr InvModeLine    ; $2A71
        lda #$80    ; $2A74
L2A76   pha    ; $2A76
        lda #$0C    ; $2A77
L2A79   pha    ; $2A79
        sec    ; $2A7A
L2A7B   sbc #$01    ; $2A7B
        bne L2A7B    ; $2A7D
        pla    ; $2A7F
        sbc #$01    ; $2A80
        bne L2A79    ; $2A82
        pla    ; $2A84
        sbc #$01    ; $2A85
        bne L2A76    ; $2A87
        jsr InvModeLine    ; $2A89
        pla    ; $2A8C
        sta CH    ; $2A8D
        pla    ; $2A8F
        sta CV    ; $2A90
        jmp vtab1    ; $2A92
;
; === TypeoutOpen ===
        brk    ; $2A95
;
; === TypeoutFlag ===
        brk    ; $2A96
;
; === TypeoutAbort ===
        ora $2B    ; $2A97
;
; === AbortedTO? ===
        ds 8        ; $2A99  8 bytes $00 fill
;
; === InitTypeout ===
        lda WindowTop    ; $2AA1
        sta $2AA0    ; $2AA3
        sta TypeoutMax    ; $2AA6
        lda WindowLft    ; $2AA9
        sta TypeoutCH    ; $2AAB
        lda #$00    ; $2AAE
        sta AbortedTO?    ; $2AB0
        sta TypeoutFlag    ; $2AB3
        cmp TypeoutOpen    ; $2AB6
        beq L2ABE    ; $2AB9
        jsr CloseTypeout1    ; $2ABB
L2ABE   lda #$FF    ; $2ABE
        sta $2A9C    ; $2AC0
        rts    ; $2AC3
;
; === OpenTypeout ===
        bit TypeoutOpen    ; $2AC4
        bpl L2ACC    ; $2AC7
        jsr CloseTypeout1    ; $2AC9
L2ACC   lda CoutDef    ; $2ACC
        sta $2A9D    ; $2ACF
        lda $2607    ; $2AD2
        sta $2A9E    ; $2AD5
        lda #$CD    ; $2AD8
        sta CoutDef    ; $2ADA
        lda #$2B    ; $2ADD
        sta $2607    ; $2ADF
        lda TypeoutCH    ; $2AE2
        sta CH    ; $2AE5
        lda $2AA0    ; $2AE7
        sta CV    ; $2AEA
        jsr vtab    ; $2AEC
        tsx    ; $2AEF
        inx    ; $2AF0
        inx    ; $2AF1
        stx TOAbortStk    ; $2AF2
        lda #$05    ; $2AF5
        sta TypeoutAbort    ; $2AF7
        lda #$2B    ; $2AFA
        sta $2A98    ; $2AFC
        lda #$FF    ; $2AFF
        sta TypeoutOpen    ; $2B01
        rts    ; $2B04
        jsr CloseTypeout1    ; $2B05
        ldx TOAbortStk    ; $2B08
        txs    ; $2B0B
        lda #$01    ; $2B0C
        rts    ; $2B0E
;
; === CloseTypeout ===
        jsr BlinkCursor    ; $2B0F
        cmp #$A0    ; $2B12
        beq CloseTypeout1    ; $2B14
        jsr L2BC4    ; $2B16
;
; === CloseTypeout1 ===
        lda $2A9D    ; $2B19
        sta CoutDef    ; $2B1C
        lda $2A9E    ; $2B1F
        sta $2607    ; $2B22
        lda CH    ; $2B25
        sta TypeoutCH    ; $2B27
        lda CV    ; $2B2A
        sta $2AA0    ; $2B2C
        jsr vtab    ; $2B2F
        lda #$00    ; $2B32
        sta TypeoutOpen    ; $2B34
        rts    ; $2B37
;
; === SaveWind ===
        ldx #$00    ; $2B38
L2B3A   lda WindowLft,x    ; $2B3A
        sta $2B55,x    ; $2B3C
        inx    ; $2B3F
        cpx #$06    ; $2B40
        bcc L2B3A    ; $2B42
        rts    ; $2B44
;
; === RstrWind ===
        ldx #$00    ; $2B45
L2B47   lda $2B55,x    ; $2B47
        sta WindowLft,x    ; $2B4A
        inx    ; $2B4C
        cpx #$06    ; $2B4D
        bcc L2B47    ; $2B4F
        jsr vtab1    ; $2B51
        rts    ; $2B54
        ds 6        ; $2B55  6 bytes $00 fill
;
; === GetTypeWind ===
        ldy #$00    ; $2B5B
        bit $111C    ; $2B5D
        bpl L2B84    ; $2B60
        lda #$1D    ; $2B62
        sta $00    ; $2B64
        lda #$11    ; $2B66
        sta $01    ; $2B68
        lda SelectedWind    ; $2B6A
        cmp #$01    ; $2B6D
        beq L2B79    ; $2B6F
        lda #$26    ; $2B71
        sta $00    ; $2B73
        lda #$11    ; $2B75
        sta $01    ; $2B77
L2B79   lda ($00),y    ; $2B79
        sta: WindowLft,y    ; $2B7B
        iny    ; $2B7E
        cpy #$04    ; $2B7F
        bcc L2B79    ; $2B81
        rts    ; $2B83
L2B84   lda #$00    ; $2B84
        sta WindowTop    ; $2B86
        sta WindowLft    ; $2B88
        lda #$14    ; $2B8A
        sta WindowBot    ; $2B8C
        lda #$50    ; $2B8E
        sta WindowRgt    ; $2B90
        rts    ; $2B92
;
; === PrepTO ===
        jsr SaveWind    ; $2B93
        jsr GetTypeWind    ; $2B96
        jsr OpenTypeout    ; $2B99
        lda #$AD    ; $2B9C
        sta TypeoutAbort    ; $2B9E
        lda #$2B    ; $2BA1
        sta $2A98    ; $2BA3
        tsx    ; $2BA6
        inx    ; $2BA7
        inx    ; $2BA8
        stx TOAbortStk    ; $2BA9
        rts    ; $2BAC
        ldx TOAbortStk    ; $2BAD
        txs    ; $2BB0
        jsr CloseTypeout1    ; $2BB1
        jmp L2BBA    ; $2BB4
;
; === UnPrepTO ===
        jsr CloseTypeout    ; $2BB7
L2BBA   jsr RstrWind    ; $2BBA
        lda #$01    ; $2BBD
        rts    ; $2BBF
        ds 4        ; $2BC0  4 bytes $00 fill
L2BC4   jsr UnTYI    ; $2BC4
        ldx #$FF    ; $2BC7
        stx AbortedTO?    ; $2BC9
        rts    ; $2BCC
        sta $2BC2    ; $2BCD
        stx $2BC0    ; $2BD0
        sty $2BC1    ; $2BD3
        php    ; $2BD6
        pla    ; $2BD7
        sta $2BC3    ; $2BD8
        bit $2A9C    ; $2BDB
        bpl L2BF8    ; $2BDE
        inc $2A9C    ; $2BE0
        lda #$FF    ; $2BE3
        sta TypeoutFlag    ; $2BE5
        lda TypeoutCH    ; $2BE8
        sta CH    ; $2BEB
        lda $2AA0    ; $2BED
        sta CV    ; $2BF0
        jsr vtab    ; $2BF2
        jsr L2C5B    ; $2BF5
L2BF8   lda $2BC2    ; $2BF8
        cmp #$A0    ; $2BFB
        bcs L2C29    ; $2BFD
        cmp #$9B    ; $2BFF
        bne L2C08    ; $2C01
        lda AltmodeChar    ; $2C03
        bne L2C29    ; $2C06
L2C08   cmp #$8D    ; $2C08
        bne L2C12    ; $2C0A
        jsr L2C5B    ; $2C0C
        jmp L2C2C    ; $2C0F
L2C12   cmp #$89    ; $2C12
        bne L2C1C    ; $2C14
        jsr L2C4C    ; $2C16
        jmp L2C2C    ; $2C19
L2C1C   lda #$DE    ; $2C1C
        jsr L2C3B    ; $2C1E
        lda $2BC2    ; $2C21
        ora #$80    ; $2C24
        clc    ; $2C26
        adc #$40    ; $2C27
L2C29   jsr L2C3B    ; $2C29
L2C2C   lda $2BC3    ; $2C2C
        pha    ; $2C2F
        lda $2BC2    ; $2C30
        ldx $2BC0    ; $2C33
        ldy $2BC1    ; $2C36
        plp    ; $2C39
        rts    ; $2C3A
L2C3B   ldy CH    ; $2C3B
        jsr StoreChar    ; $2C3D
        inc CH    ; $2C40
        lda CH    ; $2C42
        cmp WindowRgt    ; $2C44
        bcc L2C4B    ; $2C46
        jsr L2C5E    ; $2C48
L2C4B   rts    ; $2C4B
L2C4C   lda CH    ; $2C4C
        jsr TabBump    ; $2C4E
        sta CH    ; $2C51
        cmp WindowRgt    ; $2C53
        bcc L2C5A    ; $2C55
        jsr L2C5B    ; $2C57
L2C5A   rts    ; $2C5A
L2C5B   jsr ClearEOL    ; $2C5B
L2C5E   lda WindowLft    ; $2C5E
        sta CH    ; $2C60
        inc CV    ; $2C62
        ldx CV    ; $2C64
        inx    ; $2C66
        cpx WindowBot    ; $2C67
        bcc L2C79    ; $2C69
        bne L2CA7    ; $2C6B
        jsr vtab    ; $2C6D
        jsr ClearEOL    ; $2C70
        ldx WindowBot    ; $2C73
        stx TypeoutMax    ; $2C75
        rts    ; $2C78
L2C79   lda CV    ; $2C79
        pha    ; $2C7B
        lda CH    ; $2C7C
        pha    ; $2C7E
        jsr vtab    ; $2C7F
        jsr ClearEOL    ; $2C82
        inc CV    ; $2C85
        lda WindowLft    ; $2C87
        sta CH    ; $2C89
        jsr vtab    ; $2C8B
        lda #$DF    ; $2C8E
        ldx CV    ; $2C90
        cpx TypeoutMax    ; $2C92
        bcc L2C9D    ; $2C95
        stx TypeoutMax    ; $2C97
        jsr ClearEOL1    ; $2C9A
L2C9D   pla    ; $2C9D
        sta CH    ; $2C9E
        pla    ; $2CA0
        sta CV    ; $2CA1
        jsr vtab    ; $2CA3
        rts    ; $2CA6
L2CA7   lda ModeLineCV    ; $2CA7
        sta CV    ; $2CAA
        lda $2D22    ; $2CAC
        sta CH    ; $2CAF
        jsr vtab    ; $2CB1
        ldy CH    ; $2CB4
        jsr L2CE9    ; $2CB6
        sty CH    ; $2CB9
        jsr BlinkCursor    ; $2CBB
        pha    ; $2CBE
        ldy $2D22    ; $2CBF
        sty CH    ; $2CC2
        jsr L2CE9    ; $2CC4
        lda WindowTop    ; $2CC7
        sta $2AA0    ; $2CC9
        sta CV    ; $2CCC
        lda WindowLft    ; $2CCE
        sta TypeoutCH    ; $2CD0
        sta CH    ; $2CD3
        jsr vtab    ; $2CD5
        pla    ; $2CD8
        cmp #$A0    ; $2CD9
        bne L2CE3    ; $2CDB
        lda #$FF    ; $2CDD
        sta $2A9C    ; $2CDF
        rts    ; $2CE2
L2CE3   jsr L2BC4    ; $2CE3
        jmp (TypeoutAbort)    ; $2CE6
L2CE9   ldx #$00    ; $2CE9
        ldy CH    ; $2CEB
L2CED   jsr PickChar    ; $2CED
        pha    ; $2CF0
        lda $2D18,x    ; $2CF1
        bit ModeLineInv    ; $2CF4
        bmi L2D06    ; $2CF7
        bit IIcMode?    ; $2CF9
        bpl L2D08    ; $2CFC
        cmp #$4D    ; $2CFE
        bne L2D08    ; $2D00
        and #$3F    ; $2D02
        bne L2D08    ; $2D04
L2D06   ora #$80    ; $2D06
L2D08   jsr StoreChar    ; $2D08
        pla    ; $2D0B
        and #$7F    ; $2D0C
        sta $2D18,x    ; $2D0E
        iny    ; $2D11
        inx    ; $2D12
        cpx #$0A    ; $2D13
        bcc L2CED    ; $2D15
        rts    ; $2D17
        jsr $2D2D    ; $2D18
        eor $726F    ; $2D1B
        adc $2D    ; $2D1E
        and $4220    ; $2D20
        brk    ; $2D23
        brk    ; $2D24
;
; === PointToCH ===
        lda CH    ; $2D25
        sta $2D23    ; $2D27
        lda CV    ; $2D2A
        sta $2D24    ; $2D2C
        lda PageTop    ; $2D2F
        sta $04    ; $2D31
        lda $63    ; $2D33
        sta $05    ; $2D35
        jsr Home    ; $2D37
        ldy #$00    ; $2D3A
L2D3C   lda CV    ; $2D3C
        cmp $2D24    ; $2D3E
        bcc L2D58    ; $2D41
        lda CH    ; $2D43
        cmp $2D23    ; $2D45
        bcc L2D58    ; $2D48
L2D4A   lda $04    ; $2D4A
        sta TheBuffer    ; $2D4C
        lda $05    ; $2D4E
        sta $61    ; $2D50
        jsr vtab    ; $2D52
        lda #$00    ; $2D55
        rts    ; $2D57
L2D58   lda $05    ; $2D58
        cmp $6B    ; $2D5A
        bcc L2D70    ; $2D5C
        bne L2D6B    ; $2D5E
        lda $04    ; $2D60
        cmp GapTop    ; $2D62
        bcc L2D70    ; $2D64
        bne L2D6B    ; $2D66
        jsr L2EE5    ; $2D68
L2D6B   jsr L2FC6    ; $2D6B
        beq L2D4A    ; $2D6E
L2D70   jsr $D012    ; $2D70
        jsr GetXCharLen    ; $2D73
        jsr BumpXPos    ; $2D76
        inc $04    ; $2D79
        bne L2D7F    ; $2D7B
        inc $05    ; $2D7D
L2D7F   lda CV    ; $2D7F
        cmp WindowBot    ; $2D81
        bcc L2D3C    ; $2D83
        lda #$FF    ; $2D85
        rts    ; $2D87
;
; === FindPoint ===
        jsr Home    ; $2D88
        lda PageTop    ; $2D8B
        sta $00    ; $2D8D
        lda $63    ; $2D8F
        sta $01    ; $2D91
;
; === FindPoint1 ===
        ldy #$00    ; $2D93
L2D95   lda $00    ; $2D95
        cmp TheBuffer    ; $2D97
        bne L2DA7    ; $2D99
        lda $01    ; $2D9B
        cmp $61    ; $2D9D
        bne L2DA7    ; $2D9F
        jsr vtab    ; $2DA1
        lda #$00    ; $2DA4
        rts    ; $2DA6
L2DA7   lda $01    ; $2DA7
        cmp $6B    ; $2DA9
        bcc L2DC9    ; $2DAB
        bne L2DBA    ; $2DAD
        lda $00    ; $2DAF
        cmp GapTop    ; $2DB1
        bcc L2DC9    ; $2DB3
        bne L2DBA    ; $2DB5
        jsr SetTempBot    ; $2DB7
L2DBA   lda $00    ; $2DBA
        cmp BuffBot    ; $2DBC
        bne L2DC9    ; $2DBE
        lda $01    ; $2DC0
        cmp $69    ; $2DC2
        bne L2DC9    ; $2DC4
L2DC6   lda #$FF    ; $2DC6
        rts    ; $2DC8
L2DC9   jsr $D000    ; $2DC9
        jsr GetXCharLen    ; $2DCC
        jsr BumpXPos    ; $2DCF
        ldx CV    ; $2DD2
        cpx WindowBot    ; $2DD4
        bcs L2DC6    ; $2DD6
        inc $00    ; $2DD8
        bne L2DDE    ; $2DDA
        inc $01    ; $2DDC
L2DDE   bne L2D95    ; $2DDE
;
; === GetXCharLen ===
        ldx #$01    ; $2DE0
        cmp #$A0    ; $2DE2
        bcs L2DF3    ; $2DE4
        cmp #$9B    ; $2DE6
        beq L2DF3    ; $2DE8
        cmp #$8D    ; $2DEA
        beq L2DF4    ; $2DEC
        cmp #$89    ; $2DEE
        beq L2DFD    ; $2DF0
        inx    ; $2DF2
L2DF3   rts    ; $2DF3
L2DF4   lda WindowRgt    ; $2DF4
        sec    ; $2DF6
        sbc CH    ; $2DF7
        tax    ; $2DF9
        lda #$8D    ; $2DFA
        rts    ; $2DFC
L2DFD   lda CH    ; $2DFD
        jsr TabBump    ; $2DFF
        cmp WindowRgt    ; $2E02
        bcc L2E0C    ; $2E04
        jsr L2DF4    ; $2E06
        lda #$89    ; $2E09
        rts    ; $2E0B
L2E0C   sec    ; $2E0C
        sbc CH    ; $2E0D
        tax    ; $2E0F
        lda #$89    ; $2E10
        rts    ; $2E12
;
; === BumpXPos ===
        cmp #$8D    ; $2E13
        beq L2E2E    ; $2E15
        txa    ; $2E17
        clc    ; $2E18
        adc CH    ; $2E19
        sta CH    ; $2E1B
        adc #$01    ; $2E1D
        cmp WindowRgt    ; $2E1F
        bcc L2E2D    ; $2E21
        sbc WindowRgt    ; $2E23
        sta CH    ; $2E25
        lda #$00    ; $2E27
        sta CH    ; $2E29
        inc CV    ; $2E2B
L2E2D   rts    ; $2E2D
L2E2E   lda #$00    ; $2E2E
        sta CH    ; $2E30
        inc CV    ; $2E32
        rts    ; $2E34
;
; === BackLine ===
        ldy #$00    ; $2E35
L2E37   jsr L2FBB    ; $2E37
        bne L2E3D    ; $2E3A
        rts    ; $2E3C
L2E3D   jsr L2F9A    ; $2E3D
        bne L2E4F    ; $2E40
        lda GapTop    ; $2E42
        sta $04    ; $2E44
        lda $6B    ; $2E46
        sta $05    ; $2E48
        jsr L2FBB    ; $2E4A
        beq L2E5E    ; $2E4D
L2E4F   lda $04    ; $2E4F
        bne L2E55    ; $2E51
        dec $05    ; $2E53
L2E55   dec $04    ; $2E55
        jsr $D012    ; $2E57
        cmp #$8D    ; $2E5A
        bne L2E37    ; $2E5C
L2E5E   rts    ; $2E5E
        ds 4        ; $2E5F  4 bytes $00 fill
;
; === BackScrLine ===
        lda WindowTop    ; $2E63
        sta CV    ; $2E65
        lda WindowLft    ; $2E67
        sta CH    ; $2E69
        lda $04    ; $2E6B
        sta $2E5F    ; $2E6D
        lda $05    ; $2E70
        sta $2E60    ; $2E72
        jsr BackLine    ; $2E75
        jsr CheckTop    ; $2E78
        beq L2E80    ; $2E7B
        jsr L2ECC    ; $2E7D
L2E80   lda $04    ; $2E80
        sta $2E61    ; $2E82
        lda $05    ; $2E85
        sta $2E62    ; $2E87
L2E8A   lda $04    ; $2E8A
        cmp $2E5F    ; $2E8C
        bne L2E98    ; $2E8F
        lda $05    ; $2E91
        cmp $2E60    ; $2E93
        beq L2EC1    ; $2E96
L2E98   ldy #$00    ; $2E98
        jsr $D012    ; $2E9A
        jsr GetXCharLen    ; $2E9D
        ldy CV    ; $2EA0
        jsr BumpXPos    ; $2EA2
        cpy CV    ; $2EA5
        beq L2EBB    ; $2EA7
        lda $04    ; $2EA9
        sta $2E61    ; $2EAB
        lda $05    ; $2EAE
        sta $2E62    ; $2EB0
        inc $2E61    ; $2EB3
        bne L2EBB    ; $2EB6
        inc $2E62    ; $2EB8
L2EBB   jsr L2ECC    ; $2EBB
        jmp L2E8A    ; $2EBE
L2EC1   lda $2E61    ; $2EC1
        sta $04    ; $2EC4
        lda $2E62    ; $2EC6
        sta $05    ; $2EC9
        rts    ; $2ECB
L2ECC   jsr L2FD1    ; $2ECC
        beq L2EE2    ; $2ECF
        jsr L2FB0    ; $2ED1
        bne L2ED9    ; $2ED4
        jsr L2EE5    ; $2ED6
L2ED9   inc $04    ; $2ED9
        bne L2EDF    ; $2EDB
        inc $05    ; $2EDD
L2EDF   lda #$00    ; $2EDF
        rts    ; $2EE1
L2EE2   lda #$FF    ; $2EE2
        rts    ; $2EE4
L2EE5   lda GapBot    ; $2EE5
        clc    ; $2EE7
        adc #$01    ; $2EE8
        sta $04    ; $2EEA
        lda $6D    ; $2EEC
        adc #$00    ; $2EEE
        sta $05    ; $2EF0
        rts    ; $2EF2
;
; === SetTempBot ===
        lda GapBot    ; $2EF3
        clc    ; $2EF5
        adc #$01    ; $2EF6
        sta $00    ; $2EF8
        lda $6D    ; $2EFA
        adc #$00    ; $2EFC
        sta $01    ; $2EFE
        rts    ; $2F00
L2F01   jsr L2F9A    ; $2F01
        bne L2F0E    ; $2F04
        lda GapTop    ; $2F06
        sta $00    ; $2F08
        lda $6B    ; $2F0A
        sta $01    ; $2F0C
L2F0E   jsr L2FBB    ; $2F0E
        beq L2F1E    ; $2F11
        lda $04    ; $2F13
        bne L2F19    ; $2F15
        dec $05    ; $2F17
L2F19   dec $04    ; $2F19
        lda #$00    ; $2F1B
        rts    ; $2F1D
L2F1E   lda #$FF    ; $2F1E
        rts    ; $2F20
;
; === FixText ===
        txa    ; $2F21
        bpl L2F3C    ; $2F22
        jsr L2FB0    ; $2F24
        bne L2F36    ; $2F27
        jsr CheckTop    ; $2F29
        beq L2F39    ; $2F2C
        lda $04    ; $2F2E
        bne L2F34    ; $2F30
        dec $05    ; $2F32
L2F34   dec $04    ; $2F34
L2F36   lda #$00    ; $2F36
        rts    ; $2F38
L2F39   lda #$FF    ; $2F39
        rts    ; $2F3B
L2F3C   jsr L2FB0    ; $2F3C
        bcc L2F59    ; $2F3F
        bne L2F51    ; $2F41
        lda GapBot    ; $2F43
        sta $04    ; $2F45
        lda $6D    ; $2F47
        sta $05    ; $2F49
        inc $04    ; $2F4B
        bne L2F51    ; $2F4D
        inc $05    ; $2F4F
L2F51   jsr L2FC6    ; $2F51
        bne L2F59    ; $2F54
        lda #$FF    ; $2F56
        rts    ; $2F58
L2F59   lda #$00    ; $2F59
        rts    ; $2F5B
;
; === CheckTop ===
        ldy $05    ; $2F5C
        ldx $04    ; $2F5E
        bne L2F63    ; $2F60
        dey    ; $2F62
L2F63   dex    ; $2F63
        cpy $6D    ; $2F64
        bcc L2F81    ; $2F66
        bne L2F70    ; $2F68
        cpx GapBot    ; $2F6A
        beq L2F74    ; $2F6C
        bcc L2F81    ; $2F6E
L2F70   lda #$FF    ; $2F70
        bmi L2F95    ; $2F72
L2F74   lda GapTop    ; $2F74
        cmp BuffTop    ; $2F76
        bne L2F95    ; $2F78
        lda $6B    ; $2F7A
        cmp $67    ; $2F7C
        jmp L2F95    ; $2F7E
L2F81   cpy $67    ; $2F81
        bcc L2F8B    ; $2F83
        bne L2F95    ; $2F85
        cpx BuffTop    ; $2F87
        bcs L2F95    ; $2F89
L2F8B   lda BuffTop    ; $2F8B
        sta $04    ; $2F8D
        lda $67    ; $2F8F
        sta $05    ; $2F91
        lda #$00    ; $2F93
L2F95   php    ; $2F95
        ldy #$00    ; $2F96
        plp    ; $2F98
        rts    ; $2F99
L2F9A   lda GapBot    ; $2F9A
        clc    ; $2F9C
        adc #$01    ; $2F9D
        php    ; $2F9F
        cmp $04    ; $2FA0
        bne L2FAC    ; $2FA2
        plp    ; $2FA4
        lda $6D    ; $2FA5
        adc #$00    ; $2FA7
        cmp $05    ; $2FA9
        rts    ; $2FAB
L2FAC   plp    ; $2FAC
        lda #$FF    ; $2FAD
        rts    ; $2FAF
L2FB0   lda $05    ; $2FB0
        cmp $6B    ; $2FB2
        bne L2FBA    ; $2FB4
        lda $04    ; $2FB6
        cmp GapTop    ; $2FB8
L2FBA   rts    ; $2FBA
L2FBB   lda $04    ; $2FBB
        cmp BuffTop    ; $2FBD
        bne L2FC5    ; $2FBF
        lda $05    ; $2FC1
        cmp $67    ; $2FC3
L2FC5   rts    ; $2FC5
L2FC6   lda $04    ; $2FC6
        cmp BuffBot    ; $2FC8
        bne L2FD0    ; $2FCA
        lda $05    ; $2FCC
        cmp $69    ; $2FCE
L2FD0   rts    ; $2FD0
L2FD1   jsr L2FB0    ; $2FD1
        bcc L2FFD    ; $2FD4
        bne L2FED    ; $2FD6
        lda GapBot    ; $2FD8
        clc    ; $2FDA
        adc #$01    ; $2FDB
        cmp BuffBot    ; $2FDD
        bne L2FFD    ; $2FDF
        cmp #$00    ; $2FE1
        beq L2FE6    ; $2FE3
        clc    ; $2FE5
L2FE6   lda $6D    ; $2FE6
        adc #$00    ; $2FE8
        cmp $69    ; $2FEA
        rts    ; $2FEC
L2FED   lda $05    ; $2FED
        cmp $69    ; $2FEF
        bcc L2FFD    ; $2FF1
        bne L2FFE    ; $2FF3
        lda $04    ; $2FF5
        cmp BuffBot    ; $2FF7
        bcc L2FFD    ; $2FF9
        bne L2FFE    ; $2FFB
L2FFD   rts    ; $2FFD
L2FFE   lda BuffBot    ; $2FFE
        sta $04    ; $3000
        lda $69    ; $3002
        sta $05    ; $3004
        lda #$00    ; $3006
        rts    ; $3008
        brk    ; $3009
        brk    ; $300A
;
; === EnableKDisp ===
        brk    ; $300B
;
; === DisplayPage ===
        jsr InitTypeout    ; $300C
;
; === DisplayPage1 ===
        jsr ModeInfo    ; $300F
        jsr Home    ; $3012
        lda PageTop    ; $3015
        sta $00    ; $3017
        lda $63    ; $3019
        sta $01    ; $301B
;
; === DisplayTemp ===
        ldy #$00    ; $301D
        bit $300A    ; $301F
        bmi L3036    ; $3022
L3024   bit $3009    ; $3024
        bpl L3036    ; $3027
        lda $00    ; $3029
        cmp TheBuffer    ; $302B
        bne L3036    ; $302D
        lda $01    ; $302F
        cmp $61    ; $3031
        bne L3036    ; $3033
        rts    ; $3035
L3036   lda $01    ; $3036
        cmp $6B    ; $3038
        bcc L3059    ; $303A
        bne L3049    ; $303C
        lda $00    ; $303E
        cmp GapTop    ; $3040
        bcc L3059    ; $3042
        bne L3049    ; $3044
        jsr SetTempBot    ; $3046
L3049   lda $00    ; $3049
        cmp BuffBot    ; $304B
        bne L3059    ; $304D
        lda $01    ; $304F
        cmp $69    ; $3051
        bne L3059    ; $3053
        jsr ClearEOP    ; $3055
        rts    ; $3058
L3059   jsr $D000    ; $3059
        ldx CV    ; $305C
        inx    ; $305E
        cpx WindowBot    ; $305F
        bcc L309B    ; $3061
        cmp #$8D    ; $3063
        bne L306B    ; $3065
        jsr ClearEOL    ; $3067
        rts    ; $306A
L306B   jsr GetXCharLen    ; $306B
        txa    ; $306E
        clc    ; $306F
        adc CH    ; $3070
        cmp WindowRgt    ; $3072
        bcs L308E    ; $3074
        jsr $D000    ; $3076
L3079   jsr CharOut    ; $3079
L307C   bit EnableKDisp    ; $307C
        bpl L3086    ; $307F
        pha    ; $3081
        jsr GatherTYI    ; $3082
        pla    ; $3085
L3086   inc $00    ; $3086
        bne L308C    ; $3088
        inc $01    ; $308A
L308C   bne L3024    ; $308C
L308E   pha    ; $308E
        ldx WindowRgt    ; $308F
        dex    ; $3091
        stx CH    ; $3092
        lda #$A1    ; $3094
        jsr CharOut    ; $3096
        pla    ; $3099
        rts    ; $309A
L309B   jsr GetXCharLen    ; $309B
        txa    ; $309E
        clc    ; $309F
        adc CH    ; $30A0
        cmp WindowRgt    ; $30A2
        php    ; $30A4
        jsr $D000    ; $30A5
        plp    ; $30A8
        bcc L3079    ; $30A9
        cmp #$8D    ; $30AB
        beq L30B9    ; $30AD
        jsr L308E    ; $30AF
        cmp #$89    ; $30B2
        bne L3079    ; $30B4
        jmp L307C    ; $30B6
L30B9   ldx CH    ; $30B9
        inx    ; $30BB
        cpx WindowRgt    ; $30BC
        bcc L3079    ; $30BE
        jsr L308E    ; $30C0
        jmp L3024    ; $30C3
;
; === DisplayDown ===
        lda CV    ; $30C6
        pha    ; $30C8
        lda CH    ; $30C9
        pha    ; $30CB
        lda TheBuffer    ; $30CC
        sta $00    ; $30CE
        lda $61    ; $30D0
        sta $01    ; $30D2
        jsr DisplayTemp    ; $30D4
        pla    ; $30D7
        sta CH    ; $30D8
        pla    ; $30DA
        sta CV    ; $30DB
        jmp vtab    ; $30DD
;
; === DispToPoint ===
        lda #$FF    ; $30E0
        sta $3009    ; $30E2
        jsr DisplayPage1    ; $30E5
        inc $3009    ; $30E8
        rts    ; $30EB
;
; === DecrScreen ===
        lda PageTop    ; $30EC
        sta $04    ; $30EE
        lda $63    ; $30F0
        sta $05    ; $30F2
        jsr L2F01    ; $30F4
        bne L3106    ; $30F7
        jsr BackScrLine    ; $30F9
        lda $04    ; $30FC
        sta PageTop    ; $30FE
        lda $05    ; $3100
        sta $63    ; $3102
        lda #$00    ; $3104
L3106   rts    ; $3106
;
; === IncrScreen ===
        lda PageTop    ; $3107
        sta $04    ; $3109
        lda $63    ; $310B
        sta $05    ; $310D
        jsr L2F3C    ; $310F
        bne L3136    ; $3112
        ldy #$00    ; $3114
        lda WindowLft    ; $3116
        sta $3146    ; $3118
L311B   jsr $D012    ; $311B
        cmp #$8D    ; $311E
        beq L3140    ; $3120
        jsr GetXCharLen    ; $3122
        txa    ; $3125
        clc    ; $3126
        adc $3146    ; $3127
        cmp WindowRgt    ; $312A
        bcs L3137    ; $312C
        sta $3146    ; $312E
        jsr L2ECC    ; $3131
        beq L311B    ; $3134
L3136   rts    ; $3136
L3137   lda $04    ; $3137
        sta PageTop    ; $3139
        lda $05    ; $313B
        sta $63    ; $313D
        rts    ; $313F
L3140   jsr L2ECC    ; $3140
        beq L3137    ; $3143
        rts    ; $3145
        brk    ; $3146
;
; === DisplayLine ===
        lda TheBuffer    ; $3147
        sta $04    ; $3149
        lda $61    ; $314B
        sta $05    ; $314D
        lda CV    ; $314F
        pha    ; $3151
        lda CH    ; $3152
        pha    ; $3154
        jsr BackScrLine    ; $3155
        pla    ; $3158
        sta CH    ; $3159
        pla    ; $315B
        sta CV    ; $315C
        jsr PrintTextLine    ; $315E
        jmp vtab    ; $3161
;
; === PrintTextLine ===
        lda CV    ; $3164
        pha    ; $3166
        lda CH    ; $3167
        pha    ; $3169
        lda WindowLft    ; $316A
        sta CH    ; $316C
        jsr vtab    ; $316E
        ldx WindowBot    ; $3171
        inx    ; $3173
        stx CV    ; $3174
        lda $04    ; $3176
        sta $00    ; $3178
        lda $05    ; $317A
        sta $01    ; $317C
        dec $300A    ; $317E
        jsr DisplayTemp    ; $3181
        inc $300A    ; $3184
        pla    ; $3187
        sta CH    ; $3188
        pla    ; $318A
        sta CV    ; $318B
        jsr vtab    ; $318D
        rts    ; $3190
;
; === LinesPastPnt ===
        ldy #$01    ; $3191
        ldx #$00    ; $3193
        stx $00    ; $3195
        lda CV    ; $3197
        pha    ; $3199
        lda CH    ; $319A
        pha    ; $319C
L319D   tya    ; $319D
        clc    ; $319E
        adc GapBot    ; $319F
        tax    ; $31A1
        lda $6D    ; $31A2
        adc #$00    ; $31A4
        cmp $69    ; $31A6
        bne L31AE    ; $31A8
        cpx BuffBot    ; $31AA
        beq L31D9    ; $31AC
L31AE   jsr $D03F    ; $31AE
        cmp #$8D    ; $31B1
        beq L31D9    ; $31B3
        jsr GetXCharLen    ; $31B5
        pha    ; $31B8
        lda CV    ; $31B9
        sta $00    ; $31BB
        pla    ; $31BD
        jsr BumpXPos    ; $31BE
        lda CV    ; $31C1
        cmp $00    ; $31C3
        beq L31C9    ; $31C5
        inc $00    ; $31C7
L31C9   iny    ; $31C9
        bne L319D    ; $31CA
        inc $31E2    ; $31CC
        pla    ; $31CF
        sta CH    ; $31D0
        pla    ; $31D2
        sta CV    ; $31D3
        lda $31E2    ; $31D5
        rts    ; $31D8
L31D9   pla    ; $31D9
        sta CH    ; $31DA
        pla    ; $31DC
        sta CV    ; $31DD
        lda $00    ; $31DF
        rts    ; $31E1
        brk    ; $31E2
;
; === FindPointCol ===
        lda CV    ; $31E3
        pha    ; $31E5
        lda CH    ; $31E6
        pha    ; $31E8
        jsr BackScrLine    ; $31E9
        ldx CH    ; $31EC
        pla    ; $31EE
        sta CH    ; $31EF
        pla    ; $31F1
        sta CV    ; $31F2
        rts    ; $31F4
;
; === CenterLine ===
        ora #$08    ; $31F5
;
; === CenterPage ===
        lda WindowTop    ; $31F7
        clc    ; $31F9
        adc CenterLine    ; $31FA
        cmp WindowBot    ; $31FD
        bcc L320A    ; $31FF
        lda WindowBot    ; $3201
        sec    ; $3203
        sbc WindowTop    ; $3204
        lsr    ; $3206
        sec    ; $3207
        sbc #$01    ; $3208
L320A   sta CenterPoint    ; $320A
;
; === CenterPage1 ===
        lda TheBuffer    ; $320D
        sta $04    ; $320F
        lda $61    ; $3211
        sta $05    ; $3213
        jsr BackScrLine    ; $3215
        lda $04    ; $3218
        sta PageTop    ; $321A
        lda $05    ; $321C
        sta $63    ; $321E
        lda CenterPoint    ; $3220
        beq L322F    ; $3223
L3225   jsr DecrScreen    ; $3225
        bne L322F    ; $3228
        dec CenterPoint    ; $322A
        bne L3225    ; $322D
L322F   jsr DisplayPage    ; $322F
        jsr FindPoint    ; $3232
        lda #$00    ; $3235
        rts    ; $3237
;
; === GenDisplay ===
        bit TypeoutFlag    ; $3238
        bpl L324B    ; $323B
        pha    ; $323D
        jsr InitTypeout    ; $323E
        pla    ; $3241
        cmp #$06    ; $3242
        bcs L324B    ; $3244
        jsr DisplayPage    ; $3246
        lda #$01    ; $3249
L324B   asl    ; $324B
        tax    ; $324C
        cpx #$0E    ; $324D
        bcs L325E    ; $324F
        lda DispVects,x    ; $3251
        sta $00    ; $3254
        lda $3263,x    ; $3256
        sta $01    ; $3259
        jmp ($0000)    ; $325B
L325E   jsr Beep    ; $325E
        rts    ; $3261
;
; === DispVects ===
        dfb $37        ; $3262  (data/65C02-bit)
        and (PhysBuffBot)    ; $3263
        and ($C6)    ; $3265
        bmi $32B0    ; $3267
        and ($E0),y    ; $3269
        bmi $32E6    ; $326B
        and ($F7)    ; $326D
        and (WindowLft),y    ; $326F
        dey    ; $3271
        and $03F0    ; $3272
        jmp CenterPage    ; $3275
        rts    ; $3278
;
; === DispPointEnd ===
        jsr SetGap    ; $3279
        lda CV    ; $327C
        pha    ; $327E
        lda CH    ; $327F
        pha    ; $3281
        lda $6D    ; $3282
        pha    ; $3284
        lda GapBot    ; $3285
        pha    ; $3287
        inc GapBot    ; $3288
        bne L328E    ; $328A
        inc $6D    ; $328C
L328E   ldy #$00    ; $328E
L3290   lda GapBot    ; $3290
        cmp BuffBot    ; $3292
        bne L32AF    ; $3294
        lda $6D    ; $3296
        cmp $69    ; $3298
        bne L32AF    ; $329A
L329C   jsr ClearEOL    ; $329C
L329F   pla    ; $329F
        sta GapBot    ; $32A0
        pla    ; $32A2
        sta $6D    ; $32A3
        pla    ; $32A5
        sta CH    ; $32A6
        pla    ; $32A8
        sta CV    ; $32A9
        jsr vtab    ; $32AB
        rts    ; $32AE
L32AF   jsr $D03F    ; $32AF
        cmp #$8D    ; $32B2
        beq L32ED    ; $32B4
        jsr GetXCharLen    ; $32B6
        txa    ; $32B9
        clc    ; $32BA
        adc CH    ; $32BB
        cmp WindowRgt    ; $32BD
        bcs L32CF    ; $32BF
L32C1   jsr $D03F    ; $32C1
        jsr CharOut    ; $32C4
L32C7   inc GapBot    ; $32C7
        bne L32CD    ; $32C9
        inc $6D    ; $32CB
L32CD   bne L3290    ; $32CD
L32CF   jsr ClearEOL    ; $32CF
        ldy #$00    ; $32D2
        ldx WindowRgt    ; $32D4
        dex    ; $32D6
        stx CH    ; $32D7
        lda #$A1    ; $32D9
        jsr CharOut    ; $32DB
        lda CV    ; $32DE
        cmp WindowTop    ; $32E0
        beq L329F    ; $32E2
        jsr $D03F    ; $32E4
        cmp #$89    ; $32E7
        bne L32C1    ; $32E9
        beq L32C7    ; $32EB
L32ED   ldx CH    ; $32ED
        inx    ; $32EF
        cpx WindowRgt    ; $32F0
        bcc L329C    ; $32F2
        lda #$A1    ; $32F4
        jsr CharOut    ; $32F6
        jsr PrintReturn    ; $32F9
        jmp L329F    ; $32FC
;
; === ScrollLineTop ===
        ds 5        ; $32FF  5 bytes $00 fill
;
; === Scroll ===
        lda WindowRgt    ; $3304
        lsr    ; $3306
        sta $3303    ; $3307
        lda ScrollDir    ; $330A
        bpl L3337    ; $330D
L330F   lda ScrollDest    ; $330F
        jsr vtab1    ; $3312
        lda BASL    ; $3315
        sta $2A    ; $3317
        lda BASH    ; $3319
        sta $2B    ; $331B
        lda ScrollLineTop    ; $331D
        jsr vtab1    ; $3320
        jsr L335F    ; $3323
        inc ScrollDest    ; $3326
        inc ScrollLineTop    ; $3329
        lda ScrollLineTop    ; $332C
        cmp ScrollLineBot    ; $332F
        bcc L330F    ; $3332
        beq L330F    ; $3334
        rts    ; $3336
L3337   lda ScrollDest    ; $3337
        jsr vtab1    ; $333A
        lda BASL    ; $333D
        sta $2A    ; $333F
        lda BASH    ; $3341
        sta $2B    ; $3343
        lda ScrollLineBot    ; $3345
        jsr vtab1    ; $3348
        jsr L335F    ; $334B
        dec ScrollDest    ; $334E
        dec ScrollLineBot    ; $3351
        bmi L335E    ; $3354
        lda ScrollLineBot    ; $3356
        cmp ScrollLineTop    ; $3359
        bcs L3337    ; $335C
L335E   rts    ; $335E
L335F   ldy #$00    ; $335F
        sty Page2    ; $3361   <== BANK: display page 2 / aux (PAGE2 on)
L3364   lda (BASL),y    ; $3364
        sta ($2A),y    ; $3366
        iny    ; $3368
        cpy $3303    ; $3369
        bcc L3364    ; $336C
        dey    ; $336E
        sty Page1    ; $336F   <== BANK: display page 1 / main (PAGE2 off)
L3372   lda (BASL),y    ; $3372
        sta ($2A),y    ; $3374
        dey    ; $3376
        bpl L3372    ; $3377
        rts    ; $3379
;
; === TV:InsLine ===
        lda CV    ; $337A
;
; === TV:InsLine1 ===
        sta ScrollLineTop    ; $337C
        lda WindowBot    ; $337F
        sec    ; $3381
        sbc #$02    ; $3382
        sta ScrollLineBot    ; $3384
        sta ScrollDest    ; $3387
        inc ScrollDest    ; $338A
        cmp ScrollLineTop    ; $338D
        bcc L339B    ; $3390
        lda WindowRgt    ; $3392
        lsr    ; $3394
        sta $3303    ; $3395
        jsr L3337    ; $3398
L339B   lda ScrollLineTop    ; $339B
        sta CV    ; $339E
        lda #$00    ; $33A0
        sta CH    ; $33A2
        jsr vtab    ; $33A4
        jsr ClearEOL    ; $33A7
        rts    ; $33AA
;
; === TV:DelLine ===
        lda CV    ; $33AB
;
; === TV:DelLine1 ===
        sta ScrollDest    ; $33AD
        sta ScrollLineTop    ; $33B0
        inc ScrollLineTop    ; $33B3
        lda WindowBot    ; $33B6
        sec    ; $33B8
        sbc #$01    ; $33B9
        sta ScrollLineBot    ; $33BB
        cmp ScrollLineTop    ; $33BE
        beq L33CC    ; $33C1
        lda WindowRgt    ; $33C3
        lsr    ; $33C5
        sta $3303    ; $33C6
        jsr L330F    ; $33C9
L33CC   lda ScrollLineBot    ; $33CC
        sta CV    ; $33CF
        lda #$00    ; $33D1
        sta CH    ; $33D3
        jsr vtab    ; $33D5
        jsr ClearEOL    ; $33D8
        rts    ; $33DB
