;-*- Mode: Merlin -*-
;
; src/modules/07_motion.s -- AMACS: line/word/sentence movement and kill
; Address range $33DC-$3BAF. GENERATED by tools/disasm.py.
; `put' from src/amacs.s; symbols/labels are global across modules.
;
; ---- $33DC-$3BAF  code ----
;
; === PointToCol ===
        sta $3405    ; $33DC
        jsr BegOfLine    ; $33DF
        ldy #$00    ; $33E2
        sty CH    ; $33E4
L33E6   lda CH    ; $33E6
        cmp $3405    ; $33E8
        bcs L3402    ; $33EB
        jsr $D01B    ; $33ED
        cmp #$8D    ; $33F0
        beq L3402    ; $33F2
        jsr GetXCharLen    ; $33F4
        jsr BumpXPos    ; $33F7
        jsr PointForward    ; $33FA
        bne L3404    ; $33FD
        jmp L33E6    ; $33FF
L3402   lda #$00    ; $3402
L3404   rts    ; $3404
        ds 5        ; $3405  5 bytes $00 fill
;
; === GetGoalColumn ===
        lda UserGoal    ; $340A
        ora $3409    ; $340D
        beq L3421    ; $3410
        lda UserGoal    ; $3412
        sta GoalColumn    ; $3415
        lda $3409    ; $3418
        sta $3407    ; $341B
        jmp L3437    ; $341E
L3421   lda GoalColumn    ; $3421
        ora $3407    ; $3424
        bne L3437    ; $3427
        lda TheBuffer    ; $3429
        sta $04    ; $342B
        lda $61    ; $342D
        sta $05    ; $342F
        jsr FindPointCol    ; $3431
        stx GoalColumn    ; $3434
L3437   rts    ; $3437
;
; === NewLineEOB ===
        brk    ; $3438
;
; === DownRealLine ===
        jsr GetArgSign    ; $3439
        bmi UpRealLine    ; $343C
L343E   jsr ZeroArg?    ; $343E
        beq L3462    ; $3441
        jsr GetGoalColumn    ; $3443
        jsr EndOfLine    ; $3446
        jsr PointForward    ; $3449
        bne L3465    ; $344C
        lda GoalColumn    ; $344E
        jsr PointToCol    ; $3451
        lda Argument    ; $3454
        bne L345C    ; $3457
        dec $7A5C    ; $3459
L345C   dec Argument    ; $345C
        jmp L343E    ; $345F
L3462   lda #$01    ; $3462
        rts    ; $3464
L3465   jsr EndMacroExec    ; $3465
        lda NewLineEOB    ; $3468
        beq L3462    ; $346B
        jsr SetGap    ; $346D
        jsr InsertReturn    ; $3470
        jmp L3462    ; $3473
        brk    ; $3476
;
; === UpRealLine ===
        jsr GetArgSign    ; $3477
        bmi DownRealLine    ; $347A
L347C   jsr ZeroArg?    ; $347C
        beq L34A3    ; $347F
        jsr GetGoalColumn    ; $3481
        jsr BegOfLine    ; $3484
        jsr PointBackward    ; $3487
        bne L34A0    ; $348A
        lda GoalColumn    ; $348C
        jsr PointToCol    ; $348F
        lda Argument    ; $3492
        bne L349A    ; $3495
        dec $7A5C    ; $3497
L349A   dec Argument    ; $349A
        jmp L347C    ; $349D
L34A0   jsr EndMacroExec    ; $34A0
L34A3   lda #$01    ; $34A3
        rts    ; $34A5
;
; === BegOfLine ===
        ldy #$00    ; $34A6
L34A8   jsr PointBackward    ; $34A8
        bne L34B7    ; $34AB
        jsr $D01B    ; $34AD
        cmp #$8D    ; $34B0
        bne L34A8    ; $34B2
        jsr PointForward    ; $34B4
L34B7   lda #$01    ; $34B7
        rts    ; $34B9
;
; === EndOfLine ===
        jsr PointForward    ; $34BA
        bne L34D0    ; $34BD
        jsr PointBackward    ; $34BF
        ldy #$00    ; $34C2
L34C4   jsr $D01B    ; $34C4
        cmp #$8D    ; $34C7
        beq L34D0    ; $34C9
        jsr PointForward    ; $34CB
        beq L34C4    ; $34CE
L34D0   lda #$01    ; $34D0
        rts    ; $34D2
;
; === ContextLines ===
        dfb $02        ; $34D3  (data/65C02-bit)
;
; === DownScreen ===
        jsr GetArgSign    ; $34D4
        bmi UpScreen    ; $34D7
        jsr AnyArgument?    ; $34D9
        bne L3512    ; $34DC
L34DE   jsr ZeroArg?    ; $34DE
        beq L34F4    ; $34E1
        jsr IncrScreen    ; $34E3
        lda Argument    ; $34E6
        bne L34EE    ; $34E9
        dec $7A5C    ; $34EB
L34EE   dec Argument    ; $34EE
        jmp L34DE    ; $34F1
L34F4   jsr FindPoint    ; $34F4
        beq L350C    ; $34F7
        lda PageTop    ; $34F9
        sta TheBuffer    ; $34FB
        lda $63    ; $34FD
        sta $61    ; $34FF
        jsr SetGap    ; $3501
        lda TheBuffer    ; $3504
        sta PageTop    ; $3506
        lda $61    ; $3508
        sta $63    ; $350A
L350C   jsr DisplayPage    ; $350C
        lda #$01    ; $350F
        rts    ; $3511
L3512   lda WindowBot    ; $3512
        sec    ; $3514
        sbc ContextLines    ; $3515
        sta CV    ; $3518
        lda WindowLft    ; $351A
        sta CH    ; $351C
        jsr PointToCH    ; $351E
        lda TheBuffer    ; $3521
        cmp BuffBot    ; $3523
        bne L352D    ; $3525
        lda $61    ; $3527
        cmp $69    ; $3529
        beq L3546    ; $352B
L352D   jsr SetGap    ; $352D
        lda #$00    ; $3530
        sta CenterPoint    ; $3532
        jsr CenterPage1    ; $3535
        lda TheBuffer    ; $3538
        sta PageTop    ; $353A
        lda $61    ; $353C
        sta $63    ; $353E
        jsr Home    ; $3540
        lda #$00    ; $3543
        rts    ; $3545
L3546   jsr SetGap    ; $3546
        jmp CenterPage    ; $3549
;
; === UpScreen ===
        jsr GetArgSign    ; $354C
        bpl L3554    ; $354F
        jmp DownScreen    ; $3551
L3554   jsr AnyArgument?    ; $3554
        bne L3587    ; $3557
L3559   jsr ZeroArg?    ; $3559
        beq L356F    ; $355C
        jsr DecrScreen    ; $355E
        lda Argument    ; $3561
        bne L3569    ; $3564
        dec $7A5C    ; $3566
L3569   dec Argument    ; $3569
        jmp L3559    ; $356C
L356F   jsr FindPoint    ; $356F
        beq L3581    ; $3572
        lda WindowBot    ; $3574
        sta CV    ; $3576
        lda WindowLft    ; $3578
        sta CH    ; $357A
        dec CV    ; $357C
        jsr PointToCH    ; $357E
L3581   jsr DisplayPage    ; $3581
        lda #$01    ; $3584
        rts    ; $3586
L3587   lda WindowBot    ; $3587
        sec    ; $3589
        sbc WindowTop    ; $358A
        sbc ContextLines    ; $358C
L358F   pha    ; $358F
        jsr DecrScreen    ; $3590
        pla    ; $3593
        sec    ; $3594
        sbc #$01    ; $3595
        bne L358F    ; $3597
        jsr DisplayPage    ; $3599
        ldx WindowBot    ; $359C
        dex    ; $359E
        stx CV    ; $359F
        lda WindowLft    ; $35A1
        sta CH    ; $35A3
        jsr PointToCH    ; $35A5
        lda #$00    ; $35A8
        rts    ; $35AA
;
; === SetPopMark ===
        jsr AnyArgument?    ; $35AB
        beq L35BC    ; $35AE
        jsr SetGap    ; $35B0
        jsr PushMark    ; $35B3
L35B6   jsr SetGap    ; $35B6
        lda #$01    ; $35B9
        rts    ; $35BB
L35BC   jsr PopMark    ; $35BC
        jmp L35B6    ; $35BF
;
; === LeftWord ===
        jsr ClrLastKill    ; $35C2
;
; === IN:LeftWord ===
        jsr GetArgSign    ; $35C5
        bmi IN:RightWord    ; $35C8
L35CA   jsr ZeroArg?    ; $35CA
        beq L3611    ; $35CD
        ldy #$00    ; $35CF
L35D1   jsr PointBackward    ; $35D1
        bne L3611    ; $35D4
        jsr $D01B    ; $35D6
        jsr Separator?    ; $35D9
        beq L35D1    ; $35DC
L35DE   jsr PointBackward    ; $35DE
        bne L3611    ; $35E1
        jsr $D01B    ; $35E3
        jsr Separator?    ; $35E6
        bne L35DE    ; $35E9
        ldy #$40    ; $35EB
        lda (BuffData),y    ; $35ED
        ldy #$00    ; $35EF
        and #$10    ; $35F1
        beq L3600    ; $35F3
        jsr $D01B    ; $35F5
        cmp #$C1    ; $35F8
        bcc L3600    ; $35FA
        cmp #$DB    ; $35FC
        bcc L3603    ; $35FE
L3600   jsr PointForward    ; $3600
L3603   lda Argument    ; $3603
        bne L360B    ; $3606
        dec $7A5C    ; $3608
L360B   dec Argument    ; $360B
        jmp L35CA    ; $360E
L3611   jsr SetGap    ; $3611
        lda #$01    ; $3614
        rts    ; $3616
;
; === RightWord ===
        jsr ClrLastKill    ; $3617
;
; === IN:RightWord ===
        jsr GetArgSign    ; $361A
        bmi IN:LeftWord    ; $361D
L361F   jsr ZeroArg?    ; $361F
        beq L365A    ; $3622
        jsr SetGap    ; $3624
        ldy #$01    ; $3627
        jsr $D03F    ; $3629
        dey    ; $362C
        jsr Separator?    ; $362D
        bne L363F    ; $3630
L3632   jsr PointForward    ; $3632
        bne L365A    ; $3635
        jsr $D01B    ; $3637
        jsr Separator?    ; $363A
        beq L3632    ; $363D
L363F   jsr PointForward    ; $363F
        bne L365A    ; $3642
        jsr $D01B    ; $3644
        jsr Separator?    ; $3647
        bne L363F    ; $364A
        lda Argument    ; $364C
        bne L3654    ; $364F
        dec $7A5C    ; $3651
L3654   dec Argument    ; $3654
        jmp L361F    ; $3657
L365A   jsr SetGap    ; $365A
        lda #$01    ; $365D
        rts    ; $365F
;
; === UpperWord ===
        jsr L3713    ; $3660
        jsr IN:UpperReg    ; $3663
L3666   jsr SetModified    ; $3666
        jsr FindPoint    ; $3669
        beq L3671    ; $366C
        lda #$06    ; $366E
        rts    ; $3670
L3671   lda #$04    ; $3671
        rts    ; $3673
;
; === LowerWord ===
        jsr L3713    ; $3674
        jsr IN:LowerReg    ; $3677
        jmp L3666    ; $367A
;
; === CapWord ===
        jsr L3713    ; $367D
        jsr IN:CapReg    ; $3680
        jmp L3666    ; $3683
;
; === IN:UpperReg ===
        ldy #$00    ; $3686
L3688   jsr EqTempPoint?    ; $3688
        beq L369E    ; $368B
        jsr $D000    ; $368D
        jsr UpperCon    ; $3690
        jsr $D054    ; $3693
        inc $00    ; $3696
        bne L369C    ; $3698
        inc $01    ; $369A
L369C   bne L3688    ; $369C
L369E   rts    ; $369E
;
; === IN:LowerReg ===
        ldy #$00    ; $369F
L36A1   jsr EqTempPoint?    ; $36A1
        beq L36B7    ; $36A4
        jsr $D000    ; $36A6
        jsr LowerCon    ; $36A9
        jsr $D054    ; $36AC
        inc $00    ; $36AF
        bne L36B5    ; $36B1
        inc $01    ; $36B3
L36B5   bne L36A1    ; $36B5
L36B7   rts    ; $36B7
;
; === IN:CapReg ===
        ldy #$00    ; $36B8
L36BA   jsr EqTempPoint?    ; $36BA
        beq L36F1    ; $36BD
        jsr $D000    ; $36BF
        jsr Separator?    ; $36C2
        beq L36E9    ; $36C5
        jsr UpperCon    ; $36C7
        jsr $D054    ; $36CA
L36CD   inc $00    ; $36CD
        bne L36D3    ; $36CF
        inc $01    ; $36D1
L36D3   jsr EqTempPoint?    ; $36D3
        beq L36F1    ; $36D6
        jsr $D000    ; $36D8
        jsr Separator?    ; $36DB
        beq L36BA    ; $36DE
        jsr LowerCon    ; $36E0
        jsr $D054    ; $36E3
        jmp L36CD    ; $36E6
L36E9   inc $00    ; $36E9
        bne L36EF    ; $36EB
        inc $01    ; $36ED
L36EF   bne L36BA    ; $36EF
L36F1   rts    ; $36F1
;
; === EqTempPoint? ===
        lda $00    ; $36F2
        cmp TheBuffer    ; $36F4
        bne L36FC    ; $36F6
        lda $01    ; $36F8
        cmp $61    ; $36FA
L36FC   rts    ; $36FC
;
; === UpperCon ===
        cmp #$E1    ; $36FD
        bcc L3707    ; $36FF
        cmp #$FB    ; $3701
        bcs L3707    ; $3703
        and #$DF    ; $3705
L3707   rts    ; $3707
;
; === LowerCon ===
        cmp #$C1    ; $3708
        bcc L3712    ; $370A
        cmp #$DB    ; $370C
        bcs L3712    ; $370E
        adc #$20    ; $3710
L3712   rts    ; $3712
L3713   jsr SetGap    ; $3713
        lda $61    ; $3716
        pha    ; $3718
        lda TheBuffer    ; $3719
        pha    ; $371B
        lda ArgSign    ; $371C
        pha    ; $371F
        jsr IN:RightWord    ; $3720
        pla    ; $3723
L3724   bmi L372F    ; $3724
        pla    ; $3726
        sta $00    ; $3727
        pla    ; $3729
        sta $01    ; $372A
        rts    ; $372C
        brk    ; $372D
        brk    ; $372E
L372F   pla    ; $372F
        sta $00    ; $3730
        pla    ; $3732
        sta $01    ; $3733
        lda $00    ; $3735
        sec    ; $3737
        sbc TheBuffer    ; $3738
        sta $00    ; $373A
        lda $01    ; $373C
        sbc $61    ; $373E
        sta $01    ; $3740
        lda GapBot    ; $3742
        sec    ; $3744
        adc $00    ; $3745
        sta TheBuffer    ; $3747
        lda $6D    ; $3749
        adc $01    ; $374B
        sta $61    ; $374D
        lda $00    ; $374F
        sta $372D    ; $3751
        lda $01    ; $3754
        sta $372E    ; $3756
        jsr SetGap    ; $3759
        lda TheBuffer    ; $375C
        sec    ; $375E
        sbc $00    ; $375F
        sta $00    ; $3761
        lda $61    ; $3763
        sbc $01    ; $3765
        sta $01    ; $3767
        rts    ; $3769
;
; === Separator? ===
        ldx #$00    ; $376A
        sta $37A5    ; $376C
        tya    ; $376F
        pha    ; $3770
        ldy #$40    ; $3771
        lda (BuffData),y    ; $3773
        and #$10    ; $3775
        beq L378C    ; $3777
        lda $37A5    ; $3779
        cmp #$C1    ; $377C
        bcc L378C    ; $377E
        cmp #$DB    ; $3780
        bcs L378C    ; $3782
        pla    ; $3784
        tay    ; $3785
        lda $37A5    ; $3786
        ldx #$00    ; $3789
        rts    ; $378B
L378C   lda (BuffData),y    ; $378C
        and #$01    ; $378E
        beq L3794    ; $3790
        ldx #$03    ; $3792
L3794   pla    ; $3794
        tay    ; $3795
        lda $37A5    ; $3796
L3799   cmp $37C9,x    ; $3799
        beq L37A4    ; $379C
        inx    ; $379E
        cpx #$1E    ; $379F
        bcc L3799    ; $37A1
        inx    ; $37A3
L37A4   rts    ; $37A4
        brk    ; $37A5
        brk    ; $37A6
;
; === WhiteSpace? ===
        ldx #$00    ; $37A7
        bit $37A6    ; $37A9
        bpl WhiteSpace1    ; $37AC
        inx    ; $37AE
;
; === WhiteSpace1 ===
        cmp $37E4,x    ; $37AF
        beq L37BA    ; $37B2
        inx    ; $37B4
        cpx #$03    ; $37B5
        bcc WhiteSpace1    ; $37B7
        inx    ; $37B9
L37BA   rts    ; $37BA
;
; === SentDel? ===
        ldx #$00    ; $37BB
L37BD   cmp $37E1,x    ; $37BD
        beq L37C8    ; $37C0
        inx    ; $37C2
        cpx #$03    ; $37C3
        bcc L37BD    ; $37C5
        inx    ; $37C7
L37C8   rts    ; $37C8
        lda $BADF    ; $37C9
        ldx #$BB    ; $37CC
        dfb $A7        ; $37CE  (data/65C02-bit)
        dfb $DB        ; $37CF  (data/65C02-bit)
        cmp $FDFB,x    ; $37D0
        tay    ; $37D3
        lda #$AB    ; $37D4
        lda $BEAF,x    ; $37D6
        ldy $A3AC,x    ; $37D9
        ldy $A5    ; $37DC
        tax    ; $37DE
        cpy #$FC    ; $37DF
        dfb $BF        ; $37E1  (data/65C02-bit)
        lda ($AE,x)    ; $37E2
        sta $A089    ; $37E4
;
; === DeleteWord ===
        jsr GetArgSign    ; $37E7
        bpl L37EF    ; $37EA
        jmp RuboutWord    ; $37EC
L37EF   jsr L3713    ; $37EF
        lda #$00    ; $37F2
        jsr KillTempPoint    ; $37F4
        lda #$02    ; $37F7
        rts    ; $37F9
;
; === KillTempPoint ===
        jsr GenericKill    ; $37FA
        rts    ; $37FD
;
; === RuboutWord ===
        jsr GetArgSign    ; $37FE
        bpl L3806    ; $3801
        jmp DeleteWord    ; $3803
L3806   lda #$FF    ; $3806
        sta ArgSign    ; $3808
        jsr L3713    ; $380B
        jsr EqTempPoint?    ; $380E
        beq L3823    ; $3811
        lda #$FF    ; $3813
        jsr KillTempPoint    ; $3815
        jsr FindPoint    ; $3818
        beq L3820    ; $381B
        lda #$06    ; $381D
        rts    ; $381F
L3820   lda #$02    ; $3820
        rts    ; $3822
L3823   lda #$00    ; $3823
        rts    ; $3825
;
; === KillLineBk ===
        lda #$FF    ; $3826
        eor ArgSign    ; $3828
        sta ArgSign    ; $382B
;
; === KillLine ===
        jsr AnyArgument?    ; $382E
        beq L3846    ; $3831
        jsr IN:KillLine    ; $3833
L3836   bit ArgSign    ; $3836
        bpl L3843    ; $3839
        jsr FindPoint    ; $383B
        beq L3843    ; $383E
        lda #$06    ; $3840
        rts    ; $3842
L3843   lda #$02    ; $3843
        rts    ; $3845
L3846   jsr ZeroArg?    ; $3846
        beq L3836    ; $3849
        lda DeleteKill?    ; $384B
        sta $386D    ; $384E
        jsr IN:KillLine    ; $3851
        beq L385F    ; $3854
        lda $386D    ; $3856
        sta DeleteKill?    ; $3859
        jsr IN:KillLine    ; $385C
L385F   lda Argument    ; $385F
        bne L3867    ; $3862
        dec $7A5C    ; $3864
L3867   dec Argument    ; $3867
        jmp L3846    ; $386A
        brk    ; $386D
;
; === IN:KillLine ===
        lda ArgSign    ; $386E
        bpl L3876    ; $3871
        jmp L38EE    ; $3873
L3876   jsr SetGap    ; $3876
        lda $61    ; $3879
        pha    ; $387B
        lda TheBuffer    ; $387C
        pha    ; $387E
        jsr EndOfLine    ; $387F
        jsr SetGap    ; $3882
        pla    ; $3885
        sta $00    ; $3886
        pla    ; $3888
        sta $01    ; $3889
        jsr EqTempPoint?    ; $388B
        bne L38B7    ; $388E
L3890   lda GapBot    ; $3890
        clc    ; $3892
        adc #$01    ; $3893
        tax    ; $3895
        lda $6D    ; $3896
        adc #$00    ; $3898
        cmp $69    ; $389A
        bne L38A3    ; $389C
        cpx BuffBot    ; $389E
        bne L38A3    ; $38A0
        rts    ; $38A2
L38A3   sta $61    ; $38A3
        inx    ; $38A5
        bne L38AA    ; $38A6
        inc $61    ; $38A8
L38AA   stx TheBuffer    ; $38AA
        jsr SetGap    ; $38AC
        lda #$00    ; $38AF
        jsr KillTempPoint    ; $38B1
        lda #$00    ; $38B4
        rts    ; $38B6
L38B7   ldy #$00    ; $38B7
        lda $01    ; $38B9
        pha    ; $38BB
        lda $00    ; $38BC
        pha    ; $38BE
L38BF   jsr EqTempPoint?    ; $38BF
        beq L38D4    ; $38C2
        jsr $D000    ; $38C4
        jsr WhiteSpace?    ; $38C7
        bne L38E0    ; $38CA
        inc $00    ; $38CC
        bne L38D2    ; $38CE
        inc $01    ; $38D0
L38D2   bne L38BF    ; $38D2
L38D4   pla    ; $38D4
        sta $00    ; $38D5
        pla    ; $38D7
        sta $01    ; $38D8
        jsr DelTempPoint    ; $38DA
        jmp L3890    ; $38DD
L38E0   pla    ; $38E0
        sta $00    ; $38E1
        pla    ; $38E3
        sta $01    ; $38E4
        lda #$00    ; $38E6
        jsr KillTempPoint    ; $38E8
        lda #$FF    ; $38EB
        rts    ; $38ED
L38EE   jsr SetGap    ; $38EE
        lda $61    ; $38F1
        pha    ; $38F3
        lda TheBuffer    ; $38F4
        pha    ; $38F6
        jsr BegOfLine    ; $38F7
        lda TheBuffer    ; $38FA
        sta $00    ; $38FC
        lda $61    ; $38FE
        sta $01    ; $3900
        pla    ; $3902
        sta TheBuffer    ; $3903
        pla    ; $3905
        sta $61    ; $3906
        lda $01    ; $3908
        cmp $61    ; $390A
        bcc L3934    ; $390C
        bne L3918    ; $390E
        lda $00    ; $3910
        cmp TheBuffer    ; $3912
        bcc L3934    ; $3914
        beq L3934    ; $3916
L3918   lda $61    ; $3918
        pha    ; $391A
        lda TheBuffer    ; $391B
        pha    ; $391D
        jsr PointBackward    ; $391E
        bne L3939    ; $3921
        jsr BegOfLine    ; $3923
        lda TheBuffer    ; $3926
        sta $00    ; $3928
        lda $61    ; $392A
        sta $01    ; $392C
        pla    ; $392E
        sta TheBuffer    ; $392F
        pla    ; $3931
        sta $61    ; $3932
L3934   lda #$FF    ; $3934
        jsr KillTempPoint    ; $3936
L3939   lda #$00    ; $3939
        rts    ; $393B
;
; === DeleteSpace ===
        dec $37A6    ; $393C
;
; === GenSpaceDel ===
        jsr DelForSpace    ; $393F
        jsr DelBacSpace    ; $3942
        lda #$00    ; $3945
        sta $37A6    ; $3947
        jsr FindPoint    ; $394A
        beq L3952    ; $394D
        lda #$06    ; $394F
        rts    ; $3951
L3952   lda #$02    ; $3952
        rts    ; $3954
;
; === DeleteLines ===
        jsr BlankLine?    ; $3955
        beq L3970    ; $3958
        jsr EndOfLine    ; $395A
        jsr DeleteSpace    ; $395D
        jsr PointForward    ; $3960
        bne L396D    ; $3963
        jsr BlankLine?    ; $3965
        beq L3970    ; $3968
        jsr PointBackward    ; $396A
L396D   lda #$01    ; $396D
        rts    ; $396F
L3970   jsr DelBacSpace    ; $3970
        jsr InsertReturn    ; $3973
        lda $61    ; $3976
        pha    ; $3978
        lda TheBuffer    ; $3979
        pha    ; $397B
        ldy #$00    ; $397C
L397E   jsr PointForward    ; $397E
        bne L398E    ; $3981
        jsr $D01B    ; $3983
        jsr WhiteSpace?    ; $3986
        beq L397E    ; $3989
        jsr BegOfLine    ; $398B
L398E   jsr SetGap    ; $398E
        pla    ; $3991
        sta $00    ; $3992
        pla    ; $3994
        sta $01    ; $3995
        jsr DelTempPoint    ; $3997
        jsr InsertReturn    ; $399A
        lda TheBuffer    ; $399D
        bne L39A3    ; $399F
        dec $61    ; $39A1
L39A3   dec TheBuffer    ; $39A3
        jsr FindPoint    ; $39A5
        beq L39AD    ; $39A8
        lda #$06    ; $39AA
        rts    ; $39AC
L39AD   lda #$02    ; $39AD
        rts    ; $39AF
L39B0   ldx GapBot    ; $39B0
        ldy $6D    ; $39B2
        inx    ; $39B4
        bne L39B8    ; $39B5
        iny    ; $39B7
L39B8   cpy $69    ; $39B8
        bcc L39BE    ; $39BA
        cpx BuffBot    ; $39BC
L39BE   rts    ; $39BE
;
; === DelForSpace ===
        jsr SetGap    ; $39BF
L39C2   jsr L39B0    ; $39C2
        bcs L39D9    ; $39C5
        ldy #$01    ; $39C7
        jsr $D03F    ; $39C9
        jsr WhiteSpace?    ; $39CC
        bne L39D9    ; $39CF
        inc GapBot    ; $39D1
        bne L39D7    ; $39D3
        inc $6D    ; $39D5
L39D7   bne L39C2    ; $39D7
L39D9   rts    ; $39D9
;
; === DelBacSpace ===
        jsr SetGap    ; $39DA
        ldy #$00    ; $39DD
L39DF   lda TheBuffer    ; $39DF
        cmp BuffTop    ; $39E1
        bne L39EB    ; $39E3
        lda $61    ; $39E5
        cmp $67    ; $39E7
        beq L3A01    ; $39E9
L39EB   lda TheBuffer    ; $39EB
        bne L39F1    ; $39ED
        dec $61    ; $39EF
L39F1   dec TheBuffer    ; $39F1
        jsr $D01B    ; $39F3
        jsr WhiteSpace?    ; $39F6
        beq L39DF    ; $39F9
        inc TheBuffer    ; $39FB
        bne L3A01    ; $39FD
        inc $61    ; $39FF
L3A01   lda TheBuffer    ; $3A01
        sta GapTop    ; $3A03
        lda $61    ; $3A05
        sta $6B    ; $3A07
        rts    ; $3A09
;
; === DelTempPoint ===
        lda $00    ; $3A0A
        sta TheBuffer    ; $3A0C
        sta GapTop    ; $3A0E
        lda $01    ; $3A10
        sta $61    ; $3A12
        sta $6B    ; $3A14
        jsr SetGap    ; $3A16
        rts    ; $3A19
L3A1A   jsr SetGap    ; $3A1A
        lda $61    ; $3A1D
        pha    ; $3A1F
        lda TheBuffer    ; $3A20
        pha    ; $3A22
        lda ArgSign    ; $3A23
        pha    ; $3A26
        jsr IN:RightSent    ; $3A27
        pla    ; $3A2A
        jmp L3724    ; $3A2B
;
; === RightSent ===
        jsr ClrLastKill    ; $3A2E
;
; === IN:RightSent ===
        jsr GetArgSign    ; $3A31
        bmi IN:LeftSent    ; $3A34
        jsr SetGap    ; $3A36
        ldy #$00    ; $3A39
L3A3B   jsr ZeroArg?    ; $3A3B
        bne L3A46    ; $3A3E
L3A40   jsr SetGap    ; $3A40
        lda #$01    ; $3A43
        rts    ; $3A45
L3A46   jsr PointForward    ; $3A46
        bne L3A40    ; $3A49
        jsr $D01B    ; $3A4B
        jsr SentDel?    ; $3A4E
        bne L3A46    ; $3A51
        jsr PointForward    ; $3A53
        bne L3A40    ; $3A56
        jsr $D01B    ; $3A58
        jsr WhiteSpace?    ; $3A5B
        bne L3A46    ; $3A5E
        lda Argument    ; $3A60
        bne L3A68    ; $3A63
        dec $7A5C    ; $3A65
L3A68   dec Argument    ; $3A68
        jmp L3A3B    ; $3A6B
;
; === LeftSent ===
        jsr ClrLastKill    ; $3A6E
;
; === IN:LeftSent ===
        jsr GetArgSign    ; $3A71
        bmi IN:RightSent    ; $3A74
        jsr SetGap    ; $3A76
        ldy #$00    ; $3A79
L3A7B   jsr ZeroArg?    ; $3A7B
        bne L3A86    ; $3A7E
L3A80   jsr SetGap    ; $3A80
        lda #$01    ; $3A83
        rts    ; $3A85
L3A86   jsr PointBackward    ; $3A86
        bne L3A80    ; $3A89
        jsr $D01B    ; $3A8B
        jsr WhiteSpace?    ; $3A8E
        beq L3A86    ; $3A91
L3A93   jsr PointBackward    ; $3A93
        bne L3A80    ; $3A96
        jsr $D01B    ; $3A98
        jsr WhiteSpace?    ; $3A9B
        bne L3A93    ; $3A9E
        cmp #$8D    ; $3AA0
        bne L3AB0    ; $3AA2
        jsr PointBackward    ; $3AA4
        jsr $D01B    ; $3AA7
        cmp #$8D    ; $3AAA
        beq L3AC2    ; $3AAC
        bne L3AB8    ; $3AAE
L3AB0   jsr PointBackward    ; $3AB0
        bne L3A80    ; $3AB3
        jsr $D01B    ; $3AB5
L3AB8   jsr WhiteSpace?    ; $3AB8
        beq L3AB0    ; $3ABB
        jsr SentDel?    ; $3ABD
        bne L3A93    ; $3AC0
L3AC2   jsr PointForward    ; $3AC2
        bne L3ACF    ; $3AC5
        jsr $D01B    ; $3AC7
        jsr WhiteSpace?    ; $3ACA
        beq L3AC2    ; $3ACD
L3ACF   jsr SetGap    ; $3ACF
        lda Argument    ; $3AD2
        bne L3ADA    ; $3AD5
        dec $7A5C    ; $3AD7
L3ADA   dec Argument    ; $3ADA
        jmp L3A7B    ; $3ADD
;
; === KillSent ===
        jsr GetArgSign    ; $3AE0
        bmi KillSentB    ; $3AE3
        jsr L3A1A    ; $3AE5
        lda #$00    ; $3AE8
        jsr KillTempPoint    ; $3AEA
        lda #$02    ; $3AED
        rts    ; $3AEF
;
; === KillSentB ===
        jsr GetArgSign    ; $3AF0
        bmi KillSent    ; $3AF3
        lda #$FF    ; $3AF5
        sta ArgSign    ; $3AF7
        jsr L3A1A    ; $3AFA
        lda #$FF    ; $3AFD
        jsr KillTempPoint    ; $3AFF
        jsr FindPoint    ; $3B02
        beq L3B0A    ; $3B05
        lda #$06    ; $3B07
        rts    ; $3B09
L3B0A   lda #$02    ; $3B0A
        rts    ; $3B0C
;
; === BlankLine? ===
        jsr BackToIndent    ; $3B0D
        jsr SetGap    ; $3B10
        jsr L39B0    ; $3B13
        bcs L3B1F    ; $3B16
        ldy #$01    ; $3B18
        jsr $D03F    ; $3B1A
        cmp #$8D    ; $3B1D
L3B1F   rts    ; $3B1F
;
; === ReadLineHelp ===
        dfb $22        ; $3B20  (data/65C02-bit)
        dfb $3B        ; $3B21  (data/65C02-bit)
        rts    ; $3B22
;
; === ReadArgLine ===
        lda #$D2    ; $3B23
        sta ReadLineHelp    ; $3B25
        lda #$3C    ; $3B28
        sta $3B21    ; $3B2A
;
; === ReadLine ===
        lda #$00    ; $3B2D
;
; === IN:ReadLine ===
        sta CharIndex    ; $3B2F
        lda CH    ; $3B32
        sta ReadLineCH    ; $3B34
        lda CV    ; $3B37
        sta $3F19    ; $3B39
        jsr vtab    ; $3B3C
L3B3F   jsr TypeLine    ; $3B3F
        jsr BlinkCursor    ; $3B42
        jsr L3B69    ; $3B45
        jmp L3B51    ; $3B48
        jsr Beep    ; $3B4B
        jmp L3B3F    ; $3B4E
L3B51   pha    ; $3B51
        txa    ; $3B52
        asl    ; $3B53
        tax    ; $3B54
        lda $3B84,x    ; $3B55
        sta $00    ; $3B58
        lda $3B85,x    ; $3B5A
        sta $01    ; $3B5D
        pla    ; $3B5F
        jsr L3B66    ; $3B60
        jmp L3B3F    ; $3B63
L3B66   jmp ($0000)    ; $3B66
L3B69   ldx #$00    ; $3B69
L3B6B   cmp $3B76,x    ; $3B6B
        beq L3B75    ; $3B6E
        inx    ; $3B70
        cpx #$0E    ; $3B71
        bcc L3B6B    ; $3B73
L3B75   rts    ; $3B75
        dey    ; $3B76
        dfb $FF        ; $3B77  (data/65C02-bit)
        adc ($8D,x)    ; $3B78
        dfb $87        ; $3B7A  (data/65C02-bit)
        sty $9F95    ; $3B7B
        dfb $BF        ; $3B7E  (data/65C02-bit)
        sta ($99),y    ; $3B7F
        dfb $97        ; $3B81  (data/65C02-bit)
        dfb $9B        ; $3B82  (data/65C02-bit)
        ldy #$A2    ; $3B83
        dfb $3B        ; $3B85  (data/65C02-bit)
        ldx #$3B    ; $3B86
        ldx #$3B    ; $3B88
        dfb $83        ; $3B8A  (data/65C02-bit)
        bit $3C94,x    ; $3B8B
        cmp #$3F    ; $3B8E
        sei    ; $3B90
        bit $3BB1,x    ; $3B91
        dfb $B7        ; $3B94  (data/65C02-bit)
        dfb $3B        ; $3B95  (data/65C02-bit)
        dfb $BB        ; $3B96  (data/65C02-bit)
        bit $3BD1,x    ; $3B97
        dfb $07        ; $3B9A  (data/65C02-bit)
        bit $3D88,x    ; $3B9B
        sta $BC3D    ; $3B9E
        dfb $3B        ; $3BA1  (data/65C02-bit)
        lda CharIndex    ; $3BA2
        beq L3BAD    ; $3BA5
        dec CharIndex    ; $3BA7
        jmp TypeLine    ; $3BAA
L3BAD   jmp Beep    ; $3BAD
