;-*- Mode: Merlin -*-
;
; src/modules/08_minibuffer.s -- AMACS: read-line, completion read, buffer/file lists, Meta-X
; Address range $3BB0-$42AD. GENERATED by tools/disasm.py.
; `put' from src/amacs.s; symbols/labels are global across modules.
;
; ---- $3BB0-$3BB0  data  QuestionH? flag ----
        dfb $FF    ; $3BB0  .
; ---- $3BB1-$3CE8  code ----
L3BB1   ldx CharIndex    ; $3BB1
        jmp (ReadLineHelp)    ; $3BB4
        bit QuestionH?    ; $3BB7
        bmi L3BB1    ; $3BBA
L3BBC   cmp #$80    ; $3BBC
        bcc L3BAD    ; $3BBE
        ldx CharIndex    ; $3BC0
        cpx #$4F    ; $3BC3
        beq L3BAD    ; $3BC5
        sta $0200,x    ; $3BC7
        jsr CharOut    ; $3BCA
        inc CharIndex    ; $3BCD
        rts    ; $3BD0
        ldy #$01    ; $3BD1
        ldx CharIndex    ; $3BD3
L3BD6   tya    ; $3BD6
        clc    ; $3BD7
        adc GapBot    ; $3BD8
        sta $3C06    ; $3BDA
        lda $6D    ; $3BDD
        adc #$00    ; $3BDF
        cmp $69    ; $3BE1
        bcc L3BEE    ; $3BE3
        bne L3C00    ; $3BE5
        lda $3C06    ; $3BE7
        cmp BuffBot    ; $3BEA
        bcs L3C00    ; $3BEC
L3BEE   jsr $D03F    ; $3BEE
        cmp #$8D    ; $3BF1
        beq L3C00    ; $3BF3
        cpx #$4F    ; $3BF5
        bcs L3C00    ; $3BF7
        sta $0200,x    ; $3BF9
        inx    ; $3BFC
        iny    ; $3BFD
        bne L3BD6    ; $3BFE
L3C00   stx CharIndex    ; $3C00
        jmp TypeLine    ; $3C03
        brk    ; $3C06
        jsr L3C46    ; $3C07
        jsr L3C4A    ; $3C0A
        lda $61    ; $3C0D
        pha    ; $3C0F
        lda TheBuffer    ; $3C10
        pha    ; $3C12
        jsr L3C46    ; $3C13
        pla    ; $3C16
        sta $00    ; $3C17
        pla    ; $3C19
        sta $01    ; $3C1A
        ldy #$00    ; $3C1C
        ldx CharIndex    ; $3C1E
L3C21   lda $00    ; $3C21
        cmp TheBuffer    ; $3C23
        bne L3C2D    ; $3C25
        lda $01    ; $3C27
        cmp $61    ; $3C29
        beq L3C40    ; $3C2B
L3C2D   jsr $D000    ; $3C2D
        cpx #$4F    ; $3C30
        bcs L3C40    ; $3C32
        sta $0200,x    ; $3C34
        inc $00    ; $3C37
        bne L3C3D    ; $3C39
        inc $01    ; $3C3B
L3C3D   inx    ; $3C3D
        bne L3C21    ; $3C3E
L3C40   stx CharIndex    ; $3C40
        jmp TypeLine    ; $3C43
L3C46   ldx #$00    ; $3C46
        beq L3C4C    ; $3C48
L3C4A   ldx #$FF    ; $3C4A
L3C4C   lda $7A5C    ; $3C4C
        pha    ; $3C4F
        lda Argument    ; $3C50
        pha    ; $3C53
        lda ArgSign    ; $3C54
        pha    ; $3C57
        stx ArgSign    ; $3C58
        lda #$00    ; $3C5B
        sta $7A5C    ; $3C5D
        lda #$01    ; $3C60
        sta Argument    ; $3C62
        jsr IN:RightWord    ; $3C65
        jsr SetGap    ; $3C68
        pla    ; $3C6B
        sta ArgSign    ; $3C6C
        pla    ; $3C6F
        sta Argument    ; $3C70
        pla    ; $3C73
        sta $7A5C    ; $3C74
        rts    ; $3C77
L3C78   lda #$00    ; $3C78
        sta CharIndex    ; $3C7A
        jsr TypeLine    ; $3C7D
        jmp L3BAD    ; $3C80
        ldx CharIndex    ; $3C83
        sta $0200,x    ; $3C86
        pla    ; $3C89
        pla    ; $3C8A
        lda #$00    ; $3C8B
        sta BufferRead    ; $3C8D
        sta FileRead    ; $3C90
        rts    ; $3C93
        lda CharIndex    ; $3C94
        bne L3C78    ; $3C97
        lda #$87    ; $3C99
        jsr CharOut    ; $3C9B
        lda ReadLineCH    ; $3C9E
        sta CH    ; $3CA1
        lda $3F19    ; $3CA3
        sta CV    ; $3CA6
        jsr vtab    ; $3CA8
        lda #$00    ; $3CAB
        sta CharIndex    ; $3CAD
        sta BufferRead    ; $3CB0
        sta FileRead    ; $3CB3
        pla    ; $3CB6
        pla    ; $3CB7
        lda #$FF    ; $3CB8
        rts    ; $3CBA
        jsr BlinkCursor    ; $3CBB
        ldx CharIndex    ; $3CBE
        cpx #$4F    ; $3CC1
        bcs L3CCE    ; $3CC3
        sta $0200,x    ; $3CC5
        inc CharIndex    ; $3CC8
        jmp CharOut    ; $3CCB
L3CCE   jmp Beep    ; $3CCE
        brk    ; $3CD1
        tsx    ; $3CD2
        stx $3CD1    ; $3CD3
        jsr CloseEchoArea    ; $3CD6
        jsr OpenTypeout    ; $3CD9
        lda #$6C    ; $3CDC
        sta TypeoutAbort    ; $3CDE
        lda #$3D    ; $3CE1
        sta $2A98    ; $3CE3
        jsr PrintMessage    ; $3CE6
; ---- $3CE9-$3D2A  data  msg: You are typing the argument to an AMACS ----
        dfb $D9,$EF,$F5,$A0,$E1,$F2,$E5,$A0,$F4,$F9,$F0,$E9,$EE,$E7,$A0,$F4    ; $3CE9  You are typing t
        dfb $E8,$E5,$A0,$E1,$F2,$E7,$F5,$ED,$E5,$EE,$F4,$A0,$F4,$EF,$A0,$E1    ; $3CF9  he argument to a
        dfb $EE,$A0,$C1,$CD,$C1,$C3,$D3,$A0,$E3,$EF,$ED,$ED,$E1,$EE,$E4,$AE    ; $3D09  n AMACS command.
        dfb $8D,$8D,$D4,$E8,$E5,$A0,$E3,$EF,$ED,$ED,$E1,$EE,$E4,$A0,$E9,$F3    ; $3D19  ..The command is
        dfb $A0,$00    ; $3D29   .
; ---- $3D2B-$3D41  code ----
        lda CommandVector    ; $3D2B
        sta FunPtr    ; $3D2E
        lda $7835    ; $3D31
        sta $7E96    ; $3D34
        jsr GetFunName    ; $3D37
        bne L3D76    ; $3D3A
        jsr DCIStringOut    ; $3D3C
        jsr PrintMessage    ; $3D3F
; ---- $3D42-$3D45  data  msg: ; ----
        dfb $BB,$A0,$A0,$00    ; $3D42  ;  .
; ---- $3D46-$3D50  code ----
        jsr DocRef    ; $3D46
        lda WindowLft    ; $3D49
        jsr DCIStringOut1    ; $3D4B
L3D4E   jsr PrintMessage    ; $3D4E
; ---- $3D51-$3D6B  data  msg: ...Now type the argument.. ----
        dfb $AE,$8D,$8D,$CE,$EF,$F7,$A0,$F4,$F9,$F0,$E5,$A0,$F4,$E8,$E5,$A0    ; $3D51  ...Now type the 
        dfb $E1,$F2,$E7,$F5,$ED,$E5,$EE,$F4,$AE,$8D,$00    ; $3D61  argument...
; ---- $3D6C-$3D78  code ----
        ldx $3CD1    ; $3D6C
        txs    ; $3D6F
        jsr CloseTypeout1    ; $3D70
        jmp OpenEchoArea    ; $3D73
L3D76   jsr PrintMessage    ; $3D76
; ---- $3D79-$3D82  data  msg: not named ----
        dfb $EE,$EF,$F4,$A0,$EE,$E1,$ED,$E5,$E4,$00    ; $3D79  not named.
; ---- $3D83-$3F45  code ----
        jmp L3D4E    ; $3D83
;
; === BufferRead ===
        brk    ; $3D86
;
; === FileRead ===
        brk    ; $3D87
        bit BufferRead    ; $3D88
        bmi L3D95    ; $3D8B
        bit FileRead    ; $3D8D
        bmi L3DA5    ; $3D90
        jmp L3BBC    ; $3D92
L3D95   jsr MakeBuffList    ; $3D95
        lda #$00    ; $3D98
        sta CompList    ; $3D9A
        lda #$A5    ; $3D9D
        sta $5988    ; $3D9F
        jmp L3DC4    ; $3DA2
L3DA5   jsr MakeFileList    ; $3DA5
        lda #$C0    ; $3DA8
        sta CompList    ; $3DAA
        lda #$D1    ; $3DAD
        sta $5988    ; $3DAF
        ldx CharIndex    ; $3DB2
        bne L3DBE    ; $3DB5
        jsr SelfPath    ; $3DB7
        stx CharIndex    ; $3DBA
        inx    ; $3DBD
L3DBE   jsr BackPath    ; $3DBE
        stx CompOffset    ; $3DC1
L3DC4   ldx CharIndex    ; $3DC4
        lda #$9B    ; $3DC7
        sta $0200,x    ; $3DC9
        bit RdWrBank1    ; $3DCC   <== BANK: language-card RAM bank 1 (read+write, BIT twice)
        sta UseAuxZP    ; $3DCF   <== BANK: aux zero-page/stack (ALTZP on)
        jsr SI:CompleteSp    ; $3DD2
        jsr GetBank2    ; $3DD5
        sta UseMainZP    ; $3DD8   <== BANK: main zero-page/stack (ALTZP off)
        stx CharIndex    ; $3DDB
        jmp TypeLine    ; $3DDE
;
; === MakeBuffList ===
        ldx #$00    ; $3DE1
        stx $3E35    ; $3DE3
        lda #$00    ; $3DE6
        sta $00    ; $3DE8
        lda #$A5    ; $3DEA
        sta $01    ; $3DEC
L3DEE   jsr PointToBInfo    ; $3DEE
        ldy #$66    ; $3DF1
        lda (BuffPoint),y    ; $3DF3
        beq L3E2A    ; $3DF5
        ldx #$00    ; $3DF7
L3DF9   lda (BuffPoint),y    ; $3DF9
        sta ($00,x)    ; $3DFB
        beq L3E08    ; $3DFD
        inc $00    ; $3DFF
        bne L3E05    ; $3E01
        inc $01    ; $3E03
L3E05   iny    ; $3E05
        bne L3DF9    ; $3E06
L3E08   lda $00    ; $3E08
        bne L3E0E    ; $3E0A
        dec $01    ; $3E0C
L3E0E   dec $00    ; $3E0E
        lda ($00,x)    ; $3E10
        and #$7F    ; $3E12
        sta ($00,x)    ; $3E14
        lda $00    ; $3E16
        clc    ; $3E18
        adc #$05    ; $3E19
        sta $00    ; $3E1B
        bcc L3E21    ; $3E1D
        inc $01    ; $3E1F
L3E21   ldy #$02    ; $3E21
        lda #$00    ; $3E23
L3E25   sta ($00),y    ; $3E25
        dey    ; $3E27
        bpl L3E25    ; $3E28
L3E2A   inc $3E35    ; $3E2A
        ldx $3E35    ; $3E2D
        cpx #$0E    ; $3E30
        bcc L3DEE    ; $3E32
        rts    ; $3E34
        brk    ; $3E35
        brk    ; $3E36
;
; === MakeFileList ===
        ldx CharIndex    ; $3E37
        lda #$8D    ; $3E3A
        sta $0200,x    ; $3E3C
        jsr BackPath    ; $3E3F
        bit $3E36    ; $3E42
        bpl L3E73    ; $3E45
        sta UseAuxZP    ; $3E47   <== BANK: aux zero-page/stack (ALTZP on)
        stx $02    ; $3E4A
        jsr GetBank1    ; $3E4C
        lda #$80    ; $3E4F
        sta $00    ; $3E51
        lda #$D1    ; $3E53
        sta $01    ; $3E55
        ldy $02    ; $3E57
        lda ($00),y    ; $3E59
        bne L3E73    ; $3E5B
L3E5D   dey    ; $3E5D
        bmi L3E6D    ; $3E5E
        lda $0200,y    ; $3E60
        jsr UpperCon    ; $3E63
        cmp $D180,y    ; $3E66
        bne L3E73    ; $3E69
        beq L3E5D    ; $3E6B
L3E6D   sta UseMainZP    ; $3E6D   <== BANK: main zero-page/stack (ALTZP off)
        jmp GetBank2    ; $3E70
L3E73   sta UseAuxZP    ; $3E73   <== BANK: aux zero-page/stack (ALTZP on)
        jsr GetBank1    ; $3E76
        ldy $02    ; $3E79
        lda #$00    ; $3E7B
        sta ($00),y    ; $3E7D
L3E7F   dey    ; $3E7F
        bmi L3E8C    ; $3E80
        lda $0200,y    ; $3E82
        jsr UpperCon    ; $3E85
        sta ($00),y    ; $3E88
        bne L3E7F    ; $3E8A
L3E8C   sty $3E36    ; $3E8C
        sta UseMainZP    ; $3E8F   <== BANK: main zero-page/stack (ALTZP off)
        jsr GetBank2    ; $3E92
        sta UseAuxZP    ; $3E95   <== BANK: aux zero-page/stack (ALTZP on)
        lda #$C0    ; $3E98
        sta $00    ; $3E9A
        lda #$D1    ; $3E9C
        sta $01    ; $3E9E
        sta UseMainZP    ; $3EA0   <== BANK: main zero-page/stack (ALTZP off)
        jsr GetDirInfo    ; $3EA3
        bcs L3EF7    ; $3EA6
L3EA8   jsr NextFile    ; $3EA8
        bcs L3EF7    ; $3EAB
        lda FileInfo    ; $3EAD
        and #$0F    ; $3EB0
        sta $3F08    ; $3EB2
        sta UseAuxZP    ; $3EB5   <== BANK: aux zero-page/stack (ALTZP on)
        jsr GetBank1    ; $3EB8
        ldy #$00    ; $3EBB
L3EBD   lda $707F,y    ; $3EBD
        ora #$80    ; $3EC0
        jsr LowerCon    ; $3EC2
        sta ($00),y    ; $3EC5
        iny    ; $3EC7
        cpy $3F08    ; $3EC8
        bcc L3EBD    ; $3ECB
        lda FileInfo    ; $3ECD
        and #$F0    ; $3ED0
        cmp #$D0    ; $3ED2
        bcc L3EDB    ; $3ED4
        lda #$AF    ; $3ED6
        sta ($00),y    ; $3ED8
        iny    ; $3EDA
L3EDB   dey    ; $3EDB
        lda ($00),y    ; $3EDC
        and #$7F    ; $3EDE
        sta ($00),y    ; $3EE0
        tya    ; $3EE2
        clc    ; $3EE3
        adc #$05    ; $3EE4
        adc $00    ; $3EE6
        sta $00    ; $3EE8
        bcc L3EEE    ; $3EEA
        inc $01    ; $3EEC
L3EEE   sta UseMainZP    ; $3EEE   <== BANK: main zero-page/stack (ALTZP off)
        jsr GetBank2    ; $3EF1
        jmp L3EA8    ; $3EF4
L3EF7   sta UseAuxZP    ; $3EF7   <== BANK: aux zero-page/stack (ALTZP on)
        jsr GetBank1    ; $3EFA
        ldy #$00    ; $3EFD
        tya    ; $3EFF
        sta ($00),y    ; $3F00
        sta UseMainZP    ; $3F02   <== BANK: main zero-page/stack (ALTZP off)
        jmp GetBank2    ; $3F05
        brk    ; $3F08
;
; === GetBank1 ===
        bit RdWrBank1    ; $3F09   <== BANK: language-card RAM bank 1 (read+write, BIT twice)
        bit RdWrBank1    ; $3F0C   <== BANK: language-card RAM bank 1 (read+write, BIT twice)
        rts    ; $3F0F
;
; === GetBank2 ===
        bit RdWrBank2    ; $3F10   <== BANK: language-card RAM bank 2 (read+write, BIT twice)
        bit RdWrBank2    ; $3F13   <== BANK: language-card RAM bank 2 (read+write, BIT twice)
        rts    ; $3F16
;
; === MustComplete ===
        brk    ; $3F17
;
; === ReadLineCH ===
        brk    ; $3F18
        brk    ; $3F19
;
; === CommandList ===
        dfb $37        ; $3F1A  (data/65C02-bit)
        dfb $9B        ; $3F1B  (data/65C02-bit)
;
; === CompLineHelp ===
        and ($41)    ; $3F1C
        brk    ; $3F1E
;
; === MetaX ===
        lda CommandList    ; $3F1F
        sta CompList    ; $3F22
        lda $3F1B    ; $3F25
        sta $5988    ; $3F28
        jsr NewEchoArea    ; $3F2B
        jsr AnyArgument?    ; $3F2E
        bne L3F43    ; $3F31
        lda ArgSign    ; $3F33
        bpl L3F3D    ; $3F36
        lda #$AD    ; $3F38
        jsr CharOut    ; $3F3A
L3F3D   jsr PrintArgument    ; $3F3D
        jsr PrintSpace    ; $3F40
L3F43   jsr PrintMessage    ; $3F43
; ---- $3F46-$3F4A  data  msg: M-X ----
        dfb $CD,$AD,$D8,$A0,$00    ; $3F46  M-X .
; ---- $3F4B-$3F6C  code ----
        lda #$32    ; $3F4B
        sta CompLineHelp    ; $3F4D
        lda #$41    ; $3F50
        sta $3F1D    ; $3F52
        jsr ReadComplete    ; $3F55
        bne L3F6A    ; $3F58
        jsr FunctionRef    ; $3F5A
        lda $00    ; $3F5D
        sta CommandVector    ; $3F5F
        lda $01    ; $3F62
        sta $7835    ; $3F64
        jmp CallTemp    ; $3F67
L3F6A   lda #$01    ; $3F6A
        rts    ; $3F6C
; ---- $3F6D-$3F6F  data  CharIndex (3 bytes) ----
        dfb $00,$00,$00    ; $3F6D  ...
; ---- $3F70-$3F7F  code ----
;
; === ReadVariable ===
        lda #$5D    ; $3F70
        sta CompList    ; $3F72
        lda #$97    ; $3F75
        sta $5988    ; $3F77
        jsr NewEchoArea    ; $3F7A
        jsr PrintMessage    ; $3F7D
; ---- $3F80-$3F89  data  msg: Variable: ----
        dfb $D6,$E1,$F2,$E9,$E1,$E2,$EC,$E5,$BA,$00    ; $3F80  Variable:.
; ---- $3F8A-$3F9E  code ----
        jmp ReadComplete    ; $3F8A
;
; === ReadFunction ===
        lda CommandList    ; $3F8D
        sta CompList    ; $3F90
        lda $3F1B    ; $3F93
        sta $5988    ; $3F96
        jsr NewEchoArea    ; $3F99
        jsr PrintMessage    ; $3F9C
; ---- $3F9F-$3FA8  data  msg: Function: ----
        dfb $C6,$F5,$EE,$E3,$F4,$E9,$EF,$EE,$BA,$00    ; $3F9F  Function:.
; ---- $3FA9-$4153  code ----
;
; === ReadComplete ===
        lda #$FF    ; $3FA9
        sta MustComplete    ; $3FAB
;
; === ReadCompLine ===
        lda CH    ; $3FAE
        sta ReadLineCH    ; $3FB0
        lda CV    ; $3FB3
        sta $3F19    ; $3FB5
        lda #$00    ; $3FB8
        sta CharIndex    ; $3FBA
        sta $3F6E    ; $3FBD
L3FC0   jsr BlinkCursor    ; $3FC0
        jsr L3FE9    ; $3FC3
        jmp L3FC0    ; $3FC6
;
; === TypeLine ===
        lda ReadLineCH    ; $3FC9
        sta CH    ; $3FCC
        lda $3F19    ; $3FCE
        sta CV    ; $3FD1
        jsr vtab    ; $3FD3
        ldx #$00    ; $3FD6
L3FD8   lda $0200,x    ; $3FD8
        cpx CharIndex    ; $3FDB
        bcs L3FE6    ; $3FDE
        jsr CharOut    ; $3FE0
        inx    ; $3FE3
        bne L3FD8    ; $3FE4
L3FE6   jmp ClearEOP    ; $3FE6
L3FE9   ldx #$00    ; $3FE9
L3FEB   cmp $4007,x    ; $3FEB
        beq L3FF5    ; $3FEE
        inx    ; $3FF0
        cpx #$0C    ; $3FF1
        bcc L3FEB    ; $3FF3
L3FF5   pha    ; $3FF5
        txa    ; $3FF6
        asl    ; $3FF7
        tax    ; $3FF8
        lda $4013,x    ; $3FF9
        sta $00    ; $3FFC
        lda $4014,x    ; $3FFE
        sta $01    ; $4001
        pla    ; $4003
        jmp CallTemp    ; $4004
        dfb $9B        ; $4007  (data/65C02-bit)
        ldy #$BF    ; $4008
        dfb $9F        ; $400A  (data/65C02-bit)
        dey    ; $400B
        dfb $FF        ; $400C  (data/65C02-bit)
        adc ($87,x)    ; $400D
        sta $8C,x    ; $400F
        sta ($8D),y    ; $4011
        lda $E640,y    ; $4013
        rti    ; $4016
        bit $41    ; $4017
        bit $41    ; $4019
        dfb $8F        ; $401B  (data/65C02-bit)
        rti    ; $401C
        dfb $8F        ; $401D  (data/65C02-bit)
        rti    ; $401E
        dfb $8F        ; $401F  (data/65C02-bit)
        rti    ; $4020
        ror    ; $4021
        rti    ; $4022
        dfb $4B        ; $4023  (data/65C02-bit)
        rti    ; $4024
        cmp #$3F    ; $4025
        eor $40    ; $4027
        pla    ; $4029
        dfb $42        ; $402A  (data/65C02-bit)
        and $C940    ; $402B
        bra L3FC0    ; $402E
        ora ($AE),y    ; $4030
        adc $E03F    ; $4032
        dfb $FF        ; $4035  (data/65C02-bit)
        beq L4042    ; $4036
        sta $0200,x    ; $4038
        inc CharIndex    ; $403B
        jsr CharOut    ; $403E
        rts    ; $4041
L4042   jmp Beep    ; $4042
        jsr BlinkCursor    ; $4045
        jmp $402D    ; $4048
        jsr Beep    ; $404B
        ldx CharIndex    ; $404E
        beq L4067    ; $4051
        dex    ; $4053
L4054   dex    ; $4054
        bmi L405E    ; $4055
        lda $0200,x    ; $4057
        cmp #$9B    ; $405A
        bne L4054    ; $405C
L405E   inx    ; $405E
        stx CharIndex    ; $405F
        bne L4067    ; $4062
        stx $3F6E    ; $4064
L4067   jmp TypeLine    ; $4067
        jsr Beep    ; $406A
        lda #$87    ; $406D
        jsr CharOut    ; $406F
        lda #$FF    ; $4072
L4074   sta $3F6F    ; $4074
        pla    ; $4077
        pla    ; $4078
        lda $01    ; $4079
        pha    ; $407B
        lda $00    ; $407C
        pha    ; $407E
        jsr CloseEchoArea    ; $407F
        pla    ; $4082
        sta $00    ; $4083
        pla    ; $4085
        sta $01    ; $4086
        ldx CharIndex    ; $4088
        lda $3F6F    ; $408B
        rts    ; $408E
        ldx CharIndex    ; $408F
        beq L40B1    ; $4092
        dec CharIndex    ; $4094
        ldx #$00    ; $4097
L4099   lda $0200,x    ; $4099
        cpx CharIndex    ; $409C
        bcs L40A8    ; $409F
        cmp #$9B    ; $40A1
        beq L40AD    ; $40A3
        inx    ; $40A5
        bne L4099    ; $40A6
L40A8   lda #$00    ; $40A8
        sta $3F6E    ; $40AA
L40AD   jsr TypeLine    ; $40AD
        rts    ; $40B0
L40B1   jsr ClearPage    ; $40B1
        lda #$FF    ; $40B4
        jmp L4074    ; $40B6
L40B9   bit $3F6E    ; $40B9
        bpl L40C1    ; $40BC
        jmp $402D    ; $40BE
L40C1   jsr L425F    ; $40C1
        jsr SI:CompleteMe    ; $40C4
        bne L40EE    ; $40C7
        lda #$FF    ; $40C9
        sta $3F6E    ; $40CB
        lda $00    ; $40CE
        sta $40E4    ; $40D0
        lda $01    ; $40D3
        sta $40E5    ; $40D5
        stx CharIndex    ; $40D8
        jsr L425F    ; $40DB
        inc CharIndex    ; $40DE
        jmp TypeLine    ; $40E1
        brk    ; $40E4
        brk    ; $40E5
        bit $3F6E    ; $40E6
        bpl L40EE    ; $40E9
        jmp $402D    ; $40EB
L40EE   jsr L425F    ; $40EE
        jsr SI:CompleteSp    ; $40F1
        beq L410D    ; $40F4
        ldx CharIndex    ; $40F6
        lda #$A0    ; $40F9
        sta $0200,x    ; $40FB
        lda #$9B    ; $40FE
        sta $0201,x    ; $4100
        jsr SI:CompleteSp    ; $4103
        beq L410D    ; $4106
        cpx CharIndex    ; $4108
        beq L411E    ; $410B
L410D   stx CharIndex    ; $410D
        jsr TypeLine    ; $4110
        lda CompCount    ; $4113
        cmp #$01    ; $4116
        bne L411D    ; $4118
        jmp L40B9    ; $411A
L411D   rts    ; $411D
L411E   jsr Beep    ; $411E
        jmp TypeLine    ; $4121
        jmp (CompLineHelp)    ; $4124
        ldx $3F1E    ; $4127
        txs    ; $412A
        jsr CloseTypeout1    ; $412B
        jsr OpenEchoArea    ; $412E
        rts    ; $4131
        tsx    ; $4132
        stx $3F1E    ; $4133
        jsr CloseEchoArea    ; $4136
        jsr OpenTypeout    ; $4139
        lda #$27    ; $413C
        sta TypeoutAbort    ; $413E
        lda #$41    ; $4141
        sta $2A98    ; $4143
        jsr L425F    ; $4146
        jsr SI:CompleteMe    ; $4149
        lda CompCount    ; $414C
        bne L417F    ; $414F
        jsr PrintMessage    ; $4151
; ---- $4154-$4177  data  msg: There are no possible completions.. ----
        dfb $D4,$E8,$E5,$F2,$E5,$A0,$E1,$F2,$E5,$A0,$EE,$EF,$A0,$F0,$EF,$F3    ; $4154  There are no pos
        dfb $F3,$E9,$E2,$EC,$E5,$A0,$E3,$EF,$ED,$F0,$EC,$E5,$F4,$E9,$EF,$EE    ; $4164  sible completion
        dfb $F3,$AE,$8D,$00    ; $4174  s...
; ---- $4178-$4188  code ----
L4178   jsr CloseTypeout1    ; $4178
        jsr OpenEchoArea    ; $417B
        rts    ; $417E
L417F   cmp #$01    ; $417F
        beq L4186    ; $4181
        jmp L41EA    ; $4183
L4186   jsr PrintMessage    ; $4186
; ---- $4189-$41C3  data  msg: .The only possible completion of what yo ----
        dfb $8D,$D4,$E8,$E5,$A0,$EF,$EE,$EC,$F9,$A0,$F0,$EF,$F3,$F3,$E9,$E2    ; $4189  .The only possib
        dfb $EC,$E5,$A0,$E3,$EF,$ED,$F0,$EC,$E5,$F4,$E9,$EF,$EE,$A0,$EF,$E6    ; $4199  le completion of
        dfb $A0,$F7,$E8,$E1,$F4,$A0,$F9,$EF,$F5,$A0,$E8,$E1,$F6,$E5,$A0,$F4    ; $41A9   what you have t
        dfb $F9,$F0,$E5,$E4,$A0,$E9,$F3,$BA,$8D,$8D,$00    ; $41B9  yped is:...
; ---- $41C4-$41EC  code ----
        jsr PopCompPoint    ; $41C4
        lda PrintCompDoc    ; $41C7
        pha    ; $41CA
        lda CompCount    ; $41CB
        pha    ; $41CE
        jsr DCIStringOut    ; $41CF
        lda #$1E    ; $41D2
        sta CH    ; $41D4
        sta TypeoutCH    ; $41D6
        pla    ; $41D9
        sta CompCount    ; $41DA
        pla    ; $41DD
        sta PrintCompDoc    ; $41DE
        jsr PrintCompDoc    ; $41E1
        jsr PrintReturn    ; $41E4
        jmp L4178    ; $41E7
L41EA   jsr PrintMessage    ; $41EA
; ---- $41ED-$4223  data  msg: The possible completions of what you hav ----
        dfb $D4,$E8,$E5,$A0,$F0,$EF,$F3,$F3,$E9,$E2,$EC,$E5,$A0,$E3,$EF,$ED    ; $41ED  The possible com
        dfb $F0,$EC,$E5,$F4,$E9,$EF,$EE,$F3,$A0,$EF,$E6,$A0,$F7,$E8,$E1,$F4    ; $41FD  pletions of what
        dfb $A0,$F9,$EF,$F5,$A0,$E8,$E1,$F6,$E5,$A0,$F4,$F9,$F0,$E5,$E4,$A0    ; $420D   you have typed 
        dfb $E1,$F2,$E5,$BA,$8D,$8D,$00    ; $421D  are:...
; ---- $4224-$42AD  code ----
        lda #$00    ; $4224
        sta $425E    ; $4226
L4229   jsr PopCompPoint    ; $4229
        bne L424C    ; $422C
        jsr DCIStringOut    ; $422E
        lda $425E    ; $4231
        eor #$FF    ; $4234
        sta $425E    ; $4236
        bne L4241    ; $4239
        jsr PrintReturn    ; $423B
        jmp L4229    ; $423E
L4241   lda WindowRgt    ; $4241
        lsr    ; $4243
        sta CH    ; $4244
        sta TypeoutCH    ; $4246
        jmp L4229    ; $4249
L424C   lda $425E    ; $424C
        beq L4254    ; $424F
        jsr PrintReturn    ; $4251
L4254   jsr PrintDone    ; $4254
        jsr CloseTypeout1    ; $4257
        jsr OpenEchoArea    ; $425A
        rts    ; $425D
        brk    ; $425E
L425F   ldx CharIndex    ; $425F
        lda #$9B    ; $4262
        sta $0200,x    ; $4264
        rts    ; $4267
        jsr L425F    ; $4268
        lda $3F6E    ; $426B
        bmi L4281    ; $426E
        jsr SI:CompleteMe    ; $4270
        bne L42A1    ; $4273
        stx CharIndex    ; $4275
        jsr L425F    ; $4278
        jsr PopCompPoint    ; $427B
        jmp L428B    ; $427E
L4281   lda $40E4    ; $4281
        sta $00    ; $4284
        lda $40E5    ; $4286
        sta $01    ; $4289
L428B   lda $01    ; $428B
        pha    ; $428D
        lda $00    ; $428E
        pha    ; $4290
        lda #$FF    ; $4291
        jsr GiveArgs    ; $4293
        pla    ; $4296
        sta $00    ; $4297
        pla    ; $4299
        sta $01    ; $429A
        lda #$00    ; $429C
L429E   jmp L4074    ; $429E
L42A1   lda MustComplete    ; $42A1
        bmi L42AA    ; $42A4
        lda #$FF    ; $42A6
        bne L429E    ; $42A8
L42AA   jsr Beep    ; $42AA
        rts    ; $42AD
