;-*- Mode: Merlin -*-
;
; src/modules/09_buffer.s -- AMACS: buffer management, gap buffer, marks, kill ring
; Address range $42AE-$4F83. GENERATED by tools/disasm.py.
; `put' from src/amacs.s; symbols/labels are global across modules.
;
; ---- $42AE-$488B  code ----
;
; === PushArg ===
        stx CharIndex    ; $42AE
        jsr L425F    ; $42B1
        ldx #$FF    ; $42B4
        ldy #$00    ; $42B6
;
; === GiveArgs ===
        php    ; $42B8
        jsr InitStrArgs    ; $42B9
        plp    ; $42BC
        beq L42D1    ; $42BD
        ldx #$00    ; $42BF
L42C1   lda $0200,x    ; $42C1
        cpx CharIndex    ; $42C4
        bcs L42D0    ; $42C7
        cmp #$9B    ; $42C9
        beq L42D1    ; $42CB
        inx    ; $42CD
        bne L42C1    ; $42CE
L42D0   rts    ; $42D0
L42D1   ldy #$00    ; $42D1
        inx    ; $42D3
L42D4   cpx CharIndex    ; $42D4
        beq L42EF    ; $42D7
        inc ArgCount    ; $42D9
L42DC   lda $0200,x    ; $42DC
        sta StringArgs,y    ; $42DF
        iny    ; $42E2
        bmi L42F5    ; $42E3
        inx    ; $42E5
        cmp #$9B    ; $42E6
        beq L42D4    ; $42E8
        cpx CharIndex    ; $42EA
        bcc L42DC    ; $42ED
L42EF   lda #$9B    ; $42EF
        sta StringArgs,y    ; $42F1
        rts    ; $42F4
L42F5   dey    ; $42F5
        bne L42EF    ; $42F6
;
; === BotOfRam ===
        ora ($08,x)    ; $42F8
;
; === TopOfRam ===
        dfb $FF        ; $42FA  (data/65C02-bit)
        dfb $BF        ; $42FB  (data/65C02-bit)
;
; === PointToBInfo ===
        lda #$01    ; $42FC
        sta BuffPoint    ; $42FE
        lda #$08    ; $4300
        sta $5F    ; $4302
        txa    ; $4304
        beq L4315    ; $4305
L4307   lda BuffPoint    ; $4307
        clc    ; $4309
        adc #$84    ; $430A
        sta BuffPoint    ; $430C
        bcc L4312    ; $430E
        inc $5F    ; $4310
L4312   dex    ; $4312
        bne L4307    ; $4313
L4315   rts    ; $4315
;
; === InitBuffers ===
        ldx #$00    ; $4316
        stx $00    ; $4318
        stx LastBuffer    ; $431A
        stx SelectedBuff    ; $431D
L4320   lda #$00    ; $4320
        sta BuffActList,x    ; $4322
        jsr PointToBInfo    ; $4325
        ldy #$00    ; $4328
        tya    ; $432A
L432B   sta (BuffPoint),y    ; $432B
        iny    ; $432D
        cpy #$84    ; $432E
        bcc L432B    ; $4330
        ldy #$12    ; $4332
        lda #$14    ; $4334
        clc    ; $4336
        adc BuffPoint    ; $4337
        sta (BuffPoint),y    ; $4339
        iny    ; $433B
        lda $5F    ; $433C
        adc #$00    ; $433E
        sta (BuffPoint),y    ; $4340
        inc $00    ; $4342
        ldx $00    ; $4344
        cpx #$0E    ; $4346
        bcc L4320    ; $4348
        rts    ; $434A
        brk    ; $434B
        brk    ; $434C
L434D   jsr PointToBInfo    ; $434D
        ldy #$0E    ; $4350
        jsr L4357    ; $4352
        ldy #$10    ; $4355
L4357   lda (BuffPoint),y    ; $4357
        sec    ; $4359
        sbc $434B    ; $435A
        sta (BuffPoint),y    ; $435D
        iny    ; $435F
        lda (BuffPoint),y    ; $4360
        sbc $434C    ; $4362
        sta (BuffPoint),y    ; $4365
        rts    ; $4367
L4368   jsr PointToBInfo    ; $4368
        ldy #$0E    ; $436B
        jsr L4372    ; $436D
        ldy #$10    ; $4370
L4372   lda (BuffPoint),y    ; $4372
        clc    ; $4374
        adc $434B    ; $4375
        sta (BuffPoint),y    ; $4378
        iny    ; $437A
        lda (BuffPoint),y    ; $437B
        adc $434C    ; $437D
        sta (BuffPoint),y    ; $4380
        rts    ; $4382
;
; === LogBuffer ===
        jsr PointToBInfo    ; $4383
L4386   ldy #$06    ; $4386
        lda #$00    ; $4388
        sta (BuffPoint),y    ; $438A
        iny    ; $438C
        sta (BuffPoint),y    ; $438D
        ldy #$00    ; $438F
        jsr L439B    ; $4391
        ldy #$0A    ; $4394
        jsr L439B    ; $4396
        ldy #$02    ; $4399
L439B   sty TheBuffer    ; $439B
        lda (BuffPoint),y    ; $439D
        sec    ; $439F
        ldy #$0E    ; $43A0
        sbc (BuffPoint),y    ; $43A2
        ldy TheBuffer    ; $43A4
        sta (BuffPoint),y    ; $43A6
        iny    ; $43A8
        sty TheBuffer    ; $43A9
        lda (BuffPoint),y    ; $43AB
        ldy #$0F    ; $43AD
        sbc (BuffPoint),y    ; $43AF
        ldy TheBuffer    ; $43B1
        sta (BuffPoint),y    ; $43B3
        rts    ; $43B5
;
; === PhysBuffer ===
        jsr PointToBInfo    ; $43B6
        ldy #$0E    ; $43B9
        lda (BuffPoint),y    ; $43BB
        pha    ; $43BD
        iny    ; $43BE
        lda (BuffPoint),y    ; $43BF
        ldy #$07    ; $43C1
        sta (BuffPoint),y    ; $43C3
        dey    ; $43C5
        pla    ; $43C6
        sta (BuffPoint),y    ; $43C7
        ldy #$00    ; $43C9
        jsr L43D5    ; $43CB
        ldy #$0A    ; $43CE
        jsr L43D5    ; $43D0
        ldy #$02    ; $43D3
L43D5   sty TheBuffer    ; $43D5
        lda (BuffPoint),y    ; $43D7
        clc    ; $43D9
        ldy #$0E    ; $43DA
        adc (BuffPoint),y    ; $43DC
        ldy TheBuffer    ; $43DE
        sta (BuffPoint),y    ; $43E0
        iny    ; $43E2
        sty TheBuffer    ; $43E3
        lda (BuffPoint),y    ; $43E5
        ldy #$0F    ; $43E7
        adc (BuffPoint),y    ; $43E9
        ldy TheBuffer    ; $43EB
        sta (BuffPoint),y    ; $43ED
        rts    ; $43EF
;
; === Deselect ===
        jsr KillGap    ; $43F0
        ldx SelectedBuff    ; $43F3
        stx LastBuffer    ; $43F6
        jsr PointToBInfo    ; $43F9
        lda MarkStackPntr    ; $43FC
        sta MarkPnt    ; $43FF
        ldy #$00    ; $4401
L4403   lda: TheBuffer,y    ; $4403
        sta (BuffPoint),y    ; $4406
        iny    ; $4408
        cpy #$12    ; $4409
        bcc L4403    ; $440B
        ldy #$10    ; $440D
        lda GapTop    ; $440F
        sta (BuffPoint),y    ; $4411
        iny    ; $4413
        lda $6B    ; $4414
        sta (BuffPoint),y    ; $4416
        ldy #$56    ; $4418
        ldx #$00    ; $441A
L441C   lda MarkStack,x    ; $441C
        sta (BuffPoint),y    ; $441F
        iny    ; $4421
        inx    ; $4422
        cpx #$10    ; $4423
        bcc L441C    ; $4425
        jsr L4386    ; $4427
        rts    ; $442A
        brk    ; $442B
L442C   cpx SelectedBuff    ; $442C
        bne ForceSelect    ; $442F
        rts    ; $4431
;
; === ForceSelect ===
        clv    ; $4432
        stx $442B    ; $4433
        jmp L4442    ; $4436
L4439   ldx SelectedBuff    ; $4439
        stx $442B    ; $443C
        bit $4431    ; $443F
L4442   bvs L44A9    ; $4442
        bcs L4449    ; $4444
        jmp L452B    ; $4446
L4449   ldx SelectedBuff    ; $4449
        jsr PointToBInfo    ; $444C
        ldy #$10    ; $444F
        lda (BuffPoint),y    ; $4451
        sta $475E    ; $4453
        iny    ; $4456
        lda (BuffPoint),y    ; $4457
        sta $475F    ; $4459
        ldx SelectedBuff    ; $445C
        inx    ; $445F
        jsr PointToBInfo    ; $4460
        ldy #$0E    ; $4463
        lda (BuffPoint),y    ; $4465
        sta $475A    ; $4467
        iny    ; $446A
        lda (BuffPoint),y    ; $446B
        sta $475B    ; $446D
        ldx $442B    ; $4470
        jsr PointToBInfo    ; $4473
        ldy #$10    ; $4476
        lda (BuffPoint),y    ; $4478
        sta $475C    ; $447A
        iny    ; $447D
        lda (BuffPoint),y    ; $447E
        sta $475D    ; $4480
        lda $475A    ; $4483
        sec    ; $4486
        sbc $475E    ; $4487
        sta $434B    ; $448A
        lda $475B    ; $448D
        sbc $475F    ; $4490
        sta $434C    ; $4493
        jsr L4760    ; $4496
        ldx SelectedBuff    ; $4499
L449C   inx    ; $449C
        txa    ; $449D
        pha    ; $449E
        jsr L434D    ; $449F
        pla    ; $44A2
        tax    ; $44A3
        cpx $442B    ; $44A4
        bcc L449C    ; $44A7
L44A9   ldx $442B    ; $44A9
        stx SelectedBuff    ; $44AC
        jsr PhysBuffer    ; $44AF
        ldx SelectedBuff    ; $44B2
        inx    ; $44B5
        lda TopOfRam    ; $44B6
        sta $00    ; $44B9
        lda $42FB    ; $44BB
        sta $01    ; $44BE
        cpx #$0E    ; $44C0
        bcs L44D7    ; $44C2
        lda BuffActList,x    ; $44C4
        beq L44D7    ; $44C7
        jsr PointToBInfo    ; $44C9
        ldy #$0E    ; $44CC
        lda (BuffPoint),y    ; $44CE
        sta $00    ; $44D0
        iny    ; $44D2
        lda (BuffPoint),y    ; $44D3
        sta $01    ; $44D5
L44D7   ldx SelectedBuff    ; $44D7
        jsr PointToBInfo    ; $44DA
        ldy #$00    ; $44DD
L44DF   lda (BuffPoint),y    ; $44DF
        sta: TheBuffer,y    ; $44E1
        iny    ; $44E4
        cpy #$14    ; $44E5
        bcc L44DF    ; $44E7
        ldy #$56    ; $44E9
        ldx #$00    ; $44EB
L44ED   lda (BuffPoint),y    ; $44ED
        sta MarkStack,x    ; $44EF
        iny    ; $44F2
        inx    ; $44F3
        cpx #$10    ; $44F4
        bcc L44ED    ; $44F6
        lda MarkPnt    ; $44F8
        sta MarkStackPntr    ; $44FA
        ldx #$FF    ; $44FD
        lda #$02    ; $44FF
        jsr BuffFlagOff?    ; $4501
        beq L4507    ; $4504
        txa    ; $4506
L4507   sta Modified?    ; $4507
        lda $00    ; $450A
        bne L4510    ; $450C
        dec $01    ; $450E
L4510   dec $00    ; $4510
        lda $00    ; $4512
        sta BuffBot    ; $4514
        sta PhysBuffBot    ; $4516
        sta GapBot    ; $4518
        lda $01    ; $451A
        sta $69    ; $451C
        sta $71    ; $451E
        sta $6D    ; $4520
        lda GapBot    ; $4522
        bne L4528    ; $4524
        dec $6D    ; $4526
L4528   dec GapBot    ; $4528
        rts    ; $452A
L452B   ldx SelectedBuff    ; $452B
        inx    ; $452E
        lda TopOfRam    ; $452F
        sta $00    ; $4532
        lda $42FB    ; $4534
        sta $01    ; $4537
        cpx #$0E    ; $4539
        bcs L4558    ; $453B
        lda BuffActList,x    ; $453D
        beq L4558    ; $4540
        jsr PointToBInfo    ; $4542
        ldy #$0E    ; $4545
        lda (BuffPoint),y    ; $4547
        sta $00    ; $4549
        iny    ; $454B
        lda (BuffPoint),y    ; $454C
        sta $01    ; $454E
        lda $00    ; $4550
        bne L4556    ; $4552
        dec $01    ; $4554
L4556   dec $00    ; $4556
L4558   lda $00    ; $4558
        sta $475E    ; $455A
        lda $01    ; $455D
        sta $475F    ; $455F
        ldx SelectedBuff    ; $4562
        jsr PointToBInfo    ; $4565
        ldy #$10    ; $4568
        lda (BuffPoint),y    ; $456A
        sta $475A    ; $456C
        iny    ; $456F
        lda (BuffPoint),y    ; $4570
        sta $475B    ; $4572
        ldx $442B    ; $4575
        jsr PointToBInfo    ; $4578
        ldy #$10    ; $457B
        lda (BuffPoint),y    ; $457D
        sta $475C    ; $457F
        iny    ; $4582
        lda (BuffPoint),y    ; $4583
        sta $475D    ; $4585
        lda $475E    ; $4588
        sec    ; $458B
        sbc $475A    ; $458C
        sta $434B    ; $458F
        lda $475F    ; $4592
        sbc $475B    ; $4595
        sta $434C    ; $4598
        jsr L4796    ; $459B
        ldx SelectedBuff    ; $459E
L45A1   txa    ; $45A1
        pha    ; $45A2
        jsr L4368    ; $45A3
        pla    ; $45A6
        tax    ; $45A7
        dex    ; $45A8
        cpx $442B    ; $45A9
        bne L45A1    ; $45AC
        jmp L44A9    ; $45AE
;
; === SelectBuffer ===
        lda #$00    ; $45B1
        beq L45B7    ; $45B3
;
; === SelectNamed ===
        lda #$FF    ; $45B5
L45B7   bmi L45E0    ; $45B7
        jsr GetStrArg    ; $45B9
        beq L45D2    ; $45BC
        jsr DefBuffer    ; $45BE
        jsr L4B2A    ; $45C1
        dfb $D3        ; $45C4  (data/65C02-bit)
        sbc $EC    ; $45C5
        sbc $E3    ; $45C7
        stz $F0,x    ; $45C9
        asl WindowLft    ; $45CB
        lda $A929,y    ; $45CD
        ora (TheBuffer,x)    ; $45D0
L45D2   lda #$00    ; $45D2
        sta $0200,x    ; $45D4
        txa    ; $45D7
        bne L45E0    ; $45D8
        ldx LastBuffer    ; $45DA
        jmp SI:OpenBuff    ; $45DD
L45E0   jsr FindBuffer    ; $45E0
        beq SI:OpenBuff    ; $45E3
        jsr Deselect    ; $45E5
        jmp CreateBuffer    ; $45E8
;
; === SI:OpenBuff ===
        jsr IN:OpenBuff    ; $45EB
        jsr DisplayPage    ; $45EE
        lda #$01    ; $45F1
        rts    ; $45F3
;
; === IN:OpenBuff ===
        jsr SI:SelectB    ; $45F4
        jsr SetGap    ; $45F7
        ldy #$40    ; $45FA
        lda (BuffData),y    ; $45FC
        pha    ; $45FE
        ldy #$3F    ; $45FF
        lda (BuffData),y    ; $4601
        jsr SelectMode    ; $4603
        ldy #$40    ; $4606
        pla    ; $4608
        sta (BuffData),y    ; $4609
        jsr MakeModeLine    ; $460B
        rts    ; $460E
;
; === SI:SelectB ===
        txa    ; $460F
        pha    ; $4610
        jsr ClrLastKill    ; $4611
        pla    ; $4614
        cmp SelectedBuff    ; $4615
        beq L4623    ; $4618
        pha    ; $461A
        jsr Deselect    ; $461B
        pla    ; $461E
        tax    ; $461F
        jsr L442C    ; $4620
L4623   rts    ; $4623
;
; === CreateBuffer ===
        lda SelectedBuff    ; $4624
        sta $472C    ; $4627
        ldy #$3F    ; $462A
        lda (BuffData),y    ; $462C
        sta $472B    ; $462E
        ldx #$00    ; $4631
        stx $472D    ; $4633
L4636   lda BuffActList,x    ; $4636
        ora $472D    ; $4639
        sta $472D    ; $463C
        inx    ; $463F
        cpx #$0E    ; $4640
        bcc L4636    ; $4642
        lda $472D    ; $4644
        bmi L4651    ; $4647
        lda #$00    ; $4649
L464B   sta LastBuffer,x    ; $464B
        dex    ; $464E
        bne L464B    ; $464F
L4651   ldx #$00    ; $4651
L4653   lda BuffActList,x    ; $4653
        bpl L4666    ; $4656
        inx    ; $4658
        cpx #$0E    ; $4659
        bcc L4653    ; $465B
        jsr Beep    ; $465D
        jsr L4439    ; $4660
        lda #$01    ; $4663
        rts    ; $4665
L4666   lda #$FF    ; $4666
        sta BuffActList,x    ; $4668
        stx $472E    ; $466B
        txa    ; $466E
        bne L467E    ; $466F
        lda DefMajor    ; $4671
        sta $472B    ; $4674
        bit $472D    ; $4677
        bpl L468A    ; $467A
        bmi L4684    ; $467C
L467E   dex    ; $467E
        cpx SelectedBuff    ; $467F
        beq L468A    ; $4682
L4684   jsr L442C    ; $4684
        jsr Deselect    ; $4687
L468A   ldx $472E    ; $468A
        bne L4699    ; $468D
        lda BotOfRam    ; $468F
        sta GapTop    ; $4692
        lda $42F9    ; $4694
        sta $6B    ; $4697
L4699   lda GapTop    ; $4699
        sta BuffTop    ; $469B
        sta TheBuffer    ; $469D
        sta PageTop    ; $469F
        sta PhysBuffTop    ; $46A1
        lda $6B    ; $46A3
        sta $67    ; $46A5
        sta $61    ; $46A7
        sta $63    ; $46A9
        sta $6F    ; $46AB
        lda TopOfRam    ; $46AD
        sta $00    ; $46B0
        lda $42FB    ; $46B2
        sta $01    ; $46B5
        ldx $472E    ; $46B7
        inx    ; $46BA
        cpx #$0E    ; $46BB
        beq L46D2    ; $46BD
        lda BuffActList,x    ; $46BF
        beq L46D2    ; $46C2
        jsr PointToBInfo    ; $46C4
        ldy #$0E    ; $46C7
        lda (BuffPoint),y    ; $46C9
        sta $00    ; $46CB
        iny    ; $46CD
        lda (BuffPoint),y    ; $46CE
        sta $01    ; $46D0
L46D2   lda $01    ; $46D2
        sta $71    ; $46D4
        sta $6D    ; $46D6
        sta $69    ; $46D8
        lda $00    ; $46DA
        sta PhysBuffBot    ; $46DC
        sta GapBot    ; $46DE
        sta BuffBot    ; $46E0
        lda GapBot    ; $46E2
        bne L46E8    ; $46E4
        dec $6D    ; $46E6
L46E8   dec GapBot    ; $46E8
        lda $472C    ; $46EA
        sta LastBuffer    ; $46ED
        ldx $472E    ; $46F0
        stx SelectedBuff    ; $46F3
        jsr PointToBInfo    ; $46F6
        ldy #$00    ; $46F9
L46FB   lda: TheBuffer,y    ; $46FB
        sta (BuffPoint),y    ; $46FE
        iny    ; $4700
        cpy #$12    ; $4701
        bcc L46FB    ; $4703
        lda (BuffPoint),y    ; $4705
        sta BuffData    ; $4707
        iny    ; $4709
        lda (BuffPoint),y    ; $470A
        sta $73    ; $470C
        lda #$00    ; $470E
        ldy #$40    ; $4710
        sta (BuffData),y    ; $4712
        ldy #$41    ; $4714
        sta (BuffData),y    ; $4716
        ldy #$00    ; $4718
        sta (BuffData),y    ; $471A
        sta Modified?    ; $471C
        lda $472B    ; $471F
        jsr SelectMode    ; $4722
        jsr L472F    ; $4725
        lda #$06    ; $4728
        rts    ; $472A
        ds 4        ; $472B  4 bytes $00 fill
L472F   ldy #$52    ; $472F
        ldx #$00    ; $4731
L4733   lda $0200,x    ; $4733
        beq L4742    ; $4736
        cpx #$1D    ; $4738
        bcs L4742    ; $473A
        sta (BuffData),y    ; $473C
        inx    ; $473E
        iny    ; $473F
        bne L4733    ; $4740
L4742   lda #$00    ; $4742
        sta (BuffData),y    ; $4744
        jsr MakeModeLine    ; $4746
        rts    ; $4749
;
; === RenameBuffer ===
        jsr GetStrArg    ; $474A
        bne L4757    ; $474D
        lda #$00    ; $474F
        sta $0200,x    ; $4751
        jsr L472F    ; $4754
L4757   lda #$01    ; $4757
        rts    ; $4759
        ds 6        ; $475A  6 bytes $00 fill
L4760   lda $475E    ; $4760
        sta $00    ; $4763
        lda $475F    ; $4765
        sta $01    ; $4768
        lda $475A    ; $476A
        sta $02    ; $476D
        lda $475B    ; $476F
        sta $03    ; $4772
        ldy #$00    ; $4774
        lda $02    ; $4776
        cmp $00    ; $4778
        bne L4782    ; $477A
        lda $03    ; $477C
        cmp $01    ; $477E
        beq L4787    ; $4780
L4782   jsr L47D1    ; $4782
        bne L4788    ; $4785
L4787   rts    ; $4787
L4788   inc $02    ; $4788
        bne L478E    ; $478A
        inc $03    ; $478C
L478E   inc $00    ; $478E
        bne L4794    ; $4790
        inc $01    ; $4792
L4794   bne L4782    ; $4794
L4796   lda $475E    ; $4796
        sta $00    ; $4799
        lda $475F    ; $479B
        sta $01    ; $479E
        lda $475A    ; $47A0
        sta $02    ; $47A3
        lda $475B    ; $47A5
        sta $03    ; $47A8
        ldy #$00    ; $47AA
        lda $02    ; $47AC
        cmp $00    ; $47AE
        bne L47B8    ; $47B0
        lda $03    ; $47B2
        cmp $01    ; $47B4
        beq L47BD    ; $47B6
L47B8   jsr L47D1    ; $47B8
        bne L47BE    ; $47BB
L47BD   rts    ; $47BD
L47BE   lda $02    ; $47BE
        bne L47C4    ; $47C0
        dec $03    ; $47C2
L47C4   dec $02    ; $47C4
        lda $00    ; $47C6
        bne L47CC    ; $47C8
        dec $01    ; $47CA
L47CC   dec $00    ; $47CC
        jmp L47B8    ; $47CE
L47D1   jsr $D009    ; $47D1
        jsr $D054    ; $47D4
        jsr GatherTYI    ; $47D7
        lda $02    ; $47DA
        cmp $475C    ; $47DC
        bne L47E6    ; $47DF
        lda $03    ; $47E1
        cmp $475D    ; $47E3
L47E6   rts    ; $47E6
;
; === FindBuffer ===
        ldx #$00    ; $47E7
        stx $4828    ; $47E9
L47EC   ldx $4828    ; $47EC
        lda BuffActList,x    ; $47EF
        bpl L481A    ; $47F2
        jsr PointToBInfo    ; $47F4
        ldy #$66    ; $47F7
        ldx #$00    ; $47F9
L47FB   lda $0200,x    ; $47FB
        jsr UpperCon    ; $47FE
        sta $4827    ; $4801
        lda (BuffPoint),y    ; $4804
        jsr UpperCon    ; $4806
        cmp $4827    ; $4809
        bne L481A    ; $480C
        inx    ; $480E
        iny    ; $480F
        cmp #$00    ; $4810
        bne L47FB    ; $4812
        ldx $4828    ; $4814
        lda #$00    ; $4817
        rts    ; $4819
L481A   inc $4828    ; $481A
        lda $4828    ; $481D
        cmp #$0E    ; $4820
        bcc L47EC    ; $4822
        lda #$FF    ; $4824
        rts    ; $4826
        brk    ; $4827
        brk    ; $4828
;
; === FindBuffFile ===
        ldx #$00    ; $4829
        stx $4828    ; $482B
L482E   ldx $4828    ; $482E
        lda BuffActList,x    ; $4831
        bpl L4867    ; $4834
        jsr PointToBInfo    ; $4836
        ldx #$00    ; $4839
        ldy #$14    ; $483B
L483D   lda (BuffPoint),y    ; $483D
        bne L484A    ; $483F
        lda $0200,x    ; $4841
        cmp #$8D    ; $4844
        beq L4861    ; $4846
        lda (BuffPoint),y    ; $4848
L484A   jsr UpperCon    ; $484A
        sta $4827    ; $484D
        lda $0200,x    ; $4850
        jsr UpperCon    ; $4853
        cmp $4827    ; $4856
        bne L4867    ; $4859
        iny    ; $485B
        inx    ; $485C
        cpx #$3F    ; $485D
        bcc L483D    ; $485F
L4861   ldx $4828    ; $4861
        lda #$00    ; $4864
        rts    ; $4866
L4867   inc $4828    ; $4867
        lda $4828    ; $486A
        cmp #$0E    ; $486D
        bcc L482E    ; $486F
        lda #$FF    ; $4871
        rts    ; $4873
;
; === ListBuffers ===
        lda #$00    ; $4874
        sta $49A1    ; $4876
        jsr PrepTO    ; $4879
        lda #$A0    ; $487C
        sta PD:Justify    ; $487E
        ldx #$00    ; $4881
        stx $4828    ; $4883
        stx $49A2    ; $4886
        jsr PrintMessage    ; $4889
; ---- $488C-$4894  data  msg:   Buffer ----
        dfb $A0,$A0,$C2,$F5,$E6,$E6,$E5,$F2,$00    ; $488C    Buffer.
; ---- $4895-$489E  code ----
        lda #$24    ; $4895
        sta CH    ; $4897
        sta TypeoutCH    ; $4899
        jsr PrintMessage    ; $489C
; ---- $489F-$48AC  data  msg: Visiting File ----
        dfb $D6,$E9,$F3,$E9,$F4,$E9,$EE,$E7,$A0,$C6,$E9,$EC,$E5,$00    ; $489F  Visiting File.
; ---- $48AD-$48B6  code ----
        lda #$43    ; $48AD
        sta CH    ; $48AF
        sta TypeoutCH    ; $48B1
        jsr PrintMessage    ; $48B4
; ---- $48B7-$48BD  data  msg: Size.. ----
        dfb $D3,$E9,$FA,$E5,$8D,$8D,$00    ; $48B7  Size...
; ---- $48BE-$4946  code ----
L48BE   ldx $4828    ; $48BE
        lda BuffActList,x    ; $48C1
        bpl L492B    ; $48C4
        inc $49A1    ; $48C6
        jsr PointToBInfo    ; $48C9
        lda #$A0    ; $48CC
        ldx $4828    ; $48CE
        cpx SelectedBuff    ; $48D1
        bne L48D8    ; $48D4
        lda #$AE    ; $48D6
L48D8   jsr CharOut    ; $48D8
        lda #$A0    ; $48DB
        jsr CharOut    ; $48DD
        ldy #$55    ; $48E0
        lda (BuffPoint),y    ; $48E2
        and #$02    ; $48E4
        php    ; $48E6
        lda #$A0    ; $48E7
        plp    ; $48E9
        beq L48EE    ; $48EA
        lda #$AA    ; $48EC
L48EE   jsr CharOut    ; $48EE
        lda #$A0    ; $48F1
        jsr CharOut    ; $48F3
        jsr PBuffName1    ; $48F6
        ldy #$66    ; $48F9
        lda #$1E    ; $48FB
        sta CH    ; $48FD
        sta TypeoutCH    ; $48FF
        lda #$A0    ; $4902
        jsr CharOut    ; $4904
        jsr PBuffFile1    ; $4907
        lda #$42    ; $490A
        sta CH    ; $490C
        sta TypeoutCH    ; $490E
        lda #$A0    ; $4911
        jsr CharOut    ; $4913
        ldx $4828    ; $4916
        jsr MySize    ; $4919
        pha    ; $491C
        clc    ; $491D
        adc $49A2    ; $491E
        sta $49A2    ; $4921
        pla    ; $4924
        jsr PrintDec    ; $4925
        jsr PrintReturn    ; $4928
L492B   inc $4828    ; $492B
        lda $4828    ; $492E
        cmp #$0E    ; $4931
        bcc L48BE    ; $4933
        jsr PrintReturn    ; $4935
        lda $49A2    ; $4938
        lsr    ; $493B
        lsr    ; $493C
        tax    ; $493D
        jsr ZeroJustify    ; $493E
        jsr PrintDec    ; $4941
        jsr PrintMessage    ; $4944
; ---- $4947-$4953  data  msg: k in use by ----
        dfb $EB,$A0,$E9,$EE,$A0,$F5,$F3,$E5,$A0,$E2,$F9,$A0,$00    ; $4947  k in use by .
; ---- $4954-$495E  code ----
        lda #$00    ; $4954
        ldx $49A1    ; $4956
        jsr PrintDec    ; $4959
        jsr PrintMessage    ; $495C
; ---- $495F-$4966  data  msg:  buffer ----
        dfb $A0,$E2,$F5,$E6,$E6,$E5,$F2,$00    ; $495F   buffer.
; ---- $4967-$4974  code ----
        ldx $49A1    ; $4967
        dex    ; $496A
        beq L4972    ; $496B
        lda #$F3    ; $496D
        jsr CharOut    ; $496F
L4972   jsr PrintMessage    ; $4972
; ---- $4975-$4977  data  msg: , ----
        dfb $AC,$A0,$00    ; $4975  , .
; ---- $4978-$498C  code ----
        sec    ; $4978
        lda $42FB    ; $4979
        sbc $42F9    ; $497C
        sbc $49A2    ; $497F
        lsr    ; $4982
        lsr    ; $4983
        tax    ; $4984
        lda #$00    ; $4985
        jsr PrintDec    ; $4987
        jsr PrintMessage    ; $498A
; ---- $498D-$499A  data  msg: k remaining.. ----
        dfb $EB,$A0,$F2,$E5,$ED,$E1,$E9,$EE,$E9,$EE,$E7,$AE,$8D,$00    ; $498D  k remaining...
; ---- $499B-$4A49  code ----
        jsr PrintDone    ; $499B
        jmp UnPrepTO    ; $499E
        brk    ; $49A1
        brk    ; $49A2
        brk    ; $49A3
;
; === MySize ===
        cpx SelectedBuff    ; $49A4
        beq L49B5    ; $49A7
        jsr PointToBInfo    ; $49A9
        ldy #$0A    ; $49AC
        lda (BuffPoint),y    ; $49AE
        tax    ; $49B0
        iny    ; $49B1
        lda (BuffPoint),y    ; $49B2
        rts    ; $49B4
L49B5   lda GapTop    ; $49B5
        sec    ; $49B7
        sbc PhysBuffTop    ; $49B8
        tax    ; $49BA
        lda $6B    ; $49BB
        sbc $6F    ; $49BD
        pha    ; $49BF
        lda PhysBuffBot    ; $49C0
        clc    ; $49C2
        sbc GapBot    ; $49C3
        sta $49A3    ; $49C5
        lda $71    ; $49C8
        sbc $6D    ; $49CA
        pha    ; $49CC
        clc    ; $49CD
        txa    ; $49CE
        adc $49A3    ; $49CF
        tax    ; $49D2
        pla    ; $49D3
        sta $49A3    ; $49D4
        pla    ; $49D7
        adc $49A3    ; $49D8
        rts    ; $49DB
;
; === PBuffName ===
        jsr PointToBInfo    ; $49DC
;
; === PBuffName1 ===
        ldy #$66    ; $49DF
;
; === PBuffPoint ===
        lda (BuffPoint),y    ; $49E1
        beq L49EB    ; $49E3
        jsr CharOut    ; $49E5
        iny    ; $49E8
        bne PBuffPoint    ; $49E9
L49EB   rts    ; $49EB
;
; === PBuffFile ===
        jsr PointToBInfo    ; $49EC
;
; === PBuffFile1 ===
        ldy #$14    ; $49EF
        bne PBuffPoint    ; $49F1
;
; === IN:KillBuff ===
        jsr SI:SelectB    ; $49F3
;
; === ZapBuff ===
        lda PhysBuffTop    ; $49F6
        sta BuffTop    ; $49F8
        sta GapTop    ; $49FA
        sta TheBuffer    ; $49FC
        sta PageTop    ; $49FE
        lda $6F    ; $4A00
        sta $67    ; $4A02
        sta $6B    ; $4A04
        sta $61    ; $4A06
        sta $63    ; $4A08
        lda PhysBuffBot    ; $4A0A
        sta BuffBot    ; $4A0C
        sta GapBot    ; $4A0E
        lda $71    ; $4A10
        sta $69    ; $4A12
        sta $6D    ; $4A14
        lda GapBot    ; $4A16
        bne L4A1C    ; $4A18
        dec $6D    ; $4A1A
L4A1C   dec GapBot    ; $4A1C
        rts    ; $4A1E
;
; === KillBuffer ===
        ldx SelectedBuff    ; $4A1F
        stx $4A86    ; $4A22
        jsr GetStrArg    ; $4A25
        beq L4A3C    ; $4A28
        ldx $4A86    ; $4A2A
        jsr L4B2A    ; $4A2D
        dfb $CB        ; $4A30  (data/65C02-bit)
        sbc #$EC    ; $4A31
        jmp ($06F0)    ; $4A33
L4A36   jsr Beep    ; $4A36
        lda #$01    ; $4A39
        rts    ; $4A3B
L4A3C   lda #$00    ; $4A3C
        sta $0200,x    ; $4A3E
        txa    ; $4A41
        bne L4A87    ; $4A42
L4A44   jsr NewEchoArea    ; $4A44
        jsr PrintMessage    ; $4A47
; ---- $4A4A-$4A65  data  msg: Killing the current buffer. ----
        dfb $CB,$E9,$EC,$EC,$E9,$EE,$E7,$A0,$F4,$E8,$E5,$A0,$E3,$F5,$F2,$F2    ; $4A4A  Killing the curr
        dfb $E5,$EE,$F4,$A0,$E2,$F5,$E6,$E6,$E5,$F2,$AE,$00    ; $4A5A  ent buffer..
; ---- $4A66-$4A6E  code ----
        jsr DefBuffer    ; $4A66
        stx $4B82    ; $4A69
        jsr PrintMessage    ; $4A6C
; ---- $4A6F-$4A77  data  msg:   Select ----
        dfb $A0,$A0,$D3,$E5,$EC,$E5,$E3,$F4,$00    ; $4A6F    Select.
; ---- $4A78-$4B5B  code ----
        jsr L4B59    ; $4A78
        bne L4A36    ; $4A7B
        lda #$00    ; $4A7D
        sta $0200,x    ; $4A7F
        txa    ; $4A82
        jmp L4AD0    ; $4A83
        brk    ; $4A86
L4A87   jsr FindBuffer    ; $4A87
        bne L4A36    ; $4A8A
        cpx $4A86    ; $4A8C
        beq L4A44    ; $4A8F
        stx $4A86    ; $4A91
        cpx SelectedBuff    ; $4A94
        bne L4A9C    ; $4A97
        jmp L4A44    ; $4A99
L4A9C   cpx LastBuffer    ; $4A9C
        bne L4AA7    ; $4A9F
        lda SelectedBuff    ; $4AA1
        sta LastBuffer    ; $4AA4
L4AA7   lda LastBuffer    ; $4AA7
        pha    ; $4AAA
        jsr IN:KillBuff    ; $4AAB
        ldx LastBuffer    ; $4AAE
        jsr SI:SelectB    ; $4AB1
        pla    ; $4AB4
        sta LastBuffer    ; $4AB5
L4AB8   ldx $4A86    ; $4AB8
        lda #$01    ; $4ABB
        sta BuffActList,x    ; $4ABD
        jsr PointToBInfo    ; $4AC0
        lda #$00    ; $4AC3
        ldy #$14    ; $4AC5
        sta (BuffPoint),y    ; $4AC7
        ldy #$66    ; $4AC9
        sta (BuffPoint),y    ; $4ACB
        lda #$01    ; $4ACD
        rts    ; $4ACF
L4AD0   php    ; $4AD0
        ldx $4A86    ; $4AD1
        jsr IN:KillBuff    ; $4AD4
        plp    ; $4AD7
        bne L4AF5    ; $4AD8
        ldx LastBuffer    ; $4ADA
        jsr PointToBInfo    ; $4ADD
        ldy #$66    ; $4AE0
        ldx #$00    ; $4AE2
L4AE4   lda (BuffPoint),y    ; $4AE4
        sta $0200,x    ; $4AE6
        iny    ; $4AE9
        inx    ; $4AEA
        cmp #$00    ; $4AEB
        bne L4AE4    ; $4AED
        ldx SelectedBuff    ; $4AEF
        stx LastBuffer    ; $4AF2
L4AF5   jsr L4AB8    ; $4AF5
        jsr SelectNamed    ; $4AF8
        ldx SelectedBuff    ; $4AFB
        stx LastBuffer    ; $4AFE
        rts    ; $4B01
;
; === DefBuffer ===
        ldx LastBuffer    ; $4B02
        cpx SelectedBuff    ; $4B05
        beq L4B0B    ; $4B08
        rts    ; $4B0A
L4B0B   stx $B0    ; $4B0B
        ldx LastBuffer    ; $4B0D
        cpx $B0    ; $4B10
        bne L4B26    ; $4B12
        ldx $B0    ; $4B14
L4B16   dex    ; $4B16
        bpl L4B1B    ; $4B17
        ldx #$0D    ; $4B19
L4B1B   cpx $B0    ; $4B1B
        beq L4B26    ; $4B1D
        lda BuffActList,x    ; $4B1F
        bpl L4B16    ; $4B22
        bmi L4B26    ; $4B24
L4B26   stx LastBuffer    ; $4B26
        rts    ; $4B29
L4B2A   stx $4B82    ; $4B2A
        jsr NewEchoArea    ; $4B2D
        lda #$74    ; $4B30
        sta ReadLineHelp    ; $4B32
        lda #$48    ; $4B35
        sta $3B21    ; $4B37
        pla    ; $4B3A
        sta $00    ; $4B3B
        pla    ; $4B3D
        sta $01    ; $4B3E
        ldy #$00    ; $4B40
L4B42   inc $00    ; $4B42
        bne L4B48    ; $4B44
        inc $01    ; $4B46
L4B48   lda ($00),y    ; $4B48
        pha    ; $4B4A
        ora #$80    ; $4B4B
        jsr CharOut    ; $4B4D
        pla    ; $4B50
        bmi L4B42    ; $4B51
        lda $01    ; $4B53
        pha    ; $4B55
        lda $00    ; $4B56
        pha    ; $4B58
L4B59   jsr PrintMessage    ; $4B59
; ---- $4B5C-$4B65  data  msg:  Buffer ( ----
        dfb $A0,$C2,$F5,$E6,$E6,$E5,$F2,$A0,$A8,$00    ; $4B5C   Buffer (.
; ---- $4B66-$4B6E  code ----
        ldx $4B82    ; $4B66
        jsr PBuffName    ; $4B69
        jsr PrintMessage    ; $4B6C
; ---- $4B6F-$4B71  data  msg: ): ----
        dfb $A9,$BA,$00    ; $4B6F  ):.
; ---- $4B72-$4F83  code ----
        dec BufferRead    ; $4B72
        jsr ReadLine    ; $4B75
        php    ; $4B78
        txa    ; $4B79
        pha    ; $4B7A
        jsr CloseEchoArea    ; $4B7B
        pla    ; $4B7E
        tax    ; $4B7F
        plp    ; $4B80
        rts    ; $4B81
        brk    ; $4B82
;
; === Modified? ===
        brk    ; $4B83
;
; === BuffInsert ===
        pha    ; $4B84
        jsr SetGap    ; $4B85
        inc GapTop    ; $4B88
        bne L4B8E    ; $4B8A
        inc $6B    ; $4B8C
L4B8E   lda $6B    ; $4B8E
        cmp $6D    ; $4B90
        bcc L4B9C    ; $4B92
        bne L4BB1    ; $4B94
        lda GapTop    ; $4B96
        cmp GapBot    ; $4B98
        bcs L4BB1    ; $4B9A
L4B9C   pla    ; $4B9C
        jsr $D06F    ; $4B9D
        inc TheBuffer    ; $4BA0
        bne L4BA6    ; $4BA2
        inc $61    ; $4BA4
L4BA6   bit Modified?    ; $4BA6
        bmi L4BAE    ; $4BA9
        jsr SetModified    ; $4BAB
L4BAE   lda #$00    ; $4BAE
        rts    ; $4BB0
L4BB1   pla    ; $4BB1
        lda GapTop    ; $4BB2
        bne L4BB8    ; $4BB4
        dec $6B    ; $4BB6
L4BB8   dec GapTop    ; $4BB8
        lda #$FF    ; $4BBA
        rts    ; $4BBC
;
; === BuffRubout ===
        jsr SetGap    ; $4BBD
        lda GapTop    ; $4BC0
        cmp BuffTop    ; $4BC2
        bne L4BCC    ; $4BC4
        lda $6B    ; $4BC6
        cmp $67    ; $4BC8
        beq L4C12    ; $4BCA
L4BCC   lda TheBuffer    ; $4BCC
        bne L4BD2    ; $4BCE
        dec $61    ; $4BD0
L4BD2   dec TheBuffer    ; $4BD2
        lda GapTop    ; $4BD4
        bne L4BDA    ; $4BD6
        dec $6B    ; $4BD8
L4BDA   dec GapTop    ; $4BDA
        bit Modified?    ; $4BDC
        bmi L4BE4    ; $4BDF
        jsr SetModified    ; $4BE1
L4BE4   lda #$00    ; $4BE4
        rts    ; $4BE6
;
; === BuffDelete ===
        jsr SetGap    ; $4BE7
        inc GapBot    ; $4BEA
        bne L4BF0    ; $4BEC
        inc $6D    ; $4BEE
L4BF0   lda GapBot    ; $4BF0
        cmp BuffBot    ; $4BF2
        bne L4C07    ; $4BF4
        lda $6D    ; $4BF6
        cmp $69    ; $4BF8
        bne L4C07    ; $4BFA
        lda GapBot    ; $4BFC
        bne L4C02    ; $4BFE
        dec $6D    ; $4C00
L4C02   dec GapBot    ; $4C02
        jmp L4C12    ; $4C04
L4C07   bit Modified?    ; $4C07
        bmi L4C0F    ; $4C0A
        jsr SetModified    ; $4C0C
L4C0F   lda #$00    ; $4C0F
        rts    ; $4C11
L4C12   lda #$FF    ; $4C12
        rts    ; $4C14
;
; === SetLastKill ===
        lda #$04    ; $4C15
;
; === SetBuffFlag ===
        ldy #$41    ; $4C17
        ora (BuffData),y    ; $4C19
        sta (BuffData),y    ; $4C1B
        rts    ; $4C1D
;
; === ClrLastKill ===
        lda #$04    ; $4C1E
;
; === ClrBuffFlag ===
        ldy #$41    ; $4C20
        eor #$FF    ; $4C22
        and (BuffData),y    ; $4C24
        sta (BuffData),y    ; $4C26
        rts    ; $4C28
;
; === OldKill? ===
        lda #$04    ; $4C29
;
; === BuffFlagOn? ===
        jsr BuffFlagOff?    ; $4C2B
        beq L4C33    ; $4C2E
        lda #$00    ; $4C30
        rts    ; $4C32
L4C33   iny    ; $4C33
        rts    ; $4C34
;
; === BuffFlagOff? ===
        ldy #$41    ; $4C35
        and (BuffData),y    ; $4C37
        rts    ; $4C39
;
; === SetAModified ===
        bpl ClrModified    ; $4C3A
;
; === SetModified ===
        lda #$02    ; $4C3C
        jsr SetBuffFlag    ; $4C3E
        lda #$FF    ; $4C41
        bmi L4C4C    ; $4C43
;
; === ClrModified ===
        lda #$02    ; $4C45
        jsr ClrBuffFlag    ; $4C47
        lda #$00    ; $4C4A
L4C4C   sta Modified?    ; $4C4C
        jmp ModeInfo    ; $4C4F
;
; === SetGap ===
        ldy #$00    ; $4C52
        lda $61    ; $4C54
        cmp $6B    ; $4C56
        bcc L4C64    ; $4C58
        bne L4C8A    ; $4C5A
        lda TheBuffer    ; $4C5C
        cmp GapTop    ; $4C5E
        beq L4CBD    ; $4C60
        bcs L4C8A    ; $4C62
L4C64   lda GapTop    ; $4C64
        bne L4C6A    ; $4C66
        dec $6B    ; $4C68
L4C6A   dec GapTop    ; $4C6A
        jsr $D036    ; $4C6C
        jsr $D093    ; $4C6F
        jsr GatherTYI    ; $4C72
        lda GapBot    ; $4C75
        bne L4C7B    ; $4C77
        dec $6D    ; $4C79
L4C7B   dec GapBot    ; $4C7B
        lda $6B    ; $4C7D
        cmp $61    ; $4C7F
        bne L4C64    ; $4C81
        lda GapTop    ; $4C83
        cmp TheBuffer    ; $4C85
        bne L4C64    ; $4C87
        rts    ; $4C89
L4C8A   inc GapBot    ; $4C8A
        bne L4C90    ; $4C8C
        inc $6D    ; $4C8E
L4C90   lda $6D    ; $4C90
        cmp $61    ; $4C92
        bcc L4C9C    ; $4C94
        lda GapBot    ; $4C96
        cmp TheBuffer    ; $4C98
        bcs L4CAD    ; $4C9A
L4C9C   jsr $D03F    ; $4C9C
        jsr $D08A    ; $4C9F
        jsr GatherTYI    ; $4CA2
        inc GapTop    ; $4CA5
        bne L4CAB    ; $4CA7
        inc $6B    ; $4CA9
L4CAB   bne L4C8A    ; $4CAB
L4CAD   lda GapBot    ; $4CAD
        bne L4CB3    ; $4CAF
        dec $6D    ; $4CB1
L4CB3   dec GapBot    ; $4CB3
        lda GapTop    ; $4CB5
        sta TheBuffer    ; $4CB7
        lda $6B    ; $4CB9
        sta $61    ; $4CBB
L4CBD   rts    ; $4CBD
;
; === KillGap ===
        jsr L4CDE    ; $4CBE
        lda $61    ; $4CC1
        pha    ; $4CC3
        lda TheBuffer    ; $4CC4
        pha    ; $4CC6
        lda BuffBot    ; $4CC7
        sta TheBuffer    ; $4CC9
        lda $69    ; $4CCB
        sta $61    ; $4CCD
        jsr SetGap    ; $4CCF
        pla    ; $4CD2
        sta TheBuffer    ; $4CD3
        pla    ; $4CD5
        sta $61    ; $4CD6
        lda #$FF    ; $4CD8
        sta $07F7    ; $4CDA
        rts    ; $4CDD
L4CDE   lda $07F7    ; $4CDE
        sta $4CD9    ; $4CE1
        lda #$20    ; $4CE4
        sta $07F7    ; $4CE6
        rts    ; $4CE9
;
; === MarkStack ===
        ds 17        ; $4CEA  17 bytes $00 fill
;
; === PushMark ===
        lda TheBuffer    ; $4CFB
        sta $00    ; $4CFD
        lda $61    ; $4CFF
        sta $01    ; $4D01
;
; === MarkTemp ===
        lda $00    ; $4D03
        sec    ; $4D05
        sbc PhysBuffTop    ; $4D06
        sta $00    ; $4D08
        lda $01    ; $4D0A
        sbc $6F    ; $4D0C
        sta $01    ; $4D0E
;
; === IN:MarkTemp ===
        lda MarkStackPntr    ; $4D10
        asl    ; $4D13
        tax    ; $4D14
        lda $00    ; $4D15
        sta MarkStack,x    ; $4D17
        lda $01    ; $4D1A
        sta $4CEB,x    ; $4D1C
        inc MarkStackPntr    ; $4D1F
        lda MarkStackPntr    ; $4D22
        cmp #$08    ; $4D25
        bcc L4D2E    ; $4D27
        lda #$00    ; $4D29
        sta MarkStackPntr    ; $4D2B
L4D2E   rts    ; $4D2E
;
; === MarkBuffer ===
        ldx SelectedBuff    ; $4D2F
        jsr MySize    ; $4D32
        sta $01    ; $4D35
        stx $00    ; $4D37
        jsr IN:MarkTemp    ; $4D39
        lda BuffTop    ; $4D3C
        sta TheBuffer    ; $4D3E
        lda $67    ; $4D40
        sta $61    ; $4D42
        jsr SetGap    ; $4D44
        lda #$06    ; $4D47
        rts    ; $4D49
;
; === PopMark ===
        lda $01    ; $4D4A
        pha    ; $4D4C
        lda $00    ; $4D4D
        pha    ; $4D4F
        jsr PopTempMark    ; $4D50
        lda $01    ; $4D53
        cmp $6B    ; $4D55
        bcc L4D8D    ; $4D57
        bne L4D63    ; $4D59
        lda $00    ; $4D5B
        cmp GapTop    ; $4D5D
        bcc L4D8D    ; $4D5F
        beq L4D8D    ; $4D61
L4D63   lda $00    ; $4D63
        sec    ; $4D65
        sbc GapTop    ; $4D66
        tax    ; $4D68
        lda $01    ; $4D69
        sbc $6B    ; $4D6B
        pha    ; $4D6D
        txa    ; $4D6E
        sec    ; $4D6F
        adc GapBot    ; $4D70
        sta $00    ; $4D72
        pla    ; $4D74
        adc $6D    ; $4D75
        sta $01    ; $4D77
        cmp $69    ; $4D79
        bcc L4D8D    ; $4D7B
        bne L4D85    ; $4D7D
        lda $00    ; $4D7F
        cmp BuffBot    ; $4D81
        bcc L4D8D    ; $4D83
L4D85   lda BuffBot    ; $4D85
        sta $00    ; $4D87
        lda $69    ; $4D89
        sta $01    ; $4D8B
L4D8D   lda $00    ; $4D8D
        sta TheBuffer    ; $4D8F
        lda $01    ; $4D91
        sta $61    ; $4D93
        pla    ; $4D95
        sta $00    ; $4D96
        pla    ; $4D98
        sta $01    ; $4D99
        rts    ; $4D9B
;
; === PopTempMark ===
        ldx MarkStackPntr    ; $4D9C
        bne L4DA3    ; $4D9F
        ldx #$08    ; $4DA1
L4DA3   dex    ; $4DA3
        stx MarkStackPntr    ; $4DA4
        txa    ; $4DA7
        asl    ; $4DA8
        tax    ; $4DA9
        lda MarkStack,x    ; $4DAA
        clc    ; $4DAD
        adc PhysBuffTop    ; $4DAE
        sta $00    ; $4DB0
        lda $4CEB,x    ; $4DB2
        adc $6F    ; $4DB5
        sta $01    ; $4DB7
        rts    ; $4DB9
;
; === GetTempMark ===
        jsr PopTempMark    ; $4DBA
        lda $01    ; $4DBD
        pha    ; $4DBF
        lda $00    ; $4DC0
        pha    ; $4DC2
        jsr MarkTemp    ; $4DC3
        pla    ; $4DC6
        sta $00    ; $4DC7
        pla    ; $4DC9
        sta $01    ; $4DCA
        rts    ; $4DCC
;
; === SwapPointMark ===
        lda $61    ; $4DCD
        pha    ; $4DCF
        lda TheBuffer    ; $4DD0
        pha    ; $4DD2
        jsr PopMark    ; $4DD3
        pla    ; $4DD6
        sta $00    ; $4DD7
        pla    ; $4DD9
        sta $01    ; $4DDA
        jsr MarkTemp    ; $4DDC
        rts    ; $4DDF
        brk    ; $4DE0
        cld    ; $4DE1
        brk    ; $4DE2
        cld    ; $4DE3
;
; === DeleteKill? ===
        brk    ; $4DE4
        brk    ; $4DE5
L4DE6   inc $B0    ; $4DE6
        bne L4DEC    ; $4DE8
        inc $B1    ; $4DEA
L4DEC   beq L4DFA    ; $4DEC
        lda $B1    ; $4DEE
        cmp #$FF    ; $4DF0
        bcc L4E02    ; $4DF2
        lda $B0    ; $4DF4
        cmp #$F1    ; $4DF6
        bcc L4E02    ; $4DF8
L4DFA   lda #$00    ; $4DFA
        sta $B0    ; $4DFC
        lda #$D8    ; $4DFE
        sta $B1    ; $4E00
L4E02   rts    ; $4E02
L4E03   lda $B1    ; $4E03
        cmp #$D8    ; $4E05
        bne L4E17    ; $4E07
        lda $B0    ; $4E09
        cmp #$00    ; $4E0B
        bne L4E17    ; $4E0D
        lda #$F1    ; $4E0F
        sta $B0    ; $4E11
        lda #$FF    ; $4E13
        sta $B1    ; $4E15
L4E17   lda $B0    ; $4E17
        bne L4E1D    ; $4E19
        dec $B1    ; $4E1B
L4E1D   dec $B0    ; $4E1D
        rts    ; $4E1F
L4E20   jsr EqTempPoint?    ; $4E20
        bne L4E2C    ; $4E23
        rts    ; $4E25
L4E26   jsr EqTempPoint?    ; $4E26
        bne L4E38    ; $4E29
        rts    ; $4E2B
L4E2C   lda $4DE2    ; $4E2C
        sta $4DE0    ; $4E2F
        lda $4DE3    ; $4E32
        sta $4DE1    ; $4E35
L4E38   ldy #$00    ; $4E38
        lda $4DE0    ; $4E3A
        sta $B0    ; $4E3D
        lda $4DE1    ; $4E3F
        sta $B1    ; $4E42
L4E44   jsr $D000    ; $4E44
        php    ; $4E47
        sta $4DE5    ; $4E48
        lda $B1    ; $4E4B
        ldx $B0    ; $4E4D
        sta UseAuxZP    ; $4E4F   <== BANK: aux zero-page/stack (ALTZP on)
        sta $B1    ; $4E52
        stx $B0    ; $4E54
        lda $4DE5    ; $4E56
        sta ($B0),y    ; $4E59
        sta UseMainZP    ; $4E5B   <== BANK: main zero-page/stack (ALTZP off)
        plp    ; $4E5E
        jsr L4DE6    ; $4E5F
        lda $B0    ; $4E62
        cmp $4DE2    ; $4E64
        bne L4E82    ; $4E67
        lda $B1    ; $4E69
        cmp $4DE3    ; $4E6B
        bne L4E82    ; $4E6E
        jsr Beep    ; $4E70
        jsr L4E03    ; $4E73
        jsr L4E8D    ; $4E76
        jsr ClrLastKill    ; $4E79
        lda #$FF    ; $4E7C
        sta DeleteKill?    ; $4E7E
        rts    ; $4E81
L4E82   inc $00    ; $4E82
        bne L4E88    ; $4E84
        inc $01    ; $4E86
L4E88   jsr EqTempPoint?    ; $4E88
        bne L4E44    ; $4E8B
L4E8D   lda $B0    ; $4E8D
        sta $4DE0    ; $4E8F
        lda $B1    ; $4E92
        sta $4DE1    ; $4E94
        jsr SetLastKill    ; $4E97
        jsr SetModified    ; $4E9A
        rts    ; $4E9D
L4E9E   lda $4DE1    ; $4E9E
        pha    ; $4EA1
        lda $4DE0    ; $4EA2
        pha    ; $4EA5
        lda TheBuffer    ; $4EA6
        sec    ; $4EA8
        sbc $00    ; $4EA9
        sta $B2    ; $4EAB
        lda $61    ; $4EAD
        sbc $01    ; $4EAF
        sta $B3    ; $4EB1
        lda $4DE2    ; $4EB3
        sta $B0    ; $4EB6
        lda $4DE3    ; $4EB8
        sta $B1    ; $4EBB
L4EBD   lda $B3    ; $4EBD
        ora $B2    ; $4EBF
        beq L4ED1    ; $4EC1
        lda $B2    ; $4EC3
        bne L4EC9    ; $4EC5
        dec $B3    ; $4EC7
L4EC9   dec $B2    ; $4EC9
        jsr L4E03    ; $4ECB
        jmp L4EBD    ; $4ECE
L4ED1   lda $B0    ; $4ED1
        sta $4DE0    ; $4ED3
        sta $4DE2    ; $4ED6
        lda $B1    ; $4ED9
        sta $4DE1    ; $4EDB
        sta $4DE3    ; $4EDE
        jsr L4E38    ; $4EE1
        pla    ; $4EE4
        sta $4DE0    ; $4EE5
        pla    ; $4EE8
        sta $4DE1    ; $4EE9
        rts    ; $4EEC
;
; === YankKill ===
        jsr PushMark    ; $4EED
        lda $4DE2    ; $4EF0
        sta $B0    ; $4EF3
        lda $4DE3    ; $4EF5
        sta $B1    ; $4EF8
L4EFA   lda $B1    ; $4EFA
        cmp $4DE1    ; $4EFC
        bne L4F19    ; $4EFF
        lda $B0    ; $4F01
        cmp $4DE0    ; $4F03
        bne L4F19    ; $4F06
L4F08   jsr ClrLastKill    ; $4F08
        jsr FindPoint    ; $4F0B
        beq L4F13    ; $4F0E
        lda #$06    ; $4F10
        rts    ; $4F12
L4F13   jsr DisplayPage    ; $4F13
        lda #$01    ; $4F16
        rts    ; $4F18
L4F19   ldy #$00    ; $4F19
        ldx $B0    ; $4F1B
        lda $B1    ; $4F1D
        sta UseAuxZP    ; $4F1F   <== BANK: aux zero-page/stack (ALTZP on)
        sta $B1    ; $4F22
        stx $B0    ; $4F24
        lda ($B0),y    ; $4F26
        sta UseMainZP    ; $4F28   <== BANK: main zero-page/stack (ALTZP off)
        jsr BuffInsert    ; $4F2B
        bne L4F08    ; $4F2E
        jsr L4DE6    ; $4F30
        jmp L4EFA    ; $4F33
;
; === GenericKill ===
        sta $4F7D    ; $4F36
        lda #$04    ; $4F39
        jsr BuffFlagOn?    ; $4F3B
        beq L4F60    ; $4F3E
        lda $01    ; $4F40
        pha    ; $4F42
        lda $00    ; $4F43
        pha    ; $4F45
        jsr L4E20    ; $4F46
L4F49   pla    ; $4F49
        sta $00    ; $4F4A
        pla    ; $4F4C
        sta $01    ; $4F4D
        bit DeleteKill?    ; $4F4F
        bmi L4F57    ; $4F52
        jsr DelTempPoint    ; $4F54
L4F57   jsr SetLastKill    ; $4F57
        lda #$00    ; $4F5A
        sta DeleteKill?    ; $4F5C
        rts    ; $4F5F
L4F60   lda $4F7D    ; $4F60
        bmi L4F71    ; $4F63
        lda $01    ; $4F65
        pha    ; $4F67
        lda $00    ; $4F68
        pha    ; $4F6A
        jsr L4E26    ; $4F6B
        jmp L4F49    ; $4F6E
L4F71   lda $01    ; $4F71
        pha    ; $4F73
        lda $00    ; $4F74
        pha    ; $4F76
        jsr L4E9E    ; $4F77
        jmp L4F49    ; $4F7A
        brk    ; $4F7D
;
; === SetNewAppend ===
        jsr SetLastKill    ; $4F7E
        lda #$01    ; $4F81
        rts    ; $4F83
