;-*- Mode: Merlin -*-
;
; src/modules/10_comtab.s -- AMACS: command dispatch table + char->command vectors
; Address range $4F84-$5183. GENERATED by tools/disasm.py.
; `put' from src/amacs.s; symbols/labels are global across modules.
;
; ---- $4F84-$504D  data  ComTab (command dispatch table) ----
        dfb $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00    ; $4F84  ................
        dfb $00,$00,$26,$25,$00,$00,$6A,$1E,$BB,$92,$72,$25,$DD,$22,$00,$00    ; $4F94  ..&%..j.;.r%]"..
        dfb $4C,$23,$00,$00,$F0,$23,$00,$00,$00,$00,$00,$00,$00,$00,$7E,$4F    ; $4FA4  L#..p#........~O
        dfb $1F,$3F,$00,$00,$82,$10,$00,$00,$D6,$94,$00,$00,$00,$00,$00,$00    ; $4FB4  .?......V.......
        dfb $00,$00,$2B,$24,$00,$00,$00,$00,$00,$00,$75,$84,$30,$24,$00,$00    ; $4FC4  ..+$......u.0$..
        dfb $00,$00,$00,$00,$00,$00,$38,$24,$00,$00,$11,$7B,$D2,$94,$00,$00    ; $4FD4  ......8$...{R...
        dfb $D2,$7A,$D2,$7A,$D2,$7A,$D2,$7A,$D2,$7A,$D2,$7A,$D2,$7A,$D2,$7A    ; $4FE4  RzRzRzRzRzRzRzRz
        dfb $D2,$7A,$D2,$7A,$00,$00,$7A,$1E,$41,$1A,$B0,$8D,$5A,$1A,$E8,$7F    ; $4FF4  RzRz..z.A.0.Z.h.
        dfb $00,$00,$6E,$3A,$C2,$35,$7D,$36,$E7,$37,$2E,$3A,$17,$36,$00,$00    ; $5004  ..n:B5}6g7.:.6..
        dfb $B5,$22,$BB,$8E,$00,$00,$E0,$3A,$74,$36,$00,$00,$A6,$1E,$E6,$91    ; $5014  5";...`:t6..&.f.
        dfb $9E,$1E,$C7,$22,$E1,$17,$CA,$63,$00,$00,$60,$36,$4C,$35,$92,$8D    ; $5024  ..G"a.Jc..`6L5..
        dfb $1F,$3F,$00,$00,$00,$00,$39,$22,$3C,$39,$CF,$21,$00,$00,$00,$00    ; $5034  .?....9"<9O!....
        dfb $00,$00,$5E,$17,$3B,$17,$B7,$1B,$C2,$1B    ; $5044  ..^.;.7.B.
; ---- $504E-$507F  data  doc:ExitSafe documentation string ----
        dfb $CF,$EE,$A0,$ED,$E5,$E1,$EE,$F3,$A0,$F0,$F2,$EF,$ED,$F0,$F4,$A0    ; $504E  On means prompt 
        dfb $F4,$EF,$A0,$F3,$E1,$F6,$E5,$A0,$ED,$EF,$E4,$E9,$E6,$E9,$E5,$E4    ; $505E  to save modified
        dfb $A0,$E2,$F5,$E6,$E6,$E5,$F2,$73,$00,$00,$00,$00,$00,$00,$00,$00    ; $506E   buffers........
        dfb $00,$00    ; $507E  ..
; ---- $5080-$5183  ptrtable  char->command dispatch vectors (printable chars -> Insert) ----
        da  NotModified     ; $5080  -> $1BA6
        da  RuboutWord      ; $5082  -> $37FE
        da  SetPopMark      ; $5084  -> $35AB
        da  BegOfLine       ; $5086  -> $34A6
        da  LeftChar        ; $5088  -> $175E
        da  $0000           ; $508A  -> $0000
        da  Delete          ; $508C  -> $1587
        da  EndOfLine       ; $508E  -> $34BA
        da  RightChar       ; $5090  -> $173B
        da  TopAbort        ; $5092  -> $1BF4
        da  LeftChar        ; $5094  -> $175E
        da  TabInsert       ; $5096  -> $16CC
        da  DownLine        ; $5098  -> $1BC2
        da  KillLine        ; $509A  -> $382E
        da  NewCenter       ; $509C  -> $1781
        da  CRLF            ; $509E  -> $1826
        da  DownLine        ; $50A0  -> $1BC2
        da  OpenLine        ; $50A2  -> $196E
        da  UpLine          ; $50A4  -> $1BB7
        da  QuotedInsert    ; $50A6  -> $1BB1
        da  RSrch           ; $50A8  -> $1B71
        da  ISrch           ; $50AA  -> $1B79
        da  XposeChars      ; $50AC  -> $89FA
        da  UniversalArg    ; $50AE  -> $7B1D
        da  DownScreen      ; $50B0  -> $34D4
        da  KRegion         ; $50B2  -> $8D9A
        da  ControlX        ; $50B4  -> $1B00
        da  YankKill        ; $50B6  -> $4EED
        da  PrefixCMeta     ; $50B8  -> $1AEB
        da  PrefixMeta      ; $50BA  -> $1AD5
        da  $0000           ; $50BC  -> $0000
        da  OutdentLine     ; $50BE  -> $2578
        da  PrefixCtrl      ; $50C0  -> $1ADE
        da  Help            ; $50C2  -> $8391
        da  SpaceBar        ; $50C4  -> $1F9F
        da  Insert          ; $50C6  -> $16CE
        da  Insert          ; $50C8  -> $16CE
        da  Insert          ; $50CA  -> $16CE
        da  Insert          ; $50CC  -> $16CE
        da  Insert          ; $50CE  -> $16CE
        da  Insert          ; $50D0  -> $16CE
        da  Insert          ; $50D2  -> $16CE
        da  Insert          ; $50D4  -> $16CE
        da  Insert          ; $50D6  -> $16CE
        da  Insert          ; $50D8  -> $16CE
        da  Insert          ; $50DA  -> $16CE
        da  Insert          ; $50DC  -> $16CE
        da  Insert          ; $50DE  -> $16CE
        da  Insert          ; $50E0  -> $16CE
        da  Insert          ; $50E2  -> $16CE
        da  Insert          ; $50E4  -> $16CE
        da  Insert          ; $50E6  -> $16CE
        da  Insert          ; $50E8  -> $16CE
        da  Insert          ; $50EA  -> $16CE
        da  Insert          ; $50EC  -> $16CE
        da  Insert          ; $50EE  -> $16CE
        da  Insert          ; $50F0  -> $16CE
        da  Insert          ; $50F2  -> $16CE
        da  Insert          ; $50F4  -> $16CE
        da  Insert          ; $50F6  -> $16CE
        da  Insert          ; $50F8  -> $16CE
        da  Insert          ; $50FA  -> $16CE
        da  Insert          ; $50FC  -> $16CE
        da  Insert          ; $50FE  -> $16CE
        da  Insert          ; $5100  -> $16CE
        da  Insert          ; $5102  -> $16CE
        da  Insert          ; $5104  -> $16CE
        da  Insert          ; $5106  -> $16CE
        da  Insert          ; $5108  -> $16CE
        da  Insert          ; $510A  -> $16CE
        da  Insert          ; $510C  -> $16CE
        da  Insert          ; $510E  -> $16CE
        da  Insert          ; $5110  -> $16CE
        da  Insert          ; $5112  -> $16CE
        da  Insert          ; $5114  -> $16CE
        da  Insert          ; $5116  -> $16CE
        da  Insert          ; $5118  -> $16CE
        da  Insert          ; $511A  -> $16CE
        da  Insert          ; $511C  -> $16CE
        da  Insert          ; $511E  -> $16CE
        da  Insert          ; $5120  -> $16CE
        da  Insert          ; $5122  -> $16CE
        da  Insert          ; $5124  -> $16CE
        da  Insert          ; $5126  -> $16CE
        da  Insert          ; $5128  -> $16CE
        da  Insert          ; $512A  -> $16CE
        da  Insert          ; $512C  -> $16CE
        da  Insert          ; $512E  -> $16CE
        da  Insert          ; $5130  -> $16CE
        da  Insert          ; $5132  -> $16CE
        da  Insert          ; $5134  -> $16CE
        da  Insert          ; $5136  -> $16CE
        da  Insert          ; $5138  -> $16CE
        da  Insert          ; $513A  -> $16CE
        da  Insert          ; $513C  -> $16CE
        da  Insert          ; $513E  -> $16CE
        da  Insert          ; $5140  -> $16CE
        da  Insert          ; $5142  -> $16CE
        da  Insert          ; $5144  -> $16CE
        da  Insert          ; $5146  -> $16CE
        da  Insert          ; $5148  -> $16CE
        da  Insert          ; $514A  -> $16CE
        da  Insert          ; $514C  -> $16CE
        da  Insert          ; $514E  -> $16CE
        da  Insert          ; $5150  -> $16CE
        da  Insert          ; $5152  -> $16CE
        da  Insert          ; $5154  -> $16CE
        da  Insert          ; $5156  -> $16CE
        da  Insert          ; $5158  -> $16CE
        da  Insert          ; $515A  -> $16CE
        da  Insert          ; $515C  -> $16CE
        da  Insert          ; $515E  -> $16CE
        da  Insert          ; $5160  -> $16CE
        da  Insert          ; $5162  -> $16CE
        da  Insert          ; $5164  -> $16CE
        da  Insert          ; $5166  -> $16CE
        da  Insert          ; $5168  -> $16CE
        da  Insert          ; $516A  -> $16CE
        da  Insert          ; $516C  -> $16CE
        da  Insert          ; $516E  -> $16CE
        da  Insert          ; $5170  -> $16CE
        da  Insert          ; $5172  -> $16CE
        da  Insert          ; $5174  -> $16CE
        da  Insert          ; $5176  -> $16CE
        da  Insert          ; $5178  -> $16CE
        da  Insert          ; $517A  -> $16CE
        da  Insert          ; $517C  -> $16CE
        da  Insert          ; $517E  -> $16CE
        da  Insert          ; $5180  -> $16CE
        da  Rubout          ; $5182  -> $161D
