;-*- Mode: Merlin -*-
;
; src/modules/11_modeline.s -- AMACS: describe-key, mode line and percentage display
; Address range $5184-$56FA. GENERATED by tools/disasm.py.
; `put' from src/amacs.s; symbols/labels are global across modules.
;
; ---- $5184-$51CB  code ----
;
; === Describe ===
        jsr GetStrArg    ; $5184
        beq L5194    ; $5187
        jsr ReadFunction    ; $5189
        beq L519E    ; $518C
L518E   jsr Beep    ; $518E
L5191   lda #$01    ; $5191
        rts    ; $5193
L5194   lda #$9B    ; $5194
        sta $0200,x    ; $5196
        jsr SI:CompleteMe    ; $5199
        bne L518E    ; $519C
L519E   jsr L5232    ; $519E
        lda #$B0    ; $51A1
        sta $5231    ; $51A3
L51A6   inc $5231    ; $51A6
        lda $5231    ; $51A9
        jsr GetHelpFile    ; $51AC
        bne L51BF    ; $51AF
        jsr L5255    ; $51B1
        bne L51A6    ; $51B4
        jsr L529A    ; $51B6
        jsr DSK:CloseFile    ; $51B9
        jmp L5191    ; $51BC
L51BF   jsr OpenTypeout    ; $51BF
        lda $5231    ; $51C2
        cmp #$B1    ; $51C5
        bne L521C    ; $51C7
        jsr PrintMessage    ; $51C9
; ---- $51CC-$51D7  data  msg: .The file " ----
        dfb $8D,$D4,$E8,$E5,$A0,$E6,$E9,$EC,$E5,$A0,$A2,$00    ; $51CC  .The file ".
; ---- $51D8-$51E5  code ----
L51D8   lda HelpHelpFile,y    ; $51D8
        beq L51E3    ; $51DB
        jsr CharOut    ; $51DD
        iny    ; $51E0
        bne L51D8    ; $51E1
L51E3   jsr PrintMessage    ; $51E3
; ---- $51E6-$5215  data  msg: " can't be opened.  Check "System Files ----
        dfb $A2,$A0,$E3,$E1,$EE,$A7,$F4,$A0,$E2,$E5,$A0,$EF,$F0,$E5,$EE,$E5    ; $51E6  " can't be opene
        dfb $E4,$AE,$A0,$A0,$C3,$E8,$E5,$E3,$EB,$A0,$A2,$D3,$F9,$F3,$F4,$E5    ; $51F6  d.  Check "Syste
        dfb $ED,$A0,$C6,$E9,$EC,$E5,$F3,$A0,$D0,$E1,$F4,$E8,$A2,$AE,$8D,$00    ; $5206  m Files Path"...
; ---- $5216-$54F1  code ----
L5216   jsr CloseTypeout    ; $5216
        lda #$01    ; $5219
        rts    ; $521B
L521C   ldy #$00    ; $521C
L521E   lda $0280,y    ; $521E
        beq L5229    ; $5221
        jsr CharOut    ; $5223
        iny    ; $5226
        bpl L521E    ; $5227
L5229   lda #$BF    ; $5229
        jsr CharOut    ; $522B
        jmp L5216    ; $522E
        brk    ; $5231
L5232   lda $00    ; $5232
        sta $5253    ; $5234
        lda $01    ; $5237
        sta $5254    ; $5239
        ldy #$00    ; $523C
L523E   lda ($00),y    ; $523E
        php    ; $5240
        ora #$80    ; $5241
        jsr UpperCon    ; $5243
        sta $0280,y    ; $5246
        iny    ; $5249
        plp    ; $524A
        bmi L523E    ; $524B
        lda #$00    ; $524D
        sta $0280,y    ; $524F
        rts    ; $5252
        brk    ; $5253
        brk    ; $5254
L5255   jsr DSK:ReadByte    ; $5255
        bne L5297    ; $5258
        ora #$80    ; $525A
        cmp #$9B    ; $525C
        bne L5255    ; $525E
        ldy #$00    ; $5260
        sty $0300    ; $5262
L5265   jsr DSK:ReadByte    ; $5265
        bne L5297    ; $5268
        ora #$80    ; $526A
        jsr UpperCon    ; $526C
        ldy $0300    ; $526F
        cmp $0280,y    ; $5272
        bne L5255    ; $5275
        iny    ; $5277
        sty $0300    ; $5278
        lda $0280,y    ; $527B
        bne L5265    ; $527E
        jsr DSK:ReadByte    ; $5280
        bne L5297    ; $5283
        ora #$80    ; $5285
        cmp #$9B    ; $5287
        bne L5255    ; $5289
        jsr DSK:ReadByte    ; $528B
        bne L5297    ; $528E
        ora #$80    ; $5290
        cmp #$9B    ; $5292
        bne L5255    ; $5294
        rts    ; $5296
L5297   lda #$FF    ; $5297
        rts    ; $5299
L529A   jsr OpenTypeout    ; $529A
        lda $5253    ; $529D
        sta $00    ; $52A0
        lda $5254    ; $52A2
        sta $01    ; $52A5
        jsr DCIStringOut    ; $52A7
        jsr DocRef    ; $52AA
        lda #$1E    ; $52AD
        sta TypeoutCH    ; $52AF
        sta CH    ; $52B2
        jsr DCIStringOut1    ; $52B4
        lda #$BA    ; $52B7
        jsr CharOut    ; $52B9
        jsr PrintReturn    ; $52BC
L52BF   jsr DSK:ReadByte    ; $52BF
        bne L52D8    ; $52C2
L52C4   ora #$80    ; $52C4
        cmp #$8D    ; $52C6
        bne L52DF    ; $52C8
        jsr CharOut    ; $52CA
        jsr DSK:ReadByte    ; $52CD
        bne L52D8    ; $52D0
        ora #$80    ; $52D2
        cmp #$9B    ; $52D4
        bne L52C4    ; $52D6
L52D8   jsr PrintDone    ; $52D8
        jsr CloseTypeout    ; $52DB
        rts    ; $52DE
L52DF   jsr CharOut    ; $52DF
        jmp L52BF    ; $52E2
;
; === LastPercnt ===
        brk    ; $52E5
;
; === ModeLineCV ===
        trb $7F    ; $52E6
;
; === ModeLineChar ===
        sty scrny    ; $52E8
        ldy CH    ; $52EA
        cpy #$50    ; $52EC
        bcs L52F5    ; $52EE
        sta $D400,y    ; $52F0
        inc CH    ; $52F3
L52F5   ldy scrny    ; $52F5
        rts    ; $52F7
;
; === DrawModeLine ===
        lda ModeLineCV    ; $52F8
        jsr vtab1    ; $52FB
        ldy #$00    ; $52FE
L5300   lda $D400,y    ; $5300
        and ModeLineInv    ; $5303
        bmi L5311    ; $5306
        cmp #$20    ; $5308
        bcc L5311    ; $530A
        lda $D400,y    ; $530C
        and #$7F    ; $530F
L5311   jsr StoreChar    ; $5311
        iny    ; $5314
        cpy WindowRgt    ; $5315
        bcc L5300    ; $5317
        jmp vtab    ; $5319
;
; === ModeLineMsg ===
        pla    ; $531C
        sta $00    ; $531D
        pla    ; $531F
        sta $01    ; $5320
        ldy #$00    ; $5322
L5324   inc $00    ; $5324
        bne L532A    ; $5326
        inc $01    ; $5328
L532A   lda ($00),y    ; $532A
        beq L5334    ; $532C
        jsr ModeLineChar    ; $532E
        jmp L5324    ; $5331
L5334   lda $01    ; $5334
        pha    ; $5336
        lda $00    ; $5337
        pha    ; $5339
        rts    ; $533A
;
; === InvModeLine ===
        lda ModeLineInv    ; $533B
        bpl L534B    ; $533E
        lda #$7F    ; $5340
        bit IIcMode?    ; $5342
        bpl L534D    ; $5345
        lda #$3F    ; $5347
        bpl L534D    ; $5349
L534B   lda #$FF    ; $534B
L534D   sta ModeLineInv    ; $534D
        jsr DrawModeLine    ; $5350
        lda #$01    ; $5353
        rts    ; $5355
;
; === InitModeLine ===
        jsr ClearModeLine    ; $5356
        jsr DrawModeLine    ; $5359
        rts    ; $535C
;
; === ClearModeLine ===
        lda #$A0    ; $535D
        ldy #$00    ; $535F
L5361   sta $D400,y    ; $5361
        iny    ; $5364
        cpy #$50    ; $5365
        bcc L5361    ; $5367
        rts    ; $5369
;
; === MajorNames ===
        sbc ($54)    ; $536A
        sbc $0154,x    ; $536C
        eor $07,x    ; $536F
        eor $0B,x    ; $5371
        eor $0C,x    ; $5373
        eor $F2,x    ; $5375
        dfb $54        ; $5377  (data/65C02-bit)
        sbc ($54)    ; $5378
        sbc ($54)    ; $537A
        brk    ; $537C
        brk    ; $537D
;
; === MakeModeLine ===
        jsr ClearModeLine    ; $537E
        lda #$00    ; $5381
        sta CH    ; $5383
        jsr ModeLineMsg    ; $5385
        cmp ($CD,x)    ; $5388
        cmp ($C3,x)    ; $538A
        dfb $D3        ; $538C  (data/65C02-bit)
        ldy #$A8    ; $538D
        brk    ; $538F
        ldy #$41    ; $5390
        lda (BuffData),y    ; $5392
        and #$01    ; $5394
        beq L53A1    ; $5396
        jsr ModeLineMsg    ; $5398
        dfb $DB        ; $539B  (data/65C02-bit)
        cmp ($CF)    ; $539C
        cmp: $00A0,x    ; $539E
L53A1   bit MacroDef    ; $53A1
        bpl L53B1    ; $53A4
        lda #$24    ; $53A6
        sta $00    ; $53A8
        lda #$55    ; $53AA
        sta $01    ; $53AC
        jsr TempToMode    ; $53AE
L53B1   ldy #$3F    ; $53B1
        lda (BuffData),y    ; $53B3
        asl    ; $53B5
        tax    ; $53B6
        lda MajorNames,x    ; $53B7
        sta $00    ; $53BA
        lda $536B,x    ; $53BC
        sta $01    ; $53BF
        jsr TempToMode    ; $53C1
        jsr PrintMinors    ; $53C4
        jsr ModeLineMsg    ; $53C7
        lda #$00    ; $53CA
        jsr ModeLineMsg    ; $53CC
        ldy #$A0    ; $53CF
        dfb $C2        ; $53D1  (data/65C02-bit)
        sbc $E6,x    ; $53D2
        inc $E5    ; $53D4
        sbc ($BA)    ; $53D6
        brk    ; $53D8
        ldy #$52    ; $53D9
L53DB   lda (BuffData),y    ; $53DB
        beq L53E5    ; $53DD
        jsr ModeLineChar    ; $53DF
        iny    ; $53E2
        bne L53DB    ; $53E3
L53E5   jsr ModeLineMsg    ; $53E5
        ldy #$A0    ; $53E8
        ldy #$C6    ; $53EA
        sbc #$EC    ; $53EC
        sbc $BA    ; $53EE
        brk    ; $53F0
        ldy #$00    ; $53F1
        lda (BuffData),y    ; $53F3
        beq L5429    ; $53F5
        lda #$A8    ; $53F7
        ldx CH    ; $53F9
        cpx #$43    ; $53FB
        bcs L5429    ; $53FD
        jsr ModeLineChar    ; $53FF
        dey    ; $5402
        sty $5423    ; $5403
        iny    ; $5406
L5407   lda (BuffData),y    ; $5407
        beq L5415    ; $5409
        cmp #$AF    ; $540B
        bne L5412    ; $540D
        sty $5423    ; $540F
L5412   iny    ; $5412
        bne L5407    ; $5413
L5415   ldy $5423    ; $5415
        iny    ; $5418
L5419   lda (BuffData),y    ; $5419
        beq L5424    ; $541B
        jsr ModeLineChar    ; $541D
        iny    ; $5420
        bne L5419    ; $5421
        brk    ; $5423
L5424   lda #$A9    ; $5424
        jsr ModeLineChar    ; $5426
L5429   lda #$43    ; $5429
        sta CH    ; $542B
        jsr ModeLineMsg    ; $542D
        ldy #$A0    ; $5430
        ldy #$AD    ; $5432
        lda $D4A0    ; $5434
        dfb $EF        ; $5437  (data/65C02-bit)
        beq $53DA    ; $5438
        lda: $00AD    ; $543A
        jsr ModeInfo    ; $543D
        rts    ; $5440
;
; === ModeInfo ===
        lda CV    ; $5441
        pha    ; $5443
        lda CH    ; $5444
        pha    ; $5446
        lda #$43    ; $5447
        sta CH    ; $5449
        lda #$02    ; $544B
        jsr BuffFlagOn?    ; $544D
        php    ; $5450
        lda #$AA    ; $5451
        plp    ; $5453
        beq L5458    ; $5454
        lda #$A0    ; $5456
L5458   pha    ; $5458
        lda #$A0    ; $5459
        jsr ModeLineChar    ; $545B
        pla    ; $545E
        jsr ModeLineChar    ; $545F
        lda #$A0    ; $5462
        jsr ModeLineChar    ; $5464
        lda CH    ; $5467
        clc    ; $5469
        adc #$03    ; $546A
        sta CH    ; $546C
        jsr BuffPercent    ; $546E
        tax    ; $5471
        sta LastPercnt    ; $5472
        beq L54AC    ; $5475
        cmp #$64    ; $5477
        bcs L54B6    ; $5479
        lda $2607    ; $547B
        pha    ; $547E
        lda CoutDef    ; $547F
        pha    ; $5482
        lda #$E8    ; $5483
        sta CoutDef    ; $5485
        lda #$52    ; $5488
        sta $2607    ; $548A
        jsr ZeroJustify    ; $548D
        cpx #$0A    ; $5490
        bcs L5499    ; $5492
        jsr PrintSpace    ; $5494
        lda #$00    ; $5497
L5499   jsr PrintDec    ; $5499
        lda #$A5    ; $549C
        jsr CharOut    ; $549E
        pla    ; $54A1
        sta CoutDef    ; $54A2
        pla    ; $54A5
        sta $2607    ; $54A6
        jmp L54BD    ; $54A9
L54AC   jsr ModeLineMsg    ; $54AC
        dfb $D4        ; $54AF  (data/65C02-bit)
        dfb $EF        ; $54B0  (data/65C02-bit)
        beq L54B3    ; $54B1
L54B3   jmp L54BD    ; $54B3
L54B6   jsr ModeLineMsg    ; $54B6
        dfb $C2        ; $54B9  (data/65C02-bit)
        dfb $EF        ; $54BA  (data/65C02-bit)
        dfb $F4        ; $54BB  (data/65C02-bit)
        brk    ; $54BC
L54BD   jsr DrawModeLine    ; $54BD
        lda #$3D    ; $54C0
        sta CH    ; $54C2
        lda #$15    ; $54C4
        sta CV    ; $54C6
        jsr vtab    ; $54C8
        lda $2607    ; $54CB
        pha    ; $54CE
        lda CoutDef    ; $54CF
        pha    ; $54D2
        lda #$14    ; $54D3
        sta CoutDef    ; $54D5
        lda #$26    ; $54D8
        sta $2607    ; $54DA
        jsr DSK:ModeTime    ; $54DD
        pla    ; $54E0
        sta CoutDef    ; $54E1
        pla    ; $54E4
        sta $2607    ; $54E5
        pla    ; $54E8
        sta CH    ; $54E9
        pla    ; $54EB
        sta CV    ; $54EC
        jsr vtab    ; $54EE
        rts    ; $54F1
; ---- $54F2-$5527  data  ModeNames (major+minor mode name strings) ----
        dfb $46,$75,$6E,$64,$61,$6D,$65,$6E,$74,$61,$EC,$54,$65,$78,$F4,$4D    ; $54F2  FundamentalTextM
        dfb $65,$72,$6C,$69,$EE,$4C,$69,$73,$F0,$C3,$50,$61,$73,$63,$61,$EC    ; $5502  erlinLispCPascal
        dfb $41,$74,$6F,$ED,$46,$69,$6C,$EC,$49,$6E,$64,$65,$6E,$F4,$43,$61    ; $5512  AtomFillIndentCa
        dfb $70,$F3,$44,$65,$66,$A0    ; $5522  psDef 
; ---- $5528-$5537  data  MinorNames (pointers into ModeNames) ----
        dfb $12,$55,$16,$55,$1A,$55,$00,$00,$20,$55,$00,$00,$00,$00,$00,$00    ; $5528  .U.U.U.. U......
; ---- $5538-$56FA  code ----
;
; === PrintMinors ===
        ldy #$40    ; $5538
        lda (BuffData),y    ; $553A
        sta $5563    ; $553C
        ldx #$FE    ; $553F
L5541   inx    ; $5541
        inx    ; $5542
        lda $5563    ; $5543
        beq L5562    ; $5546
        lsr $5563    ; $5548
        bcc L5541    ; $554B
        lda #$A0    ; $554D
        jsr ModeLineChar    ; $554F
        lda MinorNames,x    ; $5552
        sta $00    ; $5555
        lda $5529,x    ; $5557
        sta $01    ; $555A
        jsr TempToMode    ; $555C
        jmp L5541    ; $555F
L5562   rts    ; $5562
        brk    ; $5563
;
; === TempToMode ===
        ldy #$00    ; $5564
L5566   lda ($00),y    ; $5566
        pha    ; $5568
        ora #$80    ; $5569
        jsr ModeLineChar    ; $556B
        iny    ; $556E
        pla    ; $556F
        bpl L5566    ; $5570
        rts    ; $5572
        ds 4        ; $5573  4 bytes $00 fill
;
; === SI:Divide ===
        sta $5576    ; $5577
        stx $5575    ; $557A
        lda $00    ; $557D
        sta $5573    ; $557F
        lda $01    ; $5582
        sta $5574    ; $5584
        jsr L5591    ; $5587
        lda $5574    ; $558A
        ldx $5573    ; $558D
        rts    ; $5590
L5591   lda #$00    ; $5591
        sta $00    ; $5593
        sta $01    ; $5595
        ldx #$10    ; $5597
L5599   asl $5573    ; $5599
        rol $5574    ; $559C
        rol $00    ; $559F
        rol $01    ; $55A1
        lda $00    ; $55A3
        sec    ; $55A5
        sbc $5575    ; $55A6
        tay    ; $55A9
        lda $01    ; $55AA
        sbc $5576    ; $55AC
        bcc L55B8    ; $55AF
        inc $5573    ; $55B1
        sta $01    ; $55B4
        sty $00    ; $55B6
L55B8   dex    ; $55B8
        bne L5599    ; $55B9
        rts    ; $55BB
        brk    ; $55BC
        ora $4B32,y    ; $55BD
        stz $00    ; $55C0
        ds 13        ; $55C2  13 bytes $00 fill
;
; === BuffPercent ===
        lda TheBuffer    ; $55CF
        sec    ; $55D1
        sbc PhysBuffTop    ; $55D2
        sta P:Offset    ; $55D4
        lda $61    ; $55D7
        sbc $6F    ; $55D9
        sta $55CC    ; $55DB
        ldx SelectedBuff    ; $55DE
        jsr MySize    ; $55E1
        sta $55CE    ; $55E4
        stx P:Total    ; $55E7
;
; === Percent ===
        lda P:Total    ; $55EA
        sta $55C9    ; $55ED
        sta $5573    ; $55F0
        lda $55CE    ; $55F3
        sta $55CA    ; $55F6
        sta $5574    ; $55F9
        lsr    ; $55FC
        ror P:Total    ; $55FD
        sta $55C6    ; $5600
        ldx P:Total    ; $5603
        stx $55C5    ; $5606
        lsr    ; $5609
        ror P:Total    ; $560A
        sta $55C4    ; $560D
        ldx P:Total    ; $5610
        stx $55C3    ; $5613
        lda $55C5    ; $5616
        clc    ; $5619
        adc $55C3    ; $561A
        sta $55C7    ; $561D
        lda $55C6    ; $5620
        adc $55C4    ; $5623
        sta $55C8    ; $5626
        ldx #$00    ; $5629
        ldy #$00    ; $562B
        sty $56FA    ; $562D
        lda P:Offset    ; $5630
        ora $55CC    ; $5633
        bne L563B    ; $5636
        jmp L56F8    ; $5638
L563B   lda $55CC    ; $563B
        cmp $55C4,x    ; $563E
        bcc L565A    ; $5641
        bne L5655    ; $5643
        lda P:Offset    ; $5645
        cmp $55C3,x    ; $5648
        bcc L565A    ; $564B
        bne L5655    ; $564D
        lda $55BD,y    ; $564F
        jmp L56F8    ; $5652
L5655   inx    ; $5655
        inx    ; $5656
        iny    ; $5657
        bne L563B    ; $5658
L565A   lda $55C4    ; $565A
        lsr    ; $565D
        sta $01    ; $565E
        lda $55C3    ; $5660
        ror    ; $5663
        sta $00    ; $5664
        lda $55C1,x    ; $5666
        clc    ; $5669
        adc $00    ; $566A
        sta $00    ; $566C
        lda $55C2,x    ; $566E
        adc $01    ; $5671
        sta $01    ; $5673
        lda $55CC    ; $5675
        cmp $01    ; $5678
        bcc L56B0    ; $567A
        bne L568F    ; $567C
        lda P:Offset    ; $567E
        cmp $00    ; $5681
        bcc L56B0    ; $5683
        bne L568F    ; $5685
        lda $55BC,y    ; $5687
        clc    ; $568A
        adc #$0C    ; $568B
        bne L56F8    ; $568D
L568F   lda $55BD,y    ; $568F
        sta $56F9    ; $5692
        lda #$FF    ; $5695
        sta $56FA    ; $5697
        lda $55C3,x    ; $569A
        sec    ; $569D
        sbc P:Offset    ; $569E
        sta $5575    ; $56A1
        lda $55C4,x    ; $56A4
        sbc $55CC    ; $56A7
        sta $5576    ; $56AA
        jmp L56C9    ; $56AD
L56B0   lda $55BC,y    ; $56B0
        sta $56F9    ; $56B3
        lda P:Offset    ; $56B6
        sec    ; $56B9
        sbc $55C1,x    ; $56BA
        sta $5575    ; $56BD
        lda $55CC    ; $56C0
        sbc $55C2,x    ; $56C3
        sta $5576    ; $56C6
L56C9   jsr L5591    ; $56C9
        lda $5573    ; $56CC
        sta $5575    ; $56CF
        lda $5574    ; $56D2
        sta $5576    ; $56D5
        lda #$64    ; $56D8
        sta $5573    ; $56DA
        lda #$00    ; $56DD
        sta $5574    ; $56DF
        jsr L5591    ; $56E2
        lda $56F9    ; $56E5
        bit $56FA    ; $56E8
        bpl L56F4    ; $56EB
        sec    ; $56ED
        sbc $5573    ; $56EE
        jmp L56F8    ; $56F1
L56F4   clc    ; $56F4
        adc $5573    ; $56F5
L56F8   rts    ; $56F8
        brk    ; $56F9
        brk    ; $56FA
