;-*- Mode: Merlin -*-
;
; src/modules/13_completion.s -- AMACS: completion engine, doc/function reference
; Address range $5987-$5BC7. GENERATED by tools/disasm.py.
; `put' from src/amacs.s; symbols/labels are global across modules.
;
; ---- $5987-$598B  data  CompList / CompOffset / CompCount ----
        dfb $37,$9B,$00,$00,$00    ; $5987  7....
; ---- $598C-$5BC7  code ----
;
; === PrintCompDoc ===
        jsr DocRef    ; $598C
;
; === DCIStringOut   (also PrintComp) ===
        lda CH    ; $598F
;
; === DCIStringOut1 ===
        sta $5A10    ; $5991
        ldy #$FF    ; $5994
L5996   iny    ; $5996
        sty $5A0E    ; $5997
        lda CH    ; $599A
        cmp WindowLft    ; $599C
        bne L59A5    ; $599E
        lda $5A10    ; $59A0
        sta CH    ; $59A3
L59A5   sta $5A0F    ; $59A5
L59A8   lda ($00),y    ; $59A8
        bpl L59FD    ; $59AA
        cmp #$A0    ; $59AC
        beq L59E3    ; $59AE
        cmp #$8D    ; $59B0
        beq L59E3    ; $59B2
        jsr GetXCharLen    ; $59B4
        txa    ; $59B7
        clc    ; $59B8
        adc $5A0F    ; $59B9
        sta $5A0F    ; $59BC
        cmp WindowRgt    ; $59BF
        bcs L59C6    ; $59C1
        iny    ; $59C3
        bne L59A8    ; $59C4
L59C6   tya    ; $59C6
        pha    ; $59C7
        jsr PrintReturn    ; $59C8
        lda WindowRgt    ; $59CB
        pha    ; $59CD
        lda $5A10    ; $59CE
        sta WindowRgt    ; $59D1
        jsr ClearEOL    ; $59D3
        pla    ; $59D6
        sta WindowRgt    ; $59D7
        lda $5A10    ; $59D9
        sta CH    ; $59DC
        sta $5A0F    ; $59DE
        pla    ; $59E1
        tay    ; $59E2
L59E3   sty $5A11    ; $59E3
        ldy $5A0E    ; $59E6
L59E9   lda ($00),y    ; $59E9
        php    ; $59EB
        ora #$80    ; $59EC
        jsr CharOut    ; $59EE
        plp    ; $59F1
        bpl L5A0D    ; $59F2
        cpy $5A11    ; $59F4
        beq L5996    ; $59F7
        iny    ; $59F9
        jmp L59E9    ; $59FA
L59FD   ora #$80    ; $59FD
        jsr GetXCharLen    ; $59FF
        txa    ; $5A02
        clc    ; $5A03
        adc $5A0F    ; $5A04
        cmp WindowRgt    ; $5A07
        bcc L59E3    ; $5A09
        bcs L59C6    ; $5A0B
L5A0D   rts    ; $5A0D
        ds 4        ; $5A0E  4 bytes $00 fill
;
; === DocRef ===
        jsr DCIStringLen    ; $5A12
        iny    ; $5A15
        iny    ; $5A16
        iny    ; $5A17
        lda ($00),y    ; $5A18
        pha    ; $5A1A
        dey    ; $5A1B
        lda ($00),y    ; $5A1C
        sta $00    ; $5A1E
        pla    ; $5A20
        sta $01    ; $5A21
        rts    ; $5A23
;
; === DCIStringLen ===
        ldy #$00    ; $5A24
L5A26   lda ($00),y    ; $5A26
        php    ; $5A28
        iny    ; $5A29
        plp    ; $5A2A
        bmi L5A26    ; $5A2B
        rts    ; $5A2D
;
; === FunctionRef ===
        jsr DCIStringLen    ; $5A2E
        lda ($00),y    ; $5A31
        pha    ; $5A33
        iny    ; $5A34
        lda ($00),y    ; $5A35
        sta $01    ; $5A37
        pla    ; $5A39
        sta $00    ; $5A3A
        rts    ; $5A3C
;
; === PopCompPoint ===
        ldx CompCount    ; $5A3D
        beq L5A53    ; $5A40
        dex    ; $5A42
        stx CompCount    ; $5A43
        lda rm_DataBuffer,x    ; $5A46
        sta $00    ; $5A49
        lda $AA00,x    ; $5A4B
        sta $01    ; $5A4E
        lda #$00    ; $5A50
        rts    ; $5A52
L5A53   lda #$FF    ; $5A53
        rts    ; $5A55
;
; === PushCompPoint ===
        ldx CompCount    ; $5A56
        lda $00    ; $5A59
        sta rm_DataBuffer,x    ; $5A5B
        lda $01    ; $5A5E
        sta $AA00,x    ; $5A60
        inx    ; $5A63
        stx CompCount    ; $5A64
        rts    ; $5A67
;
; === SkipEnt ===
        jsr DCIStringLen    ; $5A68
        tya    ; $5A6B
        clc    ; $5A6C
        adc #$04    ; $5A6D
        adc $00    ; $5A6F
        sta $00    ; $5A71
        bcc L5A77    ; $5A73
        inc $01    ; $5A75
L5A77   rts    ; $5A77
;
; === CompareEnt ===
        ldy #$00    ; $5A78
        ldx $598A    ; $5A7A
L5A7D   lda ($00),y    ; $5A7D
        sta $E3    ; $5A7F
        ora #$80    ; $5A81
        jsr UpperCon    ; $5A83
        sta $E2    ; $5A86
        lda $0200,x    ; $5A88
        cmp #$9B    ; $5A8B
        beq L5AA3    ; $5A8D
        jsr UpperCon    ; $5A8F
        cmp $E2    ; $5A92
        bne L5AAD    ; $5A94
        iny    ; $5A96
        inx    ; $5A97
        lda $E3    ; $5A98
        bmi L5A7D    ; $5A9A
        lda $0200,x    ; $5A9C
        cmp #$9B    ; $5A9F
        bne L5AAD    ; $5AA1
L5AA3   cpy HighMatch    ; $5AA3
        bcc L5AAB    ; $5AA6
        sty HighMatch    ; $5AA8
L5AAB   lda #$00    ; $5AAB
L5AAD   rts    ; $5AAD
L5AAE   ldy #$00    ; $5AAE
L5AB0   lda ($00),y    ; $5AB0
        sta $E3    ; $5AB2
        ora #$80    ; $5AB4
        jsr UpperCon    ; $5AB6
        sta $E2    ; $5AB9
        lda ($02),y    ; $5ABB
        sta $E4    ; $5ABD
        ora #$80    ; $5ABF
        jsr UpperCon    ; $5AC1
        cmp $E2    ; $5AC4
        bne L5AD1    ; $5AC6
        lda $E3    ; $5AC8
        ora $E4    ; $5ACA
        bpl L5AD1    ; $5ACC
        iny    ; $5ACE
        bne L5AB0    ; $5ACF
L5AD1   rts    ; $5AD1
        brk    ; $5AD2
;
; === HighMatch ===
        brk    ; $5AD3
;
; === GetCompLink ===
        ldy #$00    ; $5AD4
        lda ($00),y    ; $5AD6
        beq L5AE4    ; $5AD8
        cmp #$FF    ; $5ADA
        beq L5AE4    ; $5ADC
        jsr SkipEnt    ; $5ADE
        jmp GetCompLink    ; $5AE1
L5AE4   rts    ; $5AE4
;
; === SI:CompleteMe ===
        lda #$9B    ; $5AE5
        bne L5AEB    ; $5AE7
;
; === SI:CompleteSp ===
        lda #$A0    ; $5AE9
L5AEB   sta $5AD2    ; $5AEB
        lda CompList    ; $5AEE
        sta $00    ; $5AF1
        lda $5988    ; $5AF3
        sta $01    ; $5AF6
        lda #$00    ; $5AF8
        sta CompCount    ; $5AFA
        sta $5BC6    ; $5AFD
        sta HighMatch    ; $5B00
        ldy CompOffset    ; $5B03
        sty $598A    ; $5B06
        sta CompOffset    ; $5B09
L5B0C   ldy #$00    ; $5B0C
        lda ($00),y    ; $5B0E
        beq L5B38    ; $5B10
        cmp #$FF    ; $5B12
        bne L5B25    ; $5B14
        iny    ; $5B16
        lda ($00),y    ; $5B17
        pha    ; $5B19
        iny    ; $5B1A
        lda ($00),y    ; $5B1B
        sta $01    ; $5B1D
        pla    ; $5B1F
        sta $00    ; $5B20
        jmp L5B0C    ; $5B22
L5B25   jsr CompareEnt    ; $5B25
        bne L5B32    ; $5B28
        cpy HighMatch    ; $5B2A
        bcc L5B32    ; $5B2D
        jsr PushCompPoint    ; $5B2F
L5B32   jsr SkipEnt    ; $5B32
        jmp L5B0C    ; $5B35
L5B38   lda CompCount    ; $5B38
        beq L5B44    ; $5B3B
        cmp #$01    ; $5B3D
        beq L5B4A    ; $5B3F
        jmp L5B65    ; $5B41
L5B44   ldx CharIndex    ; $5B44
        lda #$FF    ; $5B47
        rts    ; $5B49
L5B4A   jsr PopCompPoint    ; $5B4A
        jsr PushCompPoint    ; $5B4D
        ldy #$00    ; $5B50
        ldx $598A    ; $5B52
L5B55   lda ($00),y    ; $5B55
        php    ; $5B57
        ora #$80    ; $5B58
        sta $0200,x    ; $5B5A
        iny    ; $5B5D
        inx    ; $5B5E
        plp    ; $5B5F
        bmi L5B55    ; $5B60
        lda #$00    ; $5B62
        rts    ; $5B64
L5B65   lda $5AD2    ; $5B65
        cmp #$9B    ; $5B68
        beq L5B44    ; $5B6A
        ldy #$FF    ; $5B6C
        sty $5BC5    ; $5B6E
        lda CompCount    ; $5B71
        sta $5BC7    ; $5B74
        jsr PopCompPoint    ; $5B77
L5B7A   lda $00    ; $5B7A
        sta $02    ; $5B7C
        lda $01    ; $5B7E
        sta $03    ; $5B80
        jsr PopCompPoint    ; $5B82
        bne L5B95    ; $5B85
        jsr L5AAE    ; $5B87
        cpy $5BC5    ; $5B8A
        bcs L5B7A    ; $5B8D
        sty $5BC5    ; $5B8F
        jmp L5B7A    ; $5B92
L5B95   lda $5BC7    ; $5B95
        sta CompCount    ; $5B98
        ldx $598A    ; $5B9B
        ldy #$00    ; $5B9E
L5BA0   lda ($02),y    ; $5BA0
        cpy $5BC5    ; $5BA2
        bcs L5BBF    ; $5BA5
        pha    ; $5BA7
        lda $0200,x    ; $5BA8
        cmp #$9B    ; $5BAB
        bne L5BB4    ; $5BAD
        lda #$FF    ; $5BAF
        sta $5BC6    ; $5BB1
L5BB4   pla    ; $5BB4
        ora #$80    ; $5BB5
        sta $0200,x    ; $5BB7
        iny    ; $5BBA
        inx    ; $5BBB
        jmp L5BA0    ; $5BBC
L5BBF   lda $5BC6    ; $5BBF
        eor #$FF    ; $5BC2
        rts    ; $5BC4
        brk    ; $5BC5
        brk    ; $5BC6
        brk    ; $5BC7
