;-*- Mode: Merlin -*-
;
; src/modules/15_filer.s -- AMACS: visit/save/read files, ProDOS MLI, paths, dates, types, directory
; Address range $674E-$77BE. GENERATED by tools/disasm.py.
; `put' from src/amacs.s; symbols/labels are global across modules.
;
; ---- $674E-$6755  data  AutoFileExt / ShowExtension vars ----
        dfb $00,$00,$00,$00,$00,$00,$00,$00    ; $674E  ........
; ---- $6756-$67A0  code ----
;
; === VisitFile ===
        lda #$00    ; $6756
;
; === SI:VisFile ===
        bne L6778    ; $6758
        jsr MaybeSave    ; $675A
        bne L678E    ; $675D
        dec ShowExtension    ; $675F
        lda #$D7    ; $6762
        sta $00    ; $6764
        lda #$67    ; $6766
        sta $01    ; $6768
        lda #$00    ; $676A
        jsr ReadFilename    ; $676C
        bne L678E    ; $676F
        jsr Default    ; $6771
        cmp #$8D    ; $6774
        beq L677B    ; $6776
L6778   jsr FixPath    ; $6778
L677B   jsr DSK:OpenFile    ; $677B
        bne L67E3    ; $677E
        lda #$01    ; $6780
        jsr ClrBuffFlag    ; $6782
        jsr L6875    ; $6785
        jsr ClrModified    ; $6788
        jmp L6796    ; $678B
L678E   jsr Beep    ; $678E
        lda #$87    ; $6791
        jsr CharOut    ; $6793
L6796   bit $6755    ; $6796
        bpl L67CE    ; $6799
        jsr NewEchoArea    ; $679B
        jsr PrintMessage    ; $679E
; ---- $67A1-$67C2  data  msg:  The entire file can't be loaded! ----
        dfb $A0,$D4,$E8,$E5,$A0,$E5,$EE,$F4,$E9,$F2,$E5,$A0,$E6,$E9,$EC,$E5    ; $67A1   The entire file
        dfb $A0,$E3,$E1,$EE,$A7,$F4,$A0,$E2,$E5,$A0,$EC,$EF,$E1,$E4,$E5,$E4    ; $67B1   can't be loaded
        dfb $A1,$00    ; $67C1  !.
; ---- $67C3-$67EB  code ----
        jsr CloseEchoArea    ; $67C3
        lda #$01    ; $67C6
        jsr SetBuffFlag    ; $67C8
        jsr Beep    ; $67CB
L67CE   jsr DisplayPage    ; $67CE
        jsr MakeModeLine    ; $67D1
        lda #$01    ; $67D4
        rts    ; $67D6
        dec $E9,x    ; $67D7
        dfb $F3        ; $67D9  (data/65C02-bit)
        sbc #$F4    ; $67DA
        ldy #$C6    ; $67DC
        sbc #$EC    ; $67DE
        sbc $84    ; $67E0
        dec    ; $67E2
L67E3   jsr SetFileDef    ; $67E3
        jsr NewEchoArea    ; $67E6
        jsr PrintMessage    ; $67E9
; ---- $67EC-$67F6  data  msg: (New File) ----
        dfb $A8,$CE,$E5,$F7,$A0,$C6,$E9,$EC,$E5,$A9,$00    ; $67EC  (New File).
; ---- $67F7-$682A  code ----
        jsr CloseEchoArea    ; $67F7
        jsr MakeModeLine    ; $67FA
        lda BuffTop    ; $67FD
        sta TheBuffer    ; $67FF
        sta GapTop    ; $6801
        lda $67    ; $6803
        sta $61    ; $6805
        sta $6B    ; $6807
        lda BuffBot    ; $6809
        sec    ; $680B
        sbc #$01    ; $680C
        sta GapBot    ; $680E
        lda $69    ; $6810
        sbc #$00    ; $6812
        sta $6D    ; $6814
        jsr CloseEchoArea    ; $6816
        jsr ClrModified    ; $6819
        lda #$06    ; $681C
        rts    ; $681E
;
; === MaybeSave ===
        bit Modified?    ; $681F
        bmi L6825    ; $6822
        rts    ; $6824
L6825   jsr NewEchoArea    ; $6825
        jsr PrintMessage    ; $6828
; ---- $682B-$6832  data  msg: Buffer ----
        dfb $C2,$F5,$E6,$E6,$E5,$F2,$A0,$00    ; $682B  Buffer .
; ---- $6833-$6838  code ----
        jsr PrBuffName    ; $6833
        jsr PrintMessage    ; $6836
; ---- $6839-$685B  data  msg:  has been modified.  Save it first ----
        dfb $A0,$E8,$E1,$F3,$A0,$E2,$E5,$E5,$EE,$A0,$ED,$EF,$E4,$E9,$E6,$E9    ; $6839   has been modifi
        dfb $E5,$E4,$AE,$A0,$A0,$D3,$E1,$F6,$E5,$A0,$E9,$F4,$A0,$E6,$E9,$F2    ; $6849  ed.  Save it fir
        dfb $F3,$F4,$00    ; $6859  st.
; ---- $685C-$687A  code ----
        jsr GetYOrNp    ; $685C
        php    ; $685F
        pha    ; $6860
        jsr CloseEchoArea    ; $6861
        pla    ; $6864
        plp    ; $6865
        beq L6872    ; $6866
        cmp #$87    ; $6868
        beq L686F    ; $686A
        lda #$00    ; $686C
        rts    ; $686E
L686F   lda #$FF    ; $686F
        rts    ; $6871
L6872   jmp IN:SaveFile    ; $6872
L6875   jsr NewEchoArea    ; $6875
        jsr PrintMessage    ; $6878
; ---- $687B-$6883  data  msg: Reading ----
        dfb $D2,$E5,$E1,$E4,$E9,$EE,$E7,$A0,$00    ; $687B  Reading .
; ---- $6884-$6889  code ----
        jsr PrintPath    ; $6884
        jsr PrintMessage    ; $6887
; ---- $688A-$688D  data  msg: ; ( ----
        dfb $BB,$A0,$A8,$00    ; $688A  ; (.
; ---- $688E-$689C  code ----
        sty PD:Justify    ; $688E
        lda $7127    ; $6891
        ldx GblLength    ; $6894
        jsr PrintDec    ; $6897
        jsr PrintMessage    ; $689A
; ---- $689D-$68A9  data  msg:  characters) ----
        dfb $A0,$E3,$E8,$E1,$F2,$E1,$E3,$F4,$E5,$F2,$F3,$A9,$00    ; $689D   characters).
; ---- $68AA-$696D  code ----
        jsr CloseEchoArea    ; $68AA
        jsr SetFileDef    ; $68AD
        jsr ZapBuff    ; $68B0
        jsr $6B27    ; $68B3
        sta $6755    ; $68B6
        jsr SetGap    ; $68B9
        jsr ParseMode    ; $68BC
        rts    ; $68BF
;
; === Default ===
        lda $0200    ; $68C0
        cmp #$8D    ; $68C3
        bne L68DB    ; $68C5
        ldy #$00    ; $68C7
        ldx #$00    ; $68C9
L68CB   lda (BuffData),y    ; $68CB
        beq L68D6    ; $68CD
        sta $0200,x    ; $68CF
        iny    ; $68D2
        inx    ; $68D3
        bne L68CB    ; $68D4
L68D6   lda #$8D    ; $68D6
        sta $0200,x    ; $68D8
L68DB   rts    ; $68DB
        lda #$8D    ; $68DC
        sta $0200,x    ; $68DE
        jmp DSK:ListFiles    ; $68E1
;
; === SetFileDef ===
        lda AutoFileExt    ; $68E4
        pha    ; $68E7
        lda #$00    ; $68E8
        sta AutoFileExt    ; $68EA
        jsr FixPath    ; $68ED
        pla    ; $68F0
        sta AutoFileExt    ; $68F1
        ldx #$00    ; $68F4
L68F6   lda $0200,x    ; $68F6
        beq L6904    ; $68F9
        cmp #$8D    ; $68FB
        beq L6904    ; $68FD
        inx    ; $68FF
        cpx #$3F    ; $6900
        bcc L68F6    ; $6902
L6904   lda #$00    ; $6904
        sta $0200,x    ; $6906
        tax    ; $6909
        ldy #$00    ; $690A
L690C   lda $0200,x    ; $690C
        sta (BuffData),y    ; $690F
        beq L6919    ; $6911
        iny    ; $6913
        inx    ; $6914
        cpx #$3F    ; $6915
        bcc L690C    ; $6917
L6919   lda #$00    ; $6919
        sta (BuffData),y    ; $691B
        rts    ; $691D
L691E   lda #$FF    ; $691E
        bmi L6924    ; $6920
;
; === IN:SaveFile ===
        lda #$00    ; $6922
L6924   php    ; $6924
        ldy #$41    ; $6925
        lda (BuffData),y    ; $6927
        and #$01    ; $6929
        beq L6931    ; $692B
        plp    ; $692D
        jmp L698C    ; $692E
L6931   plp    ; $6931
        bmi L6951    ; $6932
        ldy #$00    ; $6934
        lda (BuffData),y    ; $6936
        beq L6951    ; $6938
        ldx #$00    ; $693A
L693C   lda (BuffData),y    ; $693C
        beq L6949    ; $693E
        sta $0200,x    ; $6940
        iny    ; $6943
        inx    ; $6944
        cpx #$3F    ; $6945
        bcc L693C    ; $6947
L6949   lda #$8D    ; $6949
        sta $0200,x    ; $694B
        jmp L6960    ; $694E
L6951   lda #$B4    ; $6951
        sta $00    ; $6953
        lda #$69    ; $6955
        sta $01    ; $6957
        lda #$FF    ; $6959
        jsr ReadFilename    ; $695B
        bne L6986    ; $695E
L6960   jsr DSK:SaveFile    ; $6960
        bne L698C    ; $6963
        jsr SetFileDef    ; $6965
        jsr NewEchoArea    ; $6968
        jsr PrintMessage    ; $696B
; ---- $696E-$6976  data  msg: Written: ----
        dfb $D7,$F2,$E9,$F4,$F4,$E5,$EE,$BA,$00    ; $696E  Written:.
; ---- $6977-$6991  code ----
        jsr PrFileName    ; $6977
        jsr ClrModified    ; $697A
        jsr MakeModeLine    ; $697D
        jsr CloseEchoArea    ; $6980
        lda #$00    ; $6983
        rts    ; $6985
L6986   jsr CloseEchoArea    ; $6986
        lda #$FF    ; $6989
        rts    ; $698B
L698C   jsr NewEchoArea    ; $698C
        jsr PrintMessage    ; $698F
; ---- $6992-$69AA  data  msg: Failed! During write of ----
        dfb $C6,$E1,$E9,$EC,$E5,$E4,$A1,$A0,$C4,$F5,$F2,$E9,$EE,$E7,$A0,$F7    ; $6992  Failed! During w
        dfb $F2,$E9,$F4,$E5,$A0,$EF,$E6,$A0,$00    ; $69A2  rite of .
; ---- $69AB-$6A0F  code ----
        jsr PrFileName    ; $69AB
        jsr Beep    ; $69AE
        jmp L6986    ; $69B1
        dfb $D3        ; $69B4  (data/65C02-bit)
        sbc ($F6,x)    ; $69B5
        sbc $A0    ; $69B7
        dfb $E2        ; $69B9  (data/65C02-bit)
        sbc $E6,x    ; $69BA
        inc $E5    ; $69BC
        sbc ($A0)    ; $69BE
        dfb $82        ; $69C0  (data/65C02-bit)
        ldy #$E9    ; $69C1
        inc $E6A0    ; $69C3
        sbc #$EC    ; $69C6
        sbc $3A    ; $69C8
;
; === WriteFile ===
        jsr L691E    ; $69CA
        lda #$01    ; $69CD
        rts    ; $69CF
;
; === ReadFilename ===
        sta $6A7C    ; $69D0
        lda $00    ; $69D3
        sta $6A7A    ; $69D5
        lda $01    ; $69D8
        sta $6A7B    ; $69DA
        jsr GetStrArg    ; $69DD
        bne L69E8    ; $69E0
        lda #$00    ; $69E2
        sta ShowExtension    ; $69E4
        rts    ; $69E7
L69E8   jsr NewEchoArea    ; $69E8
        bit ShowExtension    ; $69EB
        bpl L6A13    ; $69EE
        inc ShowExtension    ; $69F0
        jsr AnyArgument?    ; $69F3
        beq L6A13    ; $69F6
        ldy AutoFileExt    ; $69F8
        beq L6A13    ; $69FB
        jsr PrintMessage    ; $69FD
        dfb $DB        ; $6A00  (data/65C02-bit)
        brk    ; $6A01
L6A02   lda AutoFileExt,y    ; $6A02
        beq L6A0D    ; $6A05
        jsr CharOut    ; $6A07
        iny    ; $6A0A
        bne L6A02    ; $6A0B
L6A0D   jsr PrintMessage    ; $6A0D
; ---- $6A10-$6A12  data  msg: ] ----
        dfb $DD,$A0,$00    ; $6A10  ] .
; ---- $6A13-$6A8D  code ----
L6A13   lda $6A7A    ; $6A13
        sta $00    ; $6A16
        lda $6A7B    ; $6A18
        sta $01    ; $6A1B
L6A1D   ldy #$00    ; $6A1D
        lda ($00),y    ; $6A1F
        php    ; $6A21
        ora #$80    ; $6A22
        cmp #$82    ; $6A24
        bne L6A2E    ; $6A26
        jsr PrBuffName    ; $6A28
        jmp L6A48    ; $6A2B
L6A2E   cmp #$84    ; $6A2E
        bne L6A45    ; $6A30
        ldy #$00    ; $6A32
        lda (BuffData),y    ; $6A34
        beq L6A48    ; $6A36
        jsr PrintSpace    ; $6A38
        lda #$A8    ; $6A3B
        jsr CharOut    ; $6A3D
        jsr PrFileName    ; $6A40
        lda #$A9    ; $6A43
L6A45   jsr CharOut    ; $6A45
L6A48   inc $00    ; $6A48
        bne L6A4E    ; $6A4A
        inc $01    ; $6A4C
L6A4E   plp    ; $6A4E
        bmi L6A1D    ; $6A4F
        lda #$DC    ; $6A51
        sta ReadLineHelp    ; $6A53
        lda #$68    ; $6A56
        sta $3B21    ; $6A58
        dec FileRead    ; $6A5B
        jsr ReadLine    ; $6A5E
        php    ; $6A61
        txa    ; $6A62
        pha    ; $6A63
        jsr CloseEchoArea    ; $6A64
        pla    ; $6A67
        tax    ; $6A68
        plp    ; $6A69
        bne L6A76    ; $6A6A
        lda $0200    ; $6A6C
        cmp #$8D    ; $6A6F
        bne L6A77    ; $6A71
        lda $6A7C    ; $6A73
L6A76   rts    ; $6A76
L6A77   lda #$00    ; $6A77
        rts    ; $6A79
        brk    ; $6A7A
        brk    ; $6A7B
        brk    ; $6A7C
;
; === SaveFile ===
        bit Modified?    ; $6A7D
        bpl L6A88    ; $6A80
L6A82   jsr IN:SaveFile    ; $6A82
        lda #$01    ; $6A85
        rts    ; $6A87
L6A88   jsr NewEchoArea    ; $6A88
        jsr PrintMessage    ; $6A8B
; ---- $6A8E-$6A9D  data  msg: No changes need ----
        dfb $CE,$EF,$A0,$E3,$E8,$E1,$EE,$E7,$E5,$F3,$A0,$EE,$E5,$E5,$E4,$00    ; $6A8E  No changes need.
; ---- $6A9E-$6AA6  code ----
        jsr AnyArgument?    ; $6A9E
        php    ; $6AA1
        bne L6AAA    ; $6AA2
        jsr PrintMessage    ; $6AA4
; ---- $6AA7-$6AA9  data  msg: ed ----
        dfb $E5,$E4,$00    ; $6AA7  ed.
; ---- $6AAA-$6AAC  code ----
L6AAA   jsr PrintMessage    ; $6AAA
; ---- $6AAD-$6ABC  data  msg:  to be written. ----
        dfb $A0,$F4,$EF,$A0,$E2,$E5,$A0,$F7,$F2,$E9,$F4,$F4,$E5,$EE,$AE,$00    ; $6AAD   to be written..
; ---- $6ABD-$6B07  code ----
        jsr CloseEchoArea    ; $6ABD
        plp    ; $6AC0
        beq L6A82    ; $6AC1
        lda #$01    ; $6AC3
        rts    ; $6AC5
;
; === PrBuffName ===
        ldx SelectedBuff    ; $6AC6
        jmp PBuffName    ; $6AC9
;
; === PrFileName ===
        ldx SelectedBuff    ; $6ACC
        jmp PBuffFile    ; $6ACF
;
; === InsertFile ===
        lda #$F6    ; $6AD2
        sta $00    ; $6AD4
        lda #$6A    ; $6AD6
        sta $01    ; $6AD8
        lda #$FF    ; $6ADA
        jsr ReadFilename    ; $6ADC
        bne L6AEE    ; $6ADF
        jsr DSK:OpenFile    ; $6AE1
        bne L6B02    ; $6AE4
        jsr $6B27    ; $6AE6
        bne L6B02    ; $6AE9
        lda #$06    ; $6AEB
        rts    ; $6AED
L6AEE   lda #$87    ; $6AEE
        jsr EchoOutput    ; $6AF0
        jmp BeepFindPoint    ; $6AF3
        cmp #$EE    ; $6AF6
        dfb $F3        ; $6AF8  (data/65C02-bit)
        sbc $F2    ; $6AF9
        dfb $F4        ; $6AFB  (data/65C02-bit)
        ldy #$C6    ; $6AFC
        sbc #$EC    ; $6AFE
        sbc $3A    ; $6B00
L6B02   jsr NewEchoArea    ; $6B02
        jsr PrintMessage    ; $6B05
; ---- $6B08-$6B1C  data  msg: Error reading file! ----
        dfb $C5,$F2,$F2,$EF,$F2,$A0,$F2,$E5,$E1,$E4,$E9,$EE,$E7,$A0,$E6,$E9    ; $6B08  Error reading fi
        dfb $EC,$E5,$A1,$A0,$00    ; $6B18  le! .
; ---- $6B1D-$6CC4  code ----
        jsr Beep    ; $6B1D
        jsr CloseEchoArea    ; $6B20
        jmp L6AEE    ; $6B23
;
; === EORValue ===
        bra $6ACD    ; $6B26
        adc ($48,x)    ; $6B28
        lda TheBuffer    ; $6B2A
        pha    ; $6B2C
        jsr PrepRead    ; $6B2D
L6B30   jsr DSK:ReadByte    ; $6B30
        bne L6B41    ; $6B33
        eor EORValue    ; $6B35
        jsr BuffInsert    ; $6B38
        beq L6B30    ; $6B3B
        lda #$FF    ; $6B3D
        bmi L6B43    ; $6B3F
L6B41   lda #$00    ; $6B41
L6B43   tax    ; $6B43
        pla    ; $6B44
        sta TheBuffer    ; $6B45
        pla    ; $6B47
        sta $61    ; $6B48
        txa    ; $6B4A
        pha    ; $6B4B
        jsr SetGap    ; $6B4C
        jsr DSK:CloseFile    ; $6B4F
        pla    ; $6B52
        rts    ; $6B53
;
; === FileLister ===
        lda #$00    ; $6B54
        beq L6B5A    ; $6B56
;
; === DirLister ===
        lda #$FF    ; $6B58
L6B5A   sta $6B92    ; $6B5A
        jsr GetStrArg    ; $6B5D
        beq L6B7C    ; $6B60
        jsr AnyArgument?    ; $6B62
        bne L6B79    ; $6B65
        lda #$93    ; $6B67
        sta $00    ; $6B69
        lda #$6B    ; $6B6B
        sta $01    ; $6B6D
        lda #$00    ; $6B6F
        jsr ReadFilename    ; $6B71
        beq L6B7C    ; $6B74
        jmp BeepFindPoint    ; $6B76
L6B79   jsr SelfPath    ; $6B79
L6B7C   lda #$8D    ; $6B7C
        sta $0200,x    ; $6B7E
        bit $6B92    ; $6B81
        bmi L6B8C    ; $6B84
        jsr DSK:ListFiles    ; $6B86
        jmp L6B8F    ; $6B89
L6B8C   jsr DSK:ListDir    ; $6B8C
L6B8F   lda #$00    ; $6B8F
        rts    ; $6B91
        brk    ; $6B92
        cpy $E9    ; $6B93
        sbc ($E5)    ; $6B95
        dfb $E3        ; $6B97  (data/65C02-bit)
        dfb $F4        ; $6B98  (data/65C02-bit)
        dfb $EF        ; $6B99  (data/65C02-bit)
        sbc ($F9)    ; $6B9A
        dec    ; $6B9C
;
; === SelfPath ===
        ldx #$00    ; $6B9D
        ldy #$00    ; $6B9F
L6BA1   lda (BuffData),y    ; $6BA1
        sta $0200,x    ; $6BA3
        beq BackPath    ; $6BA6
        iny    ; $6BA8
        inx    ; $6BA9
        bne L6BA1    ; $6BAA
;
; === BackPath ===
        dex    ; $6BAC
        bmi L6BB6    ; $6BAD
        lda $0200,x    ; $6BAF
        cmp #$AF    ; $6BB2
        bne BackPath    ; $6BB4
L6BB6   inx    ; $6BB6
        rts    ; $6BB7
;
; === BeepFindPoint ===
        jsr Beep    ; $6BB8
        lda #$01    ; $6BBB
        rts    ; $6BBD
;
; === FindFile ===
        dec ShowExtension    ; $6BBE
        lda #$D3    ; $6BC1
        sta $00    ; $6BC3
        lda #$6B    ; $6BC5
        sta $01    ; $6BC7
        lda #$FF    ; $6BC9
        jsr ReadFilename    ; $6BCB
        beq L6BDD    ; $6BCE
L6BD0   jmp BeepFindPoint    ; $6BD0
        dec $E9    ; $6BD3
        inc $A0E4    ; $6BD5
        dec $E9    ; $6BD8
        cpx $3AE5    ; $6BDA
L6BDD   jsr FixPath    ; $6BDD
        jsr FindBuffFile    ; $6BE0
        bne L6BE8    ; $6BE3
        jmp SI:OpenBuff    ; $6BE5
L6BE8   ldx #$00    ; $6BE8
        dex    ; $6BEA
        stx $6C25    ; $6BEB
        inx    ; $6BEE
L6BEF   lda $0200,x    ; $6BEF
        cmp #$AF    ; $6BF2
        bne L6BF9    ; $6BF4
        stx $6C25    ; $6BF6
L6BF9   sta $0280,x    ; $6BF9
        inx    ; $6BFC
        cmp #$8D    ; $6BFD
        bne L6BEF    ; $6BFF
        ldy #$00    ; $6C01
        ldx $6C25    ; $6C03
        inx    ; $6C06
L6C07   lda $0280,x    ; $6C07
        sta $0200,y    ; $6C0A
        iny    ; $6C0D
        inx    ; $6C0E
        cmp #$8D    ; $6C0F
        bne L6C07    ; $6C11
        lda #$00    ; $6C13
        sta $01FF,y    ; $6C15
        jsr Deselect    ; $6C18
        jsr CreateBuffer    ; $6C1B
        cmp #$06    ; $6C1E
        beq L6C26    ; $6C20
        jmp L6BD0    ; $6C22
        brk    ; $6C25
L6C26   ldx #$00    ; $6C26
L6C28   lda $0280,x    ; $6C28
        sta $0200,x    ; $6C2B
        inx    ; $6C2E
        cmp #$8D    ; $6C2F
        bne L6C28    ; $6C31
        lda #$FF    ; $6C33
        jmp SI:VisFile    ; $6C35
;
; === FixPath ===
        ldx #$00    ; $6C38
        lda $0200    ; $6C3A
        cmp #$AF    ; $6C3D
        beq L6C4F    ; $6C3F
L6C41   lda PrefixName,x    ; $6C41
        ora #$80    ; $6C44
        sta $0280,x    ; $6C46
        inx    ; $6C49
        cpx ThePrefix    ; $6C4A
        bcc L6C41    ; $6C4D
L6C4F   ldy #$00    ; $6C4F
L6C51   lda $0200,y    ; $6C51
        sta $0280,x    ; $6C54
        iny    ; $6C57
        inx    ; $6C58
        cmp #$8D    ; $6C59
        bne L6C51    ; $6C5B
        dex    ; $6C5D
        stx $6CB5    ; $6C5E
L6C61   lda $0280,x    ; $6C61
        sta $0200,x    ; $6C64
        dex    ; $6C67
        bpl L6C61    ; $6C68
        ldy #$00    ; $6C6A
        lda AutoFileExt    ; $6C6C
        beq L6CB4    ; $6C6F
        jsr AnyArgument?    ; $6C71
        beq L6CB4    ; $6C74
L6C76   lda AutoFileExt,y    ; $6C76
        beq L6C7E    ; $6C79
        iny    ; $6C7B
        bne L6C76    ; $6C7C
L6C7E   dey    ; $6C7E
        ldx $6CB5    ; $6C7F
        dex    ; $6C82
L6C83   lda $0200,x    ; $6C83
        jsr UpperCon    ; $6C86
        sta $6CB6    ; $6C89
        lda AutoFileExt,y    ; $6C8C
        jsr UpperCon    ; $6C8F
        cmp $6CB6    ; $6C92
        bne L6C9E    ; $6C95
        dex    ; $6C97
        dey    ; $6C98
        bpl L6C83    ; $6C99
        jmp L6CB4    ; $6C9B
L6C9E   ldy #$00    ; $6C9E
        ldx $6CB5    ; $6CA0
L6CA3   lda AutoFileExt,y    ; $6CA3
        sta $0200,x    ; $6CA6
        beq L6CAF    ; $6CA9
        iny    ; $6CAB
        inx    ; $6CAC
        bne L6CA3    ; $6CAD
L6CAF   lda #$8D    ; $6CAF
        sta $0200,x    ; $6CB1
L6CB4   rts    ; $6CB4
        brk    ; $6CB5
        brk    ; $6CB6
;
; === SetPrefix ===
        jsr GetStrArg    ; $6CB7
        beq L6CE6    ; $6CBA
        jsr L6CE9    ; $6CBC
        jsr OpenEchoArea    ; $6CBF
        jsr PrintMessage    ; $6CC2
; ---- $6CC5-$6CD1  data  msg: .New prefix: ----
        dfb $8D,$CE,$E5,$F7,$A0,$F0,$F2,$E5,$E6,$E9,$F8,$BA,$00    ; $6CC5  .New prefix:.
; ---- $6CD2-$6CEE  code ----
        dec FileRead    ; $6CD2
        jsr ReadArgLine    ; $6CD5
        php    ; $6CD8
        txa    ; $6CD9
        pha    ; $6CDA
        jsr CloseEchoArea    ; $6CDB
        pla    ; $6CDE
        tax    ; $6CDF
        plp    ; $6CE0
        bne L6CE9    ; $6CE1
        txa    ; $6CE3
        beq L6CE9    ; $6CE4
L6CE6   jsr DSK:SetPrefix    ; $6CE6
L6CE9   jsr NewEchoArea    ; $6CE9
        jsr PrintMessage    ; $6CEC
; ---- $6CEF-$6CFF  data  msg: Current prefix: ----
        dfb $C3,$F5,$F2,$F2,$E5,$EE,$F4,$A0,$F0,$F2,$E5,$E6,$E9,$F8,$BA,$A0    ; $6CEF  Current prefix: 
        dfb $00    ; $6CFF  .
; ---- $6D00-$6E78  code ----
        ldx #$00    ; $6D00
L6D02   lda PrefixName,x    ; $6D02
        ora #$80    ; $6D05
        jsr CharOut    ; $6D07
        inx    ; $6D0A
        cpx ThePrefix    ; $6D0B
        bcc L6D02    ; $6D0E
        jsr CloseEchoArea    ; $6D10
        lda #$01    ; $6D13
        rts    ; $6D15
;
; === DeleteFile ===
        lda #$30    ; $6D16
        sta $00    ; $6D18
        lda #$6D    ; $6D1A
        sta $01    ; $6D1C
        lda #$FF    ; $6D1E
        jsr ReadFilename    ; $6D20
        beq L6D28    ; $6D23
L6D25   jmp BeepFindPoint    ; $6D25
L6D28   jsr DSK:Delete    ; $6D28
        bne L6D25    ; $6D2B
        lda #$01    ; $6D2D
        rts    ; $6D2F
        cpy $E5    ; $6D30
        cpx $F4E5    ; $6D32
        sbc $A0    ; $6D35
        inc $E9    ; $6D37
        cpx $3AE5    ; $6D39
;
; === InitFiler ===
        lda ClockPatch    ; $6D3C
        bne L6D4C    ; $6D3F
        lda ReadClock    ; $6D41
        sta ClockPatch    ; $6D44
        lda #$60    ; $6D47
        sta ReadClock    ; $6D49
L6D4C   jsr GetPrefix    ; $6D4C
        rts    ; $6D4F
        brk    ; $6D50
        brk    ; $6D51
L6D52   pha    ; $6D52
        lda #$01    ; $6D53
        sta $6D72    ; $6D55
        lda #$03    ; $6D58
        sta $6D73    ; $6D5A
        pla    ; $6D5D
L6D5E   stx MLIParams    ; $6D5E
;
; === OpCallMLI ===
        sta $6D6A    ; $6D61
;
; === CallMLI ===
        jsr L72E6    ; $6D64
        jsr MLI    ; $6D67
        brk    ; $6D6A
        adc ($6D),y    ; $6D6B
        jsr L72F4    ; $6D6D
        rts    ; $6D70
;
; === MLIParams ===
        ds 18        ; $6D71  18 bytes $00 fill
;
; === DefFileType ===
        tsb $A2    ; $6D83
        ora ($A9,x)    ; $6D85
        eor ($8D,x)    ; $6D87
        adc ($6D)    ; $6D89
        lda #$03    ; $6D8B
        sta $6D73    ; $6D8D
        lda #$C7    ; $6D90
        jsr L6D5E    ; $6D92
        rts    ; $6D95
;
; === DSK:Quit ===
        jsr DSK:ChkExit    ; $6D96
        jsr L77B3    ; $6D99
        beq L6D9F    ; $6D9C
        rts    ; $6D9E
L6D9F   jsr GetStrArg    ; $6D9F
        bne L6DC4    ; $6DA2
        lda #$8D    ; $6DA4
        sta $0200,x    ; $6DA6
        jsr MakePath    ; $6DA9
        ldy #$00    ; $6DAC
L6DAE   lda PathStr,y    ; $6DAE
        ora #$80    ; $6DB1
        sta Compiler,y    ; $6DB3
        iny    ; $6DB6
        cpy ThePathname    ; $6DB7
        bcc L6DAE    ; $6DBA
        lda #$00    ; $6DBC
        sta Compiler,y    ; $6DBE
        jmp L772D    ; $6DC1
L6DC4   lda ClockPatch    ; $6DC4
        sta ReadClock    ; $6DC7
        ldx #$04    ; $6DCA
        lda #$65    ; $6DCC
        jmp L6D5E    ; $6DCE
;
; === DSK:ChkExit ===
        jsr SafetyCheck    ; $6DD1
        beq L6DDA    ; $6DD4
        pla    ; $6DD6
        pla    ; $6DD7
        lda #$01    ; $6DD8
L6DDA   rts    ; $6DDA
;
; === DSK:SetPrefix ===
        jsr OpenPath    ; $6DDB
        bne L6DEF    ; $6DDE
        jsr DSK:CloseFile    ; $6DE0
        ldx #$01    ; $6DE3
        lda #$C6    ; $6DE5
        jsr L6D52    ; $6DE7
        jsr GetPrefix    ; $6DEA
        lda #$00    ; $6DED
L6DEF   rts    ; $6DEF
;
; === SlotDrive ===
        dfb $02        ; $6DF0  (data/65C02-bit)
        ora ($0A,x)    ; $6DF1
        php    ; $6DF3
        lsr    ; $6DF4
        lsr    ; $6DF5
        lsr    ; $6DF6
        lsr    ; $6DF7
        lsr    ; $6DF8
        sta SlotDrive    ; $6DF9
        lda #$00    ; $6DFC
        plp    ; $6DFE
        rol    ; $6DFF
        adc #$01    ; $6E00
        sta $6DF1    ; $6E02
        rts    ; $6E05
        ds 9        ; $6E06  9 bytes $00 fill
;
; === GetSysDate ===
        lda SysTheDate    ; $6E0F
        sta $6E06    ; $6E12
        lda $BF91    ; $6E15
        sta $6E07    ; $6E18
        jsr L6E28    ; $6E1B
        ldy $6E08    ; $6E1E
        ldx $6E09    ; $6E21
        lda $6E0A    ; $6E24
        rts    ; $6E27
L6E28   lda $6E06    ; $6E28
        and #$1F    ; $6E2B
        sta $6E0A    ; $6E2D
        lda $6E07    ; $6E30
        lsr    ; $6E33
        sta $6E08    ; $6E34
        lda $6E06    ; $6E37
        ror    ; $6E3A
        lsr    ; $6E3B
        lsr    ; $6E3C
        lsr    ; $6E3D
        lsr    ; $6E3E
        sta $6E09    ; $6E3F
        rts    ; $6E42
;
; === GetSystemTime ===
        lda SysTheTime    ; $6E43
        sta Time    ; $6E46
        lda $BF93    ; $6E49
        sta $6E0C    ; $6E4C
;
; === GetRealTime ===
        lda $6E0C    ; $6E4F
        and #$1F    ; $6E52
        sta $6E0E    ; $6E54
        tax    ; $6E57
        lda Time    ; $6E58
        and #$3F    ; $6E5B
        sta $6E0D    ; $6E5D
        rts    ; $6E60
;
; === Months ===
        adc $7C6E,y    ; $6E61
        ror $6E7F    ; $6E64
        dfb $82        ; $6E67  (data/65C02-bit)
        ror $6E85    ; $6E68
        dey    ; $6E6B
        ror $6E8B    ; $6E6C
        stx $916E    ; $6E6F
        ror $6E94    ; $6E72
        dfb $97        ; $6E75  (data/65C02-bit)
        ror $6E9A    ; $6E76
; ---- $6E79-$6E9C  data  MonthNames (12 x 3-char month abbreviations) ----
        dfb $4A,$61,$EE,$46,$65,$E2,$4D,$61,$F2,$41,$70,$F2,$4D,$61,$F9,$4A    ; $6E79  JanFebMarAprMayJ
        dfb $75,$EE,$4A,$75,$EC,$41,$75,$E7,$53,$65,$F0,$4F,$63,$F4,$4E,$6F    ; $6E89  unJulAugSepOctNo
        dfb $F6,$44,$65,$E3    ; $6E99  vDec
; ---- $6E9D-$6EAA  code ----
;
; === PrintDate ===
        jsr L6E28    ; $6E9D
        lda $6E06    ; $6EA0
        ora $6E07    ; $6EA3
        bne L6EB6    ; $6EA6
        jsr PrintMessage    ; $6EA8
; ---- $6EAB-$6EB4  data  msg: [no date] ----
        dfb $DB,$EE,$EF,$A0,$E4,$E1,$F4,$E5,$DD,$00    ; $6EAB  [no date].
; ---- $6EB5-$742C  code ----
        rts    ; $6EB5
L6EB6   ldx $6E0A    ; $6EB6
        jsr ZeroJustify    ; $6EB9
        cpx #$0A    ; $6EBC
        bcs L6EC7    ; $6EBE
        lda #$B0    ; $6EC0
        jsr CharOut    ; $6EC2
        lda #$00    ; $6EC5
L6EC7   jsr PrintDec    ; $6EC7
        jsr L6EFA    ; $6ECA
        lda $6E09    ; $6ECD
        sec    ; $6ED0
        sbc #$01    ; $6ED1
        asl    ; $6ED3
        tax    ; $6ED4
        lda Months,x    ; $6ED5
        sta $00    ; $6ED8
        lda $6E62,x    ; $6EDA
        sta $01    ; $6EDD
        ldy #$00    ; $6EDF
        ldx #$03    ; $6EE1
L6EE3   lda ($00),y    ; $6EE3
        ora #$80    ; $6EE5
        jsr CharOut    ; $6EE7
        iny    ; $6EEA
        dex    ; $6EEB
        bne L6EE3    ; $6EEC
        jsr L6EFA    ; $6EEE
        ldx $6E08    ; $6EF1
        lda #$00    ; $6EF4
        jsr PrintDec    ; $6EF6
        rts    ; $6EF9
L6EFA   lda #$AD    ; $6EFA
        jmp CharOut    ; $6EFC
L6EFF   rts    ; $6EFF
;
; === DSK:ModeTime ===
        lda ClockPatch    ; $6F00
        cmp #$60    ; $6F03
        beq L6EFF    ; $6F05
        jsr GetTheTime    ; $6F07
        lda SysTheDate    ; $6F0A
        sta $6E06    ; $6F0D
        lda $BF91    ; $6F10
        sta $6E07    ; $6F13
        jsr PrintDate    ; $6F16
        ldx #$01    ; $6F19
        jsr L7637    ; $6F1B
        lda SysTheTime    ; $6F1E
        sta Time    ; $6F21
        lda $BF93    ; $6F24
        sta $6E0C    ; $6F27
;
; === PrintTime ===
        jsr ZeroJustify    ; $6F2A
        sta $6F7E    ; $6F2D
        jsr GetRealTime    ; $6F30
        ldx $6E0E    ; $6F33
        beq L6F45    ; $6F36
        cpx #$0C    ; $6F38
        bcc L6F47    ; $6F3A
        ror $6F7E    ; $6F3C
        txa    ; $6F3F
        sbc #$0B    ; $6F40
        tax    ; $6F42
        bne L6F47    ; $6F43
L6F45   ldx #$0C    ; $6F45
L6F47   cpx #$0A    ; $6F47
        bcs L6F4E    ; $6F49
        jsr PrintSpace    ; $6F4B
L6F4E   lda #$00    ; $6F4E
        jsr PrintDec    ; $6F50
        lda #$BA    ; $6F53
        jsr CharOut    ; $6F55
        ldx $6E0D    ; $6F58
        cpx #$0A    ; $6F5B
        bcs L6F64    ; $6F5D
        lda #$B0    ; $6F5F
        jsr CharOut    ; $6F61
L6F64   lda #$00    ; $6F64
        jsr PrintDec    ; $6F66
        jsr PrintSpace    ; $6F69
        lda #$E1    ; $6F6C
        bit $6F7E    ; $6F6E
        bpl L6F75    ; $6F71
        lda #$F0    ; $6F73
L6F75   jsr CharOut    ; $6F75
        lda #$ED    ; $6F78
        jsr CharOut    ; $6F7A
        rts    ; $6F7D
        brk    ; $6F7E
;
; === BuffDateTime ===
        jsr GetTheTime    ; $6F7F
        jsr BuffPutOn    ; $6F82
        lda SysTheDate    ; $6F85
        sta $6E06    ; $6F88
        lda $BF91    ; $6F8B
        sta $6E07    ; $6F8E
        jsr PrintDate    ; $6F91
        ldx #$01    ; $6F94
        jsr L7637    ; $6F96
        lda SysTheTime    ; $6F99
        sta Time    ; $6F9C
        lda $BF93    ; $6F9F
        sta $6E0C    ; $6FA2
        jsr PrintTime    ; $6FA5
        jsr BuffPutOff    ; $6FA8
        rts    ; $6FAB
;
; === BuffPutOn ===
        lda CoutDef    ; $6FAC
        sta $6FE7    ; $6FAF
        lda $2607    ; $6FB2
        sta $6FE8    ; $6FB5
        lda #$C3    ; $6FB8
        sta CoutDef    ; $6FBA
        lda #$6F    ; $6FBD
        sta $2607    ; $6FBF
        rts    ; $6FC2
;
; === BuffPutter ===
        stx $6FD4    ; $6FC3
        sty $6FD3    ; $6FC6
        jsr BuffInsert    ; $6FC9
        ldy $6FD3    ; $6FCC
        ldx $6FD4    ; $6FCF
        rts    ; $6FD2
        brk    ; $6FD3
        brk    ; $6FD4
;
; === BuffPutOff ===
        lda $6FE7    ; $6FD5
        sta CoutDef    ; $6FD8
        lda $6FE8    ; $6FDB
        sta $2607    ; $6FDE
        jsr DisplayPage    ; $6FE1
        lda #$01    ; $6FE4
        rts    ; $6FE6
        brk    ; $6FE7
        brk    ; $6FE8
;
; === PushFilePath ===
        ldx #$00    ; $6FE9
;
; === PushFilePath1 ===
        stx $7024    ; $6FEB
        lda $2607    ; $6FEE
        pha    ; $6FF1
        lda CoutDef    ; $6FF2
        pha    ; $6FF5
        lda #$14    ; $6FF6
        sta CoutDef    ; $6FF8
        lda #$70    ; $6FFB
        sta $2607    ; $6FFD
        jsr PrintPath    ; $7000
        pla    ; $7003
        sta CoutDef    ; $7004
        pla    ; $7007
        sta $2607    ; $7008
        lda #$00    ; $700B
        ldx $7024    ; $700D
        sta $0200,x    ; $7010
        rts    ; $7013
        stx $6FD4    ; $7014
        ldx $7024    ; $7017
        sta $0200,x    ; $701A
        ldx $6FD4    ; $701D
        inc $7024    ; $7020
        rts    ; $7023
        brk    ; $7024
;
; === PrintPath ===
        ldx #$00    ; $7025
L7027   cpx ThePathname    ; $7027
        bcs L7037    ; $702A
        lda PathStr,x    ; $702C
        ora #$80    ; $702F
        jsr CharOut    ; $7031
        inx    ; $7034
        bne L7027    ; $7035
L7037   rts    ; $7037
;
; === RBlock ===
        sta $6D72    ; $7038
;
; === RBlock1 ===
        lda #$03    ; $703B
        sta MLIParams    ; $703D
        stx $6D75    ; $7040
        sty $6D76    ; $7043
        lda #$00    ; $7046
        sta $6D73    ; $7048
        lda #$A5    ; $704B
        sta $6D74    ; $704D
        lda #$80    ; $7050
        jsr OpCallMLI    ; $7052
        rts    ; $7055
;
; === VolInfo ===
        ds 39        ; $7056  39 bytes $00 fill
        jsr $0000    ; $707D
        ds 42        ; $7080  42 bytes $00 fill
;
; === MakePath ===
        ldx #$00    ; $70AA
        ldy #$00    ; $70AC
        lda $0200    ; $70AE
        cmp #$AF    ; $70B1
        beq L70C6    ; $70B3
        lda ThePrefix    ; $70B5
        beq L70C6    ; $70B8
L70BA   lda PrefixName,y    ; $70BA
        sta PathStr,y    ; $70BD
        iny    ; $70C0
        cpy ThePrefix    ; $70C1
        bcc L70BA    ; $70C4
L70C6   lda $0200,x    ; $70C6
        and #$7F    ; $70C9
        sta PathStr,y    ; $70CB
        cmp #$0D    ; $70CE
        beq L70D8    ; $70D0
        inx    ; $70D2
        iny    ; $70D3
        cpy #$3F    ; $70D4
        bcc L70C6    ; $70D6
L70D8   sty ThePathname    ; $70D8
        rts    ; $70DB
;
; === OpenPath ===
        jsr DSK:CloseFile    ; $70DC
        jsr MakePath    ; $70DF
;
; === OpenPath1 ===
        ldx #$0A    ; $70E2
        lda #$C4    ; $70E4
        jsr L6D52    ; $70E6
        bcs L7118    ; $70E9
        lda $6D75    ; $70EB
        sta $6D51    ; $70EE
        ldx #$03    ; $70F1
        lda #$00    ; $70F3
        sta $6D74    ; $70F5
        lda #$A5    ; $70F8
        sta $6D75    ; $70FA
        lda #$00    ; $70FD
        sta GblLength    ; $70FF
        sta $7127    ; $7102
        sta $7128    ; $7105
        lda #$C8    ; $7108
        jsr L6D52    ; $710A
        lda $6D76    ; $710D
        sta $6D50    ; $7110
        sta $7125    ; $7113
        bcc L711B    ; $7116
L7118   ldx #$FF    ; $7118
        rts    ; $711A
L711B   jsr MLI    ; $711B
        cmp (CH),y    ; $711E
        adc ($A2),y    ; $7120
        brk    ; $7122
        rts    ; $7123
        dfb $02        ; $7124  (data/65C02-bit)
        ds 5        ; $7125  5 bytes $00 fill
;
; === CompFile ===
        ldy ThePathname    ; $712A
        cpy $7129    ; $712D
        beq L715D    ; $7130
        lda $727E    ; $7132
        eor #$FF    ; $7135
        beq L715D    ; $7137
        iny    ; $7139
        ldx #$00    ; $713A
L713C   lda $707F,x    ; $713C
        ora #$80    ; $713F
        jsr UpperCon    ; $7141
        sta $715E    ; $7144
        lda ThePathname,y    ; $7147
        ora #$80    ; $714A
        jsr UpperCon    ; $714C
        cmp $715E    ; $714F
        bne L715D    ; $7152
        cpy $7129    ; $7154
        beq L715D    ; $7157
        iny    ; $7159
        inx    ; $715A
        bne L713C    ; $715B
L715D   rts    ; $715D
        brk    ; $715E
;
; === GetDirInfo ===
        lda #$00    ; $715F
        sta $727E    ; $7161
        jsr OpenPath    ; $7164
        php    ; $7167
        ldy ThePathname    ; $7168
        sty $7129    ; $716B
        plp    ; $716E
        bne L717B    ; $716F
        jsr DSK:CloseFile    ; $7171
        lda $6D51    ; $7174
        cmp #$0F    ; $7177
        beq L71A8    ; $7179
L717B   ldy ThePathname    ; $717B
        iny    ; $717E
L717F   dey    ; $717F
        bmi L71A6    ; $7180
        lda ThePathname,y    ; $7182
        cmp #$2F    ; $7185
        bne L717F    ; $7187
        sty ThePathname    ; $7189
        cpy #$01    ; $718C
        bne L7197    ; $718E
        jsr GetOnline    ; $7190
        dec $727E    ; $7193
        rts    ; $7196
L7197   jsr OpenPath1    ; $7197
        bne L71A6    ; $719A
        jsr DSK:CloseFile    ; $719C
        lda $6D51    ; $719F
        cmp #$0F    ; $71A2
        beq L71A8    ; $71A4
L71A6   sec    ; $71A6
        rts    ; $71A7
L71A8   lda LastUnit    ; $71A8
        and #$F0    ; $71AB
        sta $6D72    ; $71AD
        ldy #$04    ; $71B0
        ldx #$00    ; $71B2
L71B4   lda rm_FileBuffer,y    ; $71B4
        sta VolInfo,x    ; $71B7
        iny    ; $71BA
        inx    ; $71BB
        cpx #$27    ; $71BC
        bcc L71B4    ; $71BE
        sty $70A5    ; $71C0
        lda #$00    ; $71C3
        sta $70A6    ; $71C5
        sta $70A7    ; $71C8
        inc $70A7    ; $71CB
        lda $7077    ; $71CE
        sta $70A8    ; $71D1
        lda $7078    ; $71D4
        sta $70A9    ; $71D7
        clc    ; $71DA
        rts    ; $71DB
;
; === NextFile ===
        bit $727E    ; $71DC
        bpl L7215    ; $71DF
L71E1   lda $727F    ; $71E1
        inc $727F    ; $71E4
        cmp #$10    ; $71E7
        bcs L721D    ; $71E9
        asl    ; $71EB
        asl    ; $71EC
        asl    ; $71ED
        asl    ; $71EE
        tay    ; $71EF
        lda rm_FileBuffer,y    ; $71F0
        and #$0F    ; $71F3
        sta $EF    ; $71F5
        beq L71E1    ; $71F7
        lda rm_FileBuffer,y    ; $71F9
        jsr MakeSD    ; $71FC
        ldx #$00    ; $71FF
L7201   iny    ; $7201
        lda rm_FileBuffer,y    ; $7202
        sta $707F,x    ; $7205
        inx    ; $7208
        cpx $EF    ; $7209
        bcc L7201    ; $720B
        txa    ; $720D
        ora #$D0    ; $720E
        sta FileInfo    ; $7210
        clc    ; $7213
        rts    ; $7214
L7215   lda $70A8    ; $7215
        ora $70A9    ; $7218
        bne L721F    ; $721B
L721D   sec    ; $721D
L721E   rts    ; $721E
L721F   lda $70A7    ; $721F
        cmp $7076    ; $7222
        bcc L723F    ; $7225
        ldx $A502    ; $7227
        ldy $A503    ; $722A
        jsr RBlock1    ; $722D
        bcs L721E    ; $7230
        lda #$00    ; $7232
        sta $70A7    ; $7234
        sta $70A6    ; $7237
        lda #$04    ; $723A
        sta $70A5    ; $723C
L723F   lda #$00    ; $723F
        clc    ; $7241
        adc $70A5    ; $7242
        sta $00    ; $7245
        lda #$A5    ; $7247
        adc $70A6    ; $7249
        sta $01    ; $724C
        ldy #$00    ; $724E
L7250   lda ($00),y    ; $7250
        sta FileInfo,y    ; $7252
        iny    ; $7255
        cpy #$27    ; $7256
        bcc L7250    ; $7258
        inc $70A7    ; $725A
        tya    ; $725D
        clc    ; $725E
        adc $70A5    ; $725F
        sta $70A5    ; $7262
        bcc L726A    ; $7265
        inc $70A6    ; $7267
L726A   lda FileInfo    ; $726A
        and #$F0    ; $726D
        beq L721F    ; $726F
        lda $70A8    ; $7271
        bne L7279    ; $7274
        dec $70A9    ; $7276
L7279   dec $70A8    ; $7279
        clc    ; $727C
        rts    ; $727D
        brk    ; $727E
        brk    ; $727F
;
; === GetOnline ===
        jsr DSK:CloseFile    ; $7280
        lda #$00    ; $7283
        sta $6D72    ; $7285
        sta $727F    ; $7288
        lda #$00    ; $728B
        sta $6D73    ; $728D
        lda #$A5    ; $7290
        sta $6D74    ; $7292
        ldx #$02    ; $7295
        lda #$C5    ; $7297
        jsr L6D5E    ; $7299
        rts    ; $729C
;
; === DSK:OpenFile ===
        jsr OpenPath    ; $729D
        bne L72AA    ; $72A0
        lda $6D50    ; $72A2
        sta $6D72    ; $72A5
        lda #$00    ; $72A8
L72AA   rts    ; $72AA
;
; === DSK:ReadByte ===
        jsr GatherTYI    ; $72AB
        lda $6D77    ; $72AE
        bne L72B6    ; $72B1
        dec $6D78    ; $72B3
L72B6   dec $6D77    ; $72B6
        lda $6D78    ; $72B9
        bpl L72D6    ; $72BC
        jsr CallMLI    ; $72BE
        bcs L72E3    ; $72C1
        lda #$00    ; $72C3
        sta $B0    ; $72C5
        lda #$A9    ; $72C7
        sta $B1    ; $72C9
        lda $6D77    ; $72CB
        bne L72D3    ; $72CE
        dec $6D78    ; $72D0
L72D3   dec $6D77    ; $72D3
L72D6   ldy #$00    ; $72D6
        php    ; $72D8
        lda ($B0),y    ; $72D9
        inc $B0    ; $72DB
        bne L72E1    ; $72DD
        inc $B1    ; $72DF
L72E1   plp    ; $72E1
        rts    ; $72E2
L72E3   lda #$FF    ; $72E3
        rts    ; $72E5
L72E6   pha    ; $72E6
        lda $07F5    ; $72E7
        sta $72F7    ; $72EA
        lda #$2D    ; $72ED
        sta $07F5    ; $72EF
        pla    ; $72F2
        rts    ; $72F3
L72F4   php    ; $72F4
        pha    ; $72F5
        lda #$FF    ; $72F6
        sta $07F5    ; $72F8
        pla    ; $72FB
        plp    ; $72FC
        rts    ; $72FD
;
; === PrepRead ===
        lda #$A9    ; $72FE
        sta $6D74    ; $7300
        lda #$02    ; $7303
        sta $6D76    ; $7305
        lda #$04    ; $7308
        sta MLIParams    ; $730A
        lda #$CA    ; $730D
        sta $6D6A    ; $730F
        lda #$00    ; $7312
        sta $6D73    ; $7314
        sta $6D75    ; $7317
        sta $6D77    ; $731A
        sta $6D78    ; $731D
        rts    ; $7320
;
; === PrepWrite ===
        jsr PrepRead    ; $7321
        sta $6D76    ; $7324
        inc $6D6A    ; $7327
        rts    ; $732A
;
; === DSK:WriteByte ===
        sty $7349    ; $732B
        ldy $6D75    ; $732E
        sta rm_DataBuffer,y    ; $7331
        inc $6D75    ; $7334
        bne L7341    ; $7337
        inc $6D76    ; $7339
        jsr L73A6    ; $733C
        bcs L7343    ; $733F
L7341   ldy #$00    ; $7341
L7343   php    ; $7343
        ldy $7349    ; $7344
        plp    ; $7347
        rts    ; $7348
        brk    ; $7349
;
; === DSK:SaveFile ===
        jsr DSK:OpenFile    ; $734A
        beq L7355    ; $734D
        jsr DSK:Create    ; $734F
        bcc DSK:SaveFile    ; $7352
        rts    ; $7354
L7355   jsr PrepWrite    ; $7355
        lda BuffTop    ; $7358
        sta $00    ; $735A
        lda $67    ; $735C
        sta $01    ; $735E
L7360   lda $01    ; $7360
        cmp $6B    ; $7362
        bcc L737F    ; $7364
        bne L7373    ; $7366
        lda $00    ; $7368
        cmp GapTop    ; $736A
        bcc L737F    ; $736C
        bne L7373    ; $736E
        jsr SetTempBot    ; $7370
L7373   lda $01    ; $7373
        cmp $69    ; $7375
        bcc L737F    ; $7377
        lda $00    ; $7379
        cmp BuffBot    ; $737B
        bcs L739D    ; $737D
L737F   jsr GatherTYI    ; $737F
        ldy #$00    ; $7382
        jsr $D000    ; $7384
        eor EORValue    ; $7387
        jsr DSK:WriteByte    ; $738A
        bne L7397    ; $738D
        inc $00    ; $738F
        bne L7395    ; $7391
        inc $01    ; $7393
L7395   bne L7360    ; $7395
L7397   jsr DSK:CloseFile    ; $7397
        lda #$FF    ; $739A
        rts    ; $739C
L739D   jsr DSK:CloseHere    ; $739D
        jsr SetGap    ; $73A0
        lda #$00    ; $73A3
        rts    ; $73A5
L73A6   jsr CallMLI    ; $73A6
        bcs L73B3    ; $73A9
        lda #$00    ; $73AB
        sta $6D76    ; $73AD
        sta $6D75    ; $73B0
L73B3   rts    ; $73B3
;
; === DSK:CloseHere ===
        jsr L73A6    ; $73B4
        ldx #$02    ; $73B7
        lda #$CF    ; $73B9
        jsr L6D5E    ; $73BB
        lda #$D0    ; $73BE
        jsr OpCallMLI    ; $73C0
        ldx #$0A    ; $73C3
        lda #$C4    ; $73C5
        jsr L6D52    ; $73C7
        jsr GetTheTime    ; $73CA
        ldx #$00    ; $73CD
L73CF   lda SysTheDate,x    ; $73CF
        sta $6D79,x    ; $73D2
        inx    ; $73D5
        cpx #$04    ; $73D6
        bcc L73CF    ; $73D8
        ldx #$07    ; $73DA
        lda #$C3    ; $73DC
        jsr L6D5E    ; $73DE
        jsr DSK:CloseFile    ; $73E1
        rts    ; $73E4
;
; === DSK:CloseFile ===
        lda #$00    ; $73E5
        sta $6D72    ; $73E7
        ldx #$01    ; $73EA
        lda #$CC    ; $73EC
        jsr L6D5E    ; $73EE
        rts    ; $73F1
;
; === DSK:DiskSpace ===
        jsr SelfPath    ; $73F2
        lda #$8D    ; $73F5
        sta $0200,x    ; $73F7
        jsr OpenPath    ; $73FA
        bcc L7400    ; $73FD
        rts    ; $73FF
L7400   jsr DSK:CloseFile    ; $7400
        lda LastUnit    ; $7403
        ldx #$02    ; $7406
        ldy #$00    ; $7408
        sty PD:Justify    ; $740A
        jsr RBlock    ; $740D
        ldy #$04    ; $7410
        lda rm_FileBuffer,y    ; $7412
        and #$0F    ; $7415
        tax    ; $7417
        inx    ; $7418
        stx ThePathname    ; $7419
        ldy #$00    ; $741C
L741E   lda PathStr,y    ; $741E
        ora #$80    ; $7421
        jsr CharOut    ; $7423
        iny    ; $7426
        dex    ; $7427
        bne L741E    ; $7428
        jsr PrintMessage    ; $742A
; ---- $742D-$7432  data  msg:  has ----
        dfb $A0,$E8,$E1,$F3,$A0,$00    ; $742D   has .
; ---- $7433-$745E  code ----
        ldy #$29    ; $7433
        lda rm_FileBuffer,y    ; $7435
        sta $7499    ; $7438
        tax    ; $743B
        lda $A501,y    ; $743C
        sta $749A    ; $743F
        ldx #$0A    ; $7442
        lda #$C4    ; $7444
        jsr L6D52    ; $7446
        bcs L7498    ; $7449
        lda $7499    ; $744B
        sec    ; $744E
        sbc $6D79    ; $744F
        tax    ; $7452
        lda $749A    ; $7453
        sbc $6D7A    ; $7456
        jsr PrintPages    ; $7459
        jsr PrintMessage    ; $745C
; ---- $745F-$7465  data  msg: free, ----
        dfb $E6,$F2,$E5,$E5,$AC,$A0,$00    ; $745F  free, .
; ---- $7466-$7471  code ----
        lda $6D7A    ; $7466
        ldx $6D79    ; $7469
        jsr PrintPages    ; $746C
        jsr PrintMessage    ; $746F
; ---- $7472-$7489  data  msg: in use, for a total of ----
        dfb $E9,$EE,$A0,$F5,$F3,$E5,$AC,$A0,$E6,$EF,$F2,$A0,$E1,$A0,$F4,$EF    ; $7472  in use, for a to
        dfb $F4,$E1,$EC,$A0,$EF,$E6,$A0,$00    ; $7482  tal of .
; ---- $748A-$74A6  code ----
        lda $749A    ; $748A
        ldx $7499    ; $748D
        jsr PrintDec    ; $7490
        lda #$AE    ; $7493
        jsr CharOut    ; $7495
L7498   rts    ; $7498
        brk    ; $7499
        brk    ; $749A
;
; === PrintPages ===
        stx $0100    ; $749B
        sta $0101    ; $749E
        jsr PrintDec    ; $74A1
        jsr PrintMessage    ; $74A4
; ---- $74A7-$74AC  data  msg:  page ----
        dfb $A0,$F0,$E1,$E7,$E5,$00    ; $74A7   page.
; ---- $74AD-$7514  code ----
        ldx $0100    ; $74AD
        lda $0101    ; $74B0
        jsr Plurilize    ; $74B3
        jsr PrintSpace    ; $74B6
        rts    ; $74B9
;
; === DSK:ListDir ===
        lda #$00    ; $74BA
        beq L74C0    ; $74BC
;
; === DSK:ListFiles ===
        lda #$FF    ; $74BE
L74C0   sta $753F    ; $74C0
        jsr PrepTO    ; $74C3
        jsr GetDirInfo    ; $74C6
        bcs L74FB    ; $74C9
        jsr L7501    ; $74CB
        lda #$00    ; $74CE
        sta $B0    ; $74D0
L74D2   jsr NextFile    ; $74D2
        bcs L74FB    ; $74D5
        jsr CompFile    ; $74D7
        bne L74D2    ; $74DA
        jsr L7540    ; $74DC
        bit $753F    ; $74DF
        bpl L74F5    ; $74E2
        lda #$FF    ; $74E4
        eor $B0    ; $74E6
        sta $B0    ; $74E8
        beq L74F5    ; $74EA
        lda #$28    ; $74EC
        sta CH    ; $74EE
        sta TypeoutCH    ; $74F0
        bne L74D2    ; $74F3
L74F5   jsr PrintReturn    ; $74F5
        jmp L74D2    ; $74F8
L74FB   jsr PrintReturn    ; $74FB
        jmp UnPrepTO    ; $74FE
L7501   bit $727E    ; $7501
        bmi L753D    ; $7504
        jsr ZeroJustify    ; $7506
        lda $7078    ; $7509
        ldx $7077    ; $750C
        jsr PrintDec    ; $750F
        jsr PrintMessage    ; $7512
; ---- $7515-$751A  data  msg:  file ----
        dfb $A0,$E6,$E9,$EC,$E5,$00    ; $7515   file.
; ---- $751B-$7526  code ----
        lda $7078    ; $751B
        ldx $7077    ; $751E
        jsr Plurilize    ; $7521
        jsr PrintMessage    ; $7524
; ---- $7527-$7533  data  msg:  present on ----
        dfb $A0,$F0,$F2,$E5,$F3,$E5,$EE,$F4,$A0,$EF,$EE,$A0,$00    ; $7527   present on .
; ---- $7534-$7539  code ----
        jsr PrintPath    ; $7534
        jsr PrintMessage    ; $7537
; ---- $753A-$753C  data  msg: .. ----
        dfb $8D,$8D,$00    ; $753A  ...
; ---- $753D-$763F  code ----
L753D   rts    ; $753D
;
; === HexListing ===
        dfb $FF        ; $753E  (data/65C02-bit)
        brk    ; $753F
L7540   ldy #$00    ; $7540
        lda FileInfo    ; $7542
        and #$0F    ; $7545
        tax    ; $7547
L7548   lda $707F,y    ; $7548
        dex    ; $754B
        bmi L7556    ; $754C
        ora #$80    ; $754E
        jsr CharOut    ; $7550
        iny    ; $7553
        bne L7548    ; $7554
L7556   bit $753F    ; $7556
        bpl L756E    ; $7559
        bit $727E    ; $755B
        bmi L756E    ; $755E
        lda FileInfo    ; $7560
        and #$F0    ; $7563
        cmp #$D0    ; $7565
        bcc L756E    ; $7567
        lda #$AF    ; $7569
        jsr CharOut    ; $756B
L756E   lda #$A0    ; $756E
L7570   cpy #$11    ; $7570
        bcs L757A    ; $7572
        jsr CharOut    ; $7574
        iny    ; $7577
        bne L7570    ; $7578
L757A   bit $727E    ; $757A
        bpl L7594    ; $757D
        lda #$00    ; $757F
        ldx SlotDrive    ; $7581
        jsr PrintDec    ; $7584
        lda #$AC    ; $7587
        jsr CharOut    ; $7589
        lda #$00    ; $758C
        ldx $6DF1    ; $758E
        jmp PrintDec    ; $7591
L7594   bit $753F    ; $7594
        bpl L759A    ; $7597
        rts    ; $7599
L759A   lda $708E    ; $759A
        jsr PrintType    ; $759D
        lda #$A0    ; $75A0
        sta PD:Justify    ; $75A2
        ldx $7091    ; $75A5
        lda $7092    ; $75A8
        jsr PrintDec    ; $75AB
        ldx #$03    ; $75AE
        bit HexListing    ; $75B0
        bpl L75B6    ; $75B3
        dex    ; $75B5
L75B6   jsr L7637    ; $75B6
        bit HexListing    ; $75B9
        bpl L75D9    ; $75BC
        lda #$A4    ; $75BE
        jsr CharOut    ; $75C0
        lda $7095    ; $75C3
        jsr HexByteOut    ; $75C6
        lda $7094    ; $75C9
        jsr HexByteOut    ; $75CC
        lda $7093    ; $75CF
        jsr HexByteOut    ; $75D2
        ldx #$02    ; $75D5
        bne L75E4    ; $75D7
L75D9   lda $7094    ; $75D9
        ldx $7093    ; $75DC
        jsr PrintDec    ; $75DF
        ldx #$03    ; $75E2
L75E4   jsr L7637    ; $75E4
        lda $709F    ; $75E7
        sta $6E06    ; $75EA
        lda $70A0    ; $75ED
        sta $6E07    ; $75F0
        lda #$00    ; $75F3
        jsr PrintDate    ; $75F5
        ldx #$01    ; $75F8
        jsr L7637    ; $75FA
        lda $70A1    ; $75FD
        sta Time    ; $7600
        lda $70A2    ; $7603
        sta $6E0C    ; $7606
        jsr PrintTime    ; $7609
        ldx #$03    ; $760C
        jsr L7637    ; $760E
        lda $7096    ; $7611
        sta $6E06    ; $7614
        lda $7097    ; $7617
        sta $6E07    ; $761A
        lda #$00    ; $761D
        jsr PrintDate    ; $761F
        ldx #$01    ; $7622
        jsr L7637    ; $7624
        lda $7098    ; $7627
        sta Time    ; $762A
        lda $7099    ; $762D
        sta $6E0C    ; $7630
        jsr PrintTime    ; $7633
        rts    ; $7636
L7637   lda #$A0    ; $7637
L7639   jsr CharOut    ; $7639
        dex    ; $763C
        bne L7639    ; $763D
        rts    ; $763F
; ---- $7640-$7678  data  FileTypeNames (14 [type,3-char] records: TXT,BIN,DIR.. + $00) ----
        dfb $04,$D4,$D8,$D4,$06,$C2,$C9,$CE,$0F,$C4,$C9,$D2,$19,$C1,$C4,$C2    ; $7640  .TXT.BIN.DIR.ADB
        dfb $1A,$C1,$D7,$D0,$1B,$C1,$D3,$D0,$EF,$D0,$C1,$D3,$F0,$C3,$CD,$C4    ; $7650  .AWP.ASPoPASpCMD
        dfb $F7,$C9,$CD,$C7,$F8,$CC,$CE,$CB,$FC,$C2,$C1,$D3,$FD,$D6,$C1,$D2    ; $7660  wIMGxLNK|BAS}VAR
        dfb $FE,$D2,$C5,$CC,$FF,$D3,$D9,$D3,$00    ; $7670  ~REL.SYS.
; ---- $7679-$77BE  code ----
;
; === PrintType ===
        ldy #$00    ; $7679
L767B   cmp FTypeTable,y    ; $767B
        beq L7698    ; $767E
        tax    ; $7680
        lda FTypeTable,y    ; $7681
        beq L768E    ; $7684
        tya    ; $7686
        clc    ; $7687
        adc #$04    ; $7688
        tay    ; $768A
        txa    ; $768B
        bne L767B    ; $768C
L768E   lda #$A4    ; $768E
        jsr CharOut    ; $7690
        txa    ; $7693
        jsr HexByteOut    ; $7694
        rts    ; $7697
L7698   iny    ; $7698
        ldx #$02    ; $7699
L769B   lda FTypeTable,y    ; $769B
        jsr CharOut    ; $769E
        iny    ; $76A1
        dex    ; $76A2
        bpl L769B    ; $76A3
        rts    ; $76A5
;
; === DSK:Create ===
        jsr GetTheTime    ; $76A6
        jsr MakePath    ; $76A9
        lda #$C3    ; $76AC
        sta $6D74    ; $76AE
        lda DefFileType    ; $76B1
        sta $6D75    ; $76B4
        lda #$00    ; $76B7
        tax    ; $76B9
L76BA   sta $6D76,x    ; $76BA
        inx    ; $76BD
        cpx #$08    ; $76BE
        bcc L76BA    ; $76C0
        ldx #$07    ; $76C2
        lda #$C0    ; $76C4
        jsr L6D52    ; $76C6
        rts    ; $76C9
;
; === DSK:Delete ===
        jsr MakePath    ; $76CA
        lda #$01    ; $76CD
        sta $6D72    ; $76CF
        lda #$03    ; $76D2
        sta $6D73    ; $76D4
        ldx #$01    ; $76D7
        lda #$C1    ; $76D9
        jsr L6D5E    ; $76DB
        ldx #$00    ; $76DE
        bcc L76E3    ; $76E0
        dex    ; $76E2
L76E3   rts    ; $76E3
;
; === Compiler ===
        ds 64        ; $76E4  64 bytes $00 fill
;
; === Compile ===
        jsr DSK:ChkExit    ; $7724
        jsr L77B3    ; $7727
        beq L772D    ; $772A
        rts    ; $772C
L772D   lda Compiler    ; $772D
        beq L774D    ; $7730
        ldx #$00    ; $7732
L7734   lda Compiler,x    ; $7734
        sta $0200,x    ; $7737
        inx    ; $773A
        cmp #$00    ; $773B
        bne L7734    ; $773D
        dex    ; $773F
        lda #$8D    ; $7740
        sta $0200,x    ; $7742
        jsr DSK:OpenFile    ; $7745
        beq L7750    ; $7748
L774A   jsr Beep    ; $774A
L774D   lda #$01    ; $774D
        rts    ; $774F
L7750   lda $6D51    ; $7750
        cmp #$FF    ; $7753
        bne L774A    ; $7755
        ldx #$17    ; $7757
        lda #$07    ; $7759
        sta SysMemMap,x    ; $775B
        dex    ; $775E
        lda #$00    ; $775F
L7761   sta SysMemMap,x    ; $7761
        dex    ; $7764
        bpl L7761    ; $7765
        lda #$CF    ; $7767
        sta SysMemMap    ; $7769
        ldx ThePathname    ; $776C
L776F   lda ThePathname,x    ; $776F
        and #$7F    ; $7772
        sta $0280,x    ; $7774
        dex    ; $7777
        bpl L776F    ; $7778
        lda $6D72    ; $777A
        sta $77AE    ; $777D
        ldx #$00    ; $7780
L7782   lda $7796,x    ; $7782
        sta LoRamPoint,x    ; $7785
        inx    ; $7788
        cpx #$1D    ; $7789
        bcc L7782    ; $778B
        lda ClockPatch    ; $778D
        sta ReadClock    ; $7790
        jmp LoRamPoint    ; $7793
        sta RdRomBank    ; $7796   <== BANK: language-card ROM (read)
        sta RdRomBank    ; $7799   <== BANK: language-card ROM (read)
        jsr MLI    ; $779C
        dex    ; $779F
        clc    ; $77A0
        php    ; $77A1
        jsr MLI    ; $77A2
        cpy $0816    ; $77A5
        jmp $2000    ; $77A8
        ora ($00,x)    ; $77AB
        tsb $00    ; $77AD
        brk    ; $77AF
        jsr $8000    ; $77B0
L77B3   jsr AnyArgument?    ; $77B3
        bne L77BC    ; $77B6
        jsr BufferDump    ; $77B8
        rts    ; $77BB
L77BC   lda #$00    ; $77BC
        rts    ; $77BE
