;-*- Mode: Merlin -*-
;
; src/modules/16_dispatch.s -- AMACS: clock, command dispatch, char error, (un)merlinify, decimal print
; Address range $77BF-$7A54. GENERATED by tools/disasm.py.
; `put' from src/amacs.s; symbols/labels are global across modules.
;
; ---- $77BF-$7A54  code ----
;
; === ClockPatch ===
        brk    ; $77BF
;
; === GetTheTime ===
        ldx #$20    ; $77C0
L77C2   lda $0200,x    ; $77C2
        sta rm_PathComp,x    ; $77C5
        dex    ; $77C8
        bpl L77C2    ; $77C9
        lda ClockPatch    ; $77CB
        sta ReadClock    ; $77CE
        jsr MLI    ; $77D1
        dfb $82        ; $77D4  (data/65C02-bit)
        brk    ; $77D5
        brk    ; $77D6
        lda $0204    ; $77D7
        sbc #$AF    ; $77DA
        sta DayOfWeek    ; $77DC
        lda #$60    ; $77DF
        sta ReadClock    ; $77E1
        ldx #$20    ; $77E4
L77E6   lda rm_PathComp,x    ; $77E6
        sta $0200,x    ; $77E9
        dex    ; $77EC
        bpl L77E6    ; $77ED
        rts    ; $77EF
;
; === DayOfWeek ===
        brk    ; $77F0
;
; === ExitPrompt ===
        dfb $FF        ; $77F1  (data/65C02-bit)
;
; === SafetyCheck ===
        bit ExitPrompt    ; $77F2
        bpl L782F    ; $77F5
        jsr AnyArgument?    ; $77F7
        beq L782F    ; $77FA
        ldx SelectedBuff    ; $77FC
        stx $7831    ; $77FF
L7802   stx $7830    ; $7802
        lda BuffActList,x    ; $7805
        bpl L7820    ; $7808
        jsr PointToBInfo    ; $780A
        ldy #$55    ; $780D
        lda (BuffPoint),y    ; $780F
        and #$02    ; $7811
        beq L7820    ; $7813
        ldx $7830    ; $7815
        jsr SI:OpenBuff    ; $7818
        jsr MaybeSave    ; $781B
        bne L782F    ; $781E
L7820   ldx $7830    ; $7820
        inx    ; $7823
        cpx #$0E    ; $7824
        bcc L782A    ; $7826
        ldx #$00    ; $7828
L782A   cpx $7831    ; $782A
        bne L7802    ; $782D
L782F   rts    ; $782F
        ds 9        ; $7830  9 bytes $00 fill
;
; === DispatchTab ===
        sty $4F    ; $7839
        brk    ; $783B
        brk    ; $783C
;
; === Dispatch ===
        sta CommandChar    ; $783D
        sta $783B    ; $7840
        lda #$00    ; $7843
        sta $783C    ; $7845
        asl $783B    ; $7848
        rol $783C    ; $784B
        lda DispatchTab    ; $784E
        clc    ; $7851
        adc $783B    ; $7852
        sta $00    ; $7855
        lda $783A    ; $7857
        adc $783C    ; $785A
        sta $01    ; $785D
        ldy #$00    ; $785F
        lda ($00),y    ; $7861
        pha    ; $7863
        iny    ; $7864
        lda ($00),y    ; $7865
        sta $01    ; $7867
        sta $7835    ; $7869
        pla    ; $786C
        sta $00    ; $786D
        sta CommandVector    ; $786F
        ora $01    ; $7872
        bne L7879    ; $7874
        jmp CharError    ; $7876
L7879   lda CommandChar    ; $7879
        jsr CallTemp    ; $787C
        sta DisplayCode    ; $787F
        lda CommandChar    ; $7882
        sta LastCommand    ; $7885
        lda CommandVector    ; $7888
        sta LastComVect    ; $788B
        lda $7835    ; $788E
        sta $7837    ; $7891
        lda DisplayCode    ; $7894
        rts    ; $7897
;
; === CallTemp ===
        jmp ($0000)    ; $7898
;
; === CharError ===
        lda CommandChar    ; $789B
;
; === BadCharacter ===
        jmp BadCharMsg    ; $789E
        brk    ; $78A1
;
; === NextByte ===
        jsr GatherTYI    ; $78A2
        inc $00    ; $78A5
        bne L78AB    ; $78A7
        inc $01    ; $78A9
L78AB   lda $01    ; $78AB
        cmp $6B    ; $78AD
        bcc L78D8    ; $78AF
        bne L78C9    ; $78B1
        lda $00    ; $78B3
        cmp GapTop    ; $78B5
        bcc L78D8    ; $78B7
        bne L78C9    ; $78B9
        lda GapBot    ; $78BB
        sta $00    ; $78BD
        lda $6D    ; $78BF
        sta $01    ; $78C1
        inc $00    ; $78C3
        bne L78C9    ; $78C5
        inc $01    ; $78C7
L78C9   lda $01    ; $78C9
        cmp $69    ; $78CB
        bcc L78D8    ; $78CD
        lda $00    ; $78CF
        cmp BuffBot    ; $78D1
        bcc L78D8    ; $78D3
        lda #$FF    ; $78D5
        rts    ; $78D7
L78D8   ldy #$00    ; $78D8
        jsr $D000    ; $78DA
        ldy #$00    ; $78DD
        rts    ; $78DF
;
; === UnMerlinify ===
        lda BuffTop    ; $78E0
        sta $00    ; $78E2
        lda $67    ; $78E4
        sta $01    ; $78E6
        lda $00    ; $78E8
        bne L78EE    ; $78EA
        dec $01    ; $78EC
L78EE   dec $00    ; $78EE
        lda #$8D    ; $78F0
L78F2   sta $78A1    ; $78F2
        jsr NextByte    ; $78F5
        beq L78FD    ; $78F8
L78FA   jmp L79FB    ; $78FA
L78FD   ora #$80    ; $78FD
        jsr $D054    ; $78FF
        cmp #$AA    ; $7902
        beq L7911    ; $7904
        cmp #$BB    ; $7906
        bne L791C    ; $7908
        lda $78A1    ; $790A
        cmp #$89    ; $790D
        beq L7955    ; $790F
L7911   lda $78A1    ; $7911
        cmp #$8D    ; $7914
        beq L7955    ; $7916
        lda #$BB    ; $7918
        bne L78F2    ; $791A
L791C   cmp #$A0    ; $791C
        bne L7927    ; $791E
        lda #$89    ; $7920
        jsr $D054    ; $7922
        bne L78F2    ; $7925
L7927   cmp #$A2    ; $7927
        beq L792F    ; $7929
        cmp #$A7    ; $792B
        bne L78F2    ; $792D
L792F   sta $7954    ; $792F
L7932   jsr NextByte    ; $7932
        php    ; $7935
        ora #$80    ; $7936
        jsr $D054    ; $7938
        plp    ; $793B
        bne L78FA    ; $793C
        cmp #$20    ; $793E
        bne L7949    ; $7940
        lda #$A0    ; $7942
        jsr $D054    ; $7944
        bne L7932    ; $7947
L7949   cmp $7954    ; $7949
        beq L78F2    ; $794C
        cmp #$8D    ; $794E
        bne L7932    ; $7950
        beq L78F2    ; $7952
        brk    ; $7954
L7955   jsr NextByte    ; $7955
        bne L78FA    ; $7958
        ora #$80    ; $795A
        jsr $D054    ; $795C
        cmp #$8D    ; $795F
        bne L7955    ; $7961
        beq L78F2    ; $7963
;
; === Merlinify ===
        ldx #$FF    ; $7965
        jsr AnyArgument?    ; $7967
        bne L796E    ; $796A
        ldx #$7F    ; $796C
L796E   stx $79AD    ; $796E
        lda BuffTop    ; $7971
        sta $00    ; $7973
        lda $67    ; $7975
        sta $01    ; $7977
        lda $00    ; $7979
        bne L797F    ; $797B
        dec $01    ; $797D
L797F   dec $00    ; $797F
        lda #$8D    ; $7981
L7983   sta $78A1    ; $7983
        jsr NextByte    ; $7986
        bne L79F8    ; $7989
        pha    ; $798B
        and $79AD    ; $798C
        jsr $D054    ; $798F
        pla    ; $7992
        cmp #$89    ; $7993
        bne L799E    ; $7995
        lda #$A0    ; $7997
        jsr $D054    ; $7999
        bne L7983    ; $799C
L799E   cmp #$A2    ; $799E
        beq L79AE    ; $79A0
        cmp #$BB    ; $79A2
        beq L79CE    ; $79A4
        cmp #$AA    ; $79A6
        beq L79D5    ; $79A8
        jmp L7983    ; $79AA
        brk    ; $79AD
L79AE   jsr NextByte    ; $79AE
        bne L79F8    ; $79B1
        pha    ; $79B3
        and $79AD    ; $79B4
        jsr $D054    ; $79B7
        pla    ; $79BA
        cmp #$A2    ; $79BB
        beq L7983    ; $79BD
        cmp #$8D    ; $79BF
        beq L7983    ; $79C1
        cmp #$A0    ; $79C3
        bne L79AE    ; $79C5
        lda #$20    ; $79C7
        jsr $D054    ; $79C9
        bne L79AE    ; $79CC
L79CE   lda $78A1    ; $79CE
        cmp #$A0    ; $79D1
        beq L79DC    ; $79D3
L79D5   lda $78A1    ; $79D5
        cmp #$8D    ; $79D8
        bne L7983    ; $79DA
L79DC   jsr NextByte    ; $79DC
        bne L79F8    ; $79DF
        pha    ; $79E1
        and $79AD    ; $79E2
        jsr $D054    ; $79E5
        pla    ; $79E8
        cmp #$8D    ; $79E9
        beq L7983    ; $79EB
        cmp #$A0    ; $79ED
        bne L79DC    ; $79EF
        lda #$20    ; $79F1
        jsr $D054    ; $79F3
        bne L79DC    ; $79F6
L79F8   jsr SetModified    ; $79F8
L79FB   jsr DisplayPage    ; $79FB
        lda #$01    ; $79FE
        rts    ; $7A00
;
; === PrintDec ===
        sta $7A47    ; $7A01
        stx $7A48    ; $7A04
        ldx #$09    ; $7A07
        stx $7A49    ; $7A09
L7A0C   ldy #$B0    ; $7A0C
L7A0E   lda $7A48    ; $7A0E
        cmp $7A49,x    ; $7A11
        lda $7A47    ; $7A14
        sbc $7A4A,x    ; $7A17
        bcc L7A2B    ; $7A1A
        sta $7A47    ; $7A1C
        lda $7A48    ; $7A1F
        sbc $7A49,x    ; $7A22
        sta $7A48    ; $7A25
        iny    ; $7A28
        bne L7A0E    ; $7A29
L7A2B   tya    ; $7A2B
        dex    ; $7A2C
        beq L7A40    ; $7A2D
        cmp #$B0    ; $7A2F
        beq L7A36    ; $7A31
        sta $7A49    ; $7A33
L7A36   bit $7A49    ; $7A36
        bmi L7A40    ; $7A39
        lda PD:Justify    ; $7A3B
        bpl L7A43    ; $7A3E
L7A40   jsr CharOut    ; $7A40
L7A43   dex    ; $7A43
        bpl L7A0C    ; $7A44
        rts    ; $7A46
        brk    ; $7A47
        brk    ; $7A48
        brk    ; $7A49
        ora ($00,x)    ; $7A4A
        asl    ; $7A4C
        brk    ; $7A4D
        stz $00    ; $7A4E
        inx    ; $7A50
        dfb $03        ; $7A51  (data/65C02-bit)
        bpl L7A7B    ; $7A52
;
; === PD:Justify ===
        brk    ; $7A54
