;-*- Mode: Merlin -*-
;
; src/modules/17_argument.s -- AMACS: numeric/string argument handling, point forward/back
; Address range $7A55-$7DB7. GENERATED by tools/disasm.py.
; `put' from src/amacs.s; symbols/labels are global across modules.
;
; ---- $7A55-$7B84  code ----
;
; === ZeroJustify ===
        lda #$00    ; $7A55
        sta PD:Justify    ; $7A57
        rts    ; $7A5A
;
; === Argument ===
        ora ($00,x)    ; $7A5B
;
; === ExplicitArg ===
        brk    ; $7A5D
;
; === ArgSign ===
        brk    ; $7A5E
        brk    ; $7A5F
;
; === GetArgSign ===
        lda ArgSign    ; $7A60
        pha    ; $7A63
        lda #$00    ; $7A64
        sta ArgSign    ; $7A66
        pla    ; $7A69
        rts    ; $7A6A
;
; === InitArgument ===
        lda #$00    ; $7A6B
        sta ArgSign    ; $7A6D
        sta ExplicitArg    ; $7A70
        sta $7A5F    ; $7A73
        sta $7A5C    ; $7A76
        lda #$01    ; $7A79
L7A7B   sta Argument    ; $7A7B
        rts    ; $7A7E
;
; === AnyArgument? ===
        bit ExplicitArg    ; $7A7F
        bmi L7A98    ; $7A82
        lda $7A5C    ; $7A84
        bne L7A98    ; $7A87
        lda Argument    ; $7A89
        cmp #$01    ; $7A8C
        bne L7A98    ; $7A8E
        lda ArgSign    ; $7A90
        bmi L7A98    ; $7A93
        lda #$FF    ; $7A95
        rts    ; $7A97
L7A98   lda #$00    ; $7A98
        rts    ; $7A9A
;
; === AddArgDigit ===
        pha    ; $7A9B
        lda $7A5C    ; $7A9C
        sta $01    ; $7A9F
        lda Argument    ; $7AA1
        sta $00    ; $7AA4
        asl    ; $7AA6
        rol $7A5C    ; $7AA7
        asl    ; $7AAA
        rol $7A5C    ; $7AAB
        asl    ; $7AAE
        rol $7A5C    ; $7AAF
        asl $00    ; $7AB2
        rol $01    ; $7AB4
        clc    ; $7AB6
        adc $00    ; $7AB7
        sta Argument    ; $7AB9
        lda $7A5C    ; $7ABC
        adc $01    ; $7ABF
        sta $7A5C    ; $7AC1
        pla    ; $7AC4
        clc    ; $7AC5
        adc Argument    ; $7AC6
        sta Argument    ; $7AC9
        bcc L7AD1    ; $7ACC
        inc $7A5C    ; $7ACE
L7AD1   rts    ; $7AD1
;
; === ArgumentDigit ===
        bit $7A5F    ; $7AD2
        bmi L7AE9    ; $7AD5
        pha    ; $7AD7
        lda #$00    ; $7AD8
        sta Argument    ; $7ADA
        sta $7A5C    ; $7ADD
        lda #$FF    ; $7AE0
        sta $7A5F    ; $7AE2
        sta ExplicitArg    ; $7AE5
        pla    ; $7AE8
L7AE9   ora #$80    ; $7AE9
        sec    ; $7AEB
        sbc #$B0    ; $7AEC
        jsr AddArgDigit    ; $7AEE
        pla    ; $7AF1
        pla    ; $7AF2
        jmp L7B29    ; $7AF3
;
; === ZeroArg? ===
        lda HardKey    ; $7AF6
        ora #$80    ; $7AF9
        cmp #$87    ; $7AFB
        bne L7B0A    ; $7AFD
        lda #$00    ; $7AFF
        sta Argument    ; $7B01
        sta $7A5C    ; $7B04
        jsr Beep    ; $7B07
L7B0A   lda Argument    ; $7B0A
        ora $7A5C    ; $7B0D
        rts    ; $7B10
;
; === NegativeArg ===
        jsr InitArgument    ; $7B11
        lda #$FF    ; $7B14
        sta ArgSign    ; $7B16
        jmp L7B29    ; $7B19
        brk    ; $7B1C
;
; === UniversalArg ===
        asl Argument    ; $7B1D
        rol $7A5C    ; $7B20
        asl Argument    ; $7B23
        rol $7A5C    ; $7B26
L7B29   jsr L7B59    ; $7B29
        sta $7B58    ; $7B2C
        ora #$80    ; $7B2F
        cmp #$AD    ; $7B31
        bne L7B42    ; $7B33
        bit ArgSign    ; $7B35
        bmi L7B4D    ; $7B38
        bit ExplicitArg    ; $7B3A
        bmi L7B4D    ; $7B3D
        jmp NegativeArg    ; $7B3F
L7B42   cmp #$B0    ; $7B42
        bcc L7B4D    ; $7B44
        cmp #$BA    ; $7B46
        bcs L7B4D    ; $7B48
        jsr ArgumentDigit    ; $7B4A
L7B4D   lda #$00    ; $7B4D
        sta $7B1C    ; $7B4F
        lda $7B58    ; $7B52
        jmp Dispatch    ; $7B55
        brk    ; $7B58
L7B59   bit $7B1C    ; $7B59
        bpl L7B64    ; $7B5C
        jsr L7B7F    ; $7B5E
        jmp BlinkCursor    ; $7B61
L7B64   lda #$03    ; $7B64
        sta BlinkTime    ; $7B66
        lda CH    ; $7B69
        sta Cursor2    ; $7B6B
        lda CV    ; $7B6E
        sta $28B8    ; $7B70
        jsr TimedBlink    ; $7B73
        beq L7B7E    ; $7B76
        dec $7B1C    ; $7B78
        jmp L7B59    ; $7B7B
L7B7E   rts    ; $7B7E
L7B7F   jsr NewEchoArea    ; $7B7F
        jsr PrintMessage    ; $7B82
; ---- $7B85-$7B89  data  msg: Arg: ----
        dfb $C1,$F2,$E7,$BA,$00    ; $7B85  Arg:.
; ---- $7B8A-$7D22  code ----
        lda #$AD    ; $7B8A
        bit ArgSign    ; $7B8C
        bpl L7B94    ; $7B8F
        jsr CharOut    ; $7B91
L7B94   jsr PrintArgument    ; $7B94
        jmp CloseEchoArea    ; $7B97
;
; === PrintArgument ===
        jsr ZeroJustify    ; $7B9A
        lda $7A5C    ; $7B9D
        ldx Argument    ; $7BA0
        jmp PrintDec    ; $7BA3
        dfb $9B        ; $7BA6  (data/65C02-bit)
;
; === StringArgs ===
        ds 130        ; $7BA7  130 bytes $00 fill
;
; === InitStrArgs ===
        lda #$00    ; $7C29
        sta ArgIndex    ; $7C2B
        sta ArgCount    ; $7C2E
        rts    ; $7C31
;
; === GetStrArg ===
        ldx ArgIndex    ; $7C32
        cpx ArgCount    ; $7C35
        bcs L7C65    ; $7C38
        ldy #$FF    ; $7C3A
L7C3C   iny    ; $7C3C
        bmi L7C65    ; $7C3D
        lda $7BA6,y    ; $7C3F
        cmp #$9B    ; $7C42
        bne L7C3C    ; $7C44
        dex    ; $7C46
        cpx #$FF    ; $7C47
        bne L7C3C    ; $7C49
        inx    ; $7C4B
L7C4C   lda StringArgs,y    ; $7C4C
        cmp #$9B    ; $7C4F
        beq L7C5A    ; $7C51
        sta $0200,x    ; $7C53
        inx    ; $7C56
        iny    ; $7C57
        bpl L7C4C    ; $7C58
L7C5A   lda #$8D    ; $7C5A
        sta $0200,x    ; $7C5C
        inc ArgIndex    ; $7C5F
        lda #$00    ; $7C62
        rts    ; $7C64
L7C65   lda #$FF    ; $7C65
        rts    ; $7C67
;
; === PointForward ===
        lda $61    ; $7C68
        cmp $6B    ; $7C6A
        bcc L7C8F    ; $7C6C
        bne L7C88    ; $7C6E
        lda TheBuffer    ; $7C70
        cmp GapTop    ; $7C72
        bcc L7C8F    ; $7C74
        bne L7C88    ; $7C76
        jsr GapBotPoint    ; $7C78
        cmp $69    ; $7C7B
        bne L7CAB    ; $7C7D
        lda TheBuffer    ; $7C7F
        cmp BuffBot    ; $7C81
        bne L7CAB    ; $7C83
L7C85   lda #$FF    ; $7C85
        rts    ; $7C87
L7C88   jsr PointBuffBot?    ; $7C88
        bne L7CAB    ; $7C8B
        beq L7C85    ; $7C8D
L7C8F   inc TheBuffer    ; $7C8F
        bne L7C95    ; $7C91
        inc $61    ; $7C93
L7C95   lda $61    ; $7C95
        cmp $6B    ; $7C97
        bne L7CB1    ; $7C99
        lda TheBuffer    ; $7C9B
        cmp GapTop    ; $7C9D
        bne L7CB1    ; $7C9F
        jsr GapBotPoint    ; $7CA1
        jsr PointBuffBot?    ; $7CA4
        bne L7CB1    ; $7CA7
        beq L7C85    ; $7CA9
L7CAB   inc TheBuffer    ; $7CAB
        bne L7CB1    ; $7CAD
        inc $61    ; $7CAF
L7CB1   lda #$00    ; $7CB1
        rts    ; $7CB3
;
; === GapBotPoint ===
        lda GapBot    ; $7CB4
        clc    ; $7CB6
        adc #$01    ; $7CB7
        sta TheBuffer    ; $7CB9
        lda $6D    ; $7CBB
        adc #$00    ; $7CBD
        sta $61    ; $7CBF
        rts    ; $7CC1
;
; === PointBuffBot? ===
        lda TheBuffer    ; $7CC2
        cmp BuffBot    ; $7CC4
        bne L7CCC    ; $7CC6
        lda $61    ; $7CC8
        cmp $69    ; $7CCA
L7CCC   rts    ; $7CCC
;
; === PointBackward ===
        ldx GapBot    ; $7CCD
        lda $6D    ; $7CCF
        inx    ; $7CD1
        bne L7CD7    ; $7CD2
        clc    ; $7CD4
        adc #$01    ; $7CD5
L7CD7   cmp $61    ; $7CD7
        beq L7CE8    ; $7CD9
        bcs L7D11    ; $7CDB
L7CDD   lda TheBuffer    ; $7CDD
        bne L7CE3    ; $7CDF
        dec $61    ; $7CE1
L7CE3   dec TheBuffer    ; $7CE3
        lda #$00    ; $7CE5
        rts    ; $7CE7
L7CE8   cpx TheBuffer    ; $7CE8
        bcc L7CDD    ; $7CEA
        bne L7D11    ; $7CEC
        lda GapTop    ; $7CEE
        sbc #$01    ; $7CF0
        sta TheBuffer    ; $7CF2
        lda $6B    ; $7CF4
        sbc #$00    ; $7CF6
        sta $61    ; $7CF8
        cmp $67    ; $7CFA
        bcc L7D06    ; $7CFC
        bne L7CB1    ; $7CFE
        lda TheBuffer    ; $7D00
        cmp BuffTop    ; $7D02
        bcs L7CB1    ; $7D04
L7D06   lda BuffTop    ; $7D06
        sta TheBuffer    ; $7D08
        lda $67    ; $7D0A
        sta $61    ; $7D0C
        lda #$FF    ; $7D0E
        rts    ; $7D10
L7D11   lda $61    ; $7D11
        cmp $67    ; $7D13
        bne L7CDD    ; $7D15
        lda TheBuffer    ; $7D17
        cmp BuffTop    ; $7D19
        bne L7CDD    ; $7D1B
        lda #$FF    ; $7D1D
        rts    ; $7D1F
;
; === GetYOrNp ===
        jsr PrintMessage    ; $7D20
; ---- $7D23-$7D2D  data  msg:  (Y or N)? ----
        dfb $A0,$A8,$D9,$A0,$EF,$F2,$A0,$CE,$A9,$BF,$00    ; $7D23   (Y or N)?.
; ---- $7D2E-$7D99  code ----
L7D2E   jsr BlinkCursor    ; $7D2E
        cmp #$87    ; $7D31
        beq L7D47    ; $7D33
        jsr UpperCon    ; $7D35
        cmp #$CE    ; $7D38
        beq L7D47    ; $7D3A
        cmp #$D9    ; $7D3C
        beq L7D46    ; $7D3E
        jsr Beep    ; $7D40
        jmp L7D2E    ; $7D43
L7D46   rts    ; $7D46
L7D47   ldy #$FF    ; $7D47
        rts    ; $7D49
;
; === ReadAltKey ===
        lda #$FF    ; $7D4A
        sta $B4    ; $7D4C
        jsr BlinkCursor    ; $7D4E
        cmp #$87    ; $7D51
        beq L7D80    ; $7D53
        cmp #$9B    ; $7D55
        bne L7D60    ; $7D57
        jsr print_meta    ; $7D59
        lda #$7F    ; $7D5C
        bne L7D69    ; $7D5E
L7D60   cmp #$9A    ; $7D60
        bne L7D80    ; $7D62
        jsr print_c_meta    ; $7D64
        lda #$3F    ; $7D67
L7D69   sta $B4    ; $7D69
        jsr BlinkCursor    ; $7D6B
        cmp #$87    ; $7D6E
        beq L7D80    ; $7D70
        pha    ; $7D72
        jsr CharOut    ; $7D73
        pla    ; $7D76
        ora #$80    ; $7D77
        jsr UpperCon    ; $7D79
        and $B4    ; $7D7C
        ldx #$FF    ; $7D7E
L7D80   rts    ; $7D80
;
; === HexByteOut ===
        pha    ; $7D81
        lsr    ; $7D82
        lsr    ; $7D83
        lsr    ; $7D84
        lsr    ; $7D85
        jsr L7D8C    ; $7D86
        pla    ; $7D89
        and #$0F    ; $7D8A
L7D8C   ora #$B0    ; $7D8C
        cmp #$BA    ; $7D8E
        bcc L7D94    ; $7D90
        adc #$06    ; $7D92
L7D94   jmp CharOut    ; $7D94
;
; === PrintDone ===
        jsr PrintMessage    ; $7D97
; ---- $7D9A-$7DA1  data  msg: .Done.. ----
        dfb $8D,$C4,$EF,$EE,$E5,$AE,$8D,$00    ; $7D9A  .Done...
; ---- $7DA2-$7DB7  code ----
        rts    ; $7DA2
;
; === PrintReturn ===
        lda #$8D    ; $7DA3
        bne L7DA9    ; $7DA5
;
; === PrintSpace ===
        lda #$A0    ; $7DA7
L7DA9   jmp CharOut    ; $7DA9
;
; === Plurilize ===
        dex    ; $7DAC
        bne L7DB3    ; $7DAD
        tax    ; $7DAF
        bne L7DB3    ; $7DB0
        rts    ; $7DB2
L7DB3   lda #$F3    ; $7DB3
        jmp CharOut    ; $7DB5
