;-*- Mode: Merlin -*-
;
; src/modules/18_ctrlx.s -- AMACS: C-X dispatch tables, key binding, function/key lookup
; Address range $7DB8-$8146. GENERATED by tools/disasm.py.
; `put' from src/amacs.s; symbols/labels are global across modules.
;
; ---- $7DB8-$7DDD  data  C_XCharacters (38 extended-key chars) ----
        dfb $8F,$96,$93,$98,$81,$BD,$BB,$C5,$82,$C2,$CB,$86,$C6,$B1,$B2,$CF    ; $7DB8  .....=;E.BK.F12O
        dfb $DE,$8C,$95,$83,$84,$FF,$94,$8E,$A8,$A9,$97,$C8,$89,$D6,$C3,$C1    ; $7DC8  ^.......().H.VCA
        dfb $91,$AE,$D2,$CD,$D0,$DC    ; $7DD8  ..RMP\
; ---- $7DDE-$7E29  ptrtable  C_XVectors (38 handler addresses) ----
        da  DeleteLines     ; $7DDE  -> $3955
        da  VisitFile       ; $7DE0  -> $6756
        da  SaveFile        ; $7DE2  -> $6A7D
        da  SwapMark        ; $7DE4  -> $7E2B
        da  AutoMode        ; $7DE6  -> $1C10
        da  PointInfo       ; $7DE8  -> $1C48
        da  SetCommCol      ; $7DEA  -> $7E4A
        da  DoLastMacro     ; $7DEC  -> $8B04
        da  ListBuffers     ; $7DEE  -> $4874
        da  SelectBuffer    ; $7DF0  -> $45B1
        da  KillBuffer      ; $7DF2  -> $4A1F
        da  FindFile        ; $7DF4  -> $6BBE
        da  SetFillCol      ; $7DF6  -> $7E3F
        da  OneWindow       ; $7DF8  -> $133F
        da  TwoWindows      ; $7DFA  -> $1223
        da  OtherWindow     ; $7DFC  -> $12C1
        da  GrowWindow      ; $7DFE  -> $137F
        da  LCaseRegion     ; $7E00  -> $8D61
        da  UCaseRegion     ; $7E02  -> $8D75
        da  CCaseRegion     ; $7E04  -> $8D83
        da  FileLister      ; $7E06  -> $6B54
        da  KillSentB       ; $7E08  -> $3AF0
        da  XposeLines      ; $7E0A  -> $8A7D
        da  SetGoalCol      ; $7E0C  -> $7E34
        da  StartMacro      ; $7E0E  -> $8BD9
        da  EndMacro        ; $7E10  -> $8C05
        da  WriteFile       ; $7E12  -> $69CA
        da  MarkBuffer      ; $7E14  -> $4D2F
        da  SetTabsIndent   ; $7E16  -> $1B9D
        da  VisitTags       ; $7E18  -> $9749
        da  CapsMode        ; $7E1A  -> $1C14
        da  AtomMode        ; $7E1C  -> $1C08
        da  ToggleRO        ; $7E1E  -> $7E7B
        da  SetFillPrefix   ; $7E20  -> $20AC
        da  L7E31           ; $7E22  -> $7E31
        da  L7E31           ; $7E24  -> $7E31
        da  L7E31           ; $7E26  -> $7E31
        da  L7E31           ; $7E28  -> $7E31
; ---- $7E2A-$7E2A  data  C_XCharCount ($26 = 38) ----
        dfb $26    ; $7E2A  &
; ---- $7E2B-$7F31  code ----
;
; === SwapMark ===
        jsr SwapPointMark    ; $7E2B
        jsr SetGap    ; $7E2E
L7E31   lda #$01    ; $7E31
        rts    ; $7E33
;
; === SetGoalCol ===
        lda #$08    ; $7E34
        sta $00    ; $7E36
        lda #$34    ; $7E38
        sta $01    ; $7E3A
        jmp L7E52    ; $7E3C
;
; === SetFillCol ===
        lda #$AC    ; $7E3F
        sta $00    ; $7E41
        lda #$1F    ; $7E43
        sta $01    ; $7E45
        jmp L7E52    ; $7E47
;
; === SetCommCol ===
        lda #$FF    ; $7E4A
        sta $00    ; $7E4C
        lda #$1C    ; $7E4E
        sta $01    ; $7E50
L7E52   bit ExplicitArg    ; $7E52
        bpl L7E63    ; $7E55
        lda $7A5C    ; $7E57
        bne L7E63    ; $7E5A
        lda Argument    ; $7E5C
        cmp #$50    ; $7E5F
        bcc L7E74    ; $7E61
L7E63   lda $01    ; $7E63
        pha    ; $7E65
        lda $00    ; $7E66
        pha    ; $7E68
        jsr FindPoint    ; $7E69
        pla    ; $7E6C
        sta $00    ; $7E6D
        pla    ; $7E6F
        sta $01    ; $7E70
        lda CH    ; $7E72
L7E74   ldy #$00    ; $7E74
        sta ($00),y    ; $7E76
        lda #$00    ; $7E78
        rts    ; $7E7A
;
; === ToggleRO ===
        lda #$01    ; $7E7B
        jsr BuffFlagOn?    ; $7E7D
        php    ; $7E80
        lda #$01    ; $7E81
        plp    ; $7E83
        beq L7E8F    ; $7E84
        jsr SetBuffFlag    ; $7E86
L7E89   jsr MakeModeLine    ; $7E89
        lda #$01    ; $7E8C
        rts    ; $7E8E
L7E8F   jsr ClrBuffFlag    ; $7E8F
        jmp L7E89    ; $7E92
;
; === FunPtr ===
        brk    ; $7E95
        brk    ; $7E96
;
; === FindFunKey ===
        jsr FindFunRef    ; $7E97
        ldy #$00    ; $7E9A
        lda ($00),y    ; $7E9C
        pha    ; $7E9E
        iny    ; $7E9F
        lda ($00),y    ; $7EA0
        sta $01    ; $7EA2
        pla    ; $7EA4
        sta $00    ; $7EA5
        rts    ; $7EA7
;
; === FindFunRef ===
        sta $00    ; $7EA8
        lda #$00    ; $7EAA
        sta $01    ; $7EAC
        asl $00    ; $7EAE
        rol $01    ; $7EB0
        lda DispatchTab    ; $7EB2
        clc    ; $7EB5
        adc $00    ; $7EB6
        sta $00    ; $7EB8
        lda $783A    ; $7EBA
        adc $01    ; $7EBD
        sta $01    ; $7EBF
        rts    ; $7EC1
;
; === GetFunName ===
        lda #$37    ; $7EC2
        sta $00    ; $7EC4
        lda #$9B    ; $7EC6
        sta $01    ; $7EC8
L7ECA   ldy #$00    ; $7ECA
        lda ($00),y    ; $7ECC
        beq L7EE3    ; $7ECE
        cmp #$FF    ; $7ED0
        bne L7EE9    ; $7ED2
        iny    ; $7ED4
        lda ($00),y    ; $7ED5
        pha    ; $7ED7
        iny    ; $7ED8
        lda ($00),y    ; $7ED9
        sta $01    ; $7EDB
        pla    ; $7EDD
        sta $00    ; $7EDE
        jmp L7ECA    ; $7EE0
L7EE3   sta $00    ; $7EE3
        sta $01    ; $7EE5
        dey    ; $7EE7
        rts    ; $7EE8
L7EE9   jsr PushCompPoint    ; $7EE9
        jsr FunctionRef    ; $7EEC
        lda $00    ; $7EEF
        cmp FunPtr    ; $7EF1
        bne L7F03    ; $7EF4
        lda $01    ; $7EF6
        cmp $7E96    ; $7EF8
        bne L7F03    ; $7EFB
        jsr PopCompPoint    ; $7EFD
        lda #$00    ; $7F00
        rts    ; $7F02
L7F03   jsr PopCompPoint    ; $7F03
        jsr SkipEnt    ; $7F06
        jmp L7ECA    ; $7F09
        brk    ; $7F0C
        brk    ; $7F0D
        brk    ; $7F0E
;
; === SetKey ===
        jsr ReadFunction    ; $7F0F
        beq L7F17    ; $7F12
L7F14   jmp L808A    ; $7F14
L7F17   jsr OpenEchoArea    ; $7F17
        lda $00    ; $7F1A
        sta $7F0C    ; $7F1C
        lda $01    ; $7F1F
        sta $7F0D    ; $7F21
        bit ExplicitArg    ; $7F24
        bpl L7F2F    ; $7F27
        lda Argument    ; $7F29
        jmp L7F48    ; $7F2C
L7F2F   jsr PrintMessage    ; $7F2F
; ---- $7F32-$7F3F  data  msg: .On what key: ----
        dfb $8D,$CF,$EE,$A0,$F7,$E8,$E1,$F4,$A0,$EB,$E5,$F9,$BA,$00    ; $7F32  .On what key:.
; ---- $7F40-$7F50  code ----
        jsr ReadAltKey    ; $7F40
        bne L7F48    ; $7F43
L7F45   jmp L8082    ; $7F45
L7F48   sta $7F0E    ; $7F48
        jsr Home    ; $7F4B
        jsr PrintMessage    ; $7F4E
; ---- $7F51-$7F55  data  msg: Put ----
        dfb $D0,$F5,$F4,$A0,$00    ; $7F51  Put .
; ---- $7F56-$7F65  code ----
        lda $7F0C    ; $7F56
        sta $00    ; $7F59
        lda $7F0D    ; $7F5B
        sta $01    ; $7F5E
        jsr DCIStringOut    ; $7F60
        jsr PrintMessage    ; $7F63
; ---- $7F66-$7F6A  data  msg:  on ----
        dfb $A0,$EF,$EE,$A0,$00    ; $7F66   on .
; ---- $7F6B-$7FFB  code ----
        lda $7F0E    ; $7F6B
        jsr PrettyPrint    ; $7F6E
        jsr ClearEOL    ; $7F71
        jsr GetYOrNp    ; $7F74
        bne L7F45    ; $7F77
        lda $7F0E    ; $7F79
        jsr FindFunRef    ; $7F7C
        lda $01    ; $7F7F
        pha    ; $7F81
        lda $00    ; $7F82
        pha    ; $7F84
        lda $7F0C    ; $7F85
        sta $00    ; $7F88
        lda $7F0D    ; $7F8A
        sta $01    ; $7F8D
        jsr FunctionRef    ; $7F8F
        lda $00    ; $7F92
        sta $7F0C    ; $7F94
        lda $01    ; $7F97
        sta $7F0D    ; $7F99
        pla    ; $7F9C
        sta $00    ; $7F9D
        pla    ; $7F9F
        sta $01    ; $7FA0
        ldy #$00    ; $7FA2
        lda $7F0C    ; $7FA4
        sta ($00),y    ; $7FA7
        iny    ; $7FA9
        lda $7F0D    ; $7FAA
        sta ($00),y    ; $7FAD
        jmp L7F14    ; $7FAF
;
; === BindIfNot ===
        tax    ; $7FB2
        lda $01    ; $7FB3
        pha    ; $7FB5
        lda $00    ; $7FB6
        pha    ; $7FB8
        txa    ; $7FB9
        jsr FindFunRef    ; $7FBA
        ldy #$00    ; $7FBD
        lda ($00),y    ; $7FBF
        iny    ; $7FC1
        ora ($00),y    ; $7FC2
        beq L7FDE    ; $7FC4
        pla    ; $7FC6
        sta $00    ; $7FC7
        pla    ; $7FC9
        sta $01    ; $7FCA
        rts    ; $7FCC
;
; === UnBindKey ===
        ldx #$00    ; $7FCD
        stx $00    ; $7FCF
        stx $01    ; $7FD1
;
; === BindKey ===
        tax    ; $7FD3
        lda $01    ; $7FD4
        pha    ; $7FD6
        lda $00    ; $7FD7
        pha    ; $7FD9
        txa    ; $7FDA
        jsr FindFunRef    ; $7FDB
L7FDE   ldy #$00    ; $7FDE
        pla    ; $7FE0
        sta ($00),y    ; $7FE1
        pla    ; $7FE3
        iny    ; $7FE4
        sta ($00),y    ; $7FE5
        rts    ; $7FE7
;
; === WhatKey ===
        tsx    ; $7FE8
        stx $8077    ; $7FE9
        lda #$78    ; $7FEC
        sta TypeoutAbort    ; $7FEE
        lda #$80    ; $7FF1
        sta $2A98    ; $7FF3
        jsr NewEchoArea    ; $7FF6
        jsr PrintMessage    ; $7FF9
; ---- $7FFC-$8000  data  msg: M-? ----
        dfb $CD,$AD,$BF,$A0,$00    ; $7FFC  M-? .
; ---- $8001-$8047  code ----
        jsr ReadAltKey    ; $8001
        bne L8009    ; $8004
        jmp L8082    ; $8006
L8009   sta $7F0E    ; $8009
        jsr CloseEchoArea    ; $800C
        jsr OpenTypeout    ; $800F
        lda $7F0E    ; $8012
        cmp #$98    ; $8015
        bne L801C    ; $8017
        jmp WhatCtrlX    ; $8019
L801C   jsr FindFunKey    ; $801C
        lda $00    ; $801F
        sta FunPtr    ; $8021
        lda $01    ; $8024
        sta $7E96    ; $8026
        jsr GetFunName    ; $8029
        lda $7F0E    ; $802C
        jsr PrettyPrint    ; $802F
        lda $01    ; $8032
        bne L803C    ; $8034
        jsr PrUnDefined    ; $8036
        jmp L803F    ; $8039
L803C   jsr PrFunDoc    ; $803C
L803F   jsr CloseTypeout    ; $803F
        lda #$01    ; $8042
        rts    ; $8044
;
; === PrFunDoc ===
        jsr PrintMessage    ; $8045
; ---- $8048-$805B  data  msg:  runs the function ----
        dfb $A0,$F2,$F5,$EE,$F3,$A0,$F4,$E8,$E5,$A0,$E6,$F5,$EE,$E3,$F4,$E9    ; $8048   runs the functi
        dfb $EF,$EE,$A0,$00    ; $8058  on .
; ---- $805C-$8071  code ----
        tya    ; $805C
        jsr DCIStringOut1    ; $805D
        jsr PrintMessage    ; $8060
        tsx    ; $8063
        sta: $0089    ; $8064
        jsr DocRef    ; $8067
        lda #$08    ; $806A
        jsr DCIStringOut1    ; $806C
        jsr PrintMessage    ; $806F
; ---- $8072-$8075  data  msg: ... ----
        dfb $AE,$8D,$8D,$00    ; $8072  ....
; ---- $8076-$80AE  code ----
        rts    ; $8076
        brk    ; $8077
L8078   ldx $8077    ; $8078
        txs    ; $807B
        jsr CloseTypeout1    ; $807C
        lda #$01    ; $807F
        rts    ; $8081
L8082   jsr Beep    ; $8082
        lda #$87    ; $8085
        jsr CharOut    ; $8087
L808A   jsr CloseEchoArea    ; $808A
        lda #$01    ; $808D
        rts    ; $808F
;
; === WhatCtrlX ===
        lda #$98    ; $8090
        jsr PrettyPrint    ; $8092
        lda #$9C    ; $8095
        sta $00    ; $8097
        lda #$BE    ; $8099
        sta $01    ; $809B
        lda #$00    ; $809D
        jsr DCIStringOut1    ; $809F
        jsr BlinkCursor    ; $80A2
        cmp #$87    ; $80A5
        beq L8078    ; $80A7
        sta $7F0E    ; $80A9
        jsr PrintMessage    ; $80AC
; ---- $80AF-$80B1  data  msg: .. ----
        dfb $8D,$8D,$00    ; $80AF  ...
; ---- $80B2-$8146  code ----
        lda $7F0E    ; $80B2
        cmp #$AA    ; $80B5
        beq L80E2    ; $80B7
        cmp #$80    ; $80B9
        bcc L80CE    ; $80BB
        jsr UpperCon    ; $80BD
        jsr FindXKey    ; $80C0
        bne L80CE    ; $80C3
        lda $7F0E    ; $80C5
        jsr PrCtrlXDoc    ; $80C8
        jmp L803F    ; $80CB
L80CE   lda #$98    ; $80CE
        jsr PrettyPrint    ; $80D0
        jsr PrintSpace    ; $80D3
        lda $7F0E    ; $80D6
        jsr PrettyPrint    ; $80D9
        jsr PrUnDefined    ; $80DC
        jmp L803F    ; $80DF
L80E2   ldx #$00    ; $80E2
        stx $7F0C    ; $80E4
L80E7   ldx $7F0C    ; $80E7
        cpx C_XCharCount    ; $80EA
        bcs L8105    ; $80ED
        lda C_XCharacters,x    ; $80EF
        sta $7F0E    ; $80F2
        jsr FindXKey    ; $80F5
        bne L8100    ; $80F8
        lda $7F0E    ; $80FA
        jsr PrCtrlXDoc    ; $80FD
L8100   inc $7F0C    ; $8100
        bne L80E7    ; $8103
L8105   jsr PrintDone    ; $8105
        jmp L803F    ; $8108
;
; === FindXKey ===
        ldx #$00    ; $810B
L810D   cpx C_XCharCount    ; $810D
        bcs L811A    ; $8110
        cmp C_XCharacters,x    ; $8112
        beq L811C    ; $8115
        inx    ; $8117
        bne L810D    ; $8118
L811A   inx    ; $811A
        rts    ; $811B
L811C   txa    ; $811C
        asl    ; $811D
        tax    ; $811E
        lda C_XVectors,x    ; $811F
        sta FunPtr    ; $8122
        lda $7DDF,x    ; $8125
        sta $7E96    ; $8128
        jsr GetFunName    ; $812B
        lda $01    ; $812E
        beq L811A    ; $8130
        lda #$00    ; $8132
        rts    ; $8134
;
; === PrCtrlXDoc ===
        pha    ; $8135
        lda #$98    ; $8136
        jsr PrettyPrint    ; $8138
        lda #$A0    ; $813B
        jsr CharOut    ; $813D
        pla    ; $8140
        jsr PrettyPrint    ; $8141
        jmp PrFunDoc    ; $8144
