;-*- Mode: Merlin -*-
;
; src/modules/19_mode.s -- AMACS: major/minor mode setup, help
; Address range $8147-$846E. GENERATED by tools/disasm.py.
; `put' from src/amacs.s; symbols/labels are global across modules.
;
; ---- $8147-$8396  code ----
;
; === DefMajor ===
        brk    ; $8147
;
; === TheModes ===
        sbc ($81)    ; $8148
        lda ($81),y    ; $814A
        adc $6D81,x    ; $814C
        sta ($5A,x)    ; $814F
        sta ($C6,x)    ; $8151
        sta ($F2,x)    ; $8153
        sta ($F2,x)    ; $8155
        sta ($F2,x)    ; $8157
        sta ($A9,x)    ; $8159
        php    ; $815B
        sta $00    ; $815C
        lda #$83    ; $815E
        sta $01    ; $8160
        jsr SetModeComm    ; $8162
        jsr BlockBind    ; $8165
        lda #$04    ; $8168
        jmp ModeFinish    ; $816A
;
; === MODE:Lisp ===
        lda #$05    ; $816D
        sta $00    ; $816F
        lda #$83    ; $8171
        sta $01    ; $8173
        jsr SetModeComm    ; $8175
        lda #$03    ; $8178
        jmp ModeFinish    ; $817A
;
; === MODE:Merlin ===
        lda #$05    ; $817D
        sta $00    ; $817F
        lda #$83    ; $8181
        sta $01    ; $8183
        jsr SetModeComm    ; $8185
        lda #$65    ; $8188
        sta $00    ; $818A
        lda #$79    ; $818C
        sta $01    ; $818E
        lda #$0D    ; $8190
        jsr BindKey    ; $8192
        lda #$E0    ; $8195
        sta $00    ; $8197
        lda #$78    ; $8199
        sta $01    ; $819B
        lda #$4D    ; $819D
        jsr BindKey    ; $819F
        lda #$02    ; $81A2
        eor #$FF    ; $81A4
        ldy #$40    ; $81A6
        and (BuffData),y    ; $81A8
        sta (BuffData),y    ; $81AA
        lda #$02    ; $81AC
        jmp ModeFinish    ; $81AE
;
; === MODE:Text ===
        lda #$03    ; $81B1
        sta $00    ; $81B3
        lda #$83    ; $81B5
        sta $01    ; $81B7
        jsr SetModeComm    ; $81B9
        lda #$02    ; $81BC
        jsr SetMinorMd    ; $81BE
        lda #$01    ; $81C1
        jmp ModeFinish    ; $81C3
;
; === MODE:Pascal ===
        lda #$0E    ; $81C6
        sta $00    ; $81C8
        lda #$83    ; $81CA
        sta $01    ; $81CC
        jsr SetModeComm    ; $81CE
        jsr BlockBind    ; $81D1
        lda #$05    ; $81D4
        jmp ModeFinish    ; $81D6
;
; === BlockBind ===
        lda #$04    ; $81D9
        jsr SetMinorMd    ; $81DB
        lda #$72    ; $81DE
        sta $00    ; $81E0
        lda #$25    ; $81E2
        sta $01    ; $81E4
        lda #$0D    ; $81E6
        jmp BindKey    ; $81E8
;
; === SetMinorMd ===
        ldy #$40    ; $81EB
        ora (BuffData),y    ; $81ED
        sta (BuffData),y    ; $81EF
        rts    ; $81F1
;
; === MODE:Fund ===
        lda #$05    ; $81F2
        sta $00    ; $81F4
        lda #$83    ; $81F6
        sta $01    ; $81F8
        jsr SetModeComm    ; $81FA
        lda #$00    ; $81FD
;
; === ModeFinish ===
        ldy #$3F    ; $81FF
        sta (BuffData),y    ; $8201
        cmp #$06    ; $8203
        bcc L8209    ; $8205
        lda #$00    ; $8207
L8209   asl    ; $8209
        tax    ; $820A
        lda $D0A5,x    ; $820B
        sta $00    ; $820E
        lda $D0A6,x    ; $8210
        sta $01    ; $8213
        ldy #$09    ; $8215
L8217   lda ($00),y    ; $8217
        sta TabTable,y    ; $8219
        dey    ; $821C
        bpl L8217    ; $821D
        jsr MakeModeLine    ; $821F
        lda #$01    ; $8222
        rts    ; $8224
;
; === SetModeComm ===
        ldy #$FF    ; $8225
L8227   iny    ; $8227
        lda ($00),y    ; $8228
        sta CommentBegin,y    ; $822A
        bne L8227    ; $822D
        ldx #$FF    ; $822F
L8231   iny    ; $8231
        inx    ; $8232
        lda ($00),y    ; $8233
        sta CommentEnd,x    ; $8235
        bne L8231    ; $8238
        rts    ; $823A
        lda $ADAA    ; $823B
        brk    ; $823E
;
; === ParseMode ===
        lda #$3B    ; $823F
        sta StringPntr    ; $8241
        lda #$82    ; $8244
        sta $1D0B    ; $8246
        jsr StringInLine    ; $8249
        bne L8291    ; $824C
        ldy #$00    ; $824E
L8250   jsr $D000    ; $8250
        ora #$80    ; $8253
        cmp #$8D    ; $8255
        beq L8291    ; $8257
        cmp #$BA    ; $8259
        beq L8260    ; $825B
        iny    ; $825D
        bne L8250    ; $825E
L8260   ldx #$00    ; $8260
L8262   iny    ; $8262
        jsr $D000    ; $8263
        ora #$80    ; $8266
        cmp #$A0    ; $8268
        beq L8262    ; $826A
        cmp #$89    ; $826C
        beq L8262    ; $826E
L8270   jsr $D000    ; $8270
        ora #$80    ; $8273
        jsr UpperCon    ; $8275
        sta $0200,x    ; $8278
        inx    ; $827B
        bmi L8291    ; $827C
        cmp #$89    ; $827E
        beq L8292    ; $8280
        cmp #$A0    ; $8282
        beq L8292    ; $8284
        cmp #$8D    ; $8286
        beq L8292    ; $8288
        cmp #$AD    ; $828A
        beq L8292    ; $828C
        iny    ; $828E
        bne L8270    ; $828F
L8291   rts    ; $8291
L8292   lda #$00    ; $8292
        sta $01FF,x    ; $8294
        jsr SI:ParseMode    ; $8297
        bne L8291    ; $829A
;
; === SelectMode ===
        pha    ; $829C
        lda #$84    ; $829D
        sta DispatchTab    ; $829F
        lda #$4F    ; $82A2
        sta $783A    ; $82A4
        pla    ; $82A7
        asl    ; $82A8
        tax    ; $82A9
        lda TheModes,x    ; $82AA
        sta $00    ; $82AD
        lda $8149,x    ; $82AF
        sta $01    ; $82B2
        jmp ($0000)    ; $82B4
;
; === SI:ParseMode ===
        lda #$6A    ; $82B7
        sta $00    ; $82B9
        lda #$53    ; $82BB
        sta $01    ; $82BD
;
; === SI:ListScan ===
        ldx #$00    ; $82BF
        stx $04    ; $82C1
L82C3   ldy $04    ; $82C3
        lda ($00),y    ; $82C5
        sta $02    ; $82C7
        iny    ; $82C9
        lda ($00),y    ; $82CA
        beq L82E9    ; $82CC
        sta $03    ; $82CE
        iny    ; $82D0
        sty $04    ; $82D1
        ldy #$00    ; $82D3
        ldx #$00    ; $82D5
L82D7   lda ($02),y    ; $82D7
        bmi L82EC    ; $82D9
        ora #$80    ; $82DB
        jsr UpperCon    ; $82DD
        cmp $0200,x    ; $82E0
        bne L82C3    ; $82E3
        iny    ; $82E5
        inx    ; $82E6
        bpl L82D7    ; $82E7
L82E9   lda #$FF    ; $82E9
        rts    ; $82EB
L82EC   jsr UpperCon    ; $82EC
        cmp $0200,x    ; $82EF
        bne L82C3    ; $82F2
        inx    ; $82F4
        lda $0200,x    ; $82F5
        bne L82C3    ; $82F8
        php    ; $82FA
        lda $04    ; $82FB
        lsr    ; $82FD
        sec    ; $82FE
        sbc #$01    ; $82FF
        plp    ; $8301
        rts    ; $8302
        brk    ; $8303
        brk    ; $8304
        dfb $BB        ; $8305  (data/65C02-bit)
        brk    ; $8306
        brk    ; $8307
        dfb $AF        ; $8308  (data/65C02-bit)
        tax    ; $8309
        brk    ; $830A
        tax    ; $830B
        dfb $AF        ; $830C  (data/65C02-bit)
        brk    ; $830D
        dfb $FB        ; $830E  (data/65C02-bit)
        brk    ; $830F
        sbc $E800,x    ; $8310
        sbc $EC    ; $8313
        beq $82C6    ; $8315
        sbc ($ED,x)    ; $8317
        sbc ($E3,x)    ; $8319
        dfb $F3        ; $831B  (data/65C02-bit)
        ldx $E5E8    ; $831C
        cpx $B0F0    ; $831F
        brk    ; $8322
;
; === SystemPath ===
        dfb $AF        ; $8323  (data/65C02-bit)
        sbc ($ED,x)    ; $8324
        sbc ($E3,x)    ; $8326
        dfb $F3        ; $8328  (data/65C02-bit)
        dfb $AF        ; $8329  (data/65C02-bit)
        ds 42        ; $832A  42 bytes $00 fill
        dfb $9F        ; $8354  (data/65C02-bit)
;
; === SetSysPath ===
        ldy #$00    ; $8355
L8357   lda SystemPath,y    ; $8357
        sta $0200,y    ; $835A
        beq L8362    ; $835D
        iny    ; $835F
        bne L8357    ; $8360
L8362   dey    ; $8362
        lda #$AF    ; $8363
        cmp $0200,y    ; $8365
        beq L836E    ; $8368
        iny    ; $836A
        sta $0200,y    ; $836B
L836E   iny    ; $836E
        lda #$8D    ; $836F
        sta $0200,y    ; $8371
        rts    ; $8374
;
; === GetHelpFile ===
        sta $8321    ; $8375
        jsr SetSysPath    ; $8378
        lda #$12    ; $837B
        sta $00    ; $837D
        lda #$83    ; $837F
        sta $01    ; $8381
        jsr SetMyFile    ; $8383
        jsr DSK:OpenFile    ; $8386
        bne L8390    ; $8389
        jsr PrepRead    ; $838B
        lda #$00    ; $838E
L8390   rts    ; $8390
;
; === Help ===
        jsr NewEchoArea    ; $8391
        jsr PrintMessage    ; $8394
; ---- $8397-$83A8  data  msg: Doc (? for Help): ----
        dfb $C4,$EF,$E3,$A0,$A8,$BF,$A0,$E6,$EF,$F2,$A0,$C8,$E5,$EC,$F0,$A9    ; $8397  Doc (? for Help)
        dfb $BA,$00    ; $83A7  :.
; ---- $83A9-$846E  code ----
        jsr BlinkCursor    ; $83A9
        pha    ; $83AC
        jsr CloseEchoArea    ; $83AD
        pla    ; $83B0
        jsr L83B7    ; $83B1
        jmp Help    ; $83B4
L83B7   ldx #$00    ; $83B7
        jsr UpperCon    ; $83B9
L83BC   cmp $83E9,x    ; $83BC
        beq L83CA    ; $83BF
        inx    ; $83C1
        cpx #$0A    ; $83C2
        bcc L83BC    ; $83C4
        jsr Beep    ; $83C6
        rts    ; $83C9
L83CA   cpx #$07    ; $83CA
        bcs L83D1    ; $83CC
        sta $8354    ; $83CE
L83D1   pla    ; $83D1
        pla    ; $83D2
        txa    ; $83D3
        asl    ; $83D4
        tax    ; $83D5
        lda $83F3,x    ; $83D6
        sta CommandVector    ; $83D9
        sta $00    ; $83DC
        lda $83F4,x    ; $83DE
        sta $7835    ; $83E1
        sta $01    ; $83E4
        jmp ($0000)    ; $83E6
        cmp ($CC,x)    ; $83E9
        cpy $C3    ; $83EB
        dec $BF,x    ; $83ED
        dfb $9F        ; $83EF  (data/65C02-bit)
        dfb $87        ; $83F0  (data/65C02-bit)
        dfb $FF        ; $83F1  (data/65C02-bit)
        ldy #$91    ; $83F2
        stz $CD    ; $83F4
        trb Describe    ; $83F6
        inx    ; $83F9
        dfb $7F        ; $83FA  (data/65C02-bit)
        bcs $8462    ; $83FB
        asl $1E84,x    ; $83FD
        sty $13    ; $8400
        sty $0D    ; $8402
        sty $07    ; $8404
        sty $AD    ; $8406
        dfb $54        ; $8408  (data/65C02-bit)
        dfb $83        ; $8409  (data/65C02-bit)
        jsr L83B7    ; $840A
        jsr ClrEchoArea    ; $840D
L8410   lda #$01    ; $8410
        rts    ; $8412
        jsr Beep    ; $8413
        lda #$87    ; $8416
        jsr EchoOutput    ; $8418
        jmp L8410    ; $841B
        lda UseTabTable?    ; $841E
        pha    ; $8421
        lda #$00    ; $8422
        sta UseTabTable?    ; $8424
        lda #$B0    ; $8427
        jsr GetHelpFile    ; $8429
        php    ; $842C
        jsr InitTypeout    ; $842D
        jsr OpenTypeout    ; $8430
        lda #$50    ; $8433
        sta TypeoutAbort    ; $8435
        lda #$84    ; $8438
        sta $2A98    ; $843A
        plp    ; $843D
        bne L844D    ; $843E
L8440   jsr DSK:ReadByte    ; $8440
        bne L8450    ; $8443
        ora #$80    ; $8445
        jsr CharOut    ; $8447
        jmp L8440    ; $844A
L844D   jsr Beep    ; $844D
L8450   jsr CloseTypeout1    ; $8450
        pla    ; $8453
        sta UseTabTable?    ; $8454
        jmp Help    ; $8457
;
; === SetMyFile ===
        tya    ; $845A
        tax    ; $845B
        ldy #$00    ; $845C
L845E   lda ($00),y    ; $845E
        sta $0200,x    ; $8460
        beq L8469    ; $8463
        iny    ; $8465
        inx    ; $8466
        bne L845E    ; $8467
L8469   lda #$8D    ; $8469
        sta $0200,x    ; $846B
        rts    ; $846E
