;-*- Mode: Merlin -*-
;
; src/modules/21_transpose.s -- AMACS: accumulate lines, transpose chars/lines
; Address range $8971-$8AA4. GENERATED by tools/disasm.py.
; `put' from src/amacs.s; symbols/labels are global across modules.
;
; ---- $8971-$8AA4  code ----
;
; === AccumLines ===
        jsr L8939    ; $8971
        jsr ClrLastKill    ; $8974
        jsr SetGap    ; $8977
        lda TheBuffer    ; $897A
        sta $87AC    ; $897C
        lda $61    ; $897F
        sta $87AD    ; $8981
        lda #$00    ; $8984
        sta $F0    ; $8986
        lda #$02    ; $8988
        sta $F1    ; $898A
L898C   jsr SetGap    ; $898C
        jsr TecoSearch    ; $898F
        bne L89C7    ; $8992
        lda $00    ; $8994
        sta TheBuffer    ; $8996
        lda $01    ; $8998
        sta $61    ; $899A
        jsr BegOfLine    ; $899C
        jsr SetGap    ; $899F
        lda #$FF    ; $89A2
        sta ExplicitArg    ; $89A4
        lda ArgSign    ; $89A7
        pha    ; $89AA
        eor #$FF    ; $89AB
        sta DeleteKill?    ; $89AD
        lda #$01    ; $89B0
        sta Argument    ; $89B2
        lda #$00    ; $89B5
        sta $7A5C    ; $89B7
        sta ArgSign    ; $89BA
        jsr KillLine    ; $89BD
        pla    ; $89C0
        sta ArgSign    ; $89C1
        jmp L898C    ; $89C4
L89C7   lda $87AC    ; $89C7
        sta TheBuffer    ; $89CA
        lda $87AD    ; $89CC
        sta $61    ; $89CF
        jsr SetGap    ; $89D1
        lda #$01    ; $89D4
        ldx ArgSign    ; $89D6
        bpl L89DD    ; $89D9
        lda #$02    ; $89DB
L89DD   rts    ; $89DD
;
; === XCharMove ===
        brk    ; $89DE
;
; === EOLorEOB? ===
        lda GapBot    ; $89DF
        clc    ; $89E1
        adc #$01    ; $89E2
        tay    ; $89E4
        lda $6D    ; $89E5
        adc #$00    ; $89E7
        cmp $69    ; $89E9
        bcc L89F2    ; $89EB
        cpy BuffBot    ; $89ED
        bcc L89F2    ; $89EF
        rts    ; $89F1
L89F2   ldy #$01    ; $89F2
        jsr $D03F    ; $89F4
        cmp #$8D    ; $89F7
        rts    ; $89F9
;
; === XposeChars ===
        bit XCharMove    ; $89FA
        bmi L8A53    ; $89FD
        jsr EOLorEOB?    ; $89FF
        beq L8A53    ; $8A02
        jsr PointBackward    ; $8A04
        bne L8A50    ; $8A07
        ldy #$00    ; $8A09
        jsr $D01B    ; $8A0B
        pha    ; $8A0E
        ldy #$01    ; $8A0F
        jsr $D03F    ; $8A11
        dey    ; $8A14
        jsr $D06F    ; $8A15
        sta $B4    ; $8A18
        pla    ; $8A1A
        iny    ; $8A1B
        jsr $D093    ; $8A1C
        sta $B5    ; $8A1F
        lda GapBot    ; $8A21
        sta TheBuffer    ; $8A23
        lda $6D    ; $8A25
        sta $61    ; $8A27
        inc TheBuffer    ; $8A29
        bne L8A2F    ; $8A2B
        inc $61    ; $8A2D
L8A2F   inc TheBuffer    ; $8A2F
        bne L8A35    ; $8A31
        inc $61    ; $8A33
L8A35   jsr SetGap    ; $8A35
        jsr FindPoint    ; $8A38
L8A3B   lda $B4    ; $8A3B
        cmp #$8D    ; $8A3D
        beq L8A47    ; $8A3F
        lda $B5    ; $8A41
        cmp #$8D    ; $8A43
        bne L8A4A    ; $8A45
L8A47   jsr DispToPoint    ; $8A47
L8A4A   lda #$03    ; $8A4A
        rts    ; $8A4C
L8A4D   jsr PointForward    ; $8A4D
L8A50   lda #$00    ; $8A50
        rts    ; $8A52
L8A53   jsr PointBackward    ; $8A53
        bne L8A50    ; $8A56
        jsr PointBackward    ; $8A58
        bne L8A4D    ; $8A5B
        ldy #$00    ; $8A5D
        jsr $D01B    ; $8A5F
        sta $B4    ; $8A62
        pha    ; $8A64
        iny    ; $8A65
        jsr $D01B    ; $8A66
        sta $B5    ; $8A69
        dey    ; $8A6B
        jsr $D06F    ; $8A6C
        iny    ; $8A6F
        pla    ; $8A70
        jsr $D06F    ; $8A71
        jsr PointForward    ; $8A74
        jsr PointForward    ; $8A77
        jmp L8A3B    ; $8A7A
;
; === XposeLines ===
        jsr InitArgument    ; $8A7D
        dec ExplicitArg    ; $8A80
        jsr BegOfLine    ; $8A83
        jsr SetGap    ; $8A86
        jsr ClrLastKill    ; $8A89
        jsr KillLine    ; $8A8C
        jsr PointBackward    ; $8A8F
        jsr BegOfLine    ; $8A92
        jsr YankKill    ; $8A95
        jsr PointBackward    ; $8A98
        jsr BegOfLine    ; $8A9B
        rts    ; $8A9E
        ds 6        ; $8A9F  6 bytes $00 fill
