;-*- Mode: Merlin -*-
;
; src/modules/22_macro.s -- AMACS: keyboard macro definition/execution
; Address range $8AA5-$8C2A. GENERATED by tools/disasm.py.
; `put' from src/amacs.s; symbols/labels are global across modules.
;
; ---- $8AA5-$8AA6  data  MacroExec / MacroDef state flags ----
        dfb $00,$00    ; $8AA5  ..
; ---- $8AA7-$8C2A  code ----
;
; === ViewKbdMacro ===
        jsr OpenTypeout    ; $8AA7
        sta UseAuxZP    ; $8AAA   <== BANK: aux zero-page/stack (ALTZP on)
        lda #$00    ; $8AAD
        sta $02    ; $8AAF
        lda #$D6    ; $8AB1
        sta $03    ; $8AB3
        sta UseMainZP    ; $8AB5   <== BANK: main zero-page/stack (ALTZP off)
        lda $8A9F    ; $8AB8
        sta $8B02    ; $8ABB
        lda $8AA0    ; $8ABE
        sta $8B03    ; $8AC1
L8AC4   lda $8B02    ; $8AC4
        ora $8B03    ; $8AC7
        beq L8AF6    ; $8ACA
        ldy #$00    ; $8ACC
        sta UseAuxZP    ; $8ACE   <== BANK: aux zero-page/stack (ALTZP on)
        lda ($02),y    ; $8AD1
        sta UseMainZP    ; $8AD3   <== BANK: main zero-page/stack (ALTZP off)
        jsr PrettyPrint    ; $8AD6
        jsr PrintSpace    ; $8AD9
        sta UseAuxZP    ; $8ADC   <== BANK: aux zero-page/stack (ALTZP on)
        inc $02    ; $8ADF
        bne L8AE5    ; $8AE1
        inc $03    ; $8AE3
L8AE5   sta UseMainZP    ; $8AE5   <== BANK: main zero-page/stack (ALTZP off)
        lda $8B02    ; $8AE8
        bne L8AF0    ; $8AEB
        dec $8B03    ; $8AED
L8AF0   dec $8B02    ; $8AF0
        jmp L8AC4    ; $8AF3
L8AF6   jsr PrintReturn    ; $8AF6
        jsr PrintDone    ; $8AF9
        jsr CloseTypeout    ; $8AFC
        lda #$01    ; $8AFF
        rts    ; $8B01
        brk    ; $8B02
        brk    ; $8B03
;
; === DoLastMacro ===
        lda Argument    ; $8B04
        sta $8AA3    ; $8B07
        lda $7A5C    ; $8B0A
        sta $8AA4    ; $8B0D
        lda #$00    ; $8B10
        sta $8AA1    ; $8B12
        sta $8AA2    ; $8B15
        lda #$FF    ; $8B18
        sta MacroExec    ; $8B1A
        lda #$01    ; $8B1D
        rts    ; $8B1F
;
; === KeyToMac ===
        php    ; $8B20
        bit MacroDef    ; $8B21
        bpl L8B63    ; $8B24
        pha    ; $8B26
        sty $8B66    ; $8B27
        stx $8B65    ; $8B2A
        sta UseAuxZP    ; $8B2D   <== BANK: aux zero-page/stack (ALTZP on)
        ldy $8AA0    ; $8B30
        cpy #$01    ; $8B33
        bcc L8B47    ; $8B35
        ldy $8A9F    ; $8B37
        cpy #$FF    ; $8B3A
        bcc L8B47    ; $8B3C
        sta UseMainZP    ; $8B3E   <== BANK: main zero-page/stack (ALTZP off)
        jsr EndMacro    ; $8B41
        jmp L8B5C    ; $8B44
L8B47   ldy #$00    ; $8B47
        sta ($00),y    ; $8B49
        inc $00    ; $8B4B
        bne L8B51    ; $8B4D
        inc $01    ; $8B4F
L8B51   sta UseMainZP    ; $8B51   <== BANK: main zero-page/stack (ALTZP off)
        inc $8A9F    ; $8B54
        bne L8B5C    ; $8B57
        inc $8AA0    ; $8B59
L8B5C   ldx $8B65    ; $8B5C
        ldy $8B66    ; $8B5F
        pla    ; $8B62
L8B63   plp    ; $8B63
        rts    ; $8B64
        brk    ; $8B65
        brk    ; $8B66
;
; === KeyFromMac ===
        sty $8B66    ; $8B67
        stx $8B65    ; $8B6A
        lda $8AA1    ; $8B6D
        ora $8AA2    ; $8B70
        beq L8BA0    ; $8B73
        lda $8AA1    ; $8B75
        bne L8B7D    ; $8B78
        dec $8AA2    ; $8B7A
L8B7D   dec $8AA1    ; $8B7D
        ldy #$00    ; $8B80
        sta UseAuxZP    ; $8B82   <== BANK: aux zero-page/stack (ALTZP on)
        lda ($00),y    ; $8B85
        sta UseMainZP    ; $8B87   <== BANK: main zero-page/stack (ALTZP off)
        jsr PushTYI    ; $8B8A
        sta UseAuxZP    ; $8B8D   <== BANK: aux zero-page/stack (ALTZP on)
        inc $00    ; $8B90
        bne L8B96    ; $8B92
        inc $01    ; $8B94
L8B96   sta UseMainZP    ; $8B96   <== BANK: main zero-page/stack (ALTZP off)
L8B99   ldx $8B65    ; $8B99
        ldy $8B66    ; $8B9C
        rts    ; $8B9F
L8BA0   lda $8AA3    ; $8BA0
        ora $8AA4    ; $8BA3
        beq L8BCE    ; $8BA6
        lda $8AA3    ; $8BA8
        bne L8BB0    ; $8BAB
        dec $8AA4    ; $8BAD
L8BB0   dec $8AA3    ; $8BB0
        sta UseAuxZP    ; $8BB3   <== BANK: aux zero-page/stack (ALTZP on)
        lda #$00    ; $8BB6
        sta $00    ; $8BB8
        lda #$D6    ; $8BBA
        sta $01    ; $8BBC
        sta UseMainZP    ; $8BBE   <== BANK: main zero-page/stack (ALTZP off)
        lda $8A9F    ; $8BC1
        sta $8AA1    ; $8BC4
        lda $8AA0    ; $8BC7
        sta $8AA2    ; $8BCA
        rts    ; $8BCD
L8BCE   jsr EndMacroExec    ; $8BCE
        beq L8B99    ; $8BD1
;
; === EndMacroExec ===
        lda #$00    ; $8BD3
        sta MacroExec    ; $8BD5
        rts    ; $8BD8
;
; === StartMacro ===
        bit MacroExec    ; $8BD9
        bmi L8BFC    ; $8BDC
        lda #$FF    ; $8BDE
        sta MacroDef    ; $8BE0
        sta UseAuxZP    ; $8BE3   <== BANK: aux zero-page/stack (ALTZP on)
        lda #$00    ; $8BE6
        sta $00    ; $8BE8
        lda #$D6    ; $8BEA
        sta $01    ; $8BEC
        sta UseMainZP    ; $8BEE   <== BANK: main zero-page/stack (ALTZP off)
        lda #$00    ; $8BF1
        sta $8A9F    ; $8BF3
        sta $8AA0    ; $8BF6
        jsr MakeModeLine    ; $8BF9
L8BFC   lda #$01    ; $8BFC
        rts    ; $8BFE
L8BFF   jsr Beep    ; $8BFF
        lda #$01    ; $8C02
        rts    ; $8C04
;
; === EndMacro ===
        bit MacroExec    ; $8C05
        bmi L8C28    ; $8C08
        bit MacroDef    ; $8C0A
        bpl L8BFF    ; $8C0D
        lda $8A9F    ; $8C0F
        sec    ; $8C12
        sbc #$02    ; $8C13
        sta $8A9F    ; $8C15
        lda $8AA0    ; $8C18
        sbc #$00    ; $8C1B
        sta $8AA0    ; $8C1D
        lda #$00    ; $8C20
        sta MacroDef    ; $8C22
        jsr MakeModeLine    ; $8C25
L8C28   lda #$01    ; $8C28
        rts    ; $8C2A
