;-*- Mode: Merlin -*-
;
; src/modules/23_region.s -- AMACS: region operations (case, copy, kill, fill, indent)
; Address range $8C2B-$8F33. GENERATED by tools/disasm.py.
; `put' from src/amacs.s; symbols/labels are global across modules.
;
; ---- $8C2B-$8C2C  data  RegionQSize (region-query threshold, default $01F4=500) ----
        dfb $F4,$01    ; $8C2B  t.
; ---- $8C2D-$8C4B  code ----
L8C2D   lda TheBuffer    ; $8C2D
        sec    ; $8C2F
        sbc $00    ; $8C30
        tax    ; $8C32
        lda $61    ; $8C33
        sbc $01    ; $8C35
        cmp $8C2C    ; $8C37
        bcc L8CAB    ; $8C3A
        bne L8C43    ; $8C3C
        cpx RegionQSize    ; $8C3E
        bcc L8CAB    ; $8C41
L8C43   pha    ; $8C43
        txa    ; $8C44
        pha    ; $8C45
        jsr NewEchoArea    ; $8C46
        jsr PrintMessage    ; $8C49
; ---- $8C4C-$8C64  data  msg: You are about to act on ----
        dfb $D9,$EF,$F5,$A0,$E1,$F2,$E5,$A0,$E1,$E2,$EF,$F5,$F4,$A0,$F4,$EF    ; $8C4C  You are about to
        dfb $A0,$E1,$E3,$F4,$A0,$EF,$EE,$A0,$00    ; $8C5C   act on .
; ---- $8C65-$8C70  code ----
        sty PD:Justify    ; $8C65
        pla    ; $8C68
        tax    ; $8C69
        pla    ; $8C6A
        jsr PrintDec    ; $8C6B
        jsr PrintMessage    ; $8C6E
; ---- $8C71-$8C95  data  msg:  characters, do you want to continue ----
        dfb $A0,$E3,$E8,$E1,$F2,$E1,$E3,$F4,$E5,$F2,$F3,$AC,$A0,$E4,$EF,$A0    ; $8C71   characters, do 
        dfb $F9,$EF,$F5,$A0,$F7,$E1,$EE,$F4,$A0,$F4,$EF,$A0,$E3,$EF,$EE,$F4    ; $8C81  you want to cont
        dfb $E9,$EE,$F5,$E5,$00    ; $8C91  inue.
; ---- $8C96-$8DC1  code ----
        jsr GetYOrNp    ; $8C96
        php    ; $8C99
        pha    ; $8C9A
        jsr CharOut    ; $8C9B
        jsr CloseEchoArea    ; $8C9E
        pla    ; $8CA1
        cmp #$87    ; $8CA2
        bne L8CA9    ; $8CA4
        jsr Beep    ; $8CA6
L8CA9   plp    ; $8CA9
        rts    ; $8CAA
L8CAB   lda #$00    ; $8CAB
        rts    ; $8CAD
;
; === TheRegion ===
        ds 5        ; $8CAE  5 bytes $00 fill
;
; === OpenRegion ===
        jsr SetGap    ; $8CB3
        jsr GetTempMark    ; $8CB6
        lda #$FF    ; $8CB9
        sta $8CB2    ; $8CBB
        lda $01    ; $8CBE
        cmp $61    ; $8CC0
        bcc L8CE0    ; $8CC2
        bne L8CCE    ; $8CC4
        lda $00    ; $8CC6
        cmp TheBuffer    ; $8CC8
        bcc L8CE0    ; $8CCA
        beq L8CE0    ; $8CCC
L8CCE   inc $8CB2    ; $8CCE
        lda $61    ; $8CD1
        pha    ; $8CD3
        lda TheBuffer    ; $8CD4
        pha    ; $8CD6
        jsr L8D2B    ; $8CD7
        pla    ; $8CDA
        sta $00    ; $8CDB
        pla    ; $8CDD
        sta $01    ; $8CDE
L8CE0   lda $00    ; $8CE0
        sta TheRegion    ; $8CE2
        lda $01    ; $8CE5
        sta $8CAF    ; $8CE7
        lda TheBuffer    ; $8CEA
        sta $8CB0    ; $8CEC
        lda $61    ; $8CEF
        sta $8CB1    ; $8CF1
        rts    ; $8CF4
;
; === CloseRegion ===
        lda $8CB0    ; $8CF5
        sta TheBuffer    ; $8CF8
        lda $8CB1    ; $8CFA
        sta $61    ; $8CFD
        bit $8CB2    ; $8CFF
        bmi L8D0E    ; $8D02
        lda TheRegion    ; $8D04
        sta TheBuffer    ; $8D07
        lda $8CAF    ; $8D09
        sta $61    ; $8D0C
L8D0E   lda $61    ; $8D0E
        cmp $6B    ; $8D10
        bcc L8D1E    ; $8D12
        bne L8D1F    ; $8D14
        lda TheBuffer    ; $8D16
        cmp GapTop    ; $8D18
        bcc L8D1E    ; $8D1A
        bne L8D1F    ; $8D1C
L8D1E   rts    ; $8D1E
L8D1F   lda TheBuffer    ; $8D1F
        sta $00    ; $8D21
        lda $61    ; $8D23
        sta $01    ; $8D25
        jsr L8D2B    ; $8D27
        rts    ; $8D2A
L8D2B   lda $00    ; $8D2B
        sec    ; $8D2D
        sbc GapTop    ; $8D2E
        sta $00    ; $8D30
        lda $01    ; $8D32
        sbc $6B    ; $8D34
        sta $01    ; $8D36
        lda $00    ; $8D38
        sec    ; $8D3A
        adc GapBot    ; $8D3B
        sta TheBuffer    ; $8D3D
        lda $01    ; $8D3F
        adc $6D    ; $8D41
        sta $61    ; $8D43
        lda $61    ; $8D45
        cmp $69    ; $8D47
        bcc L8D5D    ; $8D49
        bne L8D55    ; $8D4B
        lda TheBuffer    ; $8D4D
        cmp BuffBot    ; $8D4F
        bcc L8D5D    ; $8D51
        beq L8D5D    ; $8D53
L8D55   lda BuffBot    ; $8D55
        sta TheBuffer    ; $8D57
        lda $69    ; $8D59
        sta $61    ; $8D5B
L8D5D   jsr SetGap    ; $8D5D
        rts    ; $8D60
;
; === LCaseRegion ===
        jsr OpenRegion    ; $8D61
        jsr L8C2D    ; $8D64
        bne L8D6C    ; $8D67
        jsr IN:LowerReg    ; $8D69
L8D6C   jsr CloseRegion    ; $8D6C
        jsr DisplayPage    ; $8D6F
        lda #$01    ; $8D72
        rts    ; $8D74
;
; === UCaseRegion ===
        jsr OpenRegion    ; $8D75
        jsr L8C2D    ; $8D78
        bne L8D6C    ; $8D7B
        jsr IN:UpperReg    ; $8D7D
        jmp L8D6C    ; $8D80
;
; === CCaseRegion ===
        jsr OpenRegion    ; $8D83
        jsr L8C2D    ; $8D86
        bne L8D6C    ; $8D89
        jsr IN:CapReg    ; $8D8B
        jmp L8D6C    ; $8D8E
        brk    ; $8D91
;
; === CopyRegion ===
        lda #$FF    ; $8D92
        sta DeleteKill?    ; $8D94
        sta $8D91    ; $8D97
;
; === KRegion ===
        jsr OpenRegion    ; $8D9A
        jsr KillTempPoint    ; $8D9D
        lda #$00    ; $8DA0
        bit $8D91    ; $8DA2
        bmi L8DAA    ; $8DA5
        sta $8CB2    ; $8DA7
L8DAA   sta $8D91    ; $8DAA
        jmp L8D6C    ; $8DAD
;
; === CLinesRegion ===
        jsr CLInternal    ; $8DB0
        jsr NewEchoArea    ; $8DB3
        lda $8E09    ; $8DB6
        ldx LsInReg    ; $8DB9
        jsr PrintDec    ; $8DBC
        jsr PrintMessage    ; $8DBF
; ---- $8DC2-$8DD3  data  msg:  lines in Region. ----
        dfb $A0,$EC,$E9,$EE,$E5,$F3,$A0,$E9,$EE,$A0,$D2,$E5,$E7,$E9,$EF,$EE    ; $8DC2   lines in Region
        dfb $AE,$00    ; $8DD2  ..
; ---- $8DD4-$8F33  code ----
        jsr CloseEchoArea    ; $8DD4
        lda #$01    ; $8DD7
        rts    ; $8DD9
;
; === CLInternal ===
        jsr OpenRegion    ; $8DDA
        ldy #$00    ; $8DDD
        sty LsInReg    ; $8DDF
        sty $8E09    ; $8DE2
        sty PD:Justify    ; $8DE5
L8DE8   jsr EqTempPoint?    ; $8DE8
        bne L8DF1    ; $8DEB
        jsr CloseRegion    ; $8DED
        rts    ; $8DF0
L8DF1   jsr $D000    ; $8DF1
        cmp #$8D    ; $8DF4
        bne L8E00    ; $8DF6
        inc LsInReg    ; $8DF8
        bne L8E00    ; $8DFB
        inc $8E09    ; $8DFD
L8E00   inc $00    ; $8E00
        bne L8E06    ; $8E02
        inc $01    ; $8E04
L8E06   bne L8DE8    ; $8E06
;
; === LsInReg ===
        brk    ; $8E08
        brk    ; $8E09
;
; === FillRegion ===
        jsr AnyArgument?    ; $8E0A
        bne L8E14    ; $8E0D
        lda Argument    ; $8E0F
        bne L8E17    ; $8E12
L8E14   lda FillColumn    ; $8E14
L8E17   sta $EF    ; $8E17
        jsr OpenRegion    ; $8E19
L8E1C   ldy #$00    ; $8E1C
        lda $00    ; $8E1E
        bne L8E24    ; $8E20
        dec $01    ; $8E22
L8E24   dec $00    ; $8E24
L8E26   jsr EqTempPoint?    ; $8E26
        beq L8E9B    ; $8E29
        inc $00    ; $8E2B
        bne L8E31    ; $8E2D
        inc $01    ; $8E2F
L8E31   jsr $D000    ; $8E31
        cmp #$8D    ; $8E34
        beq L8E26    ; $8E36
        lda #$00    ; $8E38
        sta $EB    ; $8E3A
L8E3C   sta CH    ; $8E3C
L8E3E   jsr EqTempPoint?    ; $8E3E
        beq L8E9B    ; $8E41
        jsr $D000    ; $8E43
        cmp #$A0    ; $8E46
        beq L8E6D    ; $8E48
        cmp #$8D    ; $8E4A
        bne L8E77    ; $8E4C
        inc $00    ; $8E4E
        bne L8E54    ; $8E50
        inc $01    ; $8E52
L8E54   jsr EqTempPoint?    ; $8E54
        beq L8E9B    ; $8E57
        jsr $D000    ; $8E59
        cmp #$8D    ; $8E5C
        beq L8E26    ; $8E5E
        lda $00    ; $8E60
        bne L8E66    ; $8E62
        dec $01    ; $8E64
L8E66   dec $00    ; $8E66
        lda #$A0    ; $8E68
        jsr $D054    ; $8E6A
L8E6D   lda $00    ; $8E6D
        sta $EA    ; $8E6F
        lda $01    ; $8E71
        sta $EB    ; $8E73
        lda #$A0    ; $8E75
L8E77   inc $00    ; $8E77
        bne L8E7D    ; $8E79
        inc $01    ; $8E7B
L8E7D   jsr GetXCharLen    ; $8E7D
        txa    ; $8E80
        clc    ; $8E81
        adc CH    ; $8E82
        sta CH    ; $8E84
        cmp $EF    ; $8E86
        bcc L8E3E    ; $8E88
        lda $EB    ; $8E8A
        beq L8E3C    ; $8E8C
        sta $01    ; $8E8E
        lda $EA    ; $8E90
        sta $00    ; $8E92
        lda #$8D    ; $8E94
        jsr $D054    ; $8E96
        bne L8E1C    ; $8E99
L8E9B   jsr CloseRegion    ; $8E9B
        jsr FindPoint    ; $8E9E
        bne L8EA9    ; $8EA1
        jsr DisplayPage    ; $8EA3
        lda #$01    ; $8EA6
        rts    ; $8EA8
L8EA9   lda #$06    ; $8EA9
        rts    ; $8EAB
;
; === PrintBuffer ===
        jsr MarkBuffer    ; $8EAC
        jsr GenDisplay    ; $8EAF
;
; === PrintRegion ===
        jsr OpenRegion    ; $8EB2
        jsr PrintText    ; $8EB5
        jmp L8D6C    ; $8EB8
;
; === IndentReg ===
        lda Argument    ; $8EBB
        eor ArgSign    ; $8EBE
        sta $8F33    ; $8EC1
        bpl L8EC9    ; $8EC4
        inc $8F33    ; $8EC6
L8EC9   jsr InitArgument    ; $8EC9
        jsr CLInternal    ; $8ECC
        jsr OpenRegion    ; $8ECF
        lda $00    ; $8ED2
        sta TheBuffer    ; $8ED4
        lda $01    ; $8ED6
        sta $61    ; $8ED8
        jsr SetGap    ; $8EDA
L8EDD   jsr BackToIndent    ; $8EDD
        tya    ; $8EE0
        clc    ; $8EE1
        adc $8F33    ; $8EE2
        bpl L8EE9    ; $8EE5
        lda #$00    ; $8EE7
L8EE9   inc IndentVbtm    ; $8EE9
        jsr IndentLine    ; $8EEC
        dec IndentVbtm    ; $8EEF
        lda LsInReg    ; $8EF2
        ora $8E09    ; $8EF5
        bne L8F1C    ; $8EF8
        jsr SetGap    ; $8EFA
        lda TheBuffer    ; $8EFD
        sta $8CB0    ; $8EFF
        lda $61    ; $8F02
        sta $8CB1    ; $8F04
        bit $8CB2    ; $8F07
        bpl L8F19    ; $8F0A
        lda $8CB0    ; $8F0C
        sta $00    ; $8F0F
        lda $8CB1    ; $8F11
        sta $01    ; $8F14
        jsr MarkTemp    ; $8F16
L8F19   jmp L8D6C    ; $8F19
L8F1C   jsr EndOfLine    ; $8F1C
        jsr PointForward    ; $8F1F
        jsr SetGap    ; $8F22
        lda LsInReg    ; $8F25
        bne L8F2D    ; $8F28
        dec $8E09    ; $8F2A
L8F2D   dec LsInReg    ; $8F2D
        jmp L8EDD    ; $8F30
        brk    ; $8F33
