;-*- Mode: Merlin -*-
;
; src/modules/24_hardcopy.s -- AMACS: printer / hardcopy output
; Address range $8F34-$91D7. GENERATED by tools/disasm.py.
; `put' from src/amacs.s; symbols/labels are global across modules.
;
; ---- $8F34-$91D7  code ----
;
; === PrinterSlot ===
        ora ($42,x)    ; $8F34
;
; === PLinesPage ===
        bit $0150,x    ; $8F36
        brk    ; $8F39
;
; === FileLine? ===
        brk    ; $8F3A
;
; === AutoNumber ===
        ora ($DC,x)    ; $8F3B
        ds 37        ; $8F3D  37 bytes $00 fill
L8F62   lda PrinterSlot    ; $8F62
        ora #$C0    ; $8F65
        cmp $37    ; $8F67
        beq L8F7C    ; $8F69
        sta $37    ; $8F6B
        lda #$00    ; $8F6D
        sta $36    ; $8F6F
        sta $8F61    ; $8F71
        inc $8F61    ; $8F74
        lda #$8D    ; $8F77
        jsr PrintOut    ; $8F79
L8F7C   lda #$00    ; $8F7C
        sta $8F52    ; $8F7E
        sta $8F60    ; $8F81
        ldx AutoNumber    ; $8F84
        bmi L8F93    ; $8F87
        beq L8FA1    ; $8F89
        sta $8F39    ; $8F8B
        stx PageNum    ; $8F8E
        bpl L8FA1    ; $8F91
L8F93   lda PageNum    ; $8F93
        lsr    ; $8F96
        bcs L8FA1    ; $8F97
        inc PageNum    ; $8F99
        bne L8FA1    ; $8F9C
        inc $8F39    ; $8F9E
L8FA1   lda PrinterCols    ; $8FA1
        sec    ; $8FA4
        sbc RightMargin    ; $8FA5
        sta $8F53    ; $8FA8
        ldy #$00    ; $8FAB
L8FAD   lda PInitStr,y    ; $8FAD
        beq L8FB8    ; $8FB0
        jsr PrintOut    ; $8FB2
        iny    ; $8FB5
        bne L8FAD    ; $8FB6
L8FB8   rts    ; $8FB8
;
; === PrintOut ===
        pha    ; $8FB9
        lda RdRomBank    ; $8FBA   <== BANK: language-card ROM (read)
        lda RdRomBank    ; $8FBD   <== BANK: language-card ROM (read)
        pla    ; $8FC0
        pha    ; $8FC1
        jsr L8FCD    ; $8FC2
        lda RdWrBank2    ; $8FC5   <== BANK: language-card RAM bank 2 (read+write, BIT twice)
        lda RdWrBank2    ; $8FC8   <== BANK: language-card RAM bank 2 (read+write, BIT twice)
        pla    ; $8FCB
        rts    ; $8FCC
L8FCD   jmp ($0036)    ; $8FCD
L8FD0   lda SheetLines    ; $8FD0
        sec    ; $8FD3
        sbc PLinesPage    ; $8FD4
        lsr    ; $8FD7
        beq L8FF8    ; $8FD8
        pha    ; $8FDA
        bit FileLine?    ; $8FDB
        bpl L8FEB    ; $8FDE
        jsr L8FF9    ; $8FE0
        inc PageNum    ; $8FE3
        bne L8FEB    ; $8FE6
        inc $8F39    ; $8FE8
L8FEB   pla    ; $8FEB
L8FEC   pha    ; $8FEC
        lda #$8D    ; $8FED
        jsr L9102    ; $8FEF
        pla    ; $8FF2
        sec    ; $8FF3
        sbc #$01    ; $8FF4
        bne L8FEC    ; $8FF6
L8FF8   rts    ; $8FF8
L8FF9   lda #$00    ; $8FF9
        sta $8F60    ; $8FFB
        lda LeftMargin    ; $8FFE
        jsr L9090    ; $9001
        lda FileLine?    ; $9004
        cmp #$80    ; $9007
        beq L9040    ; $9009
        cmp #$81    ; $900B
        beq L9015    ; $900D
        lda PageNum    ; $900F
        lsr    ; $9012
        bcs L9040    ; $9013
L9015   jsr L905E    ; $9015
        ldy #$00    ; $9018
        ldx #$00    ; $901A
L901C   lda (BuffData),y    ; $901C
        beq L9024    ; $901E
        iny    ; $9020
        inx    ; $9021
        bne L901C    ; $9022
L9024   stx $903F    ; $9024
        lda $8F53    ; $9027
        sec    ; $902A
        sbc $903F    ; $902B
        cmp $8F60    ; $902E
        bcc L9039    ; $9031
        sbc $8F60    ; $9033
        jsr L9090    ; $9036
L9039   jsr L90A5    ; $9039
        jmp L9057    ; $903C
        brk    ; $903F
L9040   jsr L90A5    ; $9040
        lda $8F53    ; $9043
        sec    ; $9046
        sbc #$05    ; $9047
        cmp $8F60    ; $9049
        bcc L9054    ; $904C
        sbc $8F60    ; $904E
        jsr L9090    ; $9051
L9054   jsr L905E    ; $9054
L9057   lda #$00    ; $9057
        sta $8F60    ; $9059
        tay    ; $905C
        rts    ; $905D
L905E   lda $2607    ; $905E
        pha    ; $9061
        lda CoutDef    ; $9062
        pha    ; $9065
        lda #$B9    ; $9066
        sta CoutDef    ; $9068
        lda #$8F    ; $906B
        sta $2607    ; $906D
        lda #$A0    ; $9070
        sta PD:Justify    ; $9072
        lda $8F39    ; $9075
        ldx PageNum    ; $9078
        jsr PrintDec    ; $907B
        pla    ; $907E
        sta CoutDef    ; $907F
        pla    ; $9082
        sta $2607    ; $9083
        lda #$05    ; $9086
        clc    ; $9088
        adc $8F60    ; $9089
        sta $8F60    ; $908C
        rts    ; $908F
L9090   pha    ; $9090
        pla    ; $9091
        beq L909C    ; $9092
L9094   jsr L909D    ; $9094
        sec    ; $9097
        sbc #$01    ; $9098
        bne L9094    ; $909A
L909C   rts    ; $909C
L909D   pha    ; $909D
        lda #$A0    ; $909E
        jsr PrintOut    ; $90A0
        pla    ; $90A3
        rts    ; $90A4
L90A5   ldy #$00    ; $90A5
L90A7   lda (BuffData),y    ; $90A7
        beq L90B5    ; $90A9
        cmp #$AC    ; $90AB
        beq L90B5    ; $90AD
        jsr PrintOut    ; $90AF
        iny    ; $90B2
        bne L90A7    ; $90B3
L90B5   tya    ; $90B5
        clc    ; $90B6
        adc $8F60    ; $90B7
        sta $8F60    ; $90BA
        rts    ; $90BD
L90BE   lda SheetLines    ; $90BE
        sec    ; $90C1
        sbc $8F61    ; $90C2
        beq L90D5    ; $90C5
        bmi L90D5    ; $90C7
L90C9   pha    ; $90C9
        lda #$8D    ; $90CA
        jsr PrintOut    ; $90CC
        pla    ; $90CF
        sec    ; $90D0
        sbc #$01    ; $90D1
        bne L90C9    ; $90D3
L90D5   lda #$00    ; $90D5
        sta $8F61    ; $90D7
        rts    ; $90DA
        ds 4        ; $90DB  4 bytes $00 fill
L90DF   sta $90DB    ; $90DF
        stx $90DC    ; $90E2
        sty $90DD    ; $90E5
        php    ; $90E8
        php    ; $90E9
        pla    ; $90EA
        sta $90DE    ; $90EB
        lda $90DB    ; $90EE
        plp    ; $90F1
        rts    ; $90F2
L90F3   lda $90DE    ; $90F3
        pha    ; $90F6
        lda $90DB    ; $90F7
        ldx $90DC    ; $90FA
        ldy $90DD    ; $90FD
        plp    ; $9100
        rts    ; $9101
L9102   jsr L90DF    ; $9102
        cmp #$8D    ; $9105
        beq L912E    ; $9107
        cmp #$89    ; $9109
        beq L9155    ; $910B
        cmp #$8C    ; $910D
        beq L914C    ; $910F
        pha    ; $9111
        jsr PrintOut    ; $9112
        ldx #$01    ; $9115
        pla    ; $9117
        cmp #$A0    ; $9118
        bcs L911D    ; $911A
        dex    ; $911C
L911D   txa    ; $911D
        clc    ; $911E
        adc $8F60    ; $911F
        sta $8F60    ; $9122
        cmp $8F53    ; $9125
        bcs L912E    ; $9128
L912A   jsr L90F3    ; $912A
        rts    ; $912D
L912E   lda #$8D    ; $912E
        jsr PrintOut    ; $9130
        inc $8F61    ; $9133
        lda #$00    ; $9136
        sta $8F60    ; $9138
        lda $8F61    ; $913B
        cmp PLinesPage    ; $913E
        bcs L914C    ; $9141
        lda LeftMargin    ; $9143
        jsr L9090    ; $9146
        jmp L912A    ; $9149
L914C   jsr L90BE    ; $914C
        jsr L8FD0    ; $914F
        jmp L912A    ; $9152
L9155   lda $8F60    ; $9155
        jsr TabBump    ; $9158
        cmp PrinterCols    ; $915B
        bcs L912E    ; $915E
        pha    ; $9160
        sec    ; $9161
        sbc $8F60    ; $9162
        beq L916F    ; $9165
L9167   jsr L909D    ; $9167
        sec    ; $916A
        sbc #$01    ; $916B
        bne L9167    ; $916D
L916F   pla    ; $916F
        sta $8F60    ; $9170
        jmp L912A    ; $9173
;
; === PrintText ===
        jsr L8F62    ; $9176
        lda #$8D    ; $9179
        jsr L9102    ; $917B
        bit FileLine?    ; $917E
        bpl L9196    ; $9181
        jsr L8FF9    ; $9183
        inc PageNum    ; $9186
        bne L918E    ; $9189
        inc $8F39    ; $918B
L918E   lda #$8D    ; $918E
        jsr L9102    ; $9190
        jsr L9102    ; $9193
L9196   ldy #$00    ; $9196
L9198   jsr EqTempPoint?    ; $9198
        beq L91B9    ; $919B
        lda HardKey    ; $919D
        ora #$80    ; $91A0
        cmp #$87    ; $91A2
        beq L91B9    ; $91A4
        jsr $D000    ; $91A6
        cmp HCEscape    ; $91A9
        beq L91BD    ; $91AC
        jsr L9102    ; $91AE
L91B1   inc $00    ; $91B1
        bne L91B7    ; $91B3
        inc $01    ; $91B5
L91B7   bne L9198    ; $91B7
L91B9   jsr L90BE    ; $91B9
        rts    ; $91BC
L91BD   ldx #$00    ; $91BD
        lda $8F52    ; $91BF
        eor #$FF    ; $91C2
        sta $8F52    ; $91C4
        bmi L91CB    ; $91C7
        ldx #$0A    ; $91C9
L91CB   lda ContextBeg,x    ; $91CB
        beq L91B1    ; $91CE
        jsr PrintOut    ; $91D0
        inx    ; $91D3
        bpl L91CB    ; $91D4
        bmi L91B1    ; $91D6
