;-*- Mode: Merlin -*-
;
; src/modules/25_library.s -- AMACS: library loader
; Address range $91D8-$945B. GENERATED by tools/disasm.py.
; `put' from src/amacs.s; symbols/labels are global across modules.
;
; ---- $91D8-$9200  code ----
;
; === BaseLibAddr ===
        brk    ; $91D8
        cld    ; $91D9
;
; === LibCount ===
        brk    ; $91DA
        cpx $E2E9    ; $91DB
        dfb $AF        ; $91DE  (data/65C02-bit)
        ldx $A0    ; $91DF
        cmp #$EE    ; $91E1
        sbc #$F4    ; $91E3
        ldy #$20    ; $91E5
        dfb $7F        ; $91E7  (data/65C02-bit)
        ply    ; $91E8
        bne SI:LoadLib    ; $91E9
        lda ArgSign    ; $91EB
        bmi L91F3    ; $91EE
        jsr InitArgument    ; $91F0
L91F3   jsr FlushLibs    ; $91F3
;
; === SI:LoadLib ===
        jsr GetStrArg    ; $91F6
        beq L9224    ; $91F9
        jsr NewEchoArea    ; $91FB
        jsr PrintMessage    ; $91FE
; ---- $9201-$9209  data  msg: Library: ----
        dfb $CC,$E9,$E2,$F2,$E1,$F2,$F9,$BA,$00    ; $9201  Library:.
; ---- $920A-$92C5  code ----
        jsr ReadArgLine    ; $920A
        php    ; $920D
        txa    ; $920E
        pha    ; $920F
        jsr CloseEchoArea    ; $9210
        pla    ; $9213
        tax    ; $9214
        plp    ; $9215
        bne L921B    ; $9216
        txa    ; $9218
        bne L9224    ; $9219
L921B   jsr ClrEchoArea    ; $921B
        jsr Beep    ; $921E
L9221   lda #$01    ; $9221
        rts    ; $9223
L9224   jsr IN:LibLoad    ; $9224
        bne L921B    ; $9227
        lda $00    ; $9229
        sta $B2    ; $922B
        lda $01    ; $922D
        sta $B3    ; $922F
        lda #$37    ; $9231
        sta $00    ; $9233
        lda #$9B    ; $9235
        sta $01    ; $9237
        jsr GetLinkEnd    ; $9239
        lda #$FF    ; $923C
        sta ($00),y    ; $923E
        iny    ; $9240
        lda $B2    ; $9241
        sta ($00),y    ; $9243
        iny    ; $9245
        lda $B3    ; $9246
        sta ($00),y    ; $9248
        lda $B2    ; $924A
        sta $00    ; $924C
        lda $B3    ; $924E
        sta $01    ; $9250
        lda #$00    ; $9252
        jsr L9352    ; $9254
        lda $00    ; $9257
        clc    ; $9259
        adc #$03    ; $925A
        pha    ; $925C
        lda $01    ; $925D
        adc #$00    ; $925F
        pha    ; $9261
        lda #$5D    ; $9262
        sta $00    ; $9264
        lda #$97    ; $9266
        sta $01    ; $9268
        jsr GetLinkEnd    ; $926A
        lda #$FF    ; $926D
        sta ($00),y    ; $926F
        iny    ; $9271
        iny    ; $9272
        pla    ; $9273
        sta ($00),y    ; $9274
        dey    ; $9276
        pla    ; $9277
        sta ($00),y    ; $9278
        pha    ; $927A
        iny    ; $927B
        lda ($00),y    ; $927C
        sta $01    ; $927E
        pla    ; $9280
        sta $00    ; $9281
        lda #$FF    ; $9283
        jsr L9352    ; $9285
        ldy #$00    ; $9288
L928A   lda $91DF,y    ; $928A
        sta $0200,y    ; $928D
        iny    ; $9290
        cpy #$07    ; $9291
        bcc L928A    ; $9293
        jsr L9322    ; $9295
        lda #$37    ; $9298
        sta CompList    ; $929A
        lda #$9B    ; $929D
        sta $5988    ; $929F
        dey    ; $92A2
        lda #$9B    ; $92A3
        sta $0200,y    ; $92A5
        jsr SI:CompleteMe    ; $92A8
        lda CompCount    ; $92AB
        cmp #$01    ; $92AE
        bne L92B8    ; $92B0
        jsr FunctionRef    ; $92B2
        jsr CallTemp    ; $92B5
L92B8   jmp L9221    ; $92B8
;
; === FlushLibs ===
        jsr AnyArgument?    ; $92BB
        beq SI:FlushLibs    ; $92BE
        jsr NewEchoArea    ; $92C0
        jsr PrintMessage    ; $92C3
; ---- $92C6-$92D5  data  msg: Flush libraries ----
        dfb $C6,$EC,$F5,$F3,$E8,$A0,$EC,$E9,$E2,$F2,$E1,$F2,$E9,$E5,$F3,$00    ; $92C6  Flush libraries.
; ---- $92D6-$945B  code ----
        jsr GetYOrNp    ; $92D6
        php    ; $92D9
        jsr CloseEchoArea    ; $92DA
        plp    ; $92DD
        bne L930D    ; $92DE
;
; === SI:FlushLibs ===
        lda #$5D    ; $92E0
        sta $00    ; $92E2
        lda #$97    ; $92E4
        sta $01    ; $92E6
        jsr GetCompLink    ; $92E8
        ldy #$00    ; $92EB
        tya    ; $92ED
        sta ($00),y    ; $92EE
        lda #$37    ; $92F0
        sta $00    ; $92F2
        lda #$9B    ; $92F4
        sta $01    ; $92F6
        jsr GetCompLink    ; $92F8
        ldy #$00    ; $92FB
        tya    ; $92FD
        sta ($00),y    ; $92FE
        sta LibCount    ; $9300
        lda #$00    ; $9303
        sta BaseLibAddr    ; $9305
        lda #$D8    ; $9308
        sta $91D9    ; $930A
L930D   lda #$01    ; $930D
        rts    ; $930F
;
; === CopyLibPfx ===
        jsr SetSysPath    ; $9310
        ldx #$00    ; $9313
L9315   lda $91DB,x    ; $9315
        sta $0200,y    ; $9318
        iny    ; $931B
        inx    ; $931C
        cpx #$04    ; $931D
        bcc L9315    ; $931F
        rts    ; $9321
L9322   ldx LibCount    ; $9322
        dex    ; $9325
        txa    ; $9326
        asl    ; $9327
        asl    ; $9328
        asl    ; $9329
        asl    ; $932A
        tax    ; $932B
L932C   lda LibNames,x    ; $932C
        sta $0200,y    ; $932F
        inx    ; $9332
        iny    ; $9333
        cmp #$8D    ; $9334
        bne L932C    ; $9336
        rts    ; $9338
;
; === GetLinkEnd ===
        jsr GetCompLink    ; $9339
        ldy #$00    ; $933C
        lda ($00),y    ; $933E
        beq L9351    ; $9340
        iny    ; $9342
        lda ($00),y    ; $9343
        pha    ; $9345
        iny    ; $9346
        lda ($00),y    ; $9347
        sta $01    ; $9349
        pla    ; $934B
        sta $00    ; $934C
        jmp GetLinkEnd    ; $934E
L9351   rts    ; $9351
L9352   sta $04    ; $9352
L9354   ldy #$00    ; $9354
        lda ($00),y    ; $9356
        bne L935B    ; $9358
        rts    ; $935A
L935B   lda ($00),y    ; $935B
        php    ; $935D
        iny    ; $935E
        plp    ; $935F
        bmi L935B    ; $9360
        ldx #$02    ; $9362
L9364   lda ($00),y    ; $9364
        clc    ; $9366
        adc $B2    ; $9367
        sta ($00),y    ; $9369
        iny    ; $936B
        lda ($00),y    ; $936C
        adc $B3    ; $936E
        sta ($00),y    ; $9370
        iny    ; $9372
        dex    ; $9373
        bne L9364    ; $9374
        bit $04    ; $9376
        bpl L939B    ; $9378
        tya    ; $937A
        pha    ; $937B
        dey    ; $937C
        dey    ; $937D
        dey    ; $937E
        dey    ; $937F
        lda ($00),y    ; $9380
        sta $02    ; $9382
        iny    ; $9384
        lda ($00),y    ; $9385
        sta $03    ; $9387
        ldy #$02    ; $9389
        lda ($02),y    ; $938B
        clc    ; $938D
        adc $B2    ; $938E
        sta ($02),y    ; $9390
        iny    ; $9392
        lda ($02),y    ; $9393
        adc $B3    ; $9395
        sta ($02),y    ; $9397
        pla    ; $9399
        tay    ; $939A
L939B   tya    ; $939B
        clc    ; $939C
        adc $00    ; $939D
        sta $00    ; $939F
        bcc L93A5    ; $93A1
        inc $01    ; $93A3
L93A5   jmp L9354    ; $93A5
;
; === IN:LibLoad ===
        jsr AddLibName    ; $93A8
        bne L93DD    ; $93AB
        jsr CopyLibPfx    ; $93AD
        jsr L9322    ; $93B0
        jsr DSK:OpenFile    ; $93B3
        bne L93DA    ; $93B6
        jsr PrepRead    ; $93B8
        lda BaseLibAddr    ; $93BB
        sta $00    ; $93BE
        lda $91D9    ; $93C0
        sta $01    ; $93C3
L93C5   jsr DSK:ReadByte    ; $93C5
        bne L93E3    ; $93C8
        ldy #$00    ; $93CA
        sta ($00),y    ; $93CC
        inc $00    ; $93CE
        bne L93D4    ; $93D0
        inc $01    ; $93D2
L93D4   lda $01    ; $93D4
        cmp #$E0    ; $93D6
        bcc L93C5    ; $93D8
L93DA   dec LibCount    ; $93DA
L93DD   jsr DSK:CloseFile    ; $93DD
        lda #$FF    ; $93E0
        rts    ; $93E2
L93E3   ldx #$01    ; $93E3
L93E5   lda $00,x    ; $93E5
        pha    ; $93E7
        lda BaseLibAddr,x    ; $93E8
        sta $00,x    ; $93EB
        pla    ; $93ED
        sta BaseLibAddr,x    ; $93EE
        dex    ; $93F1
        bpl L93E5    ; $93F2
        jsr DSK:CloseFile    ; $93F4
        lda #$00    ; $93F7
        rts    ; $93F9
;
; === AddLibName ===
        lda LibCount    ; $93FA
        cmp #$08    ; $93FD
        bcs L9435    ; $93FF
        ldy #$00    ; $9401
L9403   lda $0200,y    ; $9403
        ora #$80    ; $9406
        jsr UpperCon    ; $9408
        sta $0200,y    ; $940B
        iny    ; $940E
        cmp #$8D    ; $940F
        bne L9403    ; $9411
        ldx #$00    ; $9413
        stx $04    ; $9415
        ldy #$00    ; $9417
        lda $04    ; $9419
        cmp LibCount    ; $941B
        bcs L943C    ; $941E
        asl    ; $9420
        asl    ; $9421
        asl    ; $9422
        asl    ; $9423
        tax    ; $9424
L9425   lda $0200,y    ; $9425
        cmp LibNames,x    ; $9428
        bne L9438    ; $942B
        cmp #$8D    ; $942D
        beq L9435    ; $942F
        iny    ; $9431
        inx    ; $9432
        bne L9425    ; $9433
L9435   lda #$FF    ; $9435
        rts    ; $9437
L9438   inc $04    ; $9438
        bne L943C    ; $943A
L943C   lda LibCount    ; $943C
        asl    ; $943F
        asl    ; $9440
        asl    ; $9441
        asl    ; $9442
        tay    ; $9443
        ldx #$00    ; $9444
L9446   lda $0200,x    ; $9446
        sta LibNames,y    ; $9449
        inx    ; $944C
        cpx #$10    ; $944D
        bcs L9456    ; $944F
        iny    ; $9451
        cmp #$8D    ; $9452
        bne L9446    ; $9454
L9456   inc LibCount    ; $9456
        lda #$00    ; $9459
        rts    ; $945B
