;-*- Mode: Merlin -*-
;
; src/modules/26_tags.s -- AMACS: tags (find definition) + *TAGS* buffer
; Address range $945C-$975C. GENERATED by tools/disasm.py.
; `put' from src/amacs.s; symbols/labels are global across modules.
;
; ---- $945C-$9480  data  TheTag (*TAGS* buffer name + zeroed buffer) ----
        dfb $AA,$D4,$C1,$C7,$D3,$AA,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00    ; $945C  *TAGS*..........
        dfb $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00    ; $946C  ................
        dfb $00,$00,$00,$00,$00    ; $947C  .....
; ---- $9481-$94E5  code ----
;
; === TagsFindFile ===
        dfb $FF        ; $9481  (data/65C02-bit)
        ds 6        ; $9482  6 bytes $00 fill
;
; === GetTagBuff ===
        ldy #$FF    ; $9488
L948A   iny    ; $948A
        lda $945C,y    ; $948B
        sta $0200,y    ; $948E
        bne L948A    ; $9491
        jsr FindBuffer    ; $9493
        bne L94D0    ; $9496
        cpx SelectedBuff    ; $9498
        bne L94B3    ; $949B
        jsr KillGap    ; $949D
        lda BuffTop    ; $94A0
        sta $00    ; $94A2
        lda $67    ; $94A4
        sta $01    ; $94A6
        lda GapTop    ; $94A8
        sta $02    ; $94AA
        lda $6B    ; $94AC
        sta $03    ; $94AE
        jmp L94C4    ; $94B0
L94B3   jsr PointToBInfo    ; $94B3
        ldy #$0E    ; $94B6
        ldx #$00    ; $94B8
L94BA   lda (BuffPoint),y    ; $94BA
        sta $00,x    ; $94BC
        iny    ; $94BE
        inx    ; $94BF
        cpx #$04    ; $94C0
        bcc L94BA    ; $94C2
L94C4   lda $00    ; $94C4
        sta $9482    ; $94C6
        lda $01    ; $94C9
        sta $9483    ; $94CB
        lda #$00    ; $94CE
L94D0   rts    ; $94D0
        brk    ; $94D1
;
; === ScanForTag ===
        lda #$00    ; $94D2
        beq L94D8    ; $94D4
;
; === WhatTagFile ===
        lda #$FF    ; $94D6
L94D8   sta $94D1    ; $94D8
        jsr GetTagBuff    ; $94DB
        beq L9506    ; $94DE
        jsr NewEchoArea    ; $94E0
        jsr PrintMessage    ; $94E3
; ---- $94E6-$94FC  data  msg: Missing buffer *TAGS*. ----
        dfb $CD,$E9,$F3,$F3,$E9,$EE,$E7,$A0,$E2,$F5,$E6,$E6,$E5,$F2,$A0,$AA    ; $94E6  Missing buffer *
        dfb $D4,$C1,$C7,$D3,$AA,$AE,$00    ; $94F6  TAGS*..
; ---- $94FD-$96B8  code ----
        jsr CloseEchoArea    ; $94FD
        jsr Beep    ; $9500
        lda #$01    ; $9503
        rts    ; $9505
L9506   jsr AnyArgument?    ; $9506
        bne L952E    ; $9509
        lda $00    ; $950B
        clc    ; $950D
        adc $9486    ; $950E
        sta $971E    ; $9511
        lda $01    ; $9514
        adc $9487    ; $9516
        sta $971F    ; $9519
        lda $00    ; $951C
        clc    ; $951E
        adc $9484    ; $951F
        sta $00    ; $9522
        lda $01    ; $9524
        adc $9485    ; $9526
        sta $01    ; $9529
        jmp L9580    ; $952B
L952E   jsr GetStrArg    ; $952E
        beq L956D    ; $9531
        jsr NewEchoArea    ; $9533
        lda #$20    ; $9536
        sta $00    ; $9538
        lda #$97    ; $953A
        sta $01    ; $953C
        bit $94D1    ; $953E
        bpl L954B    ; $9541
        lda #$30    ; $9543
        sta $00    ; $9545
        lda #$97    ; $9547
        sta $01    ; $9549
L954B   jsr DCIStringOut    ; $954B
        jsr ReadArgLine    ; $954E
        php    ; $9551
        txa    ; $9552
        pha    ; $9553
        jsr CloseEchoArea    ; $9554
        pla    ; $9557
        tax    ; $9558
        plp    ; $9559
        bne L955F    ; $955A
        txa    ; $955C
        bne L956D    ; $955D
L955F   bne L9567    ; $955F
        jsr ClrEchoArea    ; $9561
        jmp L956A    ; $9564
L9567   jsr Beep    ; $9567
L956A   lda #$01    ; $956A
        rts    ; $956C
L956D   lda #$8D    ; $956D
        sta $0200,x    ; $956F
        ldx #$1D    ; $9572
L9574   lda $0200,x    ; $9574
        sta TheTag,x    ; $9577
        dex    ; $957A
        bpl L9574    ; $957B
        jsr GetTagBuff    ; $957D
L9580   ldy #$00    ; $9580
L9582   ldx #$00    ; $9582
        jsr $D000    ; $9584
        ora #$80    ; $9587
        cmp #$AF    ; $9589
        beq L95C1    ; $958B
L958D   lda $01    ; $958D
        cmp $03    ; $958F
        bcc L959E    ; $9591
        beq L9598    ; $9593
L9595   jmp L96F9    ; $9595
L9598   lda $00    ; $9598
        cmp $02    ; $959A
        bcs L9595    ; $959C
L959E   jsr $D000    ; $959E
        ora #$80    ; $95A1
        jsr UpperCon    ; $95A3
        sta $971D    ; $95A6
        lda TheTag,x    ; $95A9
        cmp #$8D    ; $95AC
        beq L95E0    ; $95AE
        jsr UpperCon    ; $95B0
        cmp $971D    ; $95B3
        bne L95D1    ; $95B6
        inx    ; $95B8
        inc $00    ; $95B9
        bne L95BF    ; $95BB
        inc $01    ; $95BD
L95BF   bne L958D    ; $95BF
L95C1   lda $00    ; $95C1
        sta $971E    ; $95C3
        lda $01    ; $95C6
        sta $971F    ; $95C8
L95CB   inc $00    ; $95CB
        bne L95D1    ; $95CD
        inc $01    ; $95CF
L95D1   jsr $D000    ; $95D1
        cmp #$8D    ; $95D4
        bne L95CB    ; $95D6
        inc $00    ; $95D8
        bne L95DE    ; $95DA
        inc $01    ; $95DC
L95DE   bne L9582    ; $95DE
L95E0   lda $00    ; $95E0
        sec    ; $95E2
        sbc $9482    ; $95E3
        sta $9484    ; $95E6
        lda $01    ; $95E9
        sbc $9483    ; $95EB
        sta $9485    ; $95EE
        ldx #$00    ; $95F1
        lda $00    ; $95F3
        bne L95F9    ; $95F5
        dec $01    ; $95F7
L95F9   dec $00    ; $95F9
L95FB   inc $00    ; $95FB
        bne L9601    ; $95FD
        inc $01    ; $95FF
L9601   jsr $D000    ; $9601
        ora #$80    ; $9604
        cmp #$8D    ; $9606
        beq L962D    ; $9608
        cmp #$A1    ; $960A
        bne L95FB    ; $960C
L960E   inc $00    ; $960E
        bne L9614    ; $9610
        inc $01    ; $9612
L9614   jsr $D000    ; $9614
        ora #$80    ; $9617
        cmp #$8D    ; $9619
        beq L9627    ; $961B
        cmp #$A1    ; $961D
        beq L962D    ; $961F
        sta $0200,x    ; $9621
        inx    ; $9624
        bne L960E    ; $9625
L9627   lda #$A0    ; $9627
        sta $0200,x    ; $9629
        inx    ; $962C
L962D   lda $00    ; $962D
        bne L9633    ; $962F
        dec $01    ; $9631
L9633   dec $00    ; $9633
        jsr $D000    ; $9635
        cmp #$8D    ; $9638
        bne L962D    ; $963A
        inc $00    ; $963C
        bne L9642    ; $963E
        inc $01    ; $9640
L9642   jsr $D000    ; $9642
        cmp #$A1    ; $9645
        bne L964B    ; $9647
        lda #$8D    ; $9649
L964B   sta $0200,x    ; $964B
        iny    ; $964E
        inx    ; $964F
        cmp #$8D    ; $9650
        bne L9642    ; $9652
L9654   lda $0200,x    ; $9654
        sta TagSpace,x    ; $9657
        dex    ; $965A
        bpl L9654    ; $965B
        inx    ; $965D
        ldy #$00    ; $965E
        lda $971E    ; $9660
        sta $00    ; $9663
        sec    ; $9665
        sbc $9482    ; $9666
        sta $9486    ; $9669
        lda $971F    ; $966C
        sta $01    ; $966F
        sbc $9483    ; $9671
        sta $9487    ; $9674
L9677   jsr $D000    ; $9677
        ora #$80    ; $967A
        sta $0200,x    ; $967C
        cmp #$8D    ; $967F
        beq L968C    ; $9681
        inc $00    ; $9683
        bne L9689    ; $9685
        inc $01    ; $9687
L9689   inx    ; $9689
        bne L9677    ; $968A
L968C   bit $94D1    ; $968C
        bmi L96A4    ; $968F
        jsr PushArg    ; $9691
        lda #$FF    ; $9694
        sta ExplicitArg    ; $9696
        bit TagsFindFile    ; $9699
        bmi L96E3    ; $969C
        jsr VisitFile    ; $969E
        jmp L96E6    ; $96A1
L96A4   jsr NewEchoArea    ; $96A4
        ldx #$00    ; $96A7
L96A9   lda TagSpace,x    ; $96A9
        cmp #$8D    ; $96AC
        beq L96B6    ; $96AE
        jsr CharOut    ; $96B0
        inx    ; $96B3
        bne L96A9    ; $96B4
L96B6   jsr PrintMessage    ; $96B6
; ---- $96B9-$96CA  data  msg:  can be found in ----
        dfb $A0,$E3,$E1,$EE,$A0,$E2,$E5,$A0,$E6,$EF,$F5,$EE,$E4,$A0,$E9,$EE    ; $96B9   can be found in
        dfb $A0,$00    ; $96C9   .
; ---- $96CB-$9706  code ----
L96CB   lda $0200,y    ; $96CB
        cmp #$8D    ; $96CE
        beq L96D8    ; $96D0
        jsr CharOut    ; $96D2
        iny    ; $96D5
        bne L96CB    ; $96D6
L96D8   lda #$AE    ; $96D8
        jsr CharOut    ; $96DA
        jsr CloseEchoArea    ; $96DD
        lda #$01    ; $96E0
        rts    ; $96E2
L96E3   jsr FindFile    ; $96E3
L96E6   ldx #$00    ; $96E6
L96E8   lda TagSpace,x    ; $96E8
        sta $0200,x    ; $96EB
        inx    ; $96EE
        cmp #$8D    ; $96EF
        bne L96E8    ; $96F1
        jsr PushArg    ; $96F3
        jmp LabelSearch    ; $96F6
L96F9   jsr NewEchoArea    ; $96F9
        lda #$A7    ; $96FC
        jsr CharOut    ; $96FE
        jsr L9739    ; $9701
        jsr PrintMessage    ; $9704
; ---- $9707-$9713  data  msg: ' not found. ----
        dfb $A7,$A0,$EE,$EF,$F4,$A0,$E6,$EF,$F5,$EE,$E4,$AE,$00    ; $9707  ' not found..
; ---- $9714-$975C  code ----
        jsr CloseEchoArea    ; $9714
        jsr Beep    ; $9717
        lda #$01    ; $971A
        rts    ; $971C
        brk    ; $971D
        brk    ; $971E
        brk    ; $971F
        cmp $E4    ; $9720
        sbc #$F4    ; $9722
        ldy #$C4    ; $9724
        sbc $E6    ; $9726
        sbc #$EE    ; $9728
        sbc #$F4    ; $972A
        sbc #$EF    ; $972C
        inc $D73A    ; $972E
        inx    ; $9731
        sbc ($F4,x)    ; $9732
        ldy #$D4    ; $9734
        sbc ($E7,x)    ; $9736
        dec    ; $9738
L9739   ldx #$00    ; $9739
L973B   lda TheTag,x    ; $973B
        cmp #$8D    ; $973E
        beq L9748    ; $9740
        jsr CharOut    ; $9742
        inx    ; $9745
        bne L973B    ; $9746
L9748   rts    ; $9748
;
; === VisitTags ===
        ldx #$FF    ; $9749
        stx ExplicitArg    ; $974B
L974E   inx    ; $974E
        lda $945C,x    ; $974F
        sta $0200,x    ; $9752
        bne L974E    ; $9755
        jsr SelectNamed    ; $9757
        jmp VisitFile    ; $975A
