;-*- Mode: Merlin -*-
;
; src/modules/27_vartables.s -- AMACS: variable name/link/doc tables
; Address range $975D-$9B36. GENERATED by tools/disasm.py.
; `put' from src/amacs.s; symbols/labels are global across modules.
;
; ---- $975D-$9A69  data  Variables (variable-name + record table) ----
        dfb $C1,$F5,$F4,$EF,$A0,$C6,$E9,$EC,$E5,$A0,$C5,$F8,$F4,$E5,$EE,$F3    ; $975D  Auto File Extens
        dfb $E9,$EF,$6E,$A5,$9A,$2C,$BB,$C2,$E5,$E5,$F0,$A0,$C2,$EC,$E9,$EE    ; $976D  ion%.,;Beep Blin
        dfb $EB,$F3,$A0,$CD,$EF,$E4,$E5,$EC,$E9,$EE,$65,$8D,$9A,$73,$BA,$C2    ; $977D  ks Modeline..s:B
        dfb $E5,$E5,$F0,$A0,$D2,$E9,$EE,$E7,$F3,$A0,$C2,$E5,$EC,$6C,$91,$9A    ; $978D  eep Rings Bell..
        dfb $93,$BA,$C2,$EC,$E9,$EE,$EB,$E5,$F2,$A0,$D3,$F0,$E5,$E5,$64,$89    ; $979D  .:Blinker Speed.
        dfb $9A,$59,$BA,$C3,$E1,$F3,$E5,$A0,$D2,$E5,$F0,$EC,$E1,$E3,$65,$A1    ; $97AD  .Y:Case Replace!
        dfb $9A,$04,$BB,$C3,$E1,$F3,$E5,$A0,$D3,$E5,$E1,$F2,$E3,$68,$9D,$9A    ; $97BD  ..;Case Search..
        dfb $E6,$BA,$C3,$EC,$E9,$E3,$EB,$A0,$D6,$EF,$EC,$F5,$ED,$65,$99,$9A    ; $97CD  f:Click Volume..
        dfb $CB,$BA,$C3,$EF,$ED,$ED,$E5,$EE,$F4,$A0,$C2,$E5,$E7,$E9,$6E,$79    ; $97DD  K:Comment Beginy
        dfb $9A,$E0,$B9,$C3,$EF,$ED,$ED,$E5,$EE,$F4,$A0,$C3,$EF,$EC,$F5,$ED    ; $97ED  .`9Comment Colum
        dfb $6E,$75,$9A,$C0,$B9,$C3,$EF,$ED,$ED,$E5,$EE,$F4,$A0,$C5,$EE,$64    ; $97FD  nu.@9Comment End
        dfb $7D,$9A,$F7,$B9,$C3,$EF,$ED,$F0,$E9,$EC,$E5,$F2,$A0,$C6,$E9,$EC    ; $980D  }.w9Compiler Fil
        dfb $E5,$EE,$E1,$ED,$65,$DD,$9A,$5E,$B9,$C3,$F5,$F2,$F3,$EF,$F2,$A0    ; $981D  ename].^9Cursor 
        dfb $C3,$E5,$EE,$F4,$E5,$F2,$E9,$EE,$E7,$A0,$CC,$E9,$EE,$65,$71,$9A    ; $982D  Centering Lineq.
        dfb $9F,$B9,$C4,$E5,$E6,$E1,$F5,$EC,$F4,$A0,$C6,$E9,$EC,$E5,$A0,$D4    ; $983D  .9Default File T
        dfb $F9,$F0,$65,$B9,$9A,$4D,$BB,$C4,$E5,$E6,$E1,$F5,$EC,$F4,$A0,$CD    ; $984D  ype9.M;Default M
        dfb $E1,$EA,$EF,$F2,$A0,$CD,$EF,$E4,$65,$09,$9B,$60,$BE,$C5,$F8,$E9    ; $985D  ajor Mode..`>Exi
        dfb $F4,$A0,$D0,$F2,$EF,$ED,$F0,$74,$0D,$9B,$4E,$50,$C6,$E9,$EC,$EC    ; $986D  t Prompt..NPFill
        dfb $A0,$C3,$EF,$EC,$F5,$ED,$6E,$6D,$9A,$7A,$B9,$C7,$EF,$E1,$EC,$A0    ; $987D   Columnm.z9Goal 
        dfb $C3,$EF,$EC,$F5,$ED,$6E,$D1,$9A,$3C,$BC,$C8,$C3,$A0,$C1,$F5,$F4    ; $988D  ColumnQ.<<HC Aut
        dfb $EF,$A0,$CE,$F5,$ED,$E2,$E5,$72,$A9,$9A,$13,$BE,$C8,$C3,$A0,$C3    ; $989D  o Number)..>HC C
        dfb $EF,$EC,$F5,$ED,$EE,$73,$F1,$9A,$4D,$BD,$C8,$C3,$A0,$C3,$EF,$EE    ; $98AD  olumnsq.M=HC Con
        dfb $F4,$E5,$F8,$F4,$A0,$C2,$E5,$E7,$E9,$6E,$B1,$9A,$46,$BE,$C8,$C3    ; $98BD  text Begin1.F>HC
        dfb $A0,$C3,$EF,$EE,$F4,$E5,$F8,$F4,$A0,$C5,$EE,$64,$B5,$9A,$46,$BE    ; $98CD   Context End5.F>
        dfb $C8,$C3,$A0,$C5,$F3,$E3,$E1,$F0,$65,$AD,$9A,$3E,$BE,$C8,$C3,$A0    ; $98DD  HC Escape-.>>HC 
        dfb $C9,$EE,$E9,$F4,$A0,$D3,$F4,$F2,$E9,$EE,$67,$F5,$9A,$66,$BD,$C8    ; $98ED  Init Stringu.f=H
        dfb $C3,$A0,$CC,$E5,$E6,$F4,$A0,$CD,$E1,$F2,$E7,$E9,$6E,$F9,$9A,$83    ; $98FD  C Left Marginy..
        dfb $BD,$C8,$C3,$A0,$D0,$E1,$E7,$E5,$A0,$CC,$E9,$EE,$E5,$73,$ED,$9A    ; $990D  =HC Page Linesm.
        dfb $36,$BD,$C8,$C3,$A0,$D0,$E1,$E7,$E5,$A0,$CE,$F5,$ED,$E2,$E5,$72    ; $991D  6=HC Page Number
        dfb $01,$9B,$E3,$BC,$C8,$C3,$A0,$D2,$E9,$E7,$E8,$F4,$A0,$CD,$E1,$F2    ; $992D  ..c<HC Right Mar
        dfb $E7,$E9,$6E,$FD,$9A,$83,$BD,$C8,$C3,$A0,$D3,$EC,$EF,$74,$E5,$9A    ; $993D  gin}..=HC Slote.
        dfb $FF,$BC,$C8,$C3,$A0,$D3,$E8,$E5,$E5,$F4,$A0,$CC,$E9,$EE,$E5,$73    ; $994D  .<HC Sheet Lines
        dfb $E9,$9A,$1E,$BD,$C8,$C3,$A0,$D4,$EF,$F0,$A0,$CC,$E9,$EE,$65,$05    ; $995D  i..=HC Top Line.
        dfb $9B,$BD,$BC,$C8,$E5,$F8,$A0,$C6,$E9,$EC,$E5,$A0,$D3,$E9,$FA,$65    ; $996D  .=<Hex File Size
        dfb $11,$9B,$15,$9B,$C9,$E7,$EE,$EF,$F2,$E5,$A0,$C1,$EC,$F0,$E8,$E1    ; $997D  ....Ignore Alpha
        dfb $A0,$CC,$E1,$E2,$E5,$EC,$73,$D9,$9A,$99,$BC,$CB,$E5,$F9,$A0,$C3    ; $998D   LabelsY..<Key C
        dfb $EC,$E9,$E3,$6B,$95,$9A,$AE,$BA,$CC,$E1,$E2,$E5,$EC,$A0,$D3,$F4    ; $999D  lick...:Label St
        dfb $E1,$F2,$F4,$E5,$F2,$73,$D5,$9A,$74,$BC,$CE,$E5,$F8,$F4,$A0,$D3    ; $99AD  artersU.t<Next S
        dfb $E3,$F2,$E5,$E5,$EE,$A0,$C3,$EF,$EE,$F4,$E5,$F8,$F4,$A0,$CC,$E9    ; $99BD  creen Context Li
        dfb $EE,$E5,$73,$C5,$9A,$B4,$BB,$CE,$E5,$F7,$A0,$CC,$E9,$EE,$E5,$F3    ; $99CD  nesE.4;New Lines
        dfb $A0,$C1,$F4,$A0,$C5,$CF,$42,$C9,$9A,$DF,$BB,$D2,$E5,$E7,$E9,$EF    ; $99DD   At EOBI._;Regio
        dfb $EE,$A0,$D1,$F5,$E5,$F2,$F9,$A0,$D3,$E9,$FA,$65,$CD,$9A,$07,$BC    ; $99ED  n Query SizeM..<
        dfb $D3,$E5,$E1,$F2,$E3,$E8,$A0,$CD,$EF,$F6,$E5,$ED,$E5,$EE,$F4,$A0    ; $99FD  Search Movement 
        dfb $CD,$E1,$78,$81,$9A,$0C,$BA,$D3,$EB,$E9,$F0,$A0,$C3,$EF,$ED,$ED    ; $9A0D  Max...:Skip Comm
        dfb $E5,$EE,$F4,$A0,$C5,$EE,$64,$85,$9A,$37,$BA,$D3,$F9,$F3,$F4,$E5    ; $9A1D  ent End..7:Syste
        dfb $ED,$A0,$C6,$E9,$EC,$E5,$F3,$A0,$D0,$E1,$F4,$68,$BD,$9A,$68,$BB    ; $9A2D  m Files Path=.h;
        dfb $D4,$F2,$E1,$EE,$F3,$F0,$EF,$F3,$E5,$A0,$D0,$F2,$E5,$F6,$E9,$EF    ; $9A3D  Transpose Previo
        dfb $F5,$F3,$A0,$CF,$EE,$EC,$79,$C1,$9A,$8B,$BB,$D4,$E1,$E7,$F3,$A0    ; $9A4D  us OnlyA..;Tags 
        dfb $C6,$E9,$EE,$E4,$A0,$C6,$E9,$EC,$65,$E1,$9A,$02,$B3    ; $9A5D  Find Filea..3
; ---- $9A6A-$9A6C  data  VariableLink ----
        dfb $00,$00,$00    ; $9A6A  ...
; ---- $9A6D-$9B14  data  VarList (variable records) ----
        dfb $00,$FF,$AC,$1F,$00,$18,$F5,$31,$00,$50,$FF,$1C,$02,$05,$00,$1D    ; $9A6D  ..,...u1.P......
        dfb $02,$05,$05,$1D,$01,$00,$0F,$5D,$03,$00,$25,$18,$00,$FF,$45,$29    ; $9A7D  .......]..%...E)
        dfb $03,$00,$37,$2A,$03,$00,$38,$2A,$03,$00,$5A,$27,$00,$80,$5B,$27    ; $9A8D  ..7*..8*..Z'..['
        dfb $03,$00,$8D,$5E,$03,$00,$70,$84,$02,$06,$4E,$67,$00,$FF,$3B,$8F    ; $9A9D  ...^..p...Ng..;.
        dfb $02,$02,$3C,$8F,$02,$09,$3E,$8F,$02,$09,$48,$8F,$00,$FF,$83,$6D    ; $9AAD  ..<...>...H....m
        dfb $02,$31,$23,$83,$03,$00,$DE,$89,$00,$18,$D3,$34,$03,$00,$38,$34    ; $9ABD  .1#...^...S4..84
        dfb $01,$00,$2B,$8C,$00,$50,$08,$34,$02,$05,$98,$21,$03,$00,$9D,$21    ; $9ACD  ..+..P.4...!...!
        dfb $02,$40,$E4,$76,$03,$00,$81,$94,$00,$07,$34,$8F,$00,$FF,$35,$8F    ; $9ADD  .@dv......4...5.
        dfb $00,$FF,$36,$8F,$00,$84,$37,$8F,$02,$0A,$54,$8F,$00,$50,$5E,$8F    ; $9AED  ..6...7...T..P^.
        dfb $00,$50,$5F,$8F,$01,$00,$38,$8F,$00,$FF,$3A,$8F,$00,$05,$47,$81    ; $9AFD  .P_...8...:...G.
        dfb $03,$00,$F1,$77,$03,$00,$3E,$75    ; $9B0D  ..qw..>u
; ---- $9B15-$9B36  data  VarDocList (variable doc strings) ----
        dfb $CF,$EE,$A0,$ED,$E5,$E1,$EE,$F3,$A0,$E4,$E9,$F3,$F0,$EC,$E1,$F9    ; $9B15  On means display
        dfb $A0,$E6,$E9,$EC,$E5,$A0,$F3,$E9,$FA,$E5,$F3,$A0,$E9,$EE,$A0,$E8    ; $9B25   file sizes in h
        dfb $E5,$78    ; $9B35  ex
