;-*- Mode: Merlin -*-
;
; src/modules/28_cmdnames.s -- AMACS: command-name string table
; Address range $9B37-$A4F7. GENERATED by tools/disasm.py.
; `put' from src/amacs.s; symbols/labels are global across modules.
;
; ---- $9B37-$A4F7  data  CommandNames (command-name string table to EOF) ----
        dfb $C1,$E3,$E3,$F5,$ED,$F5,$EC,$E1,$F4,$E5,$A0,$CD,$E1,$F4,$E3,$E8    ; $9B37  Accumulate Match
        dfb $E9,$EE,$E7,$A0,$CC,$E9,$EE,$E5,$73,$71,$89,$45,$B5,$C1,$F0,$F0    ; $9B47  ing Linesq.E5App
        dfb $E5,$EE,$E4,$A0,$CE,$E5,$F8,$F4,$A0,$CB,$E9,$EC,$6C,$7E,$4F,$78    ; $9B57  end Next Kill~Ox
        dfb $B7,$C1,$F0,$F2,$EF,$F0,$EF,$73,$91,$64,$AC,$AF,$C1,$F2,$E7,$F5    ; $9B67  7Apropos.d,/Argu
        dfb $ED,$E5,$EE,$F4,$A0,$C4,$E9,$E7,$E9,$74,$D2,$7A,$0E,$AE,$C1,$F4    ; $9B77  ment DigitRz..At
        dfb $EF,$ED,$A0,$D7,$EF,$F2,$E4,$A0,$CD,$EF,$E4,$65,$08,$1C,$AC,$B0    ; $9B87  om Word Mode..,0
        dfb $C1,$F5,$F4,$EF,$A0,$C6,$E9,$EC,$EC,$A0,$CD,$EF,$E4,$65,$10,$1C    ; $9B97  Auto Fill Mode..
        dfb $D7,$B0,$C1,$F5,$F4,$EF,$A0,$C9,$EE,$E4,$E5,$EE,$F4,$A0,$CD,$EF    ; $9BA7  W0Auto Indent Mo
        dfb $E4,$65,$0C,$1C,$AF,$BD,$C2,$E1,$E3,$EB,$A0,$F4,$EF,$A0,$C9,$EE    ; $9BB7  de../=Back to In
        dfb $E4,$E5,$EE,$F4,$E1,$F4,$E9,$EF,$6E,$26,$25,$D7,$BD,$CF,$F5,$F4    ; $9BC7  dentation&%W=Out
        dfb $E4,$E5,$EE,$F4,$A0,$CC,$E9,$EE,$65,$78,$25,$6A,$B2,$CF,$F5,$F4    ; $9BD7  dent Linex%j2Out
        dfb $E4,$E5,$EE,$F4,$A0,$C3,$D2,$CC,$46,$72,$25,$5F,$B2,$C2,$E1,$E3    ; $9BE7  dent CRLFr%_2Bac
        dfb $EB,$F7,$E1,$F2,$E4,$A0,$C3,$E8,$E1,$F2,$E1,$E3,$F4,$E5,$72,$5E    ; $9BF7  kward Character^
        dfb $17,$00,$AB,$C2,$E1,$E3,$EB,$F7,$E1,$F2,$E4,$A0,$C4,$E5,$EC,$E5    ; $9C07  ..+Backward Dele
        dfb $F4,$E5,$A0,$C3,$E8,$E1,$F2,$E1,$E3,$F4,$E5,$72,$1D,$16,$B6,$AB    ; $9C17  te Character..6+
        dfb $C2,$E1,$E3,$EB,$F7,$E1,$F2,$E4,$A0,$C4,$E5,$EC,$E5,$F4,$E5,$A0    ; $9C27  Backward Delete 
        dfb $C8,$E1,$E3,$EB,$E9,$EE,$E7,$A0,$D4,$E1,$E2,$73,$8B,$16,$DC,$AB    ; $9C37  Hacking Tabs..\+
        dfb $C2,$E1,$E3,$EB,$F7,$E1,$F2,$E4,$A0,$CB,$E9,$EC,$EC,$A0,$CC,$E9    ; $9C47  Backward Kill Li
        dfb $EE,$65,$26,$38,$13,$B2,$C2,$E1,$E3,$EB,$F7,$E1,$F2,$E4,$A0,$CB    ; $9C57  ne&8.2Backward K
        dfb $E9,$EC,$EC,$A0,$D3,$E5,$EE,$F4,$E5,$EE,$E3,$65,$F0,$3A,$F1,$B8    ; $9C67  ill Sentencep:q8
        dfb $C2,$E1,$E3,$EB,$F7,$E1,$F2,$E4,$A0,$CB,$E9,$EC,$EC,$A0,$D7,$EF    ; $9C77  Backward Kill Wo
        dfb $F2,$64,$FE,$37,$1F,$AC,$C2,$E1,$E3,$EB,$F7,$E1,$F2,$E4,$A0,$D0    ; $9C87  rd~7.,Backward P
        dfb $E1,$F2,$E1,$E7,$F2,$E1,$F0,$68,$39,$22,$15,$B8,$C2,$E1,$E3,$EB    ; $9C97  aragraph9".8Back
        dfb $F7,$E1,$F2,$E4,$A0,$D3,$E5,$EE,$F4,$E5,$EE,$E3,$65,$6E,$3A,$AF    ; $9CA7  ward Sentencen:/
        dfb $B8,$C2,$E1,$E3,$EB,$F7,$E1,$F2,$E4,$A0,$D7,$EF,$F2,$64,$C2,$35    ; $9CB7  8Backward WordB5
        dfb $74,$AB,$C2,$E3,$E3,$F5,$72,$76,$87,$1E,$B5,$C2,$E5,$E7,$E9,$EE    ; $9CC7  t+Bccurv..5Begin
        dfb $EE,$E9,$EE,$E7,$A0,$EF,$E6,$A0,$CC,$E9,$EE,$65,$A6,$34,$8B,$AE    ; $9CD7  ning of Line&4..
        dfb $C3,$A0,$CD,$EF,$E4,$65,$5A,$81,$6D,$B4,$C3,$D2,$CC,$46,$26,$18    ; $9CE7  C ModeZ.m4CRLF&.
        dfb $2C,$B2,$C3,$E1,$F0,$E9,$F4,$E1,$EC,$E9,$FA,$E5,$A0,$D2,$E5,$E7    ; $9CF7  ,2Capitalize Reg
        dfb $E9,$EF,$6E,$83,$8D,$B4,$B6,$C3,$E1,$F0,$F3,$A0,$D7,$EF,$F2,$E4    ; $9D07  ion..46Caps Word
        dfb $A0,$CD,$EF,$E4,$65,$14,$1C,$7A,$BE,$C3,$EF,$ED,$F0,$E9,$EC,$65    ; $9D17   Mode..z>Compile
        dfb $24,$77,$02,$B2,$C3,$EF,$F0,$F9,$A0,$D2,$E5,$E7,$E9,$EF,$6E,$92    ; $9D27  $w.2Copy Region.
        dfb $8D,$FA,$B6,$C3,$EF,$F5,$EE,$F4,$A0,$CC,$E9,$EE,$E5,$F3,$A0,$D2    ; $9D37  .z6Count Lines R
        dfb $E5,$E7,$E9,$EF,$6E,$B0,$8D,$16,$B7,$C3,$EF,$F5,$EE,$F4,$A0,$CF    ; $9D47  egion0..7Count O
        dfb $E3,$E3,$F5,$F2,$E5,$EE,$E3,$E5,$73,$68,$87,$D3,$B4,$C4,$E5,$EC    ; $9D57  ccurencesh.S4Del
        dfb $E5,$F4,$E5,$A0,$C2,$EC,$E1,$EE,$EB,$A0,$CC,$E9,$EE,$E5,$73,$55    ; $9D67  ete Blank LinesU
        dfb $39,$57,$B0,$C4,$E5,$EC,$E5,$F4,$E5,$A0,$C3,$E8,$E1,$F2,$E1,$E3    ; $9D77  9W0Delete Charac
        dfb $F4,$E5,$72,$87,$15,$94,$AB,$C4,$E5,$EC,$E5,$F4,$E5,$A0,$C6,$E9    ; $9D87  ter...+Delete Fi
        dfb $EC,$65,$16,$6D,$EB,$B1,$C4,$E5,$EC,$E5,$F4,$E5,$A0,$C8,$EF,$F2    ; $9D97  le.mk1Delete Hor
        dfb $E9,$FA,$EF,$EE,$F4,$E1,$EC,$A0,$D3,$F0,$E1,$E3,$65,$3C,$39,$72    ; $9DA7  izontal Space<9r
        dfb $B0,$C4,$E5,$F3,$E3,$F2,$E9,$E2,$65,$84,$51,$B4,$B4,$C4,$EF,$A0    ; $9DB7  0Describe.Q44Do 
        dfb $CC,$E1,$F3,$F4,$A0,$CB,$E2,$E4,$A0,$CD,$E1,$E3,$F2,$6F,$04,$8B    ; $9DC7  Last Kbd Macro..
        dfb $66,$B5,$C4,$EF,$F7,$EE,$A0,$C3,$EF,$ED,$ED,$E5,$EE,$F4,$A0,$CC    ; $9DD7  f5Down Comment L
        dfb $E9,$EE,$65,$A6,$1E,$02,$B4,$C4,$EF,$F7,$EE,$A0,$D2,$E5,$E1,$EC    ; $9DE7  ine&..4Down Real
        dfb $A0,$CC,$E9,$EE,$65,$C2,$1B,$21,$AB,$C5,$E4,$E9,$F4,$A0,$C4,$E5    ; $9DF7   LineB.!+Edit De
        dfb $E6,$E9,$EE,$E9,$F4,$E9,$EF,$6E,$D2,$94,$AE,$B2,$C5,$EE,$E4,$A0    ; $9E07  finitionR..2End 
        dfb $CB,$E2,$E4,$A0,$CD,$E1,$E3,$F2,$6F,$05,$8C,$DD,$B7,$C5,$EE,$E4    ; $9E17  Kbd Macro..]7End
        dfb $A0,$EF,$E6,$A0,$CC,$E9,$EE,$65,$BA,$34,$A9,$AE,$C5,$F8,$E3,$E8    ; $9E27   of Line:4).Exch
        dfb $E1,$EE,$E7,$E5,$A0,$D0,$EF,$E9,$EE,$F4,$A0,$E1,$EE,$E4,$A0,$CD    ; $9E37  ange Point and M
        dfb $E1,$F2,$6B,$2B,$7E,$3F,$B3,$C5,$F8,$E9,$74,$82,$10,$48,$B9,$C5    ; $9E47  ark+~?3Exit..H9E
        dfb $F8,$F4,$E5,$EE,$E4,$E5,$E4,$A0,$C3,$EF,$ED,$ED,$E1,$EE,$64,$1F    ; $9E57  xtended Command.
        dfb $3F,$34,$AE,$C6,$E9,$EC,$EC,$A0,$D0,$E1,$F2,$E1,$E7,$F2,$E1,$F0    ; $9E67  ?4.Fill Paragrap
        dfb $68,$C7,$22,$42,$B7,$C6,$E9,$EC,$EC,$A0,$D2,$E5,$E7,$E9,$EF,$6E    ; $9E77  hG"B7Fill Region
        dfb $0A,$8E,$42,$B7,$C6,$E9,$EE,$E4,$A0,$C6,$E9,$EC,$65,$BE,$6B,$22    ; $9E87  ..B7Find File>k"
        dfb $B6,$C6,$EF,$F2,$F7,$E1,$F2,$E4,$A0,$C3,$E8,$E1,$F2,$E1,$E3,$F4    ; $9E97  6Forward Charact
        dfb $E5,$72,$3B,$17,$00,$AB,$C6,$EF,$F2,$F7,$E1,$F2,$E4,$A0,$D0,$E1    ; $9EA7  er;..+Forward Pa
        dfb $F2,$E1,$E7,$F2,$E1,$F0,$68,$CF,$21,$28,$B8,$C6,$EF,$F2,$F7,$E1    ; $9EB7  ragraphO!(8Forwa
        dfb $F2,$E4,$A0,$D3,$E5,$EE,$F4,$E5,$EE,$E3,$65,$2E,$3A,$8F,$B8,$C6    ; $9EC7  rd Sentence.:.8F
        dfb $EF,$F2,$F7,$E1,$F2,$E4,$A0,$D7,$EF,$F2,$64,$17,$36,$57,$AB,$C6    ; $9ED7  orward Word.6W+F
        dfb $F5,$EE,$E4,$E1,$ED,$E5,$EE,$F4,$E1,$EC,$A0,$CD,$EF,$E4,$65,$F2    ; $9EE7  undamental Moder
        dfb $81,$6D,$B4,$C7,$EF,$F4,$EF,$A0,$C2,$E5,$E7,$E9,$EE,$EE,$E9,$EE    ; $9EF7  .m4Goto Beginnin
        dfb $67,$41,$1A,$C5,$AE,$C7,$EF,$F4,$EF,$A0,$C5,$EE,$64,$5A,$1A,$E5    ; $9F07  gA.E.Goto EndZ.e
        dfb $AE,$C7,$EF,$F4,$EF,$A0,$CE,$E5,$F8,$F4,$A0,$CC,$E1,$E2,$E5,$6C    ; $9F17  .Goto Next Label
        dfb $DD,$22,$3D,$B8,$C7,$EF,$F4,$EF,$A0,$D0,$F2,$E5,$F6,$E9,$EF,$F5    ; $9F27  ]"=8Goto Previou
        dfb $F3,$A0,$CC,$E1,$E2,$E5,$6C,$4C,$23,$58,$B8,$C7,$F2,$EF,$F7,$A0    ; $9F37  s LabelL#X8Grow 
        dfb $D7,$E9,$EE,$E4,$EF,$77,$7F,$13,$96,$B6,$C8,$E1,$F2,$E4,$E3,$EF    ; $9F47  Window...6Hardco
        dfb $F0,$F9,$A0,$C2,$F5,$E6,$E6,$E5,$72,$AC,$8E,$95,$BD,$C8,$E1,$F2    ; $9F57  py Buffer,..=Har
        dfb $E4,$E3,$EF,$F0,$F9,$A0,$D2,$E5,$E7,$E9,$EF,$6E,$B2,$8E,$5A,$B7    ; $9F67  dcopy Region2.Z7
        dfb $C8,$E5,$EC,$70,$91,$83,$0A,$B6,$C9,$EE,$E3,$F2,$E5,$ED,$E5,$EE    ; $9F77  Help...6Incremen
        dfb $F4,$E1,$EC,$A0,$D3,$E5,$E1,$F2,$E3,$68,$79,$1B,$22,$AF,$C9,$EE    ; $9F87  tal Searchy."/In
        dfb $E4,$E5,$EE,$F4,$A0,$D2,$E5,$E7,$E9,$EF,$6E,$BB,$8E,$F9,$BD,$C9    ; $9F97  dent Region;.y=I
        dfb $EE,$E4,$E5,$EE,$F4,$A0,$E6,$EF,$F2,$A0,$C3,$EF,$ED,$ED,$E5,$EE    ; $9FA7  ndent for Commen
        dfb $74,$7A,$1E,$02,$B4,$C9,$EE,$F3,$E5,$F2,$F4,$A0,$C4,$E1,$F4,$E5    ; $9FB7  tz..4Insert Date
        dfb $A0,$E1,$EE,$E4,$A0,$D4,$E9,$ED,$65,$7F,$6F,$96,$B1,$C9,$EE,$F3    ; $9FC7   and Time.o.1Ins
        dfb $E5,$F2,$F4,$A0,$C6,$E9,$EC,$65,$D2,$6A,$17,$B1,$C9,$EE,$F6,$E5    ; $9FD7  ert FileRj.1Inve
        dfb $F2,$F4,$A0,$CD,$EF,$E4,$E5,$A0,$CC,$E9,$EE,$65,$3B,$53,$74,$B3    ; $9FE7  rt Mode Line;St3
        dfb $CB,$E9,$EC,$EC,$A0,$C2,$F5,$E6,$E6,$E5,$72,$1F,$4A,$D5,$B5,$CB    ; $9FF7  Kill Buffer.JU5K
        dfb $E9,$EC,$EC,$A0,$C3,$EF,$ED,$ED,$E5,$EE,$74,$6A,$1E,$2F,$B4,$CB    ; $A007  ill Commentj./4K
        dfb $E9,$EC,$EC,$A0,$CC,$E9,$EE,$65,$2E,$38,$13,$B2,$CB,$E9,$EC,$EC    ; $A017  ill Line.8.2Kill
        dfb $A0,$D2,$E5,$E7,$E9,$EF,$6E,$9A,$8D,$DA,$B6,$CB,$E9,$EC,$EC,$A0    ; $A027   Region..Z6Kill 
        dfb $D3,$E5,$EE,$F4,$E5,$EE,$E3,$65,$E0,$3A,$D1,$B8,$CB,$E9,$EC,$EC    ; $A037  Sentence`:Q8Kill
        dfb $A0,$D7,$EF,$F2,$64,$E7,$37,$02,$AC,$CC,$E1,$E2,$E5,$EC,$A0,$D3    ; $A047   Wordg7.,Label S
        dfb $E5,$E1,$F2,$E3,$68,$CA,$63,$E3,$B3,$CC,$E9,$F3,$F0,$A0,$CD,$EF    ; $A057  earchJcc3Lisp Mo
        dfb $E4,$65,$6D,$81,$6D,$B4,$CC,$E9,$F3,$F4,$A0,$C2,$F5,$E6,$E6,$E5    ; $A067  dem.m4List Buffe
        dfb $F2,$73,$74,$48,$B5,$B5,$CC,$E9,$F3,$F4,$A0,$C4,$E9,$F2,$E5,$E3    ; $A077  rstH55List Direc
        dfb $F4,$EF,$F2,$79,$58,$6B,$98,$B3,$CC,$E9,$F3,$F4,$A0,$C6,$E9,$EC    ; $A087  toryXk.3List Fil
        dfb $E5,$73,$54,$6B,$A0,$B3,$CC,$E9,$F3,$F4,$A0,$CD,$E1,$F4,$E3,$E8    ; $A097  esTk 3List Match
        dfb $E9,$EE,$E7,$A0,$CC,$E9,$EE,$E5,$73,$6F,$87,$F4,$B4,$CC,$E9,$F3    ; $A0A7  ing Lineso.t4Lis
        dfb $F4,$A0,$D6,$E1,$F2,$E9,$E1,$E2,$EC,$E5,$73,$B0,$65,$BB,$AF,$CC    ; $A0B7  t Variables0e;/L
        dfb $EF,$E1,$E4,$A0,$CC,$E9,$E2,$F2,$E1,$F2,$79,$E6,$91,$EA,$A4,$CC    ; $A0C7  oad Libraryf.j$L
        dfb $EF,$F7,$E5,$F2,$E3,$E1,$F3,$E5,$A0,$D2,$E5,$E7,$E9,$EF,$6E,$61    ; $A0D7  owercase Regiona
        dfb $8D,$B4,$B6,$CC,$EF,$F7,$E5,$F2,$E3,$E1,$F3,$E5,$A0,$D7,$EF,$F2    ; $A0E7  .46Lowercase Wor
        dfb $64,$74,$36,$62,$AC,$CD,$E1,$F2,$EB,$A0,$C2,$F5,$E6,$E6,$E5,$72    ; $A0F7  dt6b,Mark Buffer
        dfb $2F,$4D,$24,$B9,$CD,$E1,$F2,$EB,$A0,$D0,$E1,$F2,$E1,$E7,$F2,$E1    ; $A107  /M$9Mark Paragra
        dfb $F0,$68,$B5,$22,$13,$B9,$CD,$E5,$F2,$EC,$E9,$EE,$A0,$CD,$EF,$E4    ; $A117  ph5".9Merlin Mod
        dfb $65,$7D,$81,$6D,$B4,$CD,$E5,$F2,$EC,$E9,$EE,$E9,$FA,$65,$65,$79    ; $A127  e}.m4Merlinizeey
        dfb $07,$B0,$CD,$EF,$F6,$E5,$A0,$D4,$EF,$A0,$D3,$E3,$F2,$E5,$E5,$EE    ; $A137  .0Move To Screen
        dfb $A0,$C5,$E4,$E7,$65,$E1,$17,$ED,$AC,$CE,$E5,$E7,$E1,$F4,$E9,$F6    ; $A147   Edgea.m,Negativ
        dfb $E5,$A0,$C1,$F2,$E7,$F5,$ED,$E5,$EE,$74,$11,$7B,$E0,$AD,$CE,$E5    ; $A157  e Argument.{`-Ne
        dfb $F7,$A0,$D7,$E9,$EE,$E4,$EF,$77,$81,$17,$9C,$AC,$CE,$E5,$F8,$F4    ; $A167  w Window...,Next
        dfb $A0,$D3,$E3,$F2,$E5,$E5,$6E,$D4,$34,$B5,$AC,$CE,$EF,$F4,$A0,$CD    ; $A177   ScreenT45,Not M
        dfb $EF,$E4,$E9,$E6,$E9,$E5,$64,$A6,$1B,$57,$B3,$CF,$EE,$E5,$A0,$D7    ; $A187  odified&.W3One W
        dfb $E9,$EE,$E4,$EF,$77,$3F,$13,$5D,$B6,$CF,$F0,$E5,$EE,$A0,$C2,$EC    ; $A197  indow?.]6Open Bl
        dfb $E1,$EE,$EB,$A0,$CC,$E9,$EE,$65,$6E,$19,$44,$B2,$CF,$F4,$E8,$E5    ; $A1A7  ank Linen.D2Othe
        dfb $F2,$A0,$D7,$E9,$EE,$E4,$EF,$77,$C1,$12,$7E,$B6,$D0,$E1,$F3,$E3    ; $A1B7  r WindowA.~6Pasc
        dfb $E1,$EC,$A0,$CD,$EF,$E4,$65,$C6,$81,$6D,$B4,$D0,$F2,$E5,$E6,$E9    ; $A1C7  al ModeF.m4Prefi
        dfb $F8,$A0,$C3,$F4,$F2,$EC,$AD,$CD,$E5,$F4,$61,$EB,$1A,$29,$AD,$D0    ; $A1D7  x Ctrl-Metak.)-P
        dfb $F2,$E5,$E6,$E9,$F8,$A0,$CD,$E5,$F4,$61,$D5,$1A,$10,$AD,$D0,$F2    ; $A1E7  refix MetaU..-Pr
        dfb $E5,$F6,$E9,$EF,$F5,$F3,$A0,$D3,$E3,$F2,$E5,$E5,$6E,$4C,$35,$D0    ; $A1F7  evious ScreenL5P
        dfb $AC,$D1,$F5,$E5,$F2,$F9,$A0,$D2,$E5,$F0,$EC,$E1,$E3,$65,$75,$84    ; $A207  ,Query Replaceu.
        dfb $69,$B1,$D1,$F5,$EF,$F4,$E5,$E4,$A0,$C9,$EE,$F3,$E5,$F2,$74,$B1    ; $A217  i1Quoted Insert1
        dfb $1B,$45,$AD,$D2,$E5,$EE,$E1,$ED,$E5,$A0,$C2,$F5,$E6,$E6,$E5,$72    ; $A227  .E-Rename Buffer
        dfb $4A,$47,$9A,$B5,$D2,$E5,$F0,$EC,$E1,$E3,$E5,$A0,$D3,$F4,$F2,$E9    ; $A237  JG.5Replace Stri
        dfb $EE,$67,$79,$84,$78,$B1,$D2,$E5,$F0,$EF,$F3,$E9,$F4,$E9,$EF,$EE    ; $A247  ngy.x1Reposition
        dfb $A0,$D7,$E9,$EE,$E4,$EF,$77,$F0,$23,$75,$B8,$D2,$E5,$F6,$E5,$F2    ; $A257   Windowp#u8Rever
        dfb $F3,$E5,$A0,$C9,$EE,$E3,$F2,$E5,$ED,$E5,$EE,$F4,$E1,$EC,$A0,$D3    ; $A267  se Incremental S
        dfb $E5,$E1,$F2,$E3,$68,$71,$1B,$03,$AF,$D2,$E5,$F6,$E5,$F2,$F3,$E5    ; $A277  earchq../Reverse
        dfb $A0,$D3,$F4,$F2,$E9,$EE,$E7,$A0,$D3,$E5,$E1,$F2,$E3,$68,$88,$1B    ; $A287   String Search..
        dfb $50,$B1,$D3,$E1,$F6,$E5,$A0,$C6,$E9,$EC,$65,$7D,$6A,$88,$B0,$D3    ; $A297  P1Save File}j.0S
        dfb $E5,$EC,$E5,$E3,$F4,$A0,$C2,$F5,$E6,$E6,$E5,$72,$B1,$45,$81,$B5    ; $A2A7  elect Buffer1E.5
        dfb $D3,$E5,$EC,$E6,$A0,$C9,$EE,$F3,$E5,$F2,$74,$CE,$16,$67,$AD,$D3    ; $A2B7  Self InsertN.g-S
        dfb $E5,$F4,$A0,$C3,$EF,$ED,$ED,$E5,$EE,$F4,$A0,$C3,$EF,$EC,$F5,$ED    ; $A2C7  et Comment Colum
        dfb $6E,$4A,$7E,$4A,$B4,$D3,$E5,$F4,$A0,$C7,$EF,$E1,$EC,$A0,$C3,$EF    ; $A2D7  nJ~J4Set Goal Co
        dfb $EC,$F5,$ED,$6E,$34,$7E,$9C,$B7,$D3,$E5,$F4,$A0,$CB,$E5,$79,$0F    ; $A2E7  lumn4~.7Set Key.
        dfb $7F,$35,$B1,$D3,$E5,$F4,$A0,$D0,$EF,$F0,$A0,$CD,$E1,$F2,$6B,$AB    ; $A2F7  .51Set Pop Mark+
        dfb $35,$1B,$B3,$D3,$E5,$F4,$A0,$D0,$F2,$E5,$E6,$E9,$78,$B7,$6C,$B3    ; $A307  5.3Set Prefix7l3
        dfb $B1,$D3,$E5,$F4,$A0,$D6,$E1,$F2,$E9,$E1,$E2,$EC,$65,$AF,$14,$E9    ; $A317  1Set Variable/.i
        dfb $AF,$D3,$F0,$E1,$E3,$E5,$C2,$E1,$72,$9F,$1F,$97,$AD,$D3,$F4,$E1    ; $A327  /SpaceBar...-Sta
        dfb $F2,$F4,$A0,$CB,$E2,$E4,$A0,$CD,$E1,$E3,$F2,$6F,$D9,$8B,$C5,$B7    ; $A337  rt Kbd MacroY.E7
        dfb $D3,$F4,$F2,$E9,$EE,$E7,$A0,$D3,$E5,$E1,$F2,$E3,$68,$90,$1B,$50    ; $A347  String Search..P
        dfb $B1,$D4,$E1,$E2,$A0,$C9,$EE,$F3,$E5,$F2,$74,$CC,$16,$67,$AD,$D4    ; $A357  1Tab InsertL.g-T
        dfb $E5,$F8,$F4,$A0,$CD,$EF,$E4,$65,$B1,$81,$6D,$B4,$D4,$EF,$F0,$A0    ; $A367  ext Mode1.m4Top 
        dfb $CC,$E5,$F6,$E5,$EC,$A0,$C1,$E2,$EF,$F2,$74,$F4,$1B,$91,$AF,$D4    ; $A377  Level Abortt../T
        dfb $F2,$E1,$EE,$F3,$F0,$EF,$F3,$E5,$A0,$C3,$E8,$E1,$F2,$E1,$E3,$F4    ; $A387  ranspose Charact
        dfb $E5,$F2,$73,$FA,$89,$4E,$AE,$D4,$F2,$E1,$EE,$F3,$F0,$EF,$F3,$E5    ; $A397  ersz.N.Transpose
        dfb $A0,$CC,$E9,$EE,$E5,$73,$7D,$8A,$6F,$AE,$D4,$F7,$EF,$A0,$D7,$E9    ; $A3A7   Lines}.o.Two Wi
        dfb $EE,$E4,$EF,$F7,$73,$23,$12,$3F,$B6,$D5,$EE,$AD,$CB,$E9,$EC,$6C    ; $A3B7  ndows#.?6Un-Kill
        dfb $ED,$4E,$F3,$B7,$D5,$EE,$CD,$E5,$F2,$EC,$E9,$EE,$E9,$FA,$65,$E0    ; $A3C7  mNs7UnMerlinize`
        dfb $78,$2C,$B0,$D5,$EE,$E9,$F6,$E5,$F2,$F3,$E1,$EC,$A0,$C1,$F2,$E7    ; $A3D7  x,0Universal Arg
        dfb $F5,$ED,$E5,$EE,$74,$1D,$7B,$BA,$AD,$D5,$F0,$A0,$C3,$EF,$ED,$ED    ; $A3E7  ument.{:-Up Comm
        dfb $E5,$EE,$F4,$A0,$CC,$E9,$EE,$65,$9E,$1E,$02,$B4,$D5,$F0,$A0,$D2    ; $A3F7  ent Line...4Up R
        dfb $E5,$E1,$EC,$A0,$CC,$E9,$EE,$65,$B7,$1B,$3B,$AB,$D5,$F0,$F0,$E5    ; $A407  eal Line7.;+Uppe
        dfb $F2,$E3,$E1,$F3,$E5,$A0,$C9,$EE,$E9,$F4,$E9,$E1,$6C,$7D,$36,$84    ; $A417  rcase Initial}6.
        dfb $AC,$D5,$F0,$F0,$E5,$F2,$E3,$E1,$F3,$E5,$A0,$D2,$E5,$E7,$E9,$EF    ; $A427  ,Uppercase Regio
        dfb $6E,$75,$8D,$B4,$B6,$D5,$F0,$F0,$E5,$F2,$E3,$E1,$F3,$E5,$A0,$D7    ; $A437  nu.46Uppercase W
        dfb $EF,$F2,$64,$60,$36,$40,$AC,$D6,$E9,$E5,$F7,$A0,$CB,$E2,$E4,$A0    ; $A447  ord`6@,View Kbd 
        dfb $CD,$E1,$E3,$F2,$6F,$A7,$8A,$F2,$B5,$D6,$E9,$F3,$E9,$F4,$A0,$C6    ; $A457  Macro'.r5Visit F
        dfb $E9,$EC,$65,$56,$67,$47,$AF,$D6,$E9,$F3,$E9,$F4,$A0,$D4,$E1,$E7    ; $A467  ileVgG/Visit Tag
        dfb $A0,$D4,$E1,$E2,$EC,$65,$49,$97,$CD,$B2,$D7,$E8,$E1,$F4,$A0,$C1    ; $A477   TableI.M2What A
        dfb $F6,$E1,$E9,$EC,$E1,$E2,$EC,$E5,$A0,$D3,$F0,$E1,$E3,$65,$13,$21    ; $A487  vailable Space.!
        dfb $98,$B4,$D7,$E8,$E1,$F4,$A0,$C3,$F5,$F2,$F3,$EF,$F2,$A0,$D0,$EF    ; $A497  .4What Cursor Po
        dfb $73,$48,$1C,$F5,$B0,$D7,$E8,$E1,$F4,$A0,$CB,$E5,$79,$E8,$7F,$86    ; $A4A7  sH.u0What Keyh..
        dfb $B2,$D7,$E8,$E1,$F4,$A0,$CC,$EF,$F3,$F3,$E1,$E7,$65,$CD,$1C,$BF    ; $A4B7  2What LossageM.?
        dfb $B3,$D7,$E8,$E1,$F4,$A0,$D4,$E1,$E7,$A0,$C6,$E9,$EC,$65,$D6,$94    ; $A4C7  3What Tag FileV.
        dfb $E9,$B2,$D7,$F2,$E9,$F4,$E5,$A0,$C6,$E9,$EC,$65,$CA,$69,$6A,$AF    ; $A4D7  i2Write FileJij/
        dfb $00,$00,$00,$EC,$EF,$E1,$E4,$A0,$E1,$A0,$EC,$E9,$E2,$F2,$E1,$F2    ; $A4E7  ...load a librar
        dfb $79    ; $A4F7  y
